### ISSUE TITLE
404 on http://crossbar.io/docs/Using-Schemas/

### ISSUE THREAD

**Issue by Yamakaky** [crossbario/crossbar#1011]
404 Not Found

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: docs/Using-Schemas/index.html
    RequestId: FDD4A1A8F47AA6F3
    HostId: I5mKmQgs3+qO6gkV6qoqspX1GVFmSqjwqJg+pwEuecVkqQqBSrnT3QdXOPeBjxAKqHv+ViyH31A=

**Comment by Yamakaky** [comment]
Same for http://crossbar.io/docs/Logging-in-Crossbar.io/

**Comment by oberstet** [comment]
The Schema stuff should be removed for now ..

**Comment by goeddea** [comment]
The above links are not contained in the docs anymore.
