### ISSUE TITLE
Possible path manipulation with file upload

### ISSUE THREAD

**Issue by Yamakaky** [crossbario/crossbar#1018]
https://github.com/crossbario/crossbar/blob/master/crossbar/twisted/fileupload.py#L121
https://github.com/crossbario/crossbar/blob/master/crossbar/twisted/fileupload.py#L138
https://github.com/crossbario/crossbar/blob/master/crossbar/twisted/fileupload.py#L242
Seems to me you can have a file name with ".." inside and override any file crossbar has access to.

**Comment by meejah** [comment]
Yes, this looks like a bug to me from reading the code.

**Comment by oberstet** [comment]
The file upload code has multiple issues .. contributed code .. I just have reviewed it more closely, but lacked time. I am +1 on removing it completely.

**Comment by Yamakaky** [comment]
Well, I use it XD

**Comment by oberstet** [comment]
@Yamakaky I see. There are others as well. But this piece then really needs more attention/love. Right now, I wouldn't call it "production ready" .. at least not our own standards.

The escaping into arbitrary directories is really bad obviously. I remember there are issues under corner cases (interrupted uploads etc) as well.

**Comment by Yamakaky** [comment]
Yeah, I saw the code, it could be improved ^^

**Comment by Yamakaky** [comment]
script removed
