### ISSUE TITLE
Add custom authentication example

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#102]
Add an example where a user provides a custom authenticating procedure.

see also: https://github.com/voryx/Thruway/issues/7

**Comment by oberstet** [comment]
Here are examples (the dynamic subfolders): https://github.com/crossbario/crossbarexamples/tree/master/authenticate

**Comment by FirefighterBlu3** [comment]
@oberstet where did this example move too?

**Comment by goeddea** [comment]
@FirefighterBlu3 - Authentication examples are now at https://github.com/crossbario/crossbarexamples/tree/master/authentication
