### ISSUE TITLE
Update docs to reflect removal of most templates

### ISSUE THREAD

**Issue by thanhngvpt** [crossbario/crossbar#1020]
Hi all.
I just in touch with crossbar by following the quickstart http://crossbar.io/docs/Quick-Start/, But I got a stuck when run command `crossbar init --template hello:python --appdir hello` with message `Huh, sorry. There is no template named 'hello:python'. Try 'crossbar templates' to list the templates available.
`.  Command `crossbar templates` showed only one `default` template. How can I install a  new template. Please help me, What wrong with me? Many thanks.

**Comment by oberstet** [comment]
All templates but the default one have been removed. You can find these here: https://github.com/crossbario/crossbar-examples/tree/master/hello

Docs need updating, that's a bug.

**Comment by vlcinsky** [comment]
It is very confusing, especially for someone trying to make first steps with crossbar.

Proposal: use [cookiecutter](https://github.com/audreyr/cookiecutter) which allows generating code from templates for any purpose. E.g. Pyramid got rid of their own templates and switched to that. New templates are easy to maintain and install independently.

**Comment by meejah** [comment]
cookiecutter sounds potentially interesting .. that means each template would live in its own repository?

This would potentially make it easier for others to maintain the templates -- but a big part of the reason they were 'all' removed was lack of maintenance which isn't necessarily solved by just moving where they live.

Perhaps we could eliminate some of the things from 'crossbarexamples' and instead turn them into cookiecutter templates...?

**Comment by oberstet** [comment]
@vlcinsky sorry, yes it is confusing I can imagine. for context, here is how it happened.

The origin of this feature was the view that it would be cool to have app scaffolding just included with the `crossbar` CLI. As in "batteries included" for getting started with app components and microservices in different languages.

Now, this turned out to be a bold goal .. because of maintenance, quality, synchronisation of change, etc issues.

In particular I think it is clear now that having that kind of broad collection of templates in one repo is a bad idea.

It is particular bad to have it in the Crossbar.io repo itself.

However, it is even not really convincing for a different _single_ repo as well, like eg `crossbar-examples` I'd say. We, as a project, simply cannot maintain this variety of components in various languages.

Thinking about it, here is an alternative what we could do quite easily:

In addition to the built in templates for creating (local) node configs (a default one included), we search for installed *Crossbar.io component scaffolding plugins*.

These are distributed and deployed as Python packages, but might only contain some source files in the respective language/build system, with (optional) Jinja2 templating. These package register a pkg_resources entrypoint **"crossbar.component-template"**.

When we find such packages during startup of Crossbar.io, the respective template is loaded and made available from the CLI.

What do you think?

**Comment by oberstet** [comment]
plus of course (the whole point for the removal): we only need to maintain the generic plugin loader in the repo here (and the default _node_ templates). and that, we definitely want to maintain in this repo here.

**Comment by meejah** [comment]
@oberstet I think what you describe is very similar to how cookiecutter works, actually .. and perhaps tying in to such a project would encourage others to help maintain them?

**Comment by meejah** [comment]
I haven't looked closely enough but maybe @vlcinsky knows: it could be possible for us to simply call-through to cookiecutter from the `crossbar init --template` command (also e.g. tell users "please 'pip install cookiecutter" to use templates). I'm not sure if it has a Python-level API though.

**Comment by oberstet** [comment]
@meejah it indeed seems possible to use cookiecutter from Python:

```python
from cookiecutter.main import cookiecutter

# Create project from the cookiecutter-pypackage/ template
cookiecutter('cookiecutter-pypackage/')

# Create project from the cookiecutter-pypackage.git repo template
cookiecutter('https://github.com/audreyr/cookiecutter-pypackage.git')
```

so we could actually add cookiecutter as a dependency to CB and just call into it from `crossbar init --template` to actually do all the work! This seems kinda attractive =)

**Comment by oberstet** [comment]
I assume that it is possible to supply values and dicts so these get used in the Jinja2 templates that cookiecutter supports out of the box (nice!).

**Comment by meejah** [comment]
Hmm, yeah. We could also make cookiecutter and "optional" dependency, and anyone who uses "crossbar init --template X" would be told "please install cookiecutter first" or similar...

**Comment by oberstet** [comment]
or even better: not implement it (cookiecutter) in CB at all, and simply recommend using cookiecutter as its own CLI tool.

=)

I think this is also what @vlcinsky might have hinted at with "Pyramid got rid of own templating".

btw: there is a nice side effect: it also solves my issue with this:

the recommended way to run CB is Docker. using a CB inside a Docker image to initialize a new node directory on the _host_ system (where CB dirs would usually reside with Docker setups), this seems tedious.

however, using cookiecutter, the user only needs that on the host.

**Comment by meejah** [comment]
Ahhh, yes great point re: Docker and host vs. container etc. Also yes, "just removing" is then less code in CB CLI to maintain :) 👍

**Comment by oberstet** [comment]
so we keep `crossbar init`, but only to generate the single default node dir we ship. and for everything else (plus also the default), we point to cookiecutter. this sounds good.

and we might then officially deprecate the `--templates` argument and the `crossbar templates` command as well:

```console
(cpy362_1) oberstet@thinkpad-t430s:~/scm/crossbario/crossbar-fabric-public$ crossbar init --help
usage: crossbar init [-h] [--template TEMPLATE] [--appdir APPDIR]

optional arguments:
  -h, --help           show this help message and exit
  --template TEMPLATE  Template for initialization
  --appdir APPDIR      Application base directory where to create app and node
                       from template.
(cpy362_1) oberstet@thinkpad-t430s:~/scm/crossbario/crossbar-fabric-public$ crossbar templates

Available Crossbar.io node templates:

  default          A WAMP router speaking WebSocket plus a static Web server.

(cpy362_1) oberstet@thinkpad-t430s:~/scm/crossbario/crossbar-fabric-public$ 
``` 

because these then don't make sense anymore ..

**Comment by vlcinsky** [comment]
@oberstet and @meejah I think you got it. Nice to see so quick and deep reaction. Great.

I understand the reasons of current situation (pyramid went through very similar path).

To summarize my understanding of the situation:
- templating by crossbar brings problem
  - templates are difficult to maintain in sync with ongoing updates of crossbar
  - crossbar gets spoiled by task, which does not completely belong here as it has a bit different lifecycle (multiple types of clients being added and updated independently probably a bit slower than crossbar updates)
- current documentation does not pave path to quick success, in fact it leads to dead end.
- you feel the crossbar CLI deserves the init option to initialize the working environment with single default template (thus it can get rid of `--template` option).

I would propose:
- remove all the templates (as was already done)
- consider even removing the default one. Other python based solutions (like `celery` etc.) try to provide complete service but omit generating code, which is in fact out of their scope.
- the default template may live outside either as cookiecutter one, as referenced git repository or as whatever similar. I see, there are some pre-packaged javascript libraries, these are not simple to copy-past from doc so such support for initial steps is definitely needed in some form.

To keep the default template up to date with crossbar (incl. docs) will still require some effort, but the advantage would be, that updating may happen independently. On one side keep crossbar complete, well tested and released, on the other side keep the template or templates in shape with the freedom to update them as needed. With cookiecutter even users may customize the template on their own side.

Now I am really looking forward to play with crossbar.

**Comment by oberstet** [comment]
> Now I am really looking forward to play with crossbar.

great =)

I've splitted out the essence of above into a new issue https://github.com/crossbario/crossbar/issues/1173

**Comment by oberstet** [comment]
this implemented (via cookiecutter) in crossbarfx for some time now:

```
(cpy372_2) oberstet@intel-nuci7:~/test4$ ./crossbarfx-linux-amd64-20190108-9553865 quickstart

Crossbar.io / XBR Project Quickstart

  0: Exit

 Crossbar.io:

  1  : Create a Crossbar.io OSS app router            [gh:crossbario/cookiecutter-crossbar]
  2  : Create a Crossbar.io Fabric app router         [gh:crossbario/cookiecutter-crossbar-fabric]
  3  : Create a Crossbar.io Fabric cluster controller [gh:crossbario/cookiecutter-crossbar-fabric-center]

 XBR:

  4  : Create a XBR API bundle                        [gh:xbr/cookiecutter-xbr-api]
  5  : Create a Crossbar.io XBR data market           [gh:crossbario/cookiecutter-crossbar-fabric-xbr]

 Autobahn:

  6  : Create a Python based app or XBR service       [gh:crossbario/cookiecutter-autobahn-python]
  7  : Create a JavaScript based app or XBR service   [gh:crossbario/cookiecutter-autobahn-js]
  8  : Create a Java based app or XBR service         [gh:crossbario/cookiecutter-autobahn-java]
  9  : Create a C++ based app or XBR service          [gh:crossbario/cookiecutter-autobahn-cpp]

 Community:

  10 : Create a WampSharp/C# based app service        [gh:crossbario/cookiecutter-wampsharp]
  11 : Create a Nexus/Go based app service            [gh:crossbario/cookiecutter-nexus-go]

Please select [0]: 
```
