### ISSUE TITLE
Optional timeout on callee not found

### ISSUE THREAD

**Issue by Yamakaky** [crossbario/crossbar#1026]
For example, when I launch crossbar, one component starts doing a RPC before the callee is started. Crossbar could allow an optional timeout it waits before returning a "callee not found" error.

**Comment by meejah** [comment]
What is the real use-case here? It sounds like a dependency-type thing: component A needs to know when component B is ready to go?

**Comment by Yamakaky** [comment]
Yeah, that also works. Is there a way to do that?

**Comment by meejah** [comment]
You can wait for an appropriate publication, e.g. `foo.on_ready` and have the other component publish that when it's ready.

**Comment by Yamakaky** [comment]
OK, thanks

**Comment by oberstet** [comment]
Would best live on http://crossbar.io/docs/Programming-Guide/ probably
