### ISSUE TITLE
options.mime_types does not work in static webservice

### ISSUE THREAD

**Issue by mshahbazi** [crossbario/crossbar#1032]
I am trying to use the following config to grant access to htmls only. But it does not work.
```
"paths": {
	"/": {
		"type": "static",
		"package": "mypackage",
		"resource": "resource_name",
		"options": {
			"mime_types": {
				".html": "text/html"
			}
		}
	}
}
```
I have also tried the following, with no success:
```
"/":{                              
	"type": "static",                  
	"directory": "some_dir", 
	"options":{                        
		"mime_types": {                  
			".html": "text/html"           
		}                                
	}                                  
}
```

**Comment by vetsin** [comment]
mime_types is not for what I believe you are trying to do, see http://crossbar.io/docs/Static-Web-Service/#Configuration

**Comment by mshahbazi** [comment]
@vetsin thank you for your response. Still wondering if there is a clean way for that. I went through two alternatives:
1. use a `custom resource` inherited from `twisted.web.static.File` and check the extensions there. this seems clean but not sure about performance
2. move the shareable files to a folder (say `shared_stuff`). this seems somehow dirty. isn't it?

I was just hoping if crossbar natively supports granting/denying by extension or something.

**Comment by vetsin** [comment]
I would opt for 2, a directory with files in a public web root should all be public files. You serve `/var/www/mysite/` in a traditional context, not `/var/www/mysite/*.onlyThisExtension`. This seems the cleanest to me.

**Comment by mshahbazi** [comment]
I did 2 and am happy with it. Thanks for your time and advice
