### ISSUE TITLE
client implementations for actionscript3(flash)?

### ISSUE THREAD

**Issue by jonahzheng** [crossbario/crossbar#1035]
i want use swf connect to crossbar.

**Comment by jonahzheng** [comment]
why close it?

**Comment by goeddea** [comment]
Connecting to Crossbar.io from Flash requires a WAMP library for Flash/Shockwave. 

We at the Crossbar.io project have zero interest in creating this.

Personally, with Flash at end-of-life, I don't see why anybody would want this.

If somebody wanted to create this, then they are free to do so. The WAMP protocol is open, and Crossbar.io accepts any protocol-compliant WAMP connections.

**Comment by jonahzheng** [comment]
ok, I understand
