### ISSUE TITLE
Transition to unicode parameter strings

### ISSUE THREAD

**Issue by markope** [crossbario/crossbar#1049]
Hi,
autobahn-python with crossbar now seem to require unicode strings also in `self.join`. In my code e.g.

    `self.join(u'RE_acct', [u"wampcra"], u'system')`

In my app code execution just freezes if not unicode strings. An error message would be helpful here.

**Comment by meejah** [comment]
I see an assertion error. How are you running the client?

**Comment by markope** [comment]
I'am running it as an external worker like this:

```python
if __name__ == '__main__':
    from autobahn.twisted.wamp import ApplicationRunner
    extra = {
            "debug": True,
      }
    runner = ApplicationRunner(url=u"" + os.environ['POD_REACCT_CROSSBAR_URI'],
                               realm=u"RE_acct",
                               extra=extra)

    runner.run(myClass, auto_reconnect=True)

```
 
I use pypy 5.7.1 and autobahn 0.18.2

(not so high prio this issue) Could just as well be closed until I get you a reproducible issue description.

**Comment by meejah** [comment]
Okay. I was running mine using ApplicationRunner too (but I saw an assertion error printed).

**Comment by oberstet** [comment]
there are strict asserts for a long time now (in AB)

> we should have been migrated the issue to AB repo, but that is moot now that I'm closing it
