### ISSUE TITLE
Too verbose session logging

### ISSUE THREAD

**Issue by Yamakaky** [crossbario/crossbar#1061]
The router does this logging on client join/leave:
```
2017-04-29T12:39:08-0400 [Router      26631] >>>>> session 533088825379275 JOINED "radiokawaii" >>>>>

{'session': 533088825379275, 'authid': 'E947-QS3U-WY74-RRCX-Y6XW-JWPW', 'authrole': 'anonymous', 'authmethod': 'anonymous', 'authprovider': 'static', 'transport': {'type': 'websocket', 'protocol': 'wamp.2.json', 'peer': 'tcp4:127.0.0.1:48346', 'http_headers_received': {'host': 'localhost:60012', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0', 'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'accept-language': 'fr-FR,fr;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'sec-websocket-version': '13', 'origin': 'http://localhost:60012', 'sec-websocket-protocol': 'wamp.2.json, wamp.2.msgpack', 'sec-websocket-extensions': 'permessage-deflate', 'sec-websocket-key': 'TRsrBl9MoHyxAghKrokdWQ==', 'cookie': 'firstVisit=1492877341157; CSRF-Token-D4FUV=5beihHYWFb6qEqzkJf2G6Tu2dDAerbe9', 'dnt': '1', 'connection': 'keep-alive, Upgrade', 'pragma': 'no-cache', 'cache-control': 'no-cache', 'upgrade': 'websocket'}, 'http_headers_sent': {}, 'websocket_extensions_in_use': [], 'cbtid': None}}
```
which is ~10lines with line wrapping. Maybe keep the first line as INFO and the second as DEBUG?

**Comment by oberstet** [comment]
Problem is, putting it a DEBUG level means _tons_ of other logging.

And the info here is actually very useful in production - and since WAMP session are ment to be long-lived, it should be limited log volume.

**Comment by meejah** [comment]
I find it way too verbose too.
At the very least, the basically repr()'d dict should be properly formatted (and IMO I agree that part should be debug).

Being able to attach and get structured logs would mitigate the "debug is too much" problem -- then you can have a custom observer that only logs session join/leaves and details, for example (if that's what you're debugging at the moment).

**Comment by meejah** [comment]
My "fairly large" terminal (~140x60), taken up entirely with 4 join/leaves:

![too-much-logging](https://cloud.githubusercontent.com/assets/145599/25683622/3f844bd6-301a-11e7-9503-2ec5abf05596.jpeg)

**Comment by Yamakaky** [comment]
Yeah. One line or two is OK, 10 is too much.

**Comment by oberstet** [comment]
long fixed via above merged PR
