### ISSUE TITLE
Use h2 3.0 after next Twisted release

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1063]
Please see comments here: https://github.com/crossbario/crossbar/pull/1052

**Comment by oberstet** [comment]
We still have h2<3.0 in min requirements (https://github.com/crossbario/crossbar/blob/master/requirements-min.txt#L5)

Is that still needed after above was merged?

**Comment by meejah** [comment]
It looks from the logs like Twisted 17.5.0+ should support h2 3.0+

**Comment by oberstet** [comment]
fixed, we now use `h2>=3.0,<4.0`

https://github.com/crossbario/crossbar/blob/master/requirements-min.txt#L8
