### ISSUE TITLE
Documentation - collected feedback

### ISSUE THREAD

**Issue by goeddea** [crossbario/crossbar#107]
A collection of some of the feedback from the mailing list:
- there should be a FAQ
- References from the demos (in the ab|python repo) to the documentation: which feature does this illustrate, and where can I learn more about this
- Overview page with the core parts of the used technology (asyn programming, twisted, WAMP, ab libraries, crossbar.io) and links to articles explaining these (not necessarily in our documentation)
- Feature list for crossbar.io, giving an overview of everything which this is capable of
- Check terms consistency across the documentation
- Give a series of tutorials which build from the WebSocket and WAMP basics to advanced Crossbar features. Suggested ideal format: consumable in 10 minutes each, possibly with a Youtube video version.
- demos need more context - the user should be able to appreciate what is happening there irrespective of how he got there.

**Comment by goeddea** [comment]
reopening as part of the migration of the docs back to this repo - above still contains some valid points

**Comment by meejah** [comment]
ChangeLog/releases with features + bugfixes is very, very often requested...

**Comment by oberstet** [comment]
https://crossbar.io/docs/changelog/
