### ISSUE TITLE
Register option to kick existing registration [$5]

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1075]
Because of [this](https://github.com/crossbario/crossbar/issues/980#issuecomment-301296527), it would be useful to have an option for the client when registering a procedure to kick any existing registrations for the same procedure URI.

Maybe have two levels for this option:

* only allow to kick if the `authid` is identical to the one that originally registered the procedure
* allow to hard kick, even if `authid` is different

**Comment by oberstet** [comment]
The idea is to allow writing app code like this (ABJS):

```javascript
session.register("com.example.add2", add2, {force_reregister: true};
```

If the client is allow to register the resptive procedure _and_ (in case there already is an existing (non-shared) registration) is allowed to kick an existing registration, this will succeed then.

**Comment by oberstet** [comment]
This feature should probably be a general WAMP AP feature.

To do it "right", this (also) depends on https://github.com/wamp-proto/wamp-proto/issues/55

So the feature and its semantics should first be described in the WAMP AP spec.

Then we need to implement it in CB and 3 x AB.

**Comment by mbonneau** [comment]
This appears to be covered by #1114

**Comment by meejah** [comment]
This does indeed seem to be fixed now (besides the spec bug, but that's in wamp-proto).
