### ISSUE TITLE
no callee found but procedure still called

### ISSUE THREAD

**Issue by markope** [crossbario/crossbar#1081]
In my autobahn-js client upon a user button click I `call` a python procedure registered at crossbar .
The Front End log output from autobahn-js is: 
`"no callee registered for procedure <re.mgmt.000000004a3c584b.onled2>"`

The backend procedure's purpose is to light a lamp on a raspberry pi. 
Although "callee not found" on my raspberry pi the procedure is still called as I see an LED Lamp light up as a reaction to the button click. (The "log output" in this case)

autobahn-js 0.11.2
autobahn-python 17.5.1
crossbar 17.5.1

**Comment by oberstet** [comment]
So is obviously strange: haven't seen before.

We need more info: could you try adding a counter as payload (args) to the call, and log that counter both in the Pi procedure being called as well as in the frontend?

If the Pi logs the respective counter value, and the call returns with error for that counter, then this is verification that there is a problem. We can then go on from there ..

**Comment by markope** [comment]
Likely an issue in my front end (It was late yesterday, sorry). I'll open it again if seen again.

**Comment by oberstet** [comment]
@markope "was late" ..  np =)
