### ISSUE TITLE
Start crossbar.io programmatically

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [crossbario/crossbar#1083]
Objective
----------

I am have a simple publish server (in nodejs, using [autobahn.js][1]) that receives data from a machine and then publishes it to interested subscribers. 

I am currently doing integration tests and I need to know:

 -  If crossbar is running, I need to test if the server is able to successfully connect to it
 - If not, I need to launch crossbar, run the previous test, and then kill crossbar

Problem
------

As far as I know, there is not way to either detect if crossbar is running, or to launch it from code. Furthermore my research led me to this github issue:

 - https://github.com/crossbario/crossbar/issues/655

Which makes me believe that running integration tests with crossbar, if not impossible, needs a relative elaborated workaround. 

Questions
-------

1. Is there a way to start and test if crossbar is running programmatically?
2. If not, how do you perform integration tests with crossbar?

  [1]: https://github.com/crossbario/autobahn-js

**Comment by oberstet** [comment]
> Is there a way to start and test if crossbar is running programmatically?

Open a connection and handle a failed connection attempt in your client.

> If not, how do you perform integration tests with crossbar?

Using Docker, starting Crossbar.io in a Docker container, and then start app component containers.

**Comment by meejah** [comment]
Also, there is a way to test if crossbar is running: `crossbar status` will exit 0 if there's a crossbar running in the indicated directory, or non-zero if not.
