### ISSUE TITLE
CLA Assistant

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1085]
"Streamline your workflow and let CLA assistant handle the legal side of contributions to a repository for you. CLA assistant enables contributors to sign CLAs from within a pull request.":

* https://cla-assistant.io/
* https://github.com/cla-assistant/cla-assistant

Open-source, made by SAP, hosted by SAP.

**Comment by oberstet** [comment]
This provides a very nice automated handling and integration with GitHub.

Here is a PR by me on a project that uses CLA Assistant: https://github.com/bountysource/core/pull/1105

**Comment by goeddea** [comment]
Had a look at this a while back, and from what I saw this all depends on the continued hosting by SAP. I did not see a way to extract the data from the service so that we can keep a full record of our own.

Closing
