### ISSUE TITLE
Invalid pointer when using subprocess and pypy

### ISSUE THREAD

**Issue by jacobanana** [crossbario/crossbar#1091]
Hello,

I am trying to migrate a working crossbar application from using CPython on a Raspberry Pi to using Pypy. Unfortunately, I am expecting some issues with subprocess calls and I am getting the following messages:

`*** Error in 'crossbar-worker [container]': free(): invalid pointer: 0x745aa9e0 ***`
The subprocess returns error code -6

This can be easily reproduced with just a subprocess call in the onJoin method:
```
    def onJoin(self, details):
        print subprocess.call("ls")
```

This is using the following version of Pypy:

```
 Crossbar.io        : 17.5.1 (Crossbar.io COMMUNITY)
   Autobahn         : 17.5.1 (with JSON, MessagePack, CBOR, UBJSON)
   Twisted          : 17.1.0-EPollReactor
   LMDB             : 0.92/lmdb-0.9.18
   Python           : 2.7.13/PyPy-5.7.1
 OS                 : Linux-4.4.38-v7+-armv7l-with-debian-8.0
 Machine            : armv7l
 Release key        : RWRrH63dDsFR7o8Z7+7gv1uLF4qPKyZXq45Ble52SJ33KFz1UicMyq0b
```

This issue only happens from within a native crossbar worker, if subprocess is called directly from Pypy there is no issue.

Please let me know if you have any idea

Regards
Adrien

**Comment by meejah** [comment]
Interesting! Always rare to get segfault-style crashes in Python ;)

This likely isn't related, but when doing async-things you shouldn't do "blocking" operations (like subprocess.call). Instead, use Twisted's (or asyncio's) subprocess support to get non-blocking style subprocess launching.

(There's also the Python builtin `os.listdir()` if you really did just want to "ls").

Is this on *any* subprocess call? Can you try the same thing without crossbar etc involved at all? (i.e. this is most likely a PyPy bug)

**Comment by jacobanana** [comment]
Hi meejah

I tried without crossbar involved and this problem doesn't occur (the subprocess calls just work fine when called from pypy). 

By the way, the "ls" was just an example that was easy for me to replicate, I'm actually calling something else in my application.

I'll have a look at twisted subprocess support for that, I wasn't aware this was available.
Cheers

Adrien

**Comment by meejah** [comment]
Okay, thanks!

**Comment by jacobanana** [comment]
Hi Meejah

I've now tried replacing the subprocess call with Twisted's implementation and the same error happens.

More investigation showed that the error was caused by another library in my stack. Sorry about that.

Adrien
