### ISSUE TITLE
open_handshake_timeout for wss

### ISSUE THREAD

**Issue by DVridovic** [crossbario/crossbar#1093]
Hi

I'm trying to connect to wss://api.poloniex.com:443 from autobahn-cpp using Crossbar router and this works occasionally but most of the times I get

[2017-06-04 16:08:16] [connect] Successful connection
[2017-06-04 16:08:21] [fail] WebSocket Connection 104.20.12.48:443 - "WebSocket++/0.7.0" / 0 websocketpp:22 The opening handshake timed out

I tried settin the open_handshake_timeout option as described at http://crossbar.io/docs/WebSocket-Options/. I added

                {
                   "type": "websocket",
                   "endpoint": {
                      "type": "tcp",
                      "port": 443
                   },
                   "url": "wss://api.poloniex.com:443",
                   "options": {
                      "open_handshake_timeout": 10000
                   }
                }

at the end of "transports": section in .crossbar/config.json and the error message I get when I try to start Crossbar is

twisted.internet.error.CannotListenError: Couldn't listen on any:443: [Errno 13] Permission denied.
What is the propper way to configure this section for a wss connection?

**Comment by DVridovic** [comment]
Oh thank you very much. It's been more than a month.

**Comment by oberstet** [comment]
Sorry, but there is a big big 

> Before you submit an issue, please review the guidelines for contributing to this repository.

notice when you submit an issue. Did you read that?

**Comment by oberstet** [comment]
As in https://github.com/crossbario/crossbar/blob/master/CONTRIBUTING.md#asking-questions

**Comment by DVridovic** [comment]
It doesn't matter any more. I switched to other tools.

**Comment by oberstet** [comment]
Your community manners are stunning! ;)

**Comment by DVridovic** [comment]
Thank you very much for your timely and helpful answer.I 'm sorry that there appears a bit of text that I haven't red before before posting a question. I was trying to start using five or six new technologies at the same time so apparently I have missed something. I know that I should be ashamed and I will never do this again. Is that better? Come on, you could have told me this a month ago. Now it's too late, by any criterion.

**Comment by oberstet** [comment]
So you don't even have the time to read a big notice, kindly asking to follow our guidelines (which are there for a reason) but you expect us to answer your questions and help out immediately?

This isn't how it works. Not here. And not in any other respected open-source community. But hey, this is just me. You will make your own experiences ...
