### ISSUE TITLE
Implement authentication: client certificate based

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#11]
From https://github.com/crossbario/crossbar/wiki/Authentication-Methods

**Comment by pataelmo** [comment]
I really want this for my project.  So I dug through the code and put a hack in to make it work in my application, but was hoping you could give guidance on a better method.

To simplify things I have my crossbar hidden behind a nginx proxy, so I setup client certificate validation in nginx, and passed "X-Client-Verified" and "X-Client-DN" headers onto Crossbar

in crossbar/router/protocol.py (around line 209) I added some code to parse the request headers before the cookie parsing code to extract those values.  If verified then I get the CN from the DN header and use that for the authid.  Much more hacky i just set the authrole to what I needed and authmethod to 'ssl-cert'.

I feel like there should be a better way to manage how the authrole gets set.  I'd like to be able to set it based on either a forwarded http header or based on authid.

Let me know your thoughts and if you'd like to integrate this into the project how best to do so. (Where should this code really go, and is there a branch or place you'd like me to put this before doing a pull request?)

**Comment by meejah** [comment]
See https://github.com/crossbario/crossbar/blob/master/legal/contributors.md and http://crossbar.io/docs/Contributing-to-the-project/ -- because the project is AGPL you'll have to sign your copyright over before a patch can be merged. 

As far as an actual patch, simply fork the crossbar repo and put your code in a branch like "issue11-client-certificates" with a pull-request when finished (or when you want further feedback). If you do fine-grained commits, it'd probably be worth squashing (some of) them before the PR.

I haven't looked into the specifics you mention above about client-certificates yet, just commenting on the mechanics of contributing ;)

**Comment by pataelmo** [comment]
Thanks for the details. I will fork and push my code there for review and get my CAA signed and emailed in.

**Comment by oberstet** [comment]
@pataelmo We've received your CAA - thanks! I've added you to the list here https://github.com/crossbario/crossbar/blob/master/legal/contributors.md

**Comment by oberstet** [comment]
@pataelmo To your actual itch: authenticating WAMP clients to Crossbar.io using client certificates, but where the TLS termination is done by a reverse proxy:

This should be possible using a custom authenticator. E.g. see here for a WAMP-CRA example. Custom authenticators get transport level information as well. Which in case of WebSocket includes all HTTP headers (means you get the `X-Client-Verified` and `X-Client-DN`).

Since in your case the client fully authenticates at the transport level, neither WAMP-CRA or WAMP-Ticket applies, but we would need the option to have custom authenticators even for WAMP "anonymous" (where the client doesn't provide auth info at WAMP level).

Note: we _also_ want to have the option to let Crossbar.io terminate the TLS and do the auth dance. But that is different from above.

**Comment by oberstet** [comment]
see: https://github.com/crossbario/crossbarexamples/tree/master/authenticate/tlsdynamic
