### ISSUE TITLE
Better logging

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#111]
We really need better logging. In particular related to application components and problems with importing, loading, connecting and running those.

E.g. start of a WAMP Python app component might fail because of

* PYTHONPATH issues
* syntax errors in the component
* failing imports in the component
* ...

**Comment by hawkowl** [comment]
I'll definitely have to come up with some test cases for failing components and make sure (useful) logs are produced...

**Comment by meejah** [comment]
The imports are easy: if you define a component of type ``class`` and just put a syntax error in the ``.py`` file you don't see the error in crossbar logs. I have *some* code for one of these from some debugging I did recently; I'll try with the most recent updates.

**Comment by hawkowl** [comment]
#407 should fix up the final edge case -- it'll raise up the syntax error.

**Comment by hawkowl** [comment]
This particular ticket, I think, can be closed -- if there's any further issues, I think they're best done as new tickets with a particular focus.
