### ISSUE TITLE
Crossbar doc pages should display page name in HTML title

### ISSUE THREAD

**Issue by markerikson** [crossbario/crossbar#1112]
Currently, all docs pages under http://crossbar.io/docs/ have an identical HTML title: "Crossbar.io".  I've got about 25-30 docs tabs open, and I can't tell which one is which just by looking at them.  It would be _very_ helpful if the docs pages actually included the page name as part of the HTML title, like:  "Crossbar.io - Authorization", "Crossbar.io - Processes", etc.

**Comment by oberstet** [comment]
the docs will be moved to RTD (https://github.com/crossbario/crossbar/issues/1976), and then will have differentiated titles automatically, eg like https://autobahn.readthedocs.io/en/latest/
