### ISSUE TITLE
404 repo 

### ISSUE THREAD

**Issue by dberuben** [crossbario/crossbar#1118]
@crossbario what happened to http://package.crossbar.io ?  I get a 404 now for the centos repo??

**Comment by goeddea** [comment]
We are no longer providing packages for Crossbar.io (and haven't been for a while). This is reflected in the current documentation, which recommends either using Docker or installation in a virtualenv - see http://crossbar.io/docs/Installation-on-Linux/.

**Comment by tanhaa** [comment]
"for a while".. i was able to get packages for centos just couple of weeks ago, perhaps older packages, but now the repo is closed I assume.

**Comment by goeddea** [comment]
@tanhaa - corrected this to "haven't been **updating** them for a while"

Yes, the repo is no more.

**Comment by tanhaa** [comment]
yah realized it after my chef cookbook broke that the repo is no more.  Thanks for your time in replying to this and letting us know that it won't be coming back, I thought it may have been broken and just wanted to make the team aware of this.  We will adjust our cookbooks to use pip instead.

**Comment by oberstet** [comment]
Sorry for the inconvenience - we have limited resources and need to pick our fights.pip in a dedicated virtualenv is fine and fully supported.As is DockerAnd snaps (we have Crossbar.io already in the beta store there, though it is currently tracking head of master here - it will auto build and publish on each commit on master!).Classic distro packages are no longer supported - and we hadn't been updating them for a longer time already.Am 28.06.2017 19:42 schrieb Amit Malhotra <notifications@github.com>:yah realized it after my chef cookbook broke that the repo is no more.  Thanks for your time in replying to this and letting us know that it won't be coming back, I thought it may have been broken and just wanted to make the team aware of this.  We will adjust our cookbooks to use pip instead.
