### ISSUE TITLE
Add txtorcon as a dependency

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1130]
Crossbar.io runs over Tor - _if_ [txtorcon](https://github.com/meejah/txtorcon) is installed. The requirements of txtorcon do not add further dependencies above what we already have in CB.

**Comment by agronholm** [comment]
Add it as an extra maybe?

**Comment by oberstet** [comment]
Merged.

@agronholm txtorcon does not add deps beyond what CB already has https://github.com/meejah/txtorcon/blob/master/requirements.txt

**Comment by agronholm** [comment]
Perhaps, but txtorcon itself is not needed by the vast majority of users. It is customary to add such rarely needed dependencies to extras, all of which would be included in the Crossbar Docker image. But, your call.
