### ISSUE TITLE
Add support for binary response in RESTCallee

### ISSUE THREAD

**Issue by mtrofimm** [crossbario/crossbar#1138]
I have a running a simple file server that serves binary files (jpg) over http.
I'm looking for a solution to integrate this service into my microservice architecture built on crossbar server. 
I tried to use HTTP Bridge Callee  (RESTCallee) without success, because:
- response is serialized (probably because of usage of text_content from treq in RESTCallee).
- Content-type (which is image/jpeg) is replaced with application/json

I would be nice if the whole response and headers were returned without modification/serialization etc.

Thanks!!

related to #1067

**Comment by meejah** [comment]
Can you describe what you're trying to do? It sounds like you are trying to eliminate your server that serves JPG by having crossbar do it?

**Comment by meejah** [comment]
(Also, it might be better to try asking on the mailing-list/google-group or #autobahn on Freenode IRC)

**Comment by meejah** [comment]
http://crossbar.io/docs/Static-Web-Service/
