### ISSUE TITLE
Concurrent calls are handled incorrectly

### ISSUE THREAD

**Issue by koxu1996** [crossbario/crossbar#1145]
# Description
I wanted to see how Crossbar deal with concurrent calls, so I added `sleep(1)` to my function and called it few times. I expected to get all responses after 1 second or one response every second in case of sequential execution. But actual behaviour astonished me: I get first response after 1s but other responses comes together after several seconds:
![issue_php](https://user-images.githubusercontent.com/6506780/28462670-72f0f29a-6e1c-11e7-89e2-309aeea9935e.gif)
I thought it can be _Thruway_ issue, but using _AutobahnPy_ I get same result:
![issue_py](https://user-images.githubusercontent.com/6506780/28462695-97ba24de-6e1c-11e7-8d9f-104a747d7692.gif)

# Version:
```
Crossbar.io        : 17.6.1-3 (Crossbar.io COMMUNITY)                                                
Autobahn           : 17.6.2 (with JSON, MessagePack, CBOR, UBJSON)                                   
Twisted            : 17.5.0-EPollReactor          
LMDB               : 0.92/lmdb-0.9.18             
Python             : 2.7.9/CPython                
OS                 : Linux-4.4.0-83-generic-x86_64-with-debian-8.8                                   
Machine            : x86_64                       
Release key        : RWTAY0Umy44F3jAVWG+tEYunifD02Kmn4Pxc2cHUMEd2sckt/llYhRXp
```

# Steps to reproduce the issue
1. Download [issue.zip](https://github.com/crossbario/crossbar/files/1165450/issue.zip) and unpack
2. Run `composer install` and `crossbar start`
3. Open `index_php.html` or `index_py.html`

**Comment by oberstet** [comment]
Use `autobahn.twisted.util.sleep` instead of the Python standard library `time.sleep` - the latter is blocking the reactor, the former not.

**Comment by koxu1996** [comment]
@oberstet So non-async code won't be executed concurrently, because workers are using only single threads?

**Comment by oberstet** [comment]
To run code concurrently (utilize multiple cores), you must use threads or processes. To run blocking code, this code must be run on a background thread, because you must not block the event loop. Both of these statements are true in general (not specific to Crossbar.io, Autobahn, Twisted or even Python).

**Comment by koxu1996** [comment]
Ok, I understand. But in case of blocking code, could you explain weird behaviour presented on gif?

**Comment by koxu1996** [comment]
I see this is random. Sometimes there are 4 response after 4 sec. and last after 1 sec. more:
![ezgif-4-774105f0db](https://user-images.githubusercontent.com/6506780/28470797-2f0a8266-6e3b-11e7-9186-926674446be3.gif)

**Comment by meejah** [comment]
While you're `sleep`-ing, the reactor can't do *anything* (including receive or send data that's ready). I'm not sure exactly what happens after that, but blocking the reactor in this way will definitely lead to bad/weird behavior, as you've discovered ;)
