### ISSUE TITLE
DOC: need to mention pypy-dev and python-dev Ubuntu packages

### ISSUE THREAD

**Issue by mattip** [crossbario/crossbar#1150]
The [documentation](http://crossbar.io/docs/Installation-on-Linux/) does not mention the python-dev and pypy-dev packages necessary to compile c extensions for either python. While I am not sure about python, pypy definitely requires the pypy-dev package on Debian based system like Ubuntu.

Also you might want to add a link to this repo to the [contributing](http://crossbar.io/about/Contributing-to-the-Project/) page.

**Comment by mattip** [comment]
Looking more carefully at your process, rather than recommending ```apt get install pypy pypy-dev``` you recommend using wget from the bitbucket downloads. Maybe you could mention both alternatives.

**Comment by meejah** [comment]
The docs lean heavily towards "install the latest version" (i.e. not "the thing packaged by Debian"). I believe if you install that way you've already got what's in the `-dev` variants from Debian, right?

(In any case, it would be worth mentioning that you could rely on packaged python/pypy but would need the -dev packages too). That said, Debian's `pip` is really ancient (although should be a little less so now that jessie is stable) and means you have to run `pip install -U pip setuptools` on all new virtualenvs created with the packaged virtualenv :/

**Comment by oberstet** [comment]
fwiw, the docs https://crossbar.io/docs/Installation-on-Linux/#install-for-pypy refer to the pypy package, not the OS distro packages now
