### ISSUE TITLE
crossbar not works on windows7x64

### ISSUE THREAD

**Issue by alexey2baranov** [crossbario/crossbar#1156]
Hello! We tried our project on Win7x32 machine. Crossbar was installed successfully. After start crossbar we got this error

No modele named win32api

![default](https://user-images.githubusercontent.com/19248996/29024025-fed4de48-7b91-11e7-8b25-0c3e11104b6e.jpg)

**Comment by goeddea** [comment]
As per these instructions http://crossbar.io/docs/Installation-on-Windows/ you need to install win32api.

**Comment by alexey2baranov** [comment]
@goeddea thank you for reply. I did everything from this manual including pywin32 from hire
https://sourceforge.net/projects/pywin32/files/pywin32/Build%20221/pywin32-221.win32-py2.7.exe/download

And it is not works anyway

**Comment by alexey2baranov** [comment]
maybe we should start crossbar from some folder not from any other ?

**Comment by oberstet** [comment]
Do you have matching CPython and pywin32 versions? You need 2 x 32 Bit (mixing 32/64 bit won't work).

It does not matter from where you start crossbar.

You need pywin32 correctly installed into the same Python installation into which Crossbar.io is installed.

**Comment by alexey2baranov** [comment]
@oberstet hello! absolutely 32bit python and 32 bit win32api

**python**

> Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32

win32api (32bit, not amd64)
https://sourceforge.net/projects/pywin32/files/pywin32/Build%20221/pywin32-221.win32-py2.7.exe/download
installated into the same folder as python
![default](https://user-images.githubusercontent.com/19248996/29025702-7a7f6ae6-7b91-11e7-8bbe-8f1f0871e82b.jpg)

**Comment by oberstet** [comment]
sorry, no clue. your pywin32 isn't installed  correctly I guess. maybe just start python and check if `import win32api` works .. it should. anyways, my recommendation would be Docker. I can't test windows as we have a windows free company.

**Comment by alexey2baranov** [comment]
@oberstet sounds hard for me. we write JS project and don't know Python absolutely. could you write few lines of code how to check this?

**Comment by oberstet** [comment]
@alexey2baranov run `python -c "import win32api"` in a shell
