### ISSUE TITLE
update installation instructions

### ISSUE THREAD

**Issue by goeddea** [crossbario/crossbar#117]
Installation instructions need to be checked whether they reflect the current state.

* [x] Windows: instructions for minimal installation and full installation
* [ ] Mac OSX

**Comment by oberstet** [comment]
Yep, I agree:

* we should get rid of the offered binary download package altogether.
* only the bare minimum to get CB running on Windows should be describe (anything more is for "powerusers")
* db integration : also remove

**Comment by goeddea** [comment]
- removed DB integration
- removed the reference to the binary download package
- left the instructions for full install - nobody needs to read this far for the basic install, and better to have this here than to have people ask
