### ISSUE TITLE
forum.crossbar.io ?

### ISSUE THREAD

**Issue by om26er** [crossbario/crossbar#1194]
Forums are very important, they are a very great way through which developers interact. We currently rely on Google Groups. It works but the interface is clunky and confusing, we could do better.

We need a single place where all the conversations around Crossbar and Autobahn libraries happens, which supports better tags, supports creating wiki pages, allows to refer people and posts and makes us look something of the future.

Two websites that I visit frequently use this very nice template, I am not sure what's its name or who the creator is but I presume its something we could really consider.

https://www.pakwheels.com/forums/t/honda-n-one-fan-club/243635
https://forum.snapcraft.io/

**Comment by om26er** [comment]
So those websites are based on [Discourse](https://github.com/discourse/discourse)

**Comment by oberstet** [comment]
I am +1 on this!

**Comment by oberstet** [comment]
@goeddea ^

**Comment by oberstet** [comment]
@oddjobz $5/month for the whole app (kinda SaaS?) sounds very reasonable;)

discourse.org itself calls for $100/month for minimum plan (https://payments.discourse.org/pricing)

the other aspect I'd like to throw in: currently, we have everything on AWS. do we want another hosting contract (digitalocean)? but I guess from a TCO perspective, as on AWS we would need to run an own VM, the 5 bucks per month is pretty much a no brainer.

so from my side, digitalocean would be okay. we can raise the issue on a team call gathering opinions,  consensus and make a decision.

**Comment by meejah** [comment]
The difference is Digital Ocean will just be a "ready-to-go install" and then all maintenance etc is on us (whereas I guess the $100/month thing is "fully managed")...

(I use digitalocean and it's great for what I use it for -- the $5/month is a single-core machine, 20gb storage, 1TB bandwidth see https://www.digitalocean.com/pricing/)

**Comment by oberstet** [comment]
ah, ok! in this case:

if we have to maintain it ourself on digitalocean, then tbh I would rather stay on AWS (one contract, technical/admin synergies) **OR** go straight for "fully managed" on the discourse.org entry level plan.

> AWS starts with `t3.nano` which is $4.38/month when using on-demand instances - without EBS storage, but that is dirt cheap (in this context)

**Comment by oddjobz** [comment]
If it runs in 0.5G ram, then technically you could put it on a nano. In terms of performance however, you might find Discourse may struggle a little at that level. A 5$ instance on DO will provide many times the performance of a typical nano instance (and 1G of ram). Just as an off-the-cuff comparison, this is our main demo instance on a micro, which should be twice the performance of a nano;

#### hdparm -tT /dev/xvda1
/dev/xvda1:
 Timing cached reads:   18824 MB in  1.99 seconds = 9443.23 MB/sec
 Timing buffered disk reads: 244 MB in  3.00 seconds =  **81.29** MB/sec

And this is a 5$ DO instance;

#### hdparm -tT /dev/vda1
/dev/vda1:
 Timing cached reads:   18164 MB in  1.99 seconds = 9112.02 MB/sec
 Timing buffered disk reads: 2270 MB in  3.00 seconds = **756.58** MB/sec

(these were completely random, login/bang, no cache pre-loading or anything else)
CPU usage tends to follow a similar trend comparatively.

(what maintenance are we expecting to have to do?)

**Comment by oberstet** [comment]
yeah, I agree, a nano instance is probably not suitable. a micro instance on AWS should be good enough.  _if_ we host that ourself on not just use the discourse.org hosted plan. I would prefer not having another hoster for IaaS/etc stuff (digitalocean) besides AWS

> (what maintenance are we expecting to have to do?)

good question. I have no clue about discourse. which makes their SaaS offering somewhat attractive;)

however: can we have our own domain (eg `https://forum.crossbar.io`) when using the discourse.org hosted paid plan? not sure. quickly looked at their FAQ and couldn't find relevant info ..

**Comment by om26er** [comment]
They offer free hosting for open-source projects. The only (but blocker) problem I see with that is we can't use our own domain. We can probably check with them if they will allow us to use our domain instead (forum.crossbar.io)

https://blog.discourse.org/2018/11/free-hosting-for-open-source-v2/

**Comment by om26er** [comment]
We can probably copy over existing topics from Google Groups as well https://meta.discourse.org/t/importing-mailing-lists-mbox-listserv-google-groups-emails/79773

**Comment by oberstet** [comment]
ah, right! we actually are OSS;) also should qualify (more than 15 contributors). and this is about migrating the public forums from G, _not_ any private or commercial forums.

considering all above, how about using their free tier for OSS and be fine with `https://crossbar.discourse.group` ?

this spares us precious admin time (and hosting money of course)

---

there is another Q: currently we have 3 lists: AB, CB and WAMP

we could migrate AB+CB onto `https://crossbar.discourse.group` and WAMP nto `https://wamp.discourse.group`

note: we should not (IMO) collapse all 3 into 1 crossbar list, as the WAMP list is supposed to be neutral ground. plus: we need to ask the editors for agreement. means: post an issue on https://github.com/wamp-proto/wamp-proto etc. I _think_ it has been brought up before (move away from G) ..

**Comment by oddjobz** [comment]
Free version sounds cool .. :) .. just one query; it looks like discourse does support importing stuff from external sources, in terms of capability .. but I notice on the Free Hosting basic terms is says "We do not support imports" .. ?

**Comment by oberstet** [comment]
With "importing", you mean importing the history of posts from the google groups lists? If so, yes, that would very good if possible. I don't know whether that's possible on the free/oss tier

**Comment by oddjobz** [comment]
Well, I've never used discourse, the board I maintain uses SMF, but discourse looks good and I can see there are instructions for importing discussions for from google groups to discourse .. but I also see this "no  support for imports" clause on the free tier solution ...

**Comment by goeddea** [comment]
+1 for moving to something which has a better UI and more features. 

If I understand this correctly, then the feature tiers are for the hosted version only, with the OSS version available for installation using Docker and unlimited (?)

**Comment by meejah** [comment]
@goeddea yes, the "feature tiers" are for the hosted service. If we just downloaded + installed their software (whether on DigitalOcean or AWS) then we could do whatever we wanted (i.e. any feature they have). Of course, that comes with "someone has to do it" as a caveat ;)

The "+1" for the hosted option, for me, is that nobody here knows anything about Discourse and if the forum goes down, or database, or "whatever" then again "someone has to fix it" and that $X/month can pay itself off pretty fast then :)

**Comment by om26er** [comment]
uh, discourse have interesting customers. Linkin Park are their customer as well ;-) https://www.discourse.org/customers
![discourse-customers](https://user-images.githubusercontent.com/6350837/51132980-8ee26800-1855-11e9-85bc-bdcab1cdb95e.png)

**Comment by oddjobz** [comment]
+1 for diy .. automatic backups are a tickbox when creating a droplet on DO, I think for an extra $5 a month. If recovery is an issue, to recreate from a backup (snapshot) is handful of clicks, maybe 20 secs + boot-time. [that was me volunteering .. ;) ]

**Comment by meejah** [comment]
I'm definitely :+1: for self-hosted .. but also trying to be realistic that the cost is more than just cost of VPSes ;)

**Comment by oddjobz** [comment]
Sure, I know what you mean .. :) .. on balance tho', my annual time spend on forum maintenance is maybe a couple of hours, so if Discourse isn't a turnkey system that "just works", it might not be the right solution.

**Comment by oberstet** [comment]
as far as I see (from the infos collected):

* 1 and 2 do _not_ allow B. only the $300/month Discourse paid plan, 3 and 4 allow B.
* 1 and 2 have the least amount of admin work C, while 3 and 4 require more work - 4 possibly less than 3
* 4 is in conflict with D

if above is correct, there is no "best solution" (one that satisfies all of A-D). I am not ready to shelf out $300/month for the M-size paid plan now (which would satisfy all of A-D as I understand it).

so we need a compromise.

---

**in the light of above, my vote is for 3**

**Comment by oddjobz** [comment]
Would agree in principle, although performance was also mentioned above. 
(but I would still "vote" (4) :) )

**Comment by oberstet** [comment]
ok! could you explain why 4 is better than 3? is it about head start, because of this "one click" app thing of DO? other reasons? trying to understand the why better ..

> rgd performance: I didn't get into this (sorry, I read it and deliberately skipped it;), because I don't "believe those numbers" as in: is that instance local SSD? AWS was EBS? apples & oranges;) hdparam: not a reliable _performance_ benchmark tool (like fio). I would not believe any perf number coming out of it (rgd IO perf I have some experience on high end gear here). Then I don't feel like IO perf matters for this (discourse, given the expected load) etc. For me, this is a sidetrack .. hence the skipping. If you care about getting to the bottom of this line, I'd be ready. but it'll be likely a longer discussion;)

**Comment by oddjobz** [comment]
Ok, I read the first sentence and spent a while trying to explain and then realised the second paragraph wasn't a paste of previous text. I'm well aware "hdparm" isn't a benchmark, but if you think it's irrelevant and that IO is also irrelevant, any discussion is pretty pointless.

**Comment by oberstet** [comment]
sorry about "hiding" the 2nd comment in a note!

I figure IO performance is supposed to be the main argument for DO vs AWS then?

In that case, yes, I don't believe that this is the case (DO is faster than AWS when comparing apples to apples .. see below), and also don't think it is relevant for this workload (Discourse for our forums).

---

fwiw, here is a FIO control file which replicates PostgreSQL workload (PG does _all_ IO in 8kB and sync) - Discourse data is stored in PG.

```
[global]
group_reporting

# put the dataset file on the fast storage
filename=/tmp/test.dat

# ideally dataset should be at least 4x RAM
size=32G

# PostgreSQL does all IO 8k-sync
ioengine=sync
bs=8k
iodepth=1

# this should be at least #core/HTs (possibly higher, test)
#numjobs=32
numjobs=8

time_based=1
randrepeat=0
norandommap=1

# ideally, first burn for an hour to get the flash controller into steady state
ramp_time=240
runtime=120

[randread]
stonewall
rw=randread

[randwrite]
stonewall
rw=randwrite

[randreadwrite7030]
stonewall
rw=randrw
rwmixread=70
```

---

On AWS, the fastest storage comes with `d-type` instances, eg `c5d.large`. those have locally attached NVMe. EBS will be nowhere as fast, which is expected.

So if the question is whether locally attached storage on DO is faster than on AWS, I would compare using a FIO control file like above, and run that loong.

My best bet would be: not much of a difference.

To get max IO performance on AWS requires big d-type instances and striping over multiple NVMe (Linux MD) plus XFS plus libaio or mmap'ed IO (and a software that can make use of that .. PG cannot do that). LMDB does the latter for read, and it can optionally do for write too (mmap)

**Comment by goeddea** [comment]
+1 for our own hosted Discourse

Not sure how much overhead we're talking about with a Digital Ocean account.

**Comment by oddjobz** [comment]
I thought you were talking about putting the forums on a micro? If so, comparing apples to apples is comparing an AWS micro with a DO 5$? I'm not sure where a c5d.large comes into it?

**Comment by oberstet** [comment]
I assumed it was about IO (disk) performance in general AWS vs DO, hence c3d.large etc

For a concrete comparison using gear that fits the workload, since I don't know about DO, this is what I would use on AWS:

Discourse requires 2GB RAM, so I'd use a `t3.medium` (or `t3a.medium` or `a1.large`) instance on AWS: 4GB RAM (give it a little room above minimum requirement) and EBS storage only.

Would use 3 EBS volumes for the instance: 1 x EBS system, 2 x EBS data and put a ZFS pool (mirror) over the 2 EBS data volumes.

---

The $5 DO thing: what exactly is that? What kind of storage does it have? I assumed given the IO numbers posted that it only can be instance local SSD - and that is not suitable for PG as instance local storage can disappear any time (if DO works similar to AWS).

**Comment by oddjobz** [comment]
DO does not work in exactly the same way as AWS. Personally I think the way AWS disappears local storage is a bit .. questionable. Discourse only needs 1G of RAM. Another DO feature; it's easy to change the CPU/Memory allocation on a running instance without the need to recreate it. (and you can also increase the size of the local storage ... as well as attaching block storage or S3)

**Comment by oddjobz** [comment]
My forums, $5 instance, $5 for automatic snapshot backups, 40k posts, 4k members, 9 years, SMF+MySQL .. I won't say your AWS configuration isn't better, I will say the DO approach is cheaper and works very well.

**Comment by oberstet** [comment]
Do you know what the availability and durability guarantees (and lifecycle) DO announces for

* Droplet local storage (https://www.digitalocean.com/products/droplets/) an
* Block storage (https://www.digitalocean.com/docs/volumes/overview/)

?

The Block Storage of DO .. that at least seems similar to AWS EBS, right?

What type of storage are you using for the data on your forum running Droplets on DO?

---

Assuming for a moment DO is strictly better than AWS in technical terms and pricing ($5 vs $35), do you think it would be fair to say that it then boils down (for us) to:

Is it worth having another IaaS hoster contract/relation etc on top of AWS to save 30 USD / month?

(honest question .. I am not trying to spin-doctor the Q here .. this is just how I look at it)

> Note: we won't move off AWS to DO _in general_. so above discussion is about Discourse hosting at most. Just a comment to not to trigger "hopes" in that direction (should there be any).

**Comment by meejah** [comment]
I've been using DO for years and really like it (I've never lost data, but my droplets have occasionally been migrated or rebooted -- but always with warning). But, I just don't have much experience with AWS.

DO actually bills by the minute, BTW. So e.g. spinning up "lots" of droplets for a quick load-test would also be a thing that's possible (but I guess also with AWS).

IMO, it's probably best/easiest to let whomever is maintaining Discourse choose...?
