### ISSUE TITLE
idna > 2.5

### ISSUE THREAD

**Issue by singlecheeze** [crossbario/crossbar#1196]
Not sure if intentional (in case idna 2.6 possibly breaks something in crossbar) but it would be awesome to have the dependency declared as greater than 2.5, rather than hard set.

Popular latest **requests** [package](https://pypi.python.org/pypi/requests) now requires idna 2.6:

Release History
---------------
2.18.4 (2017-08-15)
+++++++++++++++++++
**Improvements**
- Error messages for invalid headers now include the header name for easier debugging
**Dependencies**
- We now support idna v2.6.

```
pip3.6 install -U requests
Requirement already up-to-date: requests in /usr/lib/python3.6/site-packages
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in /usr/lib/python3.6/site-packages (from requests)
Collecting idna<2.7,>=2.5 (from requests)
  Using cached idna-2.6-py2.py3-none-any.whl
Requirement already up-to-date: certifi>=2017.4.17 in /usr/lib/python3.6/site-packages (from requests)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.6/site-packages (from requests)
Installing collected packages: idna
  Found existing installation: idna 2.5
    Uninstalling idna-2.5:
      Successfully uninstalled idna-2.5
Successfully installed idna-2.6


Traceback (most recent call last):
  File "/usr/bin/crossbar", line 7, in <module>
    from crossbar.controller.cli import run
  File "/usr/lib/python3.6/site-packages/crossbar/controller/cli.py", line 120, in <module>
    node_classes = get_node_classes()
  File "/usr/lib/python3.6/site-packages/crossbar/controller/cli.py", line 105, in get_node_classes
    e = entrypoint.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2340, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2363, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (idna 2.6 (/usr/lib/python3.6/site-packages), Requirement.parse('idna<2.6,>=2.5'))
```

**Comment by Emantor** [comment]
We are running into the same issue since we have an extra option to use crossbar for out labgrid coordinator. If it is installed as an extra the idna dependency is apparently not checked again and crossbar exits with the error listed above.

**Comment by meejah** [comment]
@Emantor that might be a slightly different problem? "pip" only ever wants the first version asked for, so if "idna" was already installed I don't think pip would try to upgrade/change the version. But upgrading our `idna` dependency should still fix your use-case.

*Ideally* you should install crossbar in its own ``virtualenv`` (or, e.g. by using one of the provided Docker images). We pin all dependencies at exact versions (with hashes). This is recommended practice for Python "end-user" style programs since then we can be sure it functions as intended (i.e. instead of open-ended dependencies, which are recommended practice for "library" style Python distributions).

**Comment by Emantor** [comment]
Ah, I see. I'll think about how to implement that, thanks 👍

**Comment by meejah** [comment]
@Emantor it *might* check for the correct versions of "direct" dependencies (e.g. if your extra lists an appropriate ``idna`` version).

Basically, though, crossbar is intended to be installed as an "application" and so trying to install it in the very same virtualenv as other applications may not always be possible. Maybe upgrading idna works for this particular case, but crossbar itself doesn't actually depend on idna -- we're picking that up from Twisted. Crossbar is pinning the entire collection of all dependencies (i.e. including dependencies-of-dependencies etc) that we require.
