### ISSUE TITLE
Crossbar v17.9.2 Memory Leak with Anonymous Authentication

### ISSUE THREAD

**Issue by rrueth** [crossbario/crossbar#1202]
Hello,

Output of `crossbar version`:
```
     __  __  __  __  __  __      __     __
    /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
    \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/

 Crossbar.io        : 17.9.2 (Crossbar.io COMMUNITY)
   Autobahn         : 17.9.3 (with JSON, MessagePack, CBOR, UBJSON)
   Twisted          : 17.9.0-EPollReactor
   LMDB             : 0.93/lmdb-0.9.18
   Python           : 3.5.2/CPython
 OS                 : Linux-4.4.0-1035-aws-x86_64-with-Ubuntu-16.04-xenial
 Machine            : x86_64
 Release key        : RWRj+Sb8UH/pwLCycZ+3OroR5UV9aaLUDVbKxNcj+gYoOOZv0LrzMH1a
```

We have a Crossbar instance running in our system. We also have a job that runs frequently (multiple times an hour) that creates a lot of short connections to the Crossbar instance. Each session is created using Anonymous Authentication. We've noticed that over time, Crossbar continued to use more and more memory until we had to restart the host after about ten days.

I restarted our Crossbar instance with debug logging enabled this morning. Then, I was able to connect to our running Crossbar instance with `pyrasite` and used `objgraph`, `gc`, and `tracemalloc` to diagnose the issue.  Using `objgraph`, I could see that the number of sets being used continued to increase throughout the day:

```
>>> objgraph.show_growth()
set                 231936   +168223
Traceback              446      +446
Statistic              262      +262
StatisticDiff          184      +184
tuple                12792      +109
function             17094       +75
_Traces                 27       +27
Snapshot                27       +27
weakref               5663       +16
member_descriptor      791       +11
```

Then, using `tracemalloc`, I was able to track down that `crossbar/router/router.py:160` seemed to continue growing all day:
```
/opt/crossbar/lib/python3.5/site-packages/crossbar/router/router.py:160: size=27.8 MiB (+1733 KiB), count=74147 (+7921), average=394 B
  File "/opt/crossbar/lib/python3.5/site-packages/crossbar/router/router.py", line 160
    self._authid_to_sessions[details['authid']] = set([session])
  File "/opt/crossbar/lib/python3.5/site-packages/crossbar/router/session.py", line 767
    self._router._session_joined(self, self._session_details)
  File "/opt/crossbar/lib/python3.5/site-packages/crossbar/router/session.py", line 400
    self.onJoin(SessionDetails(self._realm, self._session_id, self._authid, self._authrole, self._authmethod, self._authprovider, self._authextra))
  File "/opt/crossbar/lib/python3.5/site-packages/crossbar/router/session.py", line 425
    welcome(res.realm, res.authid, res.authrole, res.authmethod, res.authprovider, res.authextra, custom)
  File "/opt/crossbar/lib/python3.5/site-packages/twisted/internet/defer.py", line 653
    current.result = callback(current.result, *args, **kw)
  File "/opt/crossbar/lib/python3.5/site-packages/twisted/internet/defer.py", line 310
    self._runCallbacks()
  File "/opt/crossbar/lib/python3.5/site-packages/txaio/tx.py", line 491
    future.addCallbacks(callback, errback)
  File "/opt/crossbar/lib/python3.5/site-packages/crossbar/router/session.py", line 439
    txaio.add_callbacks(d, success, self._swallow_error_and_abort)
  File "/opt/crossbar/lib/python3.5/site-packages/autobahn/wamp/websocket.py", line 95
    self._session.onMessage(msg)
  File "/opt/crossbar/lib/python3.5/site-packages/autobahn/twisted/websocket.py", line 162
    self.onMessage(payload, isBinary)
```

Looking at line 160, it appears that the issue is with the `self._authid_to_sessions` dictionary:
```
    def _session_joined(self, session, details):
        """
        Internal helper.
        """
        try:
            self._authrole_to_sessions[details['authrole']].add(session)
        except KeyError:
            self._authrole_to_sessions[details['authrole']] = set([session])

        try:
            self._authid_to_sessions[details['authid']].add(session)
        except KeyError:
            self._authid_to_sessions[details['authid']] = set([session]) #line 160

        # log session details, but skip Crossbar.io internal sessions
        if self.realm != u'crossbar':
            self.log.info(
                'session "{session_id}" joined realm "{realm}"',
                session_id=details[u'session'],
                realm=self.realm,
            )
            self.log.debug('{details}', details=details)

    def _session_left(self, session, details):
        """
        Internal helper.
        """
        self._authid_to_sessions[details['authid']].discard(session)
        self._authrole_to_sessions[details['authrole']].discard(session) #Leak

        # log session details, but skip Crossbar.io internal sessions
        if self.realm != u'crossbar':
            self.log.info(
                'session "{session_id}" left realm "{realm}"',
                session_id=details[u'session'],
                realm=self.realm,
            )
            self.log.debug('{details}', details=details)
```

Since we are using Anonymous Authentication, the `details['authid']` field appears to be randomly generated per session:

https://github.com/crossbario/crossbar/blob/5c2230e2f5858edd5128b51475f25c9d3d1da78a/crossbar/router/auth/anonymous.py#L59

Thus, each time one of our short-lived sessions is created, a new `set([session])` is added to `self._authid_to_sessions[details['authid']]`. But, when the session leaves, only the session is discarded from `self._authrole_to_sessions[details['authrole']].discard(session)`, but the reference to the empty `set()` persists. I believe that this is where we are seeing the constantly increasing memory.

A fix could be to set `self._authrole_to_sessions[details['authrole']].discard(session)` to `None` if the set is empty after removing the last session. I'm happy to create a Pull Request with this fix, I just wanted to confirm the issue and approach to the fix first.

Thank you,
Ryan

**Comment by OOPMan** [comment]
@rrueth I'm sure a PR would be appreciated, along with maybe an accelerated timeframe test-case to confirm the issue is fixed.

**Comment by meejah** [comment]
Thanks for the great bug-report!

Your approach does seem like a likely cause -- I added "needs-investigation" as well because it would be good to confirm this is the case and there's not other unbounded memory growth (as @oopman suggests, *ideal* would be an automated test).

**Comment by meejah** [comment]
Anyway, to be clear: a PR would be welcome even without an automated test-case

**Comment by rrueth** [comment]
Thanks for the quick responses, @OOPMan and @meejah. I'll see if I can simulate the cause and reproduce the issue today.  If that goes well, I'll take a stab at fixing the issue and submitting a PR.

**Comment by rrueth** [comment]
I submitted a fix in the attached Pull Request.  I didn't see a good avenue for adding a unit test.  No other tests that I saw were really checking anything with regards to memory, and other tests weren't really checking internal data structures (e.g. did `self._authid_to_sessions` return to being an empty dict after the session left).  Let me know if there's a good reference elsewhere in the existing tests that could work here.

**Comment by rrueth** [comment]
@OOPMan and @meejah, who would be the best to review the PR?

**Comment by OOPMan** [comment]
@rrueth It would have to be someone on the Crossbar team, but I don't mind taking a look and leaving a comment if anything stands out

**Comment by rrueth** [comment]
Thanks, @OOPMan!

**Comment by rrueth** [comment]
Closing this issue since the fix was merged.  @meejah, do you know when we can expect the next release that would include this fix?
