### ISSUE TITLE
install crossbar on windows 10 error

### ISSUE THREAD

**Issue by alexey2baranov** [crossbario/crossbar#1208]
Hello! I tryed install crossbar on Windows 10. I did step by step as hire https://crossbar.io/docs/Installation-on-Windows/#installing-the-dependencies. After `pip install crossbar` i and got this error. 

Can you tell me what should i do to install it? Thanks

> Университтская 3@DESKTOP-E9QCBGU C:\
> > pip install crossbar
> Collecting crossbar
>   Downloading crossbar-17.9.2-py2.py3-none-any.whl (845kB)
>     100% |################################| 849kB 628kB/s
> Collecting priority>=1.3.0 (from crossbar)
>   Downloading priority-1.3.0-py2.py3-none-any.whl
> Collecting constantly>=15.1.0 (from crossbar)
>   Downloading constantly-15.1.0-py2.py3-none-any.whl
> Collecting pyqrcode>=1.2.1 (from crossbar)
>   Downloading PyQRCode-1.2.1.zip (41kB)
>     100% |################################| 51kB 1.3MB/s
> Collecting mistune>=0.7.4 (from crossbar)
>   Downloading mistune-0.8-py2.py3-none-any.whl
> Collecting py-ubjson>=0.9.0 (from crossbar)
>   Downloading py-ubjson-0.10.0.tar.gz (44kB)
>     100% |################################| 51kB 1.6MB/s
> Collecting shutilwhich>=1.1.0 (from crossbar)
>   Downloading shutilwhich-1.1.0.tar.gz
> Collecting PyTrie>=0.3 (from crossbar)
>   Downloading PyTrie-0.3.tar.gz (228kB)
>     100% |################################| 235kB 1.1MB/s
> Collecting h2>=3.0.1 (from crossbar)
>   Downloading h2-3.0.1-py2.py3-none-any.whl (71kB)
>     100% |################################| 81kB 1.2MB/s
> Collecting Twisted>=17.5.0 (from crossbar)
>   Downloading Twisted-17.9.0-cp27-cp27m-win32.whl (3.2MB)
>     100% |################################| 3.2MB 328kB/s
> Collecting cryptography>=1.9 (from crossbar)
>   Downloading cryptography-2.1.2-cp27-cp27m-win32.whl (1.1MB)
>     100% |################################| 1.1MB 736kB/s
> Collecting pyasn1-modules>=0.0.9 (from crossbar)
>   Downloading pyasn1_modules-0.1.5-py2.py3-none-any.whl (60kB)
>     100% |################################| 61kB 1.5MB/s
> Collecting incremental>=17.5.0 (from crossbar)
>   Downloading incremental-17.5.0-py2.py3-none-any.whl
> Collecting txtorcon>=0.19.3 (from crossbar)
>   Downloading txtorcon-0.19.3-py2.py3-none-any.whl (301kB)
>     100% |################################| 307kB 906kB/s
> Collecting treq>=17.3.1 (from crossbar)
>   Downloading treq-17.8.0-py2.py3-none-any.whl (53kB)
>     100% |################################| 61kB 797kB/s
> Collecting watchdog>=0.8.3 (from crossbar)
>   Downloading watchdog-0.8.3.tar.gz (83kB)
>     100% |################################| 92kB 1.3MB/s
> Collecting psutil>=5.2.2 (from crossbar)
>   Downloading psutil-5.4.0-cp27-none-win32.whl (218kB)
>     100% |################################| 225kB 1.6MB/s
> Collecting service-identity>=17.0.0 (from crossbar)
>   Downloading service_identity-17.0.0-py2.py3-none-any.whl
> Collecting idna<2.6,>=2.5 (from crossbar)
>   Downloading idna-2.5-py2.py3-none-any.whl (55kB)
>     100% |################################| 61kB 1.1MB/s
> Collecting Jinja2>=2.9.6 (from crossbar)
>   Downloading Jinja2-2.9.6-py2.py3-none-any.whl (340kB)
>     100% |################################| 348kB 1.5MB/s
> Collecting enum34>=1.1.6 (from crossbar)
>   Downloading enum34-1.1.6-py2-none-any.whl
> Collecting autobahn>=17.9.3 (from crossbar)
>   Downloading autobahn-17.9.3-py2.py3-none-any.whl (283kB)
>     100% |################################| 286kB 1.4MB/s
> Collecting ipaddress>=1.0.18 (from crossbar)
>   Downloading ipaddress-1.0.18-py2-none-any.whl
> Collecting pyasn1>=0.2.3 (from crossbar)
>   Downloading pyasn1-0.3.7-py2.py3-none-any.whl (63kB)
>     100% |################################| 71kB 1.9MB/s
> Collecting Pygments>=2.2.0 (from crossbar)
>   Downloading Pygments-2.2.0-py2.py3-none-any.whl (841kB)
>     100% |################################| 849kB 853kB/s
> Collecting PyNaCl>=1.1.2 (from crossbar)
>   Downloading PyNaCl-1.1.2-cp27-cp27m-win32.whl (138kB)
>     100% |################################| 143kB 1.7MB/s
> Collecting zope.interface>=4.4.2 (from crossbar)
>   Downloading zope.interface-4.4.3-cp27-cp27m-win32.whl (136kB)
>     100% |################################| 143kB 1.4MB/s
> Collecting PyYAML>=3.12 (from crossbar)
>   Downloading PyYAML-3.12-cp27-cp27m-win32.whl (182kB)
>     100% |################################| 184kB 1.4MB/s
> Collecting cbor>=1.0.0 (from crossbar)
>   Downloading cbor-1.0.0.tar.gz
> Collecting sdnotify>=0.3.1 (from crossbar)
>   Downloading sdnotify-0.3.2.tar.gz
> Collecting u-msgpack-python>=2.4.1 (from crossbar)
>   Downloading u_msgpack_python-2.4.1-py2.py3-none-any.whl
> Collecting click>=6.7 (from crossbar)
>   Downloading click-6.7-py2.py3-none-any.whl (71kB)
>     100% |################################| 71kB 995kB/s
> Collecting netaddr>=0.7.19 (from crossbar)
>   Downloading netaddr-0.7.19-py2.py3-none-any.whl (1.6MB)
>     100% |################################| 1.6MB 511kB/s
> Collecting lmdb>=0.92 (from crossbar)
>   Downloading lmdb-0.93-cp27-none-win32.whl (77kB)
>     100% |################################| 81kB 1.2MB/s
> Collecting bitstring>=3.1.5 (from crossbar)
>   Downloading bitstring-3.1.5.zip (624kB)
>     100% |################################| 624kB 1.0MB/s
> Collecting txaio>=2.8.2 (from crossbar)
>   Downloading txaio-2.8.2-py2.py3-none-any.whl
> Collecting pyOpenSSL>=17.1.0 (from crossbar)
>   Downloading pyOpenSSL-17.3.0-py2.py3-none-any.whl (51kB)
>     100% |################################| 51kB 898kB/s
> Collecting setuptools>=36.0.1 (from crossbar)
>   Downloading setuptools-36.6.0-py2.py3-none-any.whl (481kB)
>     100% |################################| 481kB 1.2MB/s
> Collecting attrs>=17.2.0 (from crossbar)
>   Downloading attrs-17.2.0-py2.py3-none-any.whl
> Collecting setproctitle>=1.1.10 (from crossbar)
>   Downloading setproctitle-1.1.10.tar.gz
> Collecting sortedcontainers (from PyTrie>=0.3->crossbar)
>   Downloading sortedcontainers-1.5.7-py2.py3-none-any.whl
> Collecting hyperframe<6,>=5.0 (from h2>=3.0.1->crossbar)
>   Downloading hyperframe-5.1.0-py2.py3-none-any.whl
> Collecting hpack<4,>=2.3 (from h2>=3.0.1->crossbar)
>   Downloading hpack-3.0.0-py2.py3-none-any.whl
> Collecting hyperlink>=17.1.1 (from Twisted>=17.5.0->crossbar)
>   Downloading hyperlink-17.3.1-py2.py3-none-any.whl (73kB)
>     100% |################################| 81kB 999kB/s
> Collecting Automat>=0.3.0 (from Twisted>=17.5.0->crossbar)
>   Downloading Automat-0.6.0-py2.py3-none-any.whl
> Collecting six>=1.4.1 (from cryptography>=1.9->crossbar)
>   Downloading six-1.11.0-py2.py3-none-any.whl
> Collecting cffi>=1.7; platform_python_implementation != "PyPy" (from cryptography>=1.9->crossbar)
>   Downloading cffi-1.11.2-cp27-cp27m-win32.whl (153kB)
>     100% |################################| 153kB 1.3MB/s
> Collecting asn1crypto>=0.21.0 (from cryptography>=1.9->crossbar)
>   Downloading asn1crypto-0.23.0-py2.py3-none-any.whl (99kB)
>     100% |################################| 102kB 1.2MB/s
> Collecting requests>=2.1.0 (from treq>=17.3.1->crossbar)
>   Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
>     100% |################################| 92kB 1.2MB/s
> Collecting argh>=0.24.1 (from watchdog>=0.8.3->crossbar)
>   Downloading argh-0.26.2-py2.py3-none-any.whl
> Collecting pathtools>=0.1.1 (from watchdog>=0.8.3->crossbar)
>   Downloading pathtools-0.1.2.tar.gz
> Collecting MarkupSafe>=0.23 (from Jinja2>=2.9.6->crossbar)
>   Downloading MarkupSafe-1.0.tar.gz
> Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.9->crossbar)
>   Downloading pycparser-2.18.tar.gz (245kB)
>     100% |################################| 256kB 1.5MB/s
> Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.1.0->treq>=17.3.1->crossbar)
>   Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
>     100% |################################| 143kB 1.8MB/s
> Collecting certifi>=2017.4.17 (from requests>=2.1.0->treq>=17.3.1->crossbar)
>   Downloading certifi-2017.7.27.1-py2.py3-none-any.whl (349kB)
>     100% |################################| 358kB 1.4MB/s
> Collecting urllib3<1.23,>=1.21.1 (from requests>=2.1.0->treq>=17.3.1->crossbar)
>   Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
>     100% |################################| 133kB 1.3MB/s
> Installing collected packages: priority, constantly, pyqrcode, mistune, py-ubjson, shutilwhich, sortedcontainers, PyTrie, hyperframe, hpack, enum34, h2, setuptools, zope.interface, hyperlink, attrs, six, Automat, incremental, Twisted, pycparser, cffi, asn1crypto, idna, ipaddress, cryptography, pyasn1, pyasn1-modules, txtorcon, chardet, certifi, urllib3, requests, treq, PyYAML, argh, pathtools, watchdog, psutil, pyOpenSSL, service-identity, MarkupSafe, Jinja2, txaio, autobahn, Pygments, PyNaCl, cbor, sdnotify, u-msgpack-python, click, netaddr, lmdb, bitstring, setproctitle, crossbar
>   Running setup.py install for pyqrcode ... done
>   Running setup.py install for py-ubjson ... error
>     Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\333f5~1\\appdata\\local\\temp\\pip-build-mxxpli\\py-ubjson\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\333f5~1\appdata\local\temp\pip-plzsqe-record\install-record.txt --single-version-externally-managed --compile:
>     Warning: pypandoc module not found, will not convert Markdown to RST
>     running install
>     running build
>     running build_py
>     creating build
>     creating build\lib.win32-2.7
>     creating build\lib.win32-2.7\ubjson
>     copying ubjson\compat.py -> build\lib.win32-2.7\ubjson
>     copying ubjson\decoder.py -> build\lib.win32-2.7\ubjson
>     copying ubjson\encoder.py -> build\lib.win32-2.7\ubjson
>     copying ubjson\markers.py -> build\lib.win32-2.7\ubjson
>     copying ubjson\__init__.py -> build\lib.win32-2.7\ubjson
>     copying ubjson\__main__.py -> build\lib.win32-2.7\ubjson
>     running build_ext
>     building '_ubjson' extension
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "c:\users\333f5~1\appdata\local\temp\pip-build-mxxpli\py-ubjson\setup.py", line 109, in <module>
>         'Topic :: Software Development :: Libraries :: Python Modules'
>       File "c:\python27\lib\distutils\core.py", line 151, in setup
>         dist.run_commands()
>       File "c:\python27\lib\distutils\dist.py", line 953, in run_commands
>         self.run_command(cmd)
>       File "c:\python27\lib\distutils\dist.py", line 972, in run_command
>         cmd_obj.run()
>       File "c:\python27\lib\site-packages\setuptools\command\install.py", line 61, in run
>         return orig.install.run(self)
>       File "c:\python27\lib\distutils\command\install.py", line 563, in run
>         self.run_command('build')
>       File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
>         self.distribution.run_command(command)
>       File "c:\python27\lib\distutils\dist.py", line 972, in run_command
>         cmd_obj.run()
>       File "c:\python27\lib\distutils\command\build.py", line 127, in run
>         self.run_command(cmd_name)
>       File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
>         self.distribution.run_command(command)
>       File "c:\python27\lib\distutils\dist.py", line 972, in run_command
>         cmd_obj.run()
>       File "c:\users\333f5~1\appdata\local\temp\pip-build-mxxpli\py-ubjson\setup.py", line 56, in run
>         build_ext.run(self)
>       File "c:\python27\lib\distutils\command\build_ext.py", line 340, in run
>         self.build_extensions()
>       File "c:\python27\lib\distutils\command\build_ext.py", line 449, in build_extensions
>         self.build_extension(ext)
>       File "c:\users\333f5~1\appdata\local\temp\pip-build-mxxpli\py-ubjson\setup.py", line 64, in build_extension
>         build_ext.build_extension(self, ext)
>       File "c:\python27\lib\distutils\command\build_ext.py", line 499, in build_extension
>         depends=ext.depends)
>       File "c:\python27\lib\distutils\msvc9compiler.py", line 473, in compile
>         self.initialize()
>       File "c:\python27\lib\distutils\msvc9compiler.py", line 383, in initialize
>         vc_env = query_vcvarsall(VERSION, plat_spec)
>       File "c:\python27\lib\site-packages\setuptools\msvc.py", line 136, in msvc9_query_vcvarsall
>         return EnvironmentInfo(arch, ver).return_env()
>       File "c:\python27\lib\site-packages\setuptools\msvc.py", line 1125, in return_env
>         exists),
>       File "c:\python27\lib\site-packages\setuptools\msvc.py", line 1148, in _build_paths
>         return os.pathsep.join(unique_paths)
>     UnicodeDecodeError: 'ascii' codec can't decode byte 0xd3 in position 9: ordinal not in range(128)
> 
>     ----------------------------------------
> Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\333f5~1\\appdata\\local\\temp\\pip-build-mxxpli\\py-ubjson\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\333f5~1\appdata\local\temp\pip-plzsqe-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\333f5~1\appdata\local\temp\pip-build-mxxpli\py-ubjson\

**Comment by oberstet** [comment]
seem like the ms visual studio toolchain has problems with your paths (maybe the ~?):

```
File "c:\users\333f5~1\appdata\local\temp\pip-build-mxxpli\py-ubjson\setup.py", line 64, in build_extension
build_ext.build_extension(self, ext)
File "c:\python27\lib\distutils\command\build_ext.py", line 499, in build_extension
depends=ext.depends)
File "c:\python27\lib\distutils\msvc9compiler.py", line 473, in compile
self.initialize()
File "c:\python27\lib\distutils\msvc9compiler.py", line 383, in initialize
vc_env = query_vcvarsall(VERSION, plat_spec)
File "c:\python27\lib\site-packages\setuptools\msvc.py", line 136, in msvc9_query_vcvarsall
return EnvironmentInfo(arch, ver).return_env()
File "c:\python27\lib\site-packages\setuptools\msvc.py", line 1125, in return_env
exists),
File "c:\python27\lib\site-packages\setuptools\msvc.py", line 1148, in _build_paths
return os.pathsep.join(unique_paths)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd3 in position 9: ordinal not in range(128)
```
