### ISSUE TITLE
Running on Windows, but cannot install IOCP Twisted reactor

### ISSUE THREAD

**Issue by alexey2baranov** [crossbario/crossbar#1225]
Hello! i get this error suddenly after PC restart. As a result crossbar static web server on port 8282 not works. What's happend with it?

`> crossbar start`

> Running on Windows, but cannot install IOCP Twisted reactor                                                                                                     
> 2017-11-23T20:18:48+0500 [Controller   1536] Running on Windows, but cannot install IOCP Twisted reactor                                                        
> 2017-11-23T20:18:48+0500 [Controller   1536] Traceback (most recent call last):                                                                                 
>   File "c:\python27\lib\site-packages\autobahn\twisted\choosereactor.py", line 84, in install_optimal_reactor                                                   
>     iocpreactor.install()                                                                                                                                       
>   File "c:\python27\lib\site-packages\twisted\internet\iocpreactor\reactor.py", line 270, in install                                                            
>     main.installReactor(r)                                                                                                                                      
>   File "c:\python27\lib\site-packages\twisted\internet\main.py", line 32, in installReactor                                                                     
>     raise error.ReactorAlreadyInstalledError("reactor already installed")                                                                                       
> ReactorAlreadyInstalledError: reactor already installed                                                                                                         
>                                                                                                                                                                 
> 2017-11-23T20:18:48+0500 [Controller   1536] File permissions on node public key fixed!                                                                         
> 2017-11-23T20:18:48+0500 [Controller   1536] File permissions on node private key fixed!                                                                        
> 2017-11-23T20:18:48+0500 [Controller   1536]      __  __  __  __  __  __      __     __                                                                         
> 2017-11-23T20:18:48+0500 [Controller   1536]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \                                                                        
> 2017-11-23T20:18:48+0500 [Controller   1536]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/                                                                        
> 2017-11-23T20:18:48+0500 [Controller   1536]                                                                                                                    
> 2017-11-23T20:18:48+0500 [Controller   1536] Version:     Crossbar.io COMMUNITY 17.11.1                                                                         
> 2017-11-23T20:18:48+0500 [Controller   1536] Public Key:  48cc8a771384cb4f1c7811d45e4af2f4601a47af92d910ce21909737033a81c6                                      
> 2017-11-23T20:18:48+0500 [Controller   1536]                                                                                                                    
> 2017-11-23T20:18:48+0500 [Controller   1536] Node starting with personality "community" [crossbar.controller.node.Node]                                         
> 2017-11-23T20:18:48+0500 [Controller   1536] Running from node directory "C:\terminal\terminal-server\.crossbar"                                                
> 2017-11-23T20:18:48+0500 [Controller   1536] Node configuration loaded from "C:\terminal\terminal-server\.crossbar\config.json"                                 
> 2017-11-23T20:18:48+0500 [Controller   1536] Controller process starting [CPython-SelectReactor] ..                                                             
> 2017-11-23T20:18:48+0500 [Controller   1536] No extra node router roles                                                                                         
> 2017-11-23T20:18:48+0500 [Controller   1536] RouterServiceSession ready [no on_ready configured]                                                                
> 2017-11-23T20:18:48+0500 [Controller   1536] Registered 20 procedures                                                                                           
> 2017-11-23T20:18:48+0500 [Controller   1536] Using default node shutdown triggers [u'shutdown_on_worker_exit']                                                  
> 2017-11-23T20:18:48+0500 [Controller   1536] Configuring node from local configuration ...                                                                      
> 2017-11-23T20:18:48+0500 [Controller   1536] Starting 1 workers ...                                                                                             
> 2017-11-23T20:18:48+0500 [Controller   1536] Router worker "worker-001" starting ..                                                                             
> 2017-11-23T20:18:52+0500 [Router       4980] Started Router worker "worker-001" on node "None" [crossbar.worker.router.RouterWorkerSession / CPython-IOCPReactor
> ]                                                                                                                                                               
> 2017-11-23T20:18:52+0500 [Router       4980] Router worker "worker-001" session 574646758429096 initializing ..                                                 
> 2017-11-23T20:18:52+0500 [Router       4980] Registered 37 procedures                                                                                           
> 2017-11-23T20:18:52+0500 [Router       4980] Router worker "worker-001" session ready                                                                           
> 2017-11-23T20:18:52+0500 [Controller   1536] Router worker "worker-001" process 4980 started                                                                    
> 2017-11-23T20:18:52+0500 [Controller   1536] Router "worker-001": realm 'realm-001' (named 'terminal') started                                                  
> 2017-11-23T20:18:52+0500 [Router       4980] RouterServiceSession ready [configured on_ready fired]                                                             
> 2017-11-23T20:18:52+0500 [Router       4980] Realm 'terminal' started                                                                                           
> 2017-11-23T20:18:52+0500 [Router       4980] role role-001 on realm realm-001 started                                                                           
> 2017-11-23T20:18:52+0500 [Controller   1536] Router "worker-001": role 'role-001' (named 'anonymous') started on realm 'realm-001'                              
> 2017-11-23T20:18:52+0500 [Controller   1536] Router "worker-001": transport 'transport-001' started                                                             
> 2017-11-23T20:18:52+0500 [Controller   1536] Local node configuration applied successfully!                                                                     
> 2017-11-23T20:18:52+0500 [Router       4980] Site starting on 8282                                                                                              

My **crossbar.json** is 
```json

{
  "version": 2,
  "workers": [
    {
      "type": "router",
      "realms": [
        {
          "name": "terminal",
          "roles": [
            {
              "name": "anonymous",
              "permissions": [
                {
                  "uri": "ru.teleplus.terminal",
                  "match": "prefix",
                  "allow": {
                    "call": true,
                    "register": true,
                    "publish": true,
                    "subscribe": true
                  }
                }
              ]
            }
          ]
        }
      ],
      "transports": [
        {
          "type": "web",
          "endpoint": {
            "type": "tcp",
            "port": 8282
          },
          "paths": {
            "ws": {
              "type": "websocket",
              "options": {
                "enable_webstatus": true,
                "max_frame_size": 1048576,
                "max_message_size": 1048576,
                "auto_fragment_size": 65536,
                "fail_by_drop": true,
                "open_handshake_timeout": 2500,
                "close_handshake_timeout": 1000,
                "auto_ping_interval": 10000,
                "auto_ping_timeout": 5000,
                "auto_ping_size": 4
              },
              "serializers": [
                "json"
              ],
              "auth": {
                "anonymous": {
                  "type": "static",
                  "role": "anonymous"
                }
              }
            },
            "/": {
              "type": "static",
              "directory": "c:/terminal/terminal-client/dist",
              "options": {
                "enable_directory_listing": true,
                "cache_timeout": 0
              }
            }
          }
        }
      ]
    }
  ]
}

```

**Comment by oberstet** [comment]
Haven't seen this ("reactor already installed") for a long time. The original root cause was: Twisted has/had some implicit reactor imports. We now select and import the reactor in crossbar at the very earliest moment possible here https://github.com/crossbario/crossbar/blob/cfa1feb938a7409ebae103649d1b47de29226101/crossbar/__init__.py#L165
