### ISSUE TITLE
roundrobin does not seem to work as expected

### ISSUE THREAD

**Issue by mshahbazi** [crossbario/crossbar#1230]
due to the following, I am concluding that crossbar (the router) does not work asynchronously.
I register a method with long computational time, then call the method twice at the same time. Surprisingly, the second call waits until the first call finishes.

To deal with this, I cloned a few more containers and native workers. I registered the method with "random" and "roundrobin" as invocation options. The result is as follows:

roundrobin: have the same problem, i.e. the second call is blocked.
random: works as expected, though I need to add many containers to decrease the probability of blocking--assuming that the server has off-limit memory.

I am wondering if I am doing something wrong or misunderstood something.
Any help is greatly appreciated.

**Comment by meejah** [comment]
It seems likely you're blocking the reactor; is your "long computation" `time.sleep()` or something that otherwise blocks the reactor for more than a few milliseconds?

**Comment by mshahbazi** [comment]
@meejah you are right. I was using a blocking piece of code. Managed to make it work using `deferToThread`. However, `roundrobin` problem still exists.

**Comment by oberstet** [comment]
try this: https://github.com/crossbario/crossbar-examples/tree/master/scaling-microservices

**Comment by mshahbazi** [comment]
`roundrobin` does not work while `random` works. Finally I opted for nginx for load balancing. Just wondering if there is a crossbar-native way!

Thanks for the great work.

**Comment by oberstet** [comment]
sure, see above. round robin does work

**Comment by mshahbazi** [comment]
I see. You are right. That's why I am looking for a native way. Nginx entails clones of the whole component, i.e. memory consuming.

Thanks again.
