### ISSUE TITLE
crossbar crashes on import of flat python3 implicit namespace package

### ISSUE THREAD

**Issue by petri** [crossbario/crossbar#1236]
I wrote a simple in-process router component. Works fine, except that importing the zc.lockfile package crashes crossbar. For example, try installing zc.lockfile package using pip and then importing it within the wamp component module, you get traceback like this (snippet):

>  from zc.lockfile import LockFile
> builtins.ModuleNotFoundError: No module named 'zc.lockfile'

Apparently this is because normally zc.lockfile gets installed as a flat implicit namespace package, ie. in site-packages there is a "zc/lockfile/..." file structure without an `__init__.py` file in the "zc" directory.

I am suggesting the flat implicit namespace is the culprit because converting the zc.lockfile package into an egg, for example with humpty (available on pypi), installing the egg using easy_install and then running the code with the import works fine.

Firing up the same Python3 interpreter crossbar uses and importing zc.lockfile there works fine in BOTH above cases though, nothing unusual there. 

I wonder if the real reason is because crossbar seems to import the component class using importlib and something in that process somehow messes up the flat implicit namespace import? Could be bug in Python3 itself, who knows?

FWIW, my environment below:

 Crossbar.io        : 17.12.1 (Crossbar.io COMMUNITY)
   Autobahn         : 17.10.1 (with JSON, MessagePack, CBOR, UBJSON)
   Twisted          : 17.9.0-SelectReactor
   LMDB             : 0.93/lmdb-0.9.18
   Python           : 3.6.2/CPython
 OS                 : Darwin-17.3.0-x86_64-i386-64bit
 Machine            : x86_64

**Comment by oberstet** [comment]
>  ie. in site-packages there is a "zc/lockfile/..." file structure without an __init__.py file in the "zc" directory.

that means it is not properly packaged (not even a proper python module). pls complain to upstream

**Comment by oberstet** [comment]
ok, there seems to be some magic in zc.lockfile: https://github.com/zopefoundation/zc.lockfile/blob/master/src/zc/__init__.py

I have no clue what this is about, and what the ramifications are;)

**Comment by petri** [comment]
Well, zc.lockfile certainly is properly packaged since Python 3.3; see PEP 420. The __init__.py 'magic' you refer to is how setuptools/pkg_resources provides namespace package support prior to PEP 420.

**Comment by oberstet** [comment]
@petri I wasn't aware of PEP420. My bad, sorry. I don't have time to understand this PEP stuff (I don't even feel a need) nor track it down. Maybe this helps:

https://bugs.python.org/issue29144

You could just quickly try Python 3.5 - maybe this is the regression above issue talks about.

Or you could just use old school packaging;)

**Comment by oberstet** [comment]
practically, I would recommend using a **guest worker** instead of **native container worker**. for the guest worker, one can use any python environment (a guest worker is completely independent of the crossbar own python environment).

sorry, we don't have time/resources to track this down. this issue here is basically the one and only place I ever heard/ran into this.
