### ISSUE TITLE
Log should be more forgiving for byte arrays

### ISSUE THREAD

**Issue by blinkingmatt** [crossbario/crossbar#1241]
When feeding byte arrays into the log from a worker process - we get to module:
_crossbar.controller.processtypes_ and method _WorkerProcess.log_.
Here the byte array is decoded with UTF-8.
I think this is a too strong assumption for a log message and would suggest in line 191:
```
if type(data) != six.text_type:
   data = data.decode('utf8', 'replace')
```

**Comment by oberstet** [comment]
cleaning up issues .. a lot has changed since, however, logging is for logging of strings, and the caller is responsible for type conversion

**Comment by blinkingmatt** [comment]
Since the stdout is redirected and some deeply nested foreign hardware controlling modules (like in our case) sometimes just print messages I still believe it could be useful to include this little "replace" parameter.
I'm a great fan of your protocol/framework but I always have to forward-port this little piece of code when I update ...
