### ISSUE TITLE
Dynamic Challengers

### ISSUE THREAD

**Issue by ecorm** [crossbario/crossbar#1244]
Backend clients ought to be able to implement their own dynamic challenge-response-authorization (CRA) schemes on top of the dynamic ticket-based authorization scheme.

The only piece currently missing for custom CRA schemes is to allow the configuration of a _dynamic challenger_ RPC (in addition to the existing dynamic authenticator RPC).

The dynamic challenger RPC would return a custom object that is then forwarded to the front-end client via the `Extra` field of the  `CHALLENGE` message. The front-end can then make use of use of this custom object to create the `Signature` field returned via `AUTHENTICATE`. For example, a "client salt" for hashing the password could be passed via the `CHALLENGE.Extra` field.

A use case for this feature would be to implement client-side password hashing _in combination with_ server-side hashing, as described in [this article](http://ithare.com/client-plus-server-password-hashing-as-a-potential-way-to-improve-security-against-brute-force-attacks-without-overloading-server/) and the various other research papers it cites.

**Comment by oberstet** [comment]
The challenge algo / scheme is fixed (by design) in WAMP-CRA in the spec. IMO, what we need is a WAMP-SCRAM - pls see:

* https://github.com/wamp-proto/wamp-proto/issues/135
* https://github.com/wamp-proto/wamp-proto/issues/164

**Comment by ecorm** [comment]
For my proposed dynamic challenger feature to work, the router would have to remember the challenge details and forward them to the dynamic authenticator RPC. Otherwise, the dynamic authenticator component would have to remember the challenge and somehow associate it with the subsequent authentication attempt.

**Comment by meejah** [comment]
Having the router remember things might make dynamic challengers easier, but also would have some downsides: makes the router more complex; leaves expiry more up to the router; ... (others?)

For challenge/response algorithms, it would be pretty common to have a credential database of some kind. Beyond this, which algorithms require storing the intermediate challenges? Could they also store associated details similarly?

 - SCRAM: don't think so (just the credential-database is sufficient)
 - WAMP-cryptosign: needs to keep challenges (just a nonce) as well as the credential-database of public keys
 - WAMP-CRA: needs to keep salt, nonce, timestamp etc information (as well as credential-database); some of this is static, essentially (salt, iterations, keysize) but not all.

So it seems the answer is "yes, some schemes require remembering information about the challenges sent. My suspicion is that people building a new auth scheme into WAMP will have strong opinions about how this extra information is stored and for how long. My instinct would thus be to NOT have the router remember it but instead use a database (or etcd or similar?).

It would also be useful I think to consider the API in the context of enabling integrations for existing credential-storage systems (e.g. HashiCorp's "Vault"). I don't see any problems here either way (i.e. even if the router *can* remember some information for you, the dynamic-challenger can still do arbitrary extra work like look up credentials via some other protocol), but this use-case should be considered.

Another thing to consider here I think is the overall value of providing an "arbitrary auth scheme" API -- is it better to encourage new/better auth schemes to be "built in" to WAMP (and routers) like wamp-cryptosign etc? The internal crossbar APIs already separate auth out fairly well -- the question here is more one of structure. The approach of cryptosign is interesting: a built-in scheme that leaves the question of "where do I store my credential database" up to the user -- it can be statically configured or an RPC can be registered to look up keys.

**Comment by ecorm** [comment]
> Having the router remember things might make dynamic challengers easier, but also would have some downsides: makes the router more complex; leaves expiry more up to the router; ... (others?)

The router would only have to remember the challenge details for the duration of the `CHALLENGE->AUTHORIZE` sequence. There should be a timeout duration between `CHALLENGE` and the `AUTHORIZE` response, in order to thwart an attacker attempting to crack a password while the router waits for the `AUTHORIZE` response.

If for some reason it's still a bad idea for the router to remember all challenge details, then it could at least remember a token generated by the dynamic challenger so that the backend endpoint knows how to match-up the inbound `AUTHORIZE` details with the previous outbound `CHALLENGE` details.

> Another thing to consider here I think is the overall value of providing an "arbitrary auth scheme" API -- is it better to encourage new/better auth schemes to be "built in" to WAMP (and routers) like wamp-cryptosign etc?

**Our project doesn't have time to wait for Crossbar to implement a safer password-based auth scheme that meets our business requirements.** The only saving grace for Crossbar is ticket-based auth with our own dynamic authorizer, where we hash the password server-side. If it wasn't for that, we'd have to write/modify our own WAMP router, or adopt another middleware technology that's not so rigid.

Adding a dynamic challenger hook in Crossbar's existing machinery seems like less effort for your team than coming up with an enhanced password auth scheme.

If I were more fluent in Python and its ecosystem, I'd offer to contribute a better password authorization module for Crossbar; but I'm not. I need Crossbar to provide me with the hooks to write my own solution in C++ that meets our business requirements.

**Comment by meejah** [comment]
Ah, yes, the point about languages is a good one: exposing a generic challenge/response API via WAMP lets one write the protocol in any supported WAMP language.

As far as "router remembering", linking challenge/responses *could* be left as "an exercise to the dynamic authorizer" but yes at least the length of time this information needs to be kept is bounded. Also, there's no need for it to be persisted at this point (if the router is re-started all existing connections will be dropped anyway).

**Comment by ecorm** [comment]
> As far as "router remembering", linking challenge/responses could be left as "an exercise to the dynamic authorizer".

As I mentioned before, the dynamic authenticator would _at least_ need a token that the dynamic challenger has previously generated. Otherwise, it wouldn't be able to match-up the `CHALLENGE` and `AUTHENTICATION` details. Relying on `authid` for this matching would not be secure/reliable as WAMP supports the same `authid` being used in multiple sessions.

**Comment by meejah** [comment]
Is "session id" not sufficient for this use-case?

**Comment by ecorm** [comment]
Yes, session id would be sufficient if it exists at the time when the dynamic challenger is invoked. I'm glad you suggested it.

**Comment by meejah** [comment]
Yes, it does exist at this point. For example, this (and other session details) are provided to the "dynamic cryptosign" RPC call (this call returns a relevant user public key, or fails).

So probably what's wanted here is a two-part API? That is two RPC calls; conceptually something like this (actual names TBD):

 - `crossbar.auth.create_challenge(realm, session_details, ...)`
 - `crossbar.auth.challenge_response(session_details, response, ...)`

...which represents a two-part challenge/response. The second call would receive the session-id (at least; I used "session_details" above to be a dict possibly containing other details like authid, authrole, authextra) and the response from the client. The second call would return a dict detailing how to accept the session (in existing WAMP APIs this provides realm, authid, authrole, authextra and authprovider + authmethod). That is, the client "requests" an authrole, but ultimately what role they get is decided by the authentication machinery.

Alternate naming that matches the internal APIs better would be `.hello` for the first and `.authenticate` for the second call.

It might also make sense to allow the `create_challenge`/`hello` call to return two things: the challenge to send to the client and some opaque dict containing extra information that is passed to the second call (which is I think part of what you were asking for with the "router remembers"?); this could be any state that the authentication scheme needs to keep that is not appropriate to include in the client challenge (the "exercise to the implementer" way of doing this would be to store any such state indexed by session-id, but then there would need to be a third RPC to indicate a session setup attempt was discarded so that stale state can be deleted). So after writing that out, it would make more sense for the router to keep this state.

**Comment by ecorm** [comment]
Are you suggesting that `crossbar.auth.challenge_response(session_details, response, ...)` gives the custom dynamic authorizer access to both the `Signature` and `Extra` fields of the `AUTHORIZE` message? If so then that would give a custom auth scheme a great deal of flexibility and avoid the need to encode/decode all the desired information into/from the `Signature` string.

The actual RPC names could be set in the JSON config like they are for existing authmethods. Something like:

```
"auth": {
   "custom": {
      "challenger": "com.example.challenge"
      "authenticator": "com.example.authenticate"
   }
}
```

> It might also make sense to allow the create_challenge/hello call to return two things: the challenge to send to the client and some opaque dict containing extra information that is passed to the second call (which is I think part of what you were asking for with the "router remembers"?);

Yes, that would work for the extra information that I would need the router to remember and forward to `crossbar.auth.challenge_response` RPC. This would avoid my C++ backend needing to be "stateful" between the `CHALLENGE` and `AUTHENTICATE` pair.

**Comment by oberstet** [comment]
@ecorm pls have a look at to explain how things work _currently_ at least:

https://github.com/crossbario/crossbar/blob/master/crossbar/router/auth/ticket.py

there are exactly 2 methods called from CB code handling the session and the messages:

* hello
* authenticate

these correspond exactly to the 2 WAMP messages HELLO and AUTHENTICATE.

the fact that in above _class_, the body of `authenticate` has access to all info previously established is a result of both methods sitting on the same instance.

essentially, "hello" remembers stuff on the instance, later used in "authenticate".

so it is stateful.

**Comment by oberstet** [comment]
@meejah seems like what you suggest is essentially: make those calls work "stateless", in the sense that the info normally accumulated between calls like above is made explicit. right?

**Comment by meejah** [comment]
Yeah, exactly. What I'm suggesting isn't "make it stateless" but rather "let the hello() put in some arbitrary state and the authenticate() call will get it back". So, e.g., anything remembered on `self.*` currently could/would use this mechanism (i.e. if it wasn't a built-in auth method).

**Comment by meejah** [comment]
Concretely: if cryptosign were implemented using this (instead of "in Python") then it would put the `nonce` into the state in `hello` and check it in the `authenticate`...

**Comment by oberstet** [comment]
Ok, I think we are on the same page .. when I said "stateless", I meant when the complete authenticator itself is user provided (external component) - such a "fully generic dynamic WAMP authenticator" would expose 2 procedures - and since these are _procedures_, which might or might not live on an actual object, it is stateless. Since only when both procs (in user code) live on an object, this object could hold state - but the question then of course is, how the 2nd call (authenticate) could correlate to the right session in user code. Not sure if I am able to say what I mean;)

anyway: we could do above.

I would call that a new WAMP authentication method: `wamp-generic`.

It would only make sense as a dynamic authenticator - no static flavor, because generic and static .. don't rime;)

**Comment by oberstet** [comment]
pseudo user code for a WAMP-generic authenticator:

`def hello(...) -> state | exception`
`def authenticate(state, realm, authid, details) -> auth | exception`

something like that ..

**Comment by meejah** [comment]
Yeah. Tweak: `hello()` -> returns "state" plus the challenge to send to the client (so either a 2-tuple or a dict?)

**Comment by meejah** [comment]
To summarize: "wamp-generic" is an RPC-based mechanism that basically "just" does what you can do right now inside crossbar.io via `crossbar.router.auth.pending.PendingAuth` subclasses. That is, anything that a single CHALLENGE round-trip. This has the following advantages:

 - actual auth can be state-ful between "hello" and "authenticate" (in Python, this uses class instances; in this proposal it uses a "state" dict)
 - the concrete authentication mechanism can be implemented in any language supported by WAMP (not just Python)
 - a third-party can implement an experimental/non-standard authentication mechanism without changing/forking Crossbar.io itself
 - because "state" is captured in a dict that's passed back, the callee implementing the RPC could be a "roundrobin" or similar (i.e. have multiple machines/cores doing auth).

Of course in either case the authenticator can do arbitrary async work (like making database calls, etcd lookups, etc).

**Comment by oberstet** [comment]
> the callee implementing the RPC could be a "roundrobin"

ah yeah! this is actually sth a builtin authenticator isn't able to do. scale out the authentication. nice and comes for free ..

> when we have a WAMP aware, authenticating frontend proxy worker (in CF), that would also scale out ..

**Comment by ecorm** [comment]
My proposed Dynamic Challenger feature is not immediately urgent, because we plan on implementing server-only password hashing first, and this can be done with just the existing dynamic authenticator feature.

It might be another month or so before we'd make use of the dynamic challenger. I'll keep you posted on our progress (perhaps best done via email).

I'd just like some reassurance that this feature proposal is taken seriously in the absence or existing authmethods that meet our business needs (for password authentication, that is).

I'll read-up on the previous conversation later with fresher eyes.

**Comment by ecorm** [comment]
I've thought of a way I can implement my own custom CRA scheme on top of Crossbar's existing ticket auth, with the help of dynamic authentication/authorization. I'll leave this issue open for discussion and in case anyone else might find the "Dynamic Challenger" feature useful. Or you may close it if you choose not to implement this proposed feature.

Here's what I plan to do:

1. Frontend authenticates via WAMP-Ticket and sends only the username as part of the `ticket` string.
2. Backend's dynamic authenticator checks that username exists.
3. Backend sends the "real" challenge embedded in the `WELCOME.Extra` argument.
4. Frontend _must immediately_ call a `com.myapp.authenticate` RPC with the proper response against the previously sent challenge.
If the frontend attempts to call any other RPC before authenticating, the backend's dynamic authorizer will kick the frontend from the realm via the Session Meta API.
5. Backend sends the "real" welcome information as the response to the `com.myapp.authenticate` call.

Even though we plan to only connect frontend clients via TLS transports, there can be an intervening "portal" service between the frontend clients and our backend server. We must therefore safeguard against *both* database theft on the backend, and MITM snooping via the portal service. SCRAM is starting to look like a pretty good option at this point, and I'll be able to implement it myself before waiting for the WAMP community to standardize it. I might be able to lean on that experience in helping the WAMP community come up with a standarized SCRAM authmethod.

**Comment by oberstet** [comment]
> SCRAM is starting to look like a pretty good option at this point, and I'll be able to implement it myself before waiting for the WAMP community to standardize it.

If your itch can be solved by SCRAM, perfect, and it that case, I'd put a high prio on https://github.com/wamp-proto/wamp-proto/issues/135.

Instead of starting to develop in-house (I know, you have time pressure - as everyone these days;), would you consider starting this "in the open", as in, chime in on above issue, define it in the spec from the start?

I guess this is a feature where a competitive advantage (from your company) isn't the goal, and specifying WAMP-SCRAM for the whole WAMP community would really add something ..

I am willing to make it high-prio then rgd implementation in Crossbar.io and AutobahnXXX .. and I don't think it is that much work anyways. The important work is defining it in the first place.

**Comment by ecorm** [comment]
> Instead of starting to develop in-house (I know, you have time pressure - as everyone these days;), would you consider starting this "in the open", as in, chime in on above issue, define it in the spec from the start?

I'll consider it.

> I guess this is a feature where a competitive advantage (from your company) isn't the goal, and specifying WAMP-SCRAM for the whole WAMP community would really add something ..

It would have to be specified in a way that doesn't lock the implementors/adopters with only one password hashing algorithm. There is no consensus on the "best" hashing algorithm, and this will end up changing in the future anyway. Argon2 is good contender right now, but some feel that it hasn't been battle-tested long enough.

> I am willing to make it high-prio then rgd implementation in Crossbar.io and AutobahnXXX .. and I don't think it is that much work anyways. The important work is defining it in the first place.

I generally follow the principle of not designing on promises. I might be able to shift our company's development efforts to other features while we wait for a SCRAM to be spec'd and implemented on routers. But we can only wait so long before having to implement our own home-brew solution.

**Comment by oberstet** [comment]
> I generally follow the principle of not designing on promises.

yeah, you should not depend on us doing things when you have a hard timeline!

however, if you could organize funding, then we can dedicate staff for dev of this feature, me overseeing, and then we could have a contract that has hard, contractual timeline and delivery and not only "promised" on good will basis ..

**Comment by meejah** [comment]
> It would have to be specified in a way that doesn't lock the implementors/adopters with only one password hashing algorithm. There is no consensus on the "best" hashing algorithm, and this will end up changing in the future anyway. Argon2 is good contender right now, but some feel that it hasn't been battle-tested long enough.

"I am not a cryptographer" but I agree with both of the above: the particular hash algorithm shouldn't be "hard-coded" in the spec (but I think the spec SHOULD recommend one, with a date and proviso that it's the "recommended best choice as of X date"). I also agree that Argon2 sounds very good.

(I imagine in the above you're thinking along the lines of spec-ing "WAMP-SCRAM-X" where "X" is replaced with a particular hash algorithm, so e.g. "WAMP-SCRAM-ARGON2")

More on Argon2 here: https://github.com/P-H-C/phc-winner-argon2 and https://password-hashing.net/ -- Argon2 uses Blake2b internally.

**Comment by oberstet** [comment]
`WAMP-SCRAM-ARGON2` works for me .. I mean, we are gonna have many of these potentially once we go down that road, but I don't see why that would actually matter. The parsing code just splits on `- `, makes that into a list of strings, and positionally checks the pieces. ARGON2 then merely maps to a predefined (in the spec) list of hash algos. Cool. Should work.

**Comment by oberstet** [comment]
Oh, just noticing: I really think the list of hash algos should be fixed in the spec. The spec can be revised, and that is expected. Eg RFCs have periodic errata, revisions. np. Or we could have it configured from a list of hash algos built into Crossbar.io. But at least for Crossbar.io, I would definitely not implement a user hook here to plug into arbitrary code. And further, these alogs need to be in the WAMP client libraries too, because from the application code, this all should be abstracted away IMO. So when algos would be "open ended", how would that even work? anyways, fixed list. my 2cts

**Comment by oberstet** [comment]
rgd Argon2 in particular: we would need a pure Python impl. (preferred), or a cffi based binding to a C library.

this one https://github.com/flamewow/argon2_py/blob/master/setup.py seems to be cpyext? I don't see cffi .. bad. we have (almost?) kicked out all those, because some of instability issues (memory leaks) we had in the past were due to cpyext related issues (memory management bug in library etc).

**Comment by meejah** [comment]
There's this: https://pypi.python.org/pypi/argon2_cffi (no idea of quality, by it's from hynek (which is a good thing) and looks like it covers everything Autobahn would need: py2, py3.4+ and pypy).

**Comment by oberstet** [comment]
@meejah that looks good! yeah, hynek: looks pretty "best practice" as a Python package/project;)

rgd the pw key derivation functions .. seems like these are used commonly:

* bcrypt
* PBKDF2
* scrypt
* Argon2

Rgd Argon2, for use with authentication schemes, it seems the subvariant "Argon2i" should probably be preferred: "Argon2i uses data-independent memory access, which is preferred for password hashing and password-based key derivation."

https://tools.ietf.org/html/draft-irtf-cfrg-argon2-02

**Comment by ecorm** [comment]
Please keep in mind the technique for upgrading existing passwords to stronger algorithms. The suggested technique is to take the old password hash and use it as the password input string for the stronger algorithm. To verify the password, it has to be hashed like this: `NewHash(OldHash(password, oldParams), newParams)`. When the user is authenticated, the password is re-hashed using the new algorithm and is stored in the database as `NewHash(password, newParams)`. Note that I've described this technique in terms of "traditional" authentication where the password is sent in clear text over a secure TLS connection. I haven't yet figured out how migrating passwords would work using SCRAM.

I'm also wondering the usefulness of "negotiating" the authentication scheme or password algorithms. Shouldn't the application backend (or router configuration) dictate the scheme/algorithm?

I've been looking at both SCRAM and [SRP](https://en.wikipedia.org/wiki/Secure_Remote_Password_protocol), and I'm finding it difficult to decide which would be best for our application. I can't find a comparative analysis of the two. It seems that SCRAM might have been borne out of the concern that SRP was patent-encumbered.

**Comment by ecorm** [comment]
I drafted a WAMP-SCRAM spec: https://github.com/wamp-proto/wamp-proto/issues/135#issuecomment-370074220

As I was drafting WAMP-SCRAM, I found that SRP seemed to have fewer vulnerabilities. The only downside I could find for SRP was that there are few library implementations to choose from. I might write a WAMP-SRP draft someday, but that would be more of a spare time thing that's not needed for my work.

In my study of SCRAM and SRP, I figured out that these don't allow the technique of chaining hashes when it comes to password migration. I'm also not crazy about the prospect of getting mobile web browsers to compute strong hashes client-side. To get a decent amount of Javascript performance, you need to use Emscripten-ized crypto libraries, and that gets me worried about browser compatibility.

I've therefore decided to stick with the traditional approach of only hashing the password server-side. To avoid the passwords being sniffed on our intermediary portal service, we're going to use public key encryption to avoid having the client send passwords as cleartext. The private/public key pairs are going to be "ephemeral" for the duration of the authentication exchange, so that avoids the risk of the private crypto keys getting stolen from a database backup.

WAMP-crypto authentication is not an option for our app, due to the need for users to "carry around" keys.

I'm now back in need of a "dynamic challenger" where I can send a public key to the client. Again, if this is not available, I can resort to a special "authenticate" RPC that must be called by the client before any other RPC or subscribe operation.

**Comment by ecorm** [comment]
It turns out my idea of encrypting passwords using a public key is not feasible for reasons I won't get into here. I'm now stuck with either SCRAM or SRP for authentication, and I'm leaning towards the latter due to better resistance against evesdropping. Fortunately, a lot of the discussion on WAMP-SCRAM is also applicable to a WAMP-SRP authmethod I'm about to propose.

**Comment by oberstet** [comment]
> WAMP-crypto authentication is not an option for our app, due to the need for users to "carry around" keys.

Private keys with WAMP-cryptosign are just short 32 bytes random values, and you can derive these from a user passphrase using some KDF, so there is no need to carry around a key ..

**Comment by ecorm** [comment]
@oberstet  Thanks for clearing that up. I need to study-up more on how WAMP-cryptosign actually works, and would appreciate a link to some learning material. Note that our clients are web browsers, and we don't expect users to have to do anything except remembering a password in their head.

**Comment by oberstet** [comment]
> we don't expect users to have to do anything except remembering a password

what do you expect users to remember in terms of length of password?

eg if you expect me to remember 32 bytes (highly unlikely .. I barely can remember anything), I can just type in my cryptosign private key.

in fact, expecting me to remember anything, with the security depending on me remembering a substantial amount of info to make a system secure, is a bad idea;)

**Comment by ecorm** [comment]
@oberstet Of course our users are free to use password managers, as they can for any other web service that uses password security. What I really meant is that users are not expected to install software/certificates, or configure anything on their end. Sorry if I wasn't clear.

**Comment by oberstet** [comment]
- crossbar and autobahn(python) now fully support and implement WAMP-SCRAM
- the challenge message/mechanism used with WAMP-SCRAM is specified in the WAMP spec (and cannot be user defined)

> hence I'm closing this. if you feel different, pls comment here
