### ISSUE TITLE
Crossbar snap based on PyPy

### ISSUE THREAD

**Issue by om26er** [crossbario/crossbar#1253]
We should have a snap published for Crossbar that uses PyPy instead of CPython.

**Comment by oberstet** [comment]
Are we using plugins? Is there a snapcraft PyPy plugin?

**Comment by om26er** [comment]
@oberstet there is no plugin for PyPy yet. I initiated a conversation yesterday on upstream [forum](https://forum.snapcraft.io/t/support-pypy-as-an-option-for-the-python-plugin/1669/2).

**Comment by om26er** [comment]
Yes, we are currently based on CPy. The above paste was when I built a PyPy based crossbar snap.

Not sure how to handle it, should we have a separate `crossbar-pypy` snap (if we want to support it) ?

**Comment by oberstet** [comment]
a separate `crossbar-pypy` snap in addition to the existing `crossbar` cpython based on, yes! I think this would be good (for now / mid term). one reason: ARM64 PyPy is under development (we sponsor the port .. together with ARM Ltd)

**Comment by oberstet** [comment]
related crossbarfx issue https://github.com/crossbario/crossbarfx/issues/177

**Comment by om26er** [comment]
@oberstet Should it always use the latest pypy or can we settle on pypy distributed by Ubuntu ? Ubuntu 16.04 has pypy 5.1.2 in its archives, its the same release which build.snapcraft.io uses to build snaps.

Alternatively we could find a way to download latest pypy from https://bitbucket.org/pypy/pypy/downloads/ for each architecture.

**Comment by oberstet** [comment]
we should use and bundle the upstream pypy (latest) directly, not ubuntu packages.

reasons:

* pypy 5.1 is old, on not compatible with python 3.5 (which we need)
* the ARM64 port is coming .. and it will require the latest pypy

also:

```
oberstet@intel-nuci7:~$ sudo snap install pypy
Fehler: This revision of snap "pypy" was published using classic confinement
        and thus may perform arbitrary system changes outside of the security
        sandbox that snaps are usually confined to, which may put your system
        at risk.

        If you understand and want to proceed repeat the command including
        --classic.
oberstet@intel-nuci7:~$ sudo snap install --classic pypy
pypy 5.8.0 from The PyPy Project (pypyproject) installed
oberstet@intel-nuci7:~$ /snap/bin/pypy --version
Python 2.7.13 (c925e7381036, Jun 05 2017, 21:20:51)
[PyPy 5.8.0 with GCC 6.2.0 20160901]
oberstet@intel-nuci7:~$ sudo snap install --classic pypy3
pypy3 5.8.0 from The PyPy Project (pypyproject) installed
oberstet@intel-nuci7:~$ /snap/bin/pypy3 --version
Python 3.5.3 (a39af0be3a22, Jun 05 2017, 20:18:00)
[PyPy 5.8.0-beta0 with GCC 6.2.0 20160901]
oberstet@intel-nuci7:~$ 
```

**Comment by oberstet** [comment]
another small thing: somehow/sometimes the snap badge on this repos readme shows a broken link .. I think the target should go to https://snapcraft.io/crossbar?

**Comment by oberstet** [comment]
fixed

https://github.com/crossbario/crossbar-pypy-snap
https://github.com/crossbario/crossbarfx-pypy-snap
https://snapcraft.io/crossbar-pypy/listing

however, these should actually move to https://github.com/crossbario/crossbar-binaries
