### ISSUE TITLE
WebSocket opening handshake timeout

### ISSUE THREAD

**Issue by kinderp** [crossbario/crossbar#1254]
I get this error when a long call blocks the server.

```
dropping connection to peer tcp4:127.0.0.1:8050 with abort=True: WebSocket opening handshake timeout (peer did not finish the opening handshake in time)
```
It seems no other clients can authenticate on the server.
This is my environment:

>(server_prova) arkimede@tensorflow:~/dev/server$ pip freeze|grep crossbar
>crossbar==17.9.2

>(server_prova) arkimede@tensorflow:~/dev/server$ python --version
>Python 3.6.3

>(server_prova) arkimede@tensorflow:~/dev/server$ lsb_release -a
>No LSB modules are available.
>Distributor ID:	Ubuntu
>Description:	Ubuntu 17.10
>Release:	17.10
>Codename:	

my config

```json
{
                    "type": "universal",
                    "endpoint": {
                        "type": "tcp",
                        "port": 8050
                    },
                    "rawsocket": {
                    },
                    "websocket": {
                        "ws": {
                            "type": "websocket",
                            "auth": {
                                "ticket": {
                                  "type": "dynamic",
                                  "authenticator": "com.justpith.authenticate"
                                },
                                "anonymous": {
                                  "type": "static",
                                  "role": "public"
                                }
                            },
                            "options": {
                             "open_handshake_timeout": 0,
                             "close_handshake_timeout": 0,
                             "auto_ping_interval": 0,
                             "auto_ping_timeout": 0
                            }
                        }
                    },
```
I'have tried to disable all timeouts in config with no results.
Thanks in advance

**Comment by meejah** [comment]
What do you mean "when a long call blocks the server"?

**Comment by kinderp** [comment]
A blocking request, like an http post or an i/o operation.

**Comment by meejah** [comment]
Those shouldn't block; how are you doing them? (That is, you should use a Twisted or asyncio library as appropriate to do the request in a non-blocking fashion)

**Comment by kinderp** [comment]
No i don't use non blocking library . I use requests for http and MySQLdb for queries.
Am i forced to change my code or can i workaround that use timeout options ?

**Comment by meejah** [comment]
Yes, your code must be non-blocking. There are tools to help you use blocking/threaded code with Twisted (e.g. `deferToThread`) but you can't block the main reactor loop. Same for asyncio.

**Comment by meejah** [comment]
Working around this by changing timeouts won't work -- network traffic won't be happening whenever the main thread is blocked and this will just not work well.

**Comment by kinderp** [comment]
Thanks meejah :+1:

**Comment by meejah** [comment]
The twisted library "treq" provides a "requests-like" API for Twisted. Basically, Autobahn/crossbar are designed around non-blocking/event-based thinking and frameworks -- so you'll have the best experience if you "buy in" to that and use non-blocking code everywhere. Of course, for simple things using `deferToThread` and the like can be made to work fine as well (by "simple" I mean: not high-traffic)
