### ISSUE TITLE
Scaling Crosssbar Up and Out

### ISSUE THREAD

**Issue by asgoel** [crossbario/crossbar#1257]
Hey there,

First of all, thanks for developing crossbar and autobahn! We are using it pretty extensively at our company and it has made our lives much easier. As we start to gear up for a production launch, we wanted to tackle some issues that are not currently implemented in Crossbar open source - namely High Availability with fast-failover, multi-machine routing, and to a lesser extent, multi-core routing. I noticed that on the roadmap here: https://crossbario.com/products/roadmap/ you have these features listed, but it wasn't clear to me whether these features are only going to be available as part of the commercial offering, or if they will be added to the open source version as well? In either case, what would be the timeline for some of these features?

**Comment by oberstet** [comment]
@asgoel In fact, we already have shipped a first feature in Crossbar.io Fabric (the commercial offering) that allows for scale-out / HA: a new native worker type for proxying incoming WAMP connections. Using that, you can run a set of native proxy workers terminating the incoming TLS/WebWebSocket connection on multiple cores and multiple machines. This is a first feature in a series where we address more and more scenarios/setups. Those enterprise features are only in the commercial offering, not part of the OSS releases. Please contact me privately for more infos ..
