### ISSUE TITLE
Don't install enum34 if python 3.4+

### ISSUE THREAD

**Issue by om26er** [crossbario/crossbar#1261]
Currently `requirements.txt` and `requirements-min.txt` contains enum34, we should only install it if python is 3.3-

as upstream [says](https://bitbucket.org/stoneleaf/enum34/issues/19/enum34-isnt-compatible-with-python-36#comment-36515102).

**Comment by oberstet** [comment]
If you find out how to combine conditional dependencies with freezing and hashin, let me know;)
