### ISSUE TITLE
"crossbar start" doesn't work 

### ISSUE THREAD

**Issue by rafamttz** [crossbario/crossbar#1268]
I'm trying start my node for my first project with crossbar, I already applied "crossbar init" command, and now "crossbar start" show me some problem in 'cli.py' file. The problem appears in the terminal: 

``Traceback (most recent call last):
  File "/home/rafamttz/python2713/bin/crossbar", line 7, in <module>
    from crossbar.controller.cli import run
  File "/home/rafamttz/python2713/lib/python2.7/site-packages/crossbar/controller/cli.py", line 55, in <module>
    from crossbar.controller.personality import Personality as CommunityPersonality
ImportError: No module named personality``

I'm using Ubuntu 16.04 LTS and Python 2.7

**Comment by oberstet** [comment]
not sure, works for me on Ubuntu 16.04: https://gist.github.com/oberstet/d3d8ede8103efeb9175ab356cb8a54bc

**Comment by om26er** [comment]
I just tested with Python 2.7 and Ubuntu 17.10, worked fine for me as well. Will test in a clean LXD container using Ubuntu 16.04 just to be sure.

**Comment by rafamttz** [comment]
ok, I installed crossbar in LXD container but when I try create the 'hello' template ...
``root@beloved-shrimp:~# crossbar init --template hello:python --appdir hello
Huh, sorry. There is no template named 'hello:python'. Try 'crossbar templates' to list the templates available.``
There is only the default template, what I must do to work with other template?

**Comment by oberstet** [comment]
@rafamttz the templating feature was deprecated .. there is only the default template.

**Comment by rafamttz** [comment]
ok... how can I use this default template?

**Comment by oberstet** [comment]
@rafamttz `crossbar init && crossbar start` is all you need to fire up a node with the default template. sorry, there is still some older docs out there that refer to this templating feature with different templates
