### ISSUE TITLE
Support TLS for hosted components

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#128]
```
        {
               "type": "class",
               "classname": "hello.hello.AppSession",
               "realm": "realm1",
               "transport": {
                  "type": "websocket",
                  "endpoint": {
                     "type": "tcp",
                     "host": "example.com",
                     "port": 9090,
                     "tls": {
                        ... client TLS configuration, like ciphers and certificate chain to verify the server certificate against ...
                     }
                  },
                  "url": "wss://example.com:9090/somepath"
               }
            }
```

**Comment by oberstet** [comment]
we need to complete support of connecting endpoints using TLS

**Comment by meejah** [comment]
Note that I think people find it confusing that you can right now provide an empty dict to "turn it on", so maybe we want to provide an option like ``enabled`` whose default is True? So you could be explicit like:

```
"tls": {
    "enabled": True
}
```

We'd also want a way to specify the certificate and private-key paths for a client-side certificate. To follow the server-side options, that might mean:
```
"tls": {
    "key": "/path/to/private_key",
    "certificate": "/path/to/client_cert",
    "hostname": "example.com"   # optional; expected hostname of the server
}
```

Beyond that, what other options? Probably setting the trust-root (i.e. "CA certificate bundle path"). This would allow one to work with self-signed certs (or a "corporation wide" root cert, for example). Something like ``"trust_root": "/usr/share/ca-certificates"`` and it recursively finds all ``.crt`` files in there (or something)?

It might also be interesting/useful to support pinning certificates, but I'd personally put that in a separate enhancement ticket. I would imagine this would look something like:

```
...
"tls": {
    "pinned_certificate_public_keys": ["public-key ID of cert", "public-key ID of intermediate cert", "public-key ID of root cert", "etc"]
}
```

**Comment by meejah** [comment]
For pinning, should be hashes of the public-key. Also, see good info here: https://www.imperialviolet.org/2011/05/04/pinning.html

**Comment by oberstet** [comment]
Other options: acceptable server certificates? Rgd certificate pinning: yeah, that could be a later enhancement if any.

**Comment by meejah** [comment]
@oberstet what do you mean by "acceptable server certificates"? That sounds like what I mean by "certificate pinning" ;) (that is, hard-coding what public-key should sign particular certs in the chain, but could be "just" the server-cert).

**Comment by meejah** [comment]
How about this for a first cut:

```
"tls": {
    "hostname": "expected hostname",
    "ca_certificates": [
        "self_signed.crt"
    }
}
```

``hostname`` is required (and turns on verification) -- if you don't specify ``ca_certificates``, we call Twisted's ``optionsForClientTLS(hostname)`` (which should result in using the default CA certificate store and do "browser-like" verification). Otherwise, you have to specify all the CA certs you're willing to trust.

For people using self-signed certificates, they can specify their server cert directly as the one-and-only CA certificate. The "hostname" *could* be auto-discovered from the containing endpoint, but then we'd probably want an ``enabled: true`` option?

TLS client-certificates: not possible with above; future enhancement.

Pinned certificate public-keys: not possible with the above; future enhancement.

**Comment by meejah** [comment]
see https://github.com/crossbario/crossbar/compare/master...meejah:issue128-client-tls-config?expand=1 and https://github.com/crossbario/crossbarexamples/compare/master...meejah:client-side-tls-example

**Comment by meejah** [comment]
p.s. the above-referenced branch (issue128-...) has preliminary TLS client-certificate support.

**Comment by oberstet** [comment]
works now: https://github.com/crossbario/crossbarexamples/tree/master/authenticate/tlsdynamic
