### ISSUE TITLE
Cannot listen on transport endpoint: 'OpenSSLCertificateOptions' has no attribute '_ecCurve'

### ISSUE THREAD

**Issue by Paradoxeuh** [crossbario/crossbar#1312]
Hi,

I've recently been seeing this issue while trying to launch crossbar (18.4.1) with TLS.
It seems related to twisted, and recent (I'm using a docker image and it has always been working until today, when I tried to install it from scratch again). Any idea of what it could be?

`--- <exception caught here> ---
  File "/usr/local/site-packages/crossbar/twisted/endpoint.py", line 558, in create_listening_port_from_config
    endpoint = create_listening_endpoint_from_config(config, cbdir, reactor, log)
  File "/usr/local/site-packages/crossbar/twisted/endpoint.py", line 376, in create_listening_endpoint_from_config
    context = _create_tls_server_context(config['tls'], cbdir, log)
  File "/usr/local/site-packages/crossbar/twisted/endpoint.py", line 257, in _create_tls_server_context
    if ctx._ecCurve is None:
builtins.AttributeError: 'OpenSSLCertificateOptions' object has no attribute '_ecCurve'
`

My docker image:
`
FROM amd64/pypy:3

RUN    apt-get update
RUN    apt-get install -y --no-install-recommends \
               ca-certificates \
               curl \
               expat \
               build-essential \
               libssl-dev
RUN    pip install --no-cache-dir -U pip
RUN    pip install --no-cache-dir crossbar

RUN crossbar version

ADD vizcab_backend/config.json /
ADD /certificate_crossbar/private.key /certificate_crossbar/private.key
ADD /certificate_crossbar/certificate.crt /certificate_crossbar/certificate.crt
ADD /certificate_crossbar/ca_bundle.crt /certificate_crossbar/ca_bundle.crt

ENTRYPOINT ["crossbar", "start", "--config", "config.json"]
`

**Comment by Paradoxeuh** [comment]
Ok i've just seen the code comments you wrote in endpoint.py my bad !

**Comment by meejah** [comment]
Okay, so: fixed in master (well, "fixed" because not using that code any more) so you can either upgrade crossbar to "master" or downgrade Twisted until the next crossbar release.

Please re-open if the above is incorrect!

**Comment by oberstet** [comment]
I commented the code that broke for now https://github.com/crossbario/crossbar/blob/master/crossbar/common/twisted/endpoint.py#L267 - it is non-critical logging code.

What we really should have, if that is possible with pyOpenSSL/Twisted now is to let users configure the default, or the permissible elliptic curves in the node configuration.

**Comment by meejah** [comment]
We were of course depending on "internal details" (`_ecCurve`) so not surprising it broke.

I haven't recently looked at the TLS "stuff" in Twisted but I know there's appetite for improving user-facing APIs in TLS in general, so if there *isn't* a "Twisted blessed" way to get this feature (i.e. query what elliptic curve we've selected), I could probably add it.

**Comment by oberstet** [comment]
yeah, we used a private thing, so fallout is ours;) such knobs and query functions would be nice to have in pyopenssl or twisted definitely .. but I would say it is very advanced TLS stuff that most won't touch, and given our backlog, I would postpone work from our side at least on this.
