### ISSUE TITLE
RouterWorkers IDs should not allow "." in them

### ISSUE THREAD

**Issue by meejah** [crossbario/crossbar#1324]
If a router worker's ID has a dot in it, it messed up internally-used WAMP URIs, like `crossbar.worker..on_worker_ready`. For example, if you had "my.id.has.dots" in it, then that URI becomes `crossbar.worker.my.id.has.dots.on_worker_ready` and the wildcard match doesn't match.

**Comment by oberstet** [comment]
uhh, bad: this again teaches me that working thoroughly (like eg adding the ID check in the first place that I likely missed) is a good thing and pays off in the end, because I guess this was tricky and time consuming to track down. it also reminds me of you poking me to write unit tests;)
