### ISSUE TITLE
Windows - Crossbar won't start - "cannot import name which"

### ISSUE THREAD

**Issue by Tsunami2069** [crossbario/crossbar#1328]
Hello everybody.

We have updated our development station's crossbar to the latest version (18.5.1) and crossbar stopped working.
Here is the error in question: 
![crossbarerror](https://user-images.githubusercontent.com/14236716/40193657-e24140da-59ff-11e8-85cf-10362bbde7a3.png)

Upon a little further investigation, it seems that it is related to the shutil and this latest version's removal of the shutilwhich.
Falling back to the previous version (18.4.1) fixes and crossbar starts working again.

We're running on Windows 10 machines.

Just thought you should know.

Keep up the great work.
Thank you.

**Comment by oberstet** [comment]
we don't support python 2 anymore

**Comment by Tsunami2069** [comment]
@oberstet 

Sorry to disturb you once more but i'm having an issue...
Installed the Python 3.6.5 (x86 executable) and installed crossbar for that version of Python.

Crossbar version shows, apparently, all OK but when i try to start my router i get the following error:

![snip1](https://user-images.githubusercontent.com/14236716/40197333-14e48c12-5a0b-11e8-97b9-78376c19d528.JPG)

What could be causing this? 
Can any1 help?

Thank you.
