### ISSUE TITLE
New docs

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1337]
* https://github.com/crossbario/crossbar/tree/master/docs
* https://s3.eu-central-1.amazonaws.com/download.crossbario.com/docs/crossbar/index.html

**Comment by goeddea** [comment]
Docs should move from a markdown-based rendering to RST/Sphinx because of the increased feature set there. Above links are to the new docs infrastructure for this.

**Comment by goeddea** [comment]
First task here: Come up with a new docs structure. This has to cover the two main purposes, getting new users to something basic working as simply as possible and providing the full documentation for power users.

Deliverable for this: pull request against this issue with a draft TOC.

**Comment by goeddea** [comment]
also needs integration into the crossbar-www repository which has the mechanism for deploying the docs to https://crossbar.io

rendering here is in web/server.py

**Comment by haizaar** [comment]
The currently published [Getting Started](https://crossbar.io/docs/Getting-Started/) guide is quite meaningless, since it refers to git repository that does not exist anymore.

**Comment by madflow** [comment]
I just tried to get "started" (https://crossbar.io/docs/Getting-Started/) - but I have to agree, that it is quite hard at the moment. I found the cookiecutter templates - but no documentation what ```generated```, ```service_uid``` or ```uid``` means. I do not require any more assistance or help - this is just a friendly ping, that "Getting started" is no quite clear at the moment.

**Comment by oberstet** [comment]
@codelectron has been doing a lot of work to convert all docs to Sphinx (ReST), cleanup the docs and bring them into good shape.

please see: https://crossbar.io/docs/

also, the docs are now automatically built and deployed in Travis CI (eg here is a log https://travis-ci.org/crossbario/crossbar/jobs/522515984)

further, any doc page may now be edited directly here in GitHub, eg https://github.com/crossbario/crossbar/blob/master/docs/Getting-Started.rst, and hit edit .. the idea is to lower the entry bar to quickly fix sth and let others contribute more easily. because, you know, it's a lot of work;) hope you like it
