### ISSUE TITLE
Kill all sessions by authid

### ISSUE THREAD

**Issue by ecorm** [crossbario/crossbar#1340]
We need a meta procedure that allows us to kill all active sessions under a particular `authid`. We have two use cases where we need to do this:

1. The application admin removing a user account at runtime.
2. The application admin suspending (deactivating) a user account at runtime.

If there are active sessions of the suspended/removed user still remaining, it would allow that user to continue interacting with the application, thus compromising security at the application level.

We are currently resorting to our application backend keeping track of all frontend sessions and associating each of the active sessions with the `authid`. Our backend must then call the `wamp.session.kill` meta procedure in a loop for each active session associated with the `authid`.

The lack of a `wamp.session.kill_by_authid` meta procedure is the only thing that requires us to do this tricky session tracking on the backend.

**Comment by oberstet** [comment]
Agreed: Crossbar.io should be provide that as a router management procedure, so sth like:

* `crossbar.session.kill_by_authid`

**Comment by oberstet** [comment]
implemented: https://github.com/crossbario/crossbar/blob/ecc8b4e0d9f8fa3efa7d59755cb2e16151055870/crossbar/router/service.py#L359
