### ISSUE TITLE
IOCP reactor Windows/Twisted backpressure issue

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1347]
This is an **upstream (Twisted) issue** effecting Crossbar.io on Windows when running IOCP reactor, in a backpressure situation. I dump the links here to track the issue on our side:

* https://twistedmatrix.com/trac/ticket/9446
* https://github.com/crossbario/autobahn-python/issues/993

**Comment by oberstet** [comment]
* windows tcp send buffer size
* https://support.microsoft.com/en-gb/help/224829/description-of-windows-2000-and-windows-server-2003-tcp-features
* netsh winsock set autotuning on
* netsh winsock set autotuning off
* HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\AFD\Parameters\REG_DWORD "DynamicSendBufferDisable"

**Comment by oberstet** [comment]
@asodeur so your Twisted PR has been merged https://github.com/twisted/twisted/pull/1025/commits/55fb0c49e8467c742ccdd6ea05146bd75d436517 - which means: `iocp` should work for crossbar on windows even on high load situations. we don't have a way to test this though. do you have a chance?

**Comment by ygl-rg** [comment]
how about the test?

**Comment by oberstet** [comment]
@asodeur ^ ping (did you had a chance to test/verify this stuff on windows after above fix was landed on twisted?)

**Comment by asodeur** [comment]
The patch has made it into twisted 19.2.1 or 19.7.0. We have been using twisted 19.10.0 and 20.3.0 for some time now and did not see the issue again.

**Comment by oberstet** [comment]
awesome. thanks for reporting back!

**Comment by ygl-rg** [comment]
thx for your info.
