### ISSUE TITLE
Crossbar does not rotates log files

### ISSUE THREAD

**Issue by chou666** [crossbario/crossbar#1359]
Version: Crossbar.io COMMUNITY 18.4.1

Start command line: crossbar start --cbdir="C:\Crossbar" --logdir="C:\Logs\Crossbar" --logtofile

As described in this page https://crossbar.io/docs/Automatic-Startup-and-Restart/#administration, "By default - if given --logdir option - Crossbar.io will create daily rotated log files", but this is not the case, only one file node.log is created.

As described in #512, this must be the case, but not mention of DailyLogFile in crossbar/_logging.py.

An idea?

**Comment by oddjobz** [comment]
I'm afraid I'm not sure how Windows deals with permissions (so this question may  be irrelevant) , but does your crossbar instance have permission to create a new file in C:\Logs\Crossbar? (on Linux, if crossbar can't create a new logfile in the specified directory, I think the behaviour is to fail silently and continue  logging to the same file) (actually I think this is  the behaviour of  'twisted' rather than Crossbar  itself)

**Comment by chou666** [comment]
Thanks for your answer. 
In fact when crossbar start, "Crossbar" subfolder does not exist in C:\Logs:
- directory created (SYSTEM user have full control on this folder)
- node.log file created
So I think this is not a users permission (running in SYSTEM context).

Maybe similar to #512?

**Comment by oddjobz** [comment]
Mmm, maybe similar effect, but it looks like that was rectified quite some time ago .. will see if I can replicate the issue here ...

**Comment by oddjobz** [comment]
Ok, it's seems to be happy on Linux .. will ponder access to a Windows machine .. in the meantime, are you actually logging stuff on a regular basis, or does the file remain mostly empty?

**Comment by chou666** [comment]
The file node.log append data:

2018-07-04T20:21:34+0200 [Router       4696] session "5918956507297840" joined realm "admin"
2018-07-05T09:12:58+0200 [Router       4696] session "3397403981562401" joined realm "admin"

**Comment by telatoa** [comment]
Hi,

While this issue is not fixed, do you have any workaround?

**Comment by oberstet** [comment]
daily log rotation: https://github.com/crossbario/crossbar/blob/ecc8b4e0d9f8fa3efa7d59755cb2e16151055870/crossbar/_logging.py#L296
