### ISSUE TITLE
Issue with personalities init code

### ISSUE THREAD

**Issue by oddjobz** [crossbario/crossbar#1365]
Currently we have;
https://github.com/crossbario/crossbar/blob/bd9b934923a313f93806cd952687da234d8d1259/crossbar/__init__.py#L221-L226

Two issues;

- Missing dependencies are masked, i.e. if a required random sub-module isn't included in the right requirements.txt files, it will result in an invalid personality error at run-time
- Actual errors in imported modules can also end in an ImportError

Maybe do the test using fopen, rather than try to catch import errors?
(although - do we need this code in CB, or is it obsolete?)

**Comment by meejah** [comment]
Yes I believe we need this code, or something similar anyway. This is to detect if you have "crossbarfx" at all -- if you're using plain-vanilla Crossbar, you won't. You're correct that an import-error in crossbarfx itself would be masked by the above -- but perhaps that's better detected by a unit-test of some kind in crossbarfx itself?

It would be possible to inspect the exact error message and re-raise if it doesn't look like "crossbarfx isn't installed" but that could be fragile...

**Comment by oddjobz** [comment]
Mmm, my thinking is that CB always has one personality, and FX always has two .. so this code could be refactored / split such that try/except aren't needed to make the decision. i.e. there are two distinct versions of that bit of code, so personality is determined by whether you launched 'crossbar' or 'crossbarfx' ...

**Comment by oberstet** [comment]
"crossbar" has personality "standalone" (or similar), while "crossbarfx" has "edge" or "master"

**Comment by oberstet** [comment]
> It would be possible to inspect the exact error message and re-raise if it doesn't look like "crossbarfx isn't installed" but that could be fragile...

yeah, we could do that .. or maybe some other loosely coupled way of determining the personalities installed. but if it works for now, I tend to .. leave it open for now for improvement

**Comment by oberstet** [comment]
@oddjobz it might break the code in crossbarfx. A better fix IMO is to look into the ImportError and check the actual class ..

**Comment by oberstet** [comment]
the respective code has been massively refactored. we now have "pluggable classes" for a lot of important internal surfaces. closing this. if you have/do run into this, pls don't hesitate to reopen - haven't seen such issues for quite some time now ..
