### ISSUE TITLE
Unexpected log output for every 'wget' on websocket

### ISSUE THREAD

**Issue by aberres** [crossbario/crossbar#1370]
I have crossbar running on Kubernetes.
As liveness check, it does a `wget` on the exposed websocket ever N seconds. If crossbar is up and running this nicely returns an 'information page'.

The thing is: For every successful connection I get an entry like the following in the log:
```
[Router 15] dropping connection to peer tcp4:10.44.0.1:56400 with abort=False: None
```
Does this happen on purpose? It looks like an error message while there is no real error. Everything was successful.
Until I was remembering my liveness check I was kinda confused...

**Comment by aberres** [comment]
Uhm, well there is no actual question. Everything is working fine.

I just claim that this message is a bit misleading when all that is happening is a GET request on the socket:
```
[Router 15] dropping connection to peer tcp4:10.44.0.1:56400 with abort=False: None
```

**Comment by oberstet** [comment]
well, it is a question: "why does this log message appear?"

answer: because browsers keep up to 6 http connections to a given target persistent .. until crossbar times out the idle connections.

**Comment by aberres** [comment]
Understood. But I *think* this case is different. I do not have a browser here.
It is Kubernetes doing the http GET.

The same behavior can be seen when hitting the endpoint with curl or wget.
E.g., with `wget -q -T 1 localhost:8080/ws`
The message appears instantly when the client closes the connection.

**Comment by oberstet** [comment]
answer is the same: http clients keeping connections persistent .. and crossbar killing them after some time of idleness. if a server doesn't do that, you have a DoS problem coming up ..

**Comment by aberres** [comment]
I was a bit confused as we have no real timeout in this case, but a look into the code makes things clear.

The connection is immediately dropped after the server status page is delivered: https://github.com/crossbario/autobahn-python/blob/master/autobahn/websocket/protocol.py#L2622

Makes sense and fine with me.
Should have activated debug logging - then it prints 
```
HTTP Upgrade header missing : render server status page
```
which helps with not being confused ;-)
