### ISSUE TITLE
ImportError: No module named abc

### ISSUE THREAD

**Issue by alexey-baranov** [crossbario/crossbar#1371]
Hello!

We have error when strarting crossbar on win7x64. What's wrong ?

> $ crossbar start                                                                                                                       
> Traceback (most recent call last):                                                                                                     
>   File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main                                                                    
>     "__main__", fname, loader, pkg_name)                                                                                               
>   File "c:\python27\lib\runpy.py", line 72, in _run_code                                                                               
>     exec code in run_globals                                                                                                           
>   File "C:\Python27\Scripts\crossbar.exe\__main__.py", line 9, in <module>                                                             
>   File "c:\python27\lib\site-packages\crossbar\__init__.py", line 177, in run                                                          
>     _personalities = personalities()                                                                                                   
>   File "c:\python27\lib\site-packages\crossbar\__init__.py", line 215, in personalities                                                
>     from crossbar import personality as standalone                                                                                     
>   File "c:\python27\lib\site-packages\crossbar\personality.py", line 34, in <module>                                                   
>     from collections.abc import Mapping                                                                                                
> ImportError: No module named abc                                                                                                       

python 2.7.14
pip 9.0.1

**Comment by meejah** [comment]
You need to use Python3 for recent crossbar releases. Sorry about the docs :(

**Comment by hoomi88** [comment]
I saw also that abc was deprecated. You can use some of the abc functions directly from the collections datatypes:
https://docs.python.org/2/library/collections.html
