### ISSUE TITLE
Broken python2 support

### ISSUE THREAD

**Issue by AndreySV** [crossbario/crossbar#1375]
Neither crossbar version nor crossbar start work on python2 anymore.

**Comment by oberstet** [comment]
yes, correct, because it is no longer supported: https://github.com/crossbario/crossbar/blob/master/setup.py#L118

**Comment by AndreySV** [comment]
Thanks, I wasn't sure about python2 support, because previous version worked without an issue on python2 and current version can be installed with pip on python2.
I see wheel package is built for py2 and py3. 
https://pypi.org/project/crossbar/#files

Maybe it's better then to build package only for py3?
