### ISSUE TITLE
INTERRUPT sent to callees that don't support call_cancelling

### ISSUE THREAD

**Issue by ecorm** [crossbario/crossbar#1382]
We are using a C++ client (CppWAMP) for our backend which does not support the `INTERRUPT` and therefore does not include the `call_canceling` feature in its `HELLO.Details.roles.callee.features`.

We are using a Javascript client (Thruway.js) on the web browser front-end which can and does send `CANCEL` messages.

We are noticing that whenever Crossbar receives a `CANCEL` message from a browser, it sends an `INTERRUPT` to our C++ backend, causing the latter to drop the connection due to receiving an unsupported message type. This is with the latest Crossbar release (v18.7.2).

The behavior we would expect from Crossbar in this situation is that if the callee does not support `call_canceling`, then Crossbar will not propagate the cancellation to the callee in the form of an `INTERRUPT` message.

All of the RPCs in our application are essentially non-blocking, so there's no inherent need for us to support `INTERRUPT` messages in our C++ backend.

Looking at https://github.com/crossbario/crossbar/blob/86e4d93251d25d430f6bc223a85c412ac52ace7a/crossbar/router/dealer.py#L973, I see that the `if` condition is checking if `session` supports `call_canceling` (whatever `session` means here in this context - boy, do I hate dynamically typed languages). Shouldn't the condition here be checking if the _callee_ supports `call_canceling`?

**Comment by oberstet** [comment]
the WAMP spec text has recently been polished up / clarified, and gaps filled in rgd the call cancelation feature: https://wamp-proto.org/static/rfc/draft-oberstet-hybi-crossbar-wamp.html#call-canceling

and yeah, crossbar is not yet reflecting this! I'd consider this pretty important (support). once we have it here in crossbar, yes, next thing is to get autobahn client libs fully support it too. right now, I am not deep into this enough / have oversight, but rgd the Python based stuff (crossbar/abpy), I hope @meejah could jump onto this probably;) obviously, implementation requires some bits deep inside the routing code etc .. not many lines, but the right ones at the right places, and to do that, one needs a deep understanding of the codebases ..

**Comment by ecorm** [comment]
You may close this as a duplicate of #1377 if you wish.

**Comment by meejah** [comment]
See #1377
