### ISSUE TITLE
Is it possible to change authid in a session?

### ISSUE THREAD

**Issue by sevaho** [crossbario/crossbar#1389]
Hello

When connecting to a crossbar server for example anonymously (WAMP-anonymous) you specify a realm and a crossbar url. Next your session_id for example 123456789 gets assigned a role and a random authid which is a UUID.

Now my question is, is it possible to ask crossbar to change your authid on the fly to something else?

Greetings

**Comment by oberstet** [comment]
Yes, this is possible using dynamic authenticators - here is an example https://github.com/crossbario/crossbar-examples/tree/master/authentication/advanced
