### ISSUE TITLE
[Freature request] Running authorizators on separate realm

### ISSUE THREAD

**Issue by haizaar** [crossbario/crossbar#1399]
Good day,

Today it's [possible](https://crossbar.io/docs/Dynamic-Authenticators/) to run a realm's authenticator on a separate realm, which is cool, since it solves an issue of who authenticates the authenticator.

Can we have the same for authorizers?

My motivation is as follows: I have a realm that my users connect to. Each user is authenticated and their requests require authorization. When having authorizer on the same real, it requires a dedicated user account for it with authenticator explicitly setting its role to the one defined for authorization in crossbar config.

While the above setup works, I think it's cleaner to have both authn and authz separately. It minimizes attack surface - a dedicated authn/z realm can run on a separate port, accessible only internally for backend services.

What do you think?

**Comment by oberstet** [comment]
Yes, I agree, that would be useful

**Comment by oberstet** [comment]
fixed long ago https://github.com/crossbario/crossbar-examples/tree/master/authentication/advanced#running-authenticators-in-configurable-realms
