### ISSUE TITLE
Router-to-router communication

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#14]

**Comment by erichonkanen** [comment]
hello, is there any movement on this or any git branches in progress to check out? Is this the multi-node enhancement?

just trying to gather more info on future support for support multiple routers (for redundancy and high-scalability)...

**Comment by goeddea** [comment]
Router-to-router communication is part of what is necessary for multi-node to work on part of the router. There isn't anything to check out yet, but work is underway.

**Comment by braingineer** [comment]
Hi!  Is there any progress on this?  I've had to hack together a deferredQueue and some other things to get one router subscription to be published to another router's subscriptions

**Comment by erichonkanen** [comment]
Curious if this is still in development or if it's not likely to come any time soon?

**Comment by braingineer** [comment]
@erichonkanen I use a Queue and two sessions to connect up two routers:

https://gist.github.com/braingineer/9c688d96a28c4fbf74f41ae66f5972c0#file-relay-py

basically, your home router sets up and starts the other application session, which is pointed the router you want to connect to.  it uses a python multiprocessing queue to put and get echo'ed items. 

https://gist.github.com/braingineer/9c688d96a28c4fbf74f41ae66f5972c0#file-relay-py-L74

**Comment by oberstet** [comment]
r2r links have been added to https://github.com/crossbario/crossbarfx - closing this one
