### ISSUE TITLE
EMFILE encountered; releasing reserved file descriptor.

### ISSUE THREAD

**Issue by arnstein** [crossbario/crossbar#1423]
Recently I've started receiving this error on Crossbar.
I have done minor changes to the code of one of the two devices on the network, but none that are related to Crossbar, so I have no idea why this is starting to pop up.
If I restart Crossbar it works well again, but after some time this happens again.

The version is 18.9.2.

Here's the log:
```
Oct 26 12:16:11 localhost crossbar[11919]: 2018-10-26T12:16:11+0200 [Router      11926] EMFILE encountered; releasing reserved file descriptor.
Oct 26 12:16:11 localhost crossbar[11919]: 2018-10-26T12:16:11+0200 [Router      11926] EMFILE recovery: Closed socket from ('10.42.0.95', 53512)
Oct 26 12:16:11 localhost crossbar[11919]: 2018-10-26T12:16:11+0200 [Router      11926] Re-reserving EMFILE recovery file descriptor.
```

**Comment by meejah** [comment]
Those messages come from Twisted. I'm not sure what they mean, exactly, but try the mailing-list or the `#autobahn` or `#twisted` IRC channels.

**Comment by oberstet** [comment]
you might run out of file descriptors .. to increase, see https://crossbar.io/docs/Network-Tuning/
