### ISSUE TITLE
Crossbar documentation is confusing (especially for Docker)

### ISSUE THREAD

**Issue by sjdv1982** [crossbario/crossbar#1444]
Maybe it is on my side, but I find it very difficult to understand Crossbar from the documentation. Since I find this a fantastic project, here is my feedback, I hope that it is useful to you.

Now I finally understand that "crossbar.io" means the software, not the website. Initially (i.e. a year ago)  I thought that Crossbar worked like Teletype or BitTorrent trackers, i.e. that channels were brokered via the crossbar.io website, which is why I rejected it at first. I am glad to learn I can set up my own router running from a Docker image.

The  site https://crossbar.io/docs/Getting-Started/ lacks essential information. For me, the essential steps are:
1.  `docker pull crossbario/crossbar` 
which is on the main web site but not on the Getting-Started page.
2. Understand that I do not need any of the other Docker containers (instead, `sudo pip autobahn` on my dev machine; why would I want to have the API libraries in a Docker container??)
3. Understand that I do not need any "Starter templates", as everything is in the config.json
4. Understand that Crossbar docker container reads documentation from the "node" directory, which has to contain ".crossbar/config.json" (I had to read the Dockerfile itself to learn this). Obviously, I want my own config.json, so the proper invocation becomes "docker run -it -p HPORT:PORT -v DIR:/node crossbario/crossbar", where DIR is the config directory with ".crossbar/config.json", containing the value of PORT.   I learned that DIR must be writable, since Crossbar writes some files there (maybe something to change? After some studying, I settled for using the --config option instead). 
Then I could run the basic Python example (minor issue: I had to change "crossbardemo" to "realm1", but that was easy to understand).
5. Understand that it is possible to bundle arbitrary WAMP components with the router itself (although I do not understand why; a program should do just one thing, IMO). I got very confused earlier by reading the Administration guide about configuring containers, components and guests (and even a file server!), until I realized that I don't need them as they have nothing to do with Crossbar's main function, i.e. the routing of  WAMP messages. Now I feel that I understand the json.config and the whole Crossbar system much better.

I hope that this feedback is useful.

**Comment by guanzo** [comment]
Agreed, the docs need to be updated with more information.

**Comment by nguyen-tam** [comment]
Then run docker with : 

sudo docker run -d -it -p 8080:8080 crossbario/crossbar
​

**Comment by codelectron** [comment]
@oberstet With the updated documentation, this issue is resolved, we can close it.
