### ISSUE TITLE
Channel redirect commands

### ISSUE THREAD

**Issue by sjdv1982** [crossbario/crossbar#1445]
I would like to suggest a feature, which I think will be useful for myself and others. I can code it myself, if the PR would be accepted (or even if not), but I would like to hear if you think it a good idea or not.

I am mostly interested in Crossbar to coordinate a cluster of computing nodes. I want precise control over which node receives which job, so I don't want to use slurm/torque, nor do I want to use any kind of automatic load balancer (random, round-robin or otherwise). In any case, each job is a stream of requests, with large payloads per request.

For my case, Crossbar is ideal, because I can set up WAMP channels for each worker (input.workerX and output.workerX), and my own frontend, with input.frontend and output.frontend channels. All job streams would go to input.frontend (in the public realm) and the frontend would then decide dynamically where to send it.
Now, I could already do this, but the frontend would have to re-encode each request and send it back to the router on the input.workerX channel, to be forwarded to the worker. With big payloads and multiple layers of frontends, this would be very bad for performance.

What I would like to implement is a special kind of channel, the redirect channel. 
Any message sent over the  redirect channel will be interpreted by Crossbar.io as a redirect command. 
A redirect command must have the format `<command>, <source channel>, <target channel>, [target realm]`. 
`<command>` must be "add" or "remove". A redirect command causes all messages from `<source channel>` to be sent to `<target channel>` in the target realm. 

- Every realm may have one redirect channel, of which the name must be configured in config.json.
- Only clients with {"allow": {"redirect": true}}  are allowed to send messages to the redirect channel.
- Every realm may have a list of friend realms (empty by default) that are allowed to target the realm via redirect commands.

As far as I can see, the place to store redirect commands would be in the UriObservationMap class in crossbar/router/observation.py.

For this to work, the ordering guarantees of the WAMP protocol must be strong enough (I was not sure from reading the spec).
Is the event handler of a client required to be synchronous and unbuffered? In other words, if a client responds to a event X with an unsubscribe, is it guaranteed that it will never receive event X+1 (from the same channel)?
Are subscribe and unsubscribe guaranteed to be ordered? If in an event handler, a client subscribes to A and unsubscribes to B, will it at every point in time be subscribed to A XOR B?

**Comment by meejah** [comment]
Hmm. So first of all it might be better to use crossbar-specific terminology; we don't have "channels". We have "topics" to which you can publish. So what I think you're really asking for here is to be able to re-target an already-`publish()`-ed event to a new topic?

For just your last question about subscribe+unsubscribe: No, there will be an interval during which it is subscribed to both A and B (the time between the router processing the `subscribe(A)` and whenever it processes `unsubscribe(B)`). This can be an arbitrary amount of time "because network". So, the *order* in which those messages are processed is 100% certain (the `subscribe(A)` will be processed first for that client) but not the amount of time that passes between any two messages getting processed.

As to the general feature: could you maybe re-structure your application to make the "big payloads" not-big, thusly:

 - a client with the big payload keeps it locally
 - you `publish()` events to topics to get work done
   - part of the information here is a WAMP method-name of where to fetch the "big payload" from (instead of the big payload itself)
 - when a worker gets an event to do some work, it finds the WAMP method-name and calls it to fetch the "big payload".

**Comment by meejah** [comment]
(I guess the thing to remember here is that everything in WAMP is a client of the router, and so it doesn't really matter which way information flows; things that are typically "clients" can register methods and things that are typically "servers" can call them..)

**Comment by sjdv1982** [comment]
> Hmm. So first of all it might be better to use crossbar-specific terminology; we don't have "channels". We have "topics" to which you can publish. 
...
> (I guess the thing to remember here is that everything in WAMP is a client of the router, and so it 
> doesn't really matter which way information flows ...)

Sorry about that. I will talk about "topics", "subscribers" and "events"  then.

> So what I think you're really asking for here is to be able to re-target an already-`publish()`-ed event to a new topic?

No, that would be impossible, I guess. I wouldn't expect a router to keep an event in memory after it has notified all subscribers. I am talking about future events on the topic.

> 
> For just your last question about subscribe+unsubscribe: No, there will be an interval during which it is subscribed to both A and B (the time between the router processing the `subscribe(A)` and whenever it processes `unsubscribe(B)`). This can be an arbitrary amount of time "because network". So, the _order_ in which those messages are processed is 100% certain (the `subscribe(A)` will be processed first for that client) but not the amount of time that passes between any two messages getting processed.

Ugh, that is bad! I need such "atomic transaction" guarantees, else events could be lost or duplicated!
Would there be any objection against an Autobahn/Crossbar "hold" flag for .(un)subscribe and .publish requests? On the router, each hold request would be held until a non-hold request is received from the same client, and then all of those requests would be processed as a batch, without any other requests from other clients being processed in between. That should do the job, yes?


> 
> As to the general feature: could you maybe re-structure your application to make the "big payloads" not-big, thusly:
> 
> * a client with the big payload keeps it locally
> * you `publish()` events to topics to get work done
>   
>   * part of the information here is a WAMP method-name of where to fetch the "big payload" from (instead of the big payload itself)
> * when a worker gets an event to do some work, it finds the WAMP method-name and calls it to fetch the "big payload".

Hmmm, unfortunately the big payloads are an integral part of it (scientific computing, you know). And the requests will come from the web, but my nodes will not have direct access to the web; all network traffic will go through Crossbar.

**Comment by sjdv1982** [comment]
> So what I think you're really asking for here is to be able to re-target an already-`publish()`-ed event to a new topic?

Also, the source topic would still exist. It is just that all subscribers to the target topic would also receive the event. So maybe "forwarding command" would be a better term.

**Comment by meejah** [comment]
So essentially you want to publish to topic "redirect" always but be able to "re-target" where which topic that publish is "really" sent out on..?

If so, one approach w/o modifying crossbar could be to run a component "in/alongside" the router which simply does that: re-publishes the event to whatever the new topic is. If this component is written in Twisted, it can run in the same process as the router-process (and hence, even though you're technically re-publishing something large, it should be very fast as it's all in-memory and not round-tripping over the network to some other component).

**Comment by meejah** [comment]
WAMP has "auto-ping" from either the server or client side (or both); is that what you mean by "heartbeat"..? And there's the "WAMP meta API" which can notify you of any session dropping (or starting), so that's also already built-in.

**Comment by sjdv1982** [comment]
> WAMP has "auto-ping" from either the server or client side (or both); is that what you mean by "heartbeat"..? And there's the "WAMP meta API" which can notify you of any session dropping (or starting), so that's also already built-in.

Now I am getting very confused... there is nothing about auto-ping in the WAMP spec, am I reading an old version? (wamp-proto.org is down at the moment).

I was under the impression that my on_event handler could be blocking, i.e. that I could do a one-hour computation in it. This is ideal for me, because since I am not giving any ACKs, Crossbar.io will hold on to future events on the input topic because it can't dispatch them to me. And I can then decide at the end of my computation if I want to unsubscribe or not. 

If I try that in Jupyter, I immediately get a "kernel dead" message, because Jupyter indeed sends a continous streams of messages (these would be what you call auto-pings?) on the heartbeat channel, and expects me to acknowledge them. So in Jupyter, I simply cannot do that, and I have to yield or to run in a different thread.

**Comment by sjdv1982** [comment]
> I guess as an overall comment here: this seems like a case of "premature optimization". Can you try having a component that simply re-publishes messages of the size you're expecting (as outlined in [#1445 (comment)](https://github.com/crossbario/crossbar/issues/1445#issuecomment-442979015)) and see if that's actually "too slow"?
> 
> Another option is to use unix-sockets and have a normal (not in-router-process) component re-publish the message; this will also be very fast. Without some numbers on these kinds of scenarios we wouldn't even know if an "all in-router" approach was significantly faster :)

I have had payloads up to 40 GB. At that scale, it is not just the socket speed, it is also the copying of messages that I want to avoid.

Thanks your suggestion of a separate component. If there is insufficient interest in forwarding or atomic transactions to have it added to the main router, that will be the best way to go. I will have it listen on a separate network port.

**Comment by sjdv1982** [comment]
> > WAMP has "auto-ping" from either the server or client side (or both); is that what you mean by "heartbeat"..? And there's the "WAMP meta API" which can notify you of any session dropping (or starting), so that's also already built-in.
> 
> Now I am getting very confused... there is nothing about auto-ping in the WAMP spec, am I reading an old version? (wamp-proto.org is down at the moment).
> 
> I was under the impression that my on_event handler could be blocking, i.e. that I could do a one-hour computation in it. This is ideal for me, because since I am not giving any ACKs, Crossbar.io will hold on to future events on the input topic because it can't dispatch them to me. And I can then decide at the end of my computation if I want to unsubscribe or not.
> 
> If I try that in Jupyter, I immediately get a "kernel dead" message, because Jupyter indeed sends a continous streams of messages (these would be what you call auto-pings?) on the heartbeat channel, and expects me to acknowledge them. So in Jupyter, I simply cannot do that, and I have to yield or to run in a different thread.

My confusion continues... I wanted to find out if on_event can indeed be blocking (i.e. take a long time). I have been adding different values of time.sleep() to on_event in the basic example 
(https://github.com/crossbario/autobahn-python/blob/master/examples/asyncio/wamp/pubsub/basic/frontend.py, line 44)

Even with time.sleep(0.5), I get a strange error message, and at time.sleep(10), the frontend does not die after receiving 6 events, even though it is supposed to. No difference when I port it from asyncio to Twisted.
The expected error message (about failed ping), appears only at the end.

I can file a bug report, if you like, but maybe Crossbar simply isn't designed for what I want to do :(

**Comment by oddjobz** [comment]
time.sleep() inside an twisted event loop may not always be what you want as it may block the IO you're waiting for .. does it make any difference if you use txaio.sleep() ?? https://github.com/crossbario/txaio

**Comment by meejah** [comment]
Yeah 40GB is a lot .. probably worth using "progressive results" somehow? (We would like to add "progressive inputs" too but that's not implemented)

With that much data, it seems like maybe simply `publish()`-ing it would be problematic even if the router could do this sort of aliasing on `publish()`? Almost like it should be a separate step, so it could be re-started etc and then it's definitely "on the storage system" before you kick off any CPU-intensive jobs against it...

> I was under the impression that my on_event handler could be blocking, i.e. that I could do a one-hour computation in it. This is ideal for me, because since I am not giving any ACKs, Crossbar.io will hold on to future events on the input topic because it can't dispatch them to me. And I can then decide at the end of my computation if I want to unsubscribe or not.

If you mean simply blocking the reactor/event-loop for an hour: no, you can't do that. You'd have to do compute-intensive things in a separate thread (or ideally separate process) and arrange some method of either rejecting work or not being given it in the first place.

> Now I am getting very confused... there is nothing about auto-ping in the WAMP spec, am I reading an old version? (wamp-proto.org is down at the moment).

Yes, you're right I'm thinking of WebSocket features; sorry for the confusion.

**Comment by meejah** [comment]
Yes, you can't use `time.sleep()` in Twisted or asyncio. `txaio.sleep` returns a `Deferred` or `Future` that "fires" in the given timeout (so it doesn't actually block the reactor/event-loop)

**Comment by sjdv1982** [comment]
> time.sleep() inside an twisted event loop may not always be what you want as it may block the IO you're waiting for .. does it make any difference if you use txaio.sleep() ?? https://github.com/crossbario/txaio

> Yes, you can't use `time.sleep()` in Twisted or asyncio. `txaio.sleep` returns a `Deferred` or `Future` that "fires" in the given timeout (so it doesn't actually block the reactor/event-loop)

Well, I *want* to block the reactor/event-loop (i.e. I don't want to receive any more messages until my long computation is done). Clearly, twisted/asyncio are not designed for my use case. 

It seems that Crossbar is not suitable for what I want to do, I will have to build something else (or maybe on top of it). Thanks for all your help! I have learned a lot from this.

**Comment by oddjobz** [comment]
In general, any kind of asyncio or event loop framework will expect you to complete computation in the minimum amount of time possible. Whereas 'you' might want to block and wait, the framework itself still needs to be able to react .. and time.sleep effectively blocks everything (including the framework), whereas txaio.sleep effectively only blocks 'you'. If you have something that takes a non-trivial amount of time to complete, you either need to yield to the event loop on a regular basis, or run the procedure in a separate thread (or process). (I think txaio.sleep will address your problem) You might also consider that if standard mechanism's for handling IO don't suit your use-case, whereas these mechanisms may be inadequate, there's also a possibility that maybe you're doing it wrong!  ;-)

**Comment by meejah** [comment]
> Now I understand also why WAMP cannot make stronger ordering guarantees, or support atomic blocks of transactions; all of these require that all event handling be blocked until the current event has been processed in full.

No, you still don't require to block the event loop to achieve ordering. For example, there are asynchronous semaphores. There is a Twisted library to speak to Postgres (which absolutely does do transactions). WAMP doesn't do transactions. There are some orderings that you can depend on: a single client's messages won't be processed out-of-order so `publish(A)` and then `publish(B)` will always result in the A publish arriving at the router first (and being processed by it first).

In any case, the mechanism to limit the amount of work you do should definitely NOT be based on "I will now ignore all networking for 1 hour" no matter if you're using threads or event-based concurrency paradigms...

**Comment by sjdv1982** [comment]
With "atomic transaction" I mean in the context of WAMP, i.e.  "upon
receiving event E from topic B, unsubscribe from B, and subscribe to A" and
be sure that:
- No events after E from topic B will be sent to me
- All events from topic A after E will be sent to me
- If I have the power to unsubscribe *others*, they will not receive any
events after E, either.

And I will be happy to ignore networking for one hour when doing
computations. I have a privileged channel already to kill it off, if needed.

**Comment by meejah** [comment]
Being able to have a group of messages ("a transaction") might be an interesting feature, but it would have to start in wamp-proto I'd say and I think there will be a TON of edge cases to figure out and specify here.

e.g. what if that client disconnects part way through? What if some of the "others" are very slow (or even completely unresponsive)? You may think you're "happy to ignore networking" but also that's sort of a completely different thing; why not simply disconnect when you've received one work-unit then?

Anyway, please stop by `#autobahn` on Freenode if you want to discuss further; this bug-tracker isn't really the place.
