### ISSUE TITLE
Remove dependency on six

### ISSUE THREAD

**Issue by om26er** [crossbario/crossbar#1456]
Seems we no longer support Python 2, so we probably need to get rid of all the `six` usage in the code base. Unless if we use it for something that I don't know ?

**Comment by meejah** [comment]
Yes, we could probably remove all `six` usage (at least, I can't think of a reason why not).

**Comment by om26er** [comment]
Ok, I proposed my initial effort [here](https://github.com/crossbario/crossbar/pull/1457), let the CI run and see how things are.
