### ISSUE TITLE
Hixie76 protocol not supported.

### ISSUE THREAD

**Issue by antoniosap** [crossbario/crossbar#1458]
in .crossbar/config.json

if i drop parameter option/enable_hixie76 and have this warning
Hixie76 protocol not supported.

if i add "enable_hixie76": true i have from crossbar check 
warning of unsupported option

and then ? any ideas?

crossbar v18.12.1

**Comment by oberstet** [comment]
hixie76 is no longer supported (it was in the past, but we removed it from crossbar, since hixie76 is fundamentally flawed and can be a security issue). autobahn-python still supports it.
