### ISSUE TITLE
Error after install Crossbar on Ubuntu 14.04

### ISSUE THREAD

**Issue by carlosbbraga** [crossbario/crossbar#1462]
Can´t make crossbar to work. Keep getting the error below: 

root@SRV-WEB-CPT:~# crossbar version
Traceback (most recent call last):
  File "/usr/local/bin/crossbar", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/crossbar/__init__.py", line 177, in run
    _personalities = personalities()
  File "/usr/local/lib/python2.7/dist-packages/crossbar/__init__.py", line 215, in personalities
    from crossbar import personality as standalone
  File "/usr/local/lib/python2.7/dist-packages/crossbar/personality.py", line 34, in <module>
    from collections.abc import Mapping
ImportError: No module named abc

**Comment by glenfant** [comment]
Python 2.7 support has been dropped with the latest crossbar. You need Python 3.5 or later. This has apparently no connection with your Ubuntu version.

**Comment by oberstet** [comment]
Yeah, pls use Python 3 .. preferably in a dedicated virtualenv (to not pollute or run into version conflicts when installing into global env).

> you can also use snaps: `snap install crossbar` - even better

**Comment by carlosbbraga** [comment]
I have uninstalled python2.7 and python 3 and it is still not working.
I have a legacy application running crossbar and it has been days and I can´t even make crossbar work
the error now:: 


Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/cryptography
Storing debug log for failure in /root/.pip/pip.log
root@SRV-WEB-CPT:~# crossbar version
-bash: /usr/local/bin/crossbar: /usr/bin/python: bad interpreter: No such file or directory

**Comment by oberstet** [comment]
I'm sorry to hear you wasted a lot of time on this. fwiw, I just tested in a completely fresh virtualenv - works for me:

https://gist.github.com/oberstet/83b5f1e8752bfced8fdaa2b8b065d6bc

could you try the following?

```
python3 -V
python3 -m venv ~/crossbar
source ~/crossbar/bin/activate
mkdir ~/test
cd ~/test
pip install crossbar
which crossbar
crossbar version
crossbar init
crossbar start
```

```

**Comment by oberstet** [comment]
also: I tested on Python 3.7.2 (the very latest), but anything >=3.5 should work fine.

**Comment by oddjobz** [comment]
Just in case, (Ubuntu has in the past allowed both pip2 and pip3 to coexist and defaulted to pip2) for the pip command, you could also do;
```
python3 -m pip crossbar
``
Just to make sure it's the "right" "pip" ..

**Comment by oberstet** [comment]
^ oh yes! also a common source of issues (wrong pip)

**Comment by carlosbbraga** [comment]
> I'm sorry to hear you wasted a lot of time on this. fwiw, I just tested in a completely fresh virtualenv - works for me:
> 
> https://gist.github.com/oberstet/83b5f1e8752bfced8fdaa2b8b065d6bc
> 
> could you try the following and post the complete output here (or as a GH gist or sth)?
> 
> ```
> python3 -V
> python3 -m venv ~/crossbar
> source ~/crossbar/bin/activate
> mkdir ~/test
> cd ~/test
> pip install crossbar
> which crossbar
> crossbar version
> crossbar init
> crossbar start
> ```

First of all, thanks for all the help!
But I still can´t get it to install. 

Here is where I am right now:

(crossbar) root@SRV-WEB-CPT:~# pip install crossbar
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting crossbar
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/crossbar/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/crossbar/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/crossbar/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/crossbar/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/crossbar/
  Could not fetch URL https://pypi.org/simple/crossbar/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/crossbar/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
  Could not find a version that satisfies the requirement crossbar (from versions: )
No matching distribution found for crossbar
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping


(crossbar) root@SRV-WEB-CPT:~# python3.7 -m pip install crossbar
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting crossbar
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/crossbar/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/crossbar/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/crossbar/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/crossbar/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/crossbar/
  Could not fetch URL https://pypi.org/simple/crossbar/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/crossbar/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
  Could not find a version that satisfies the requirement crossbar (from versions: )
No matching distribution found for crossbar
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

**Comment by oddjobz** [comment]
Hi, can you try;
```
apt install python3-openssl
```
Then try the pip again?

**Comment by carlosbbraga** [comment]
> Hi, can you try;
> 
> ```
> apt install python3-openssl
> ```
> Then try the pip again?

Nothing changed! Same result after pip install crossbar

**Comment by carlosbbraga** [comment]
> The issue likely is because Trusty has some old version of libssl that doesn't play nice with Python 3.7 -- I found one post on Ask Ubuntu and seems that person was also facing a similar issue https://askubuntu.com/questions/999462/ubuntu-14-04-lts-update-openssl-manually
> 
> PS: Trusty goes EOL in April, so its time to upgrade ;-)

You mean upgrade ubuntu ?

**Comment by carlosbbraga** [comment]
Something odd is happening. 

I´ve managed to sucessfully install and run crossbar by deleting everything related to python on the system, resintalling python3 and manually including python bynari from python3 ( cloning and renaming file ). After that, crossbar was up and running.

Than I´ve resintalled node.js to finally test my application, and since node.js have some old python2.7 dependency, guess what ? The same problem is back!

**Comment by oberstet** [comment]
as said, pls use a dedicatede venv - then you dont run into issues with version conflicts ..

**Comment by carlosbbraga** [comment]
I suggest a big change on crossbar documentation.
I could only make it work by changing installation methods and version of ubuntu ( from 14.04 to 18.4 )

Using the regular sudo apt-get install python3-pip and installing crossbar by using sudo snap install crossbar 
After that everythin ran normal.
Thanks for all the help. I´ll be more than happy to help you change the docs so people will no longer have this kind of issue.

**Comment by oddjobz** [comment]
@carlosbbraga can I ask how / why you ended up trying to get Crossbar running on 14.04, as opposed to something a little more up-to-date?

**Comment by om26er** [comment]
> I suggest a big change on crossbar documentation.
> I could only make it work by changing installation methods and version of ubuntu ( from 14.04 to 18.4 )

I think the issue is unrelated to Crossbar itself. The problem seem to happen when a newer version of Python (other than the one that's shipped with Ubuntu 14.04) is installed. Apparently libssl doesn't like newer Python there.

One option could be to use Crossbar as snap on Ubuntu 14.04... without changing much on the host machine
```bash
$ apt install snapd -y
$ snap install crossbar
```

**Comment by oberstet** [comment]
fwiw, I also think the least trouble running on old ubuntu/debian is definitely snaps (or the EXE or snap for crossbarfx). or upgrade your OS - if that is an option

**Comment by carlosbbraga** [comment]
> @carlosbbraga can I ask how / why you ended up trying to get Crossbar running on 14.04, as opposed to something a little more up-to-date?

Sure. I have just landed a new job and as my first assignment they gave me a legacy application and a server with ubuntu 14.04 for me to run the application there. There was no specific reason, it was just what they had available at the time.
