### ISSUE TITLE
Missing docker release for v18.12.1

### ISSUE THREAD

**Issue by haizaar** [crossbario/crossbar#1464]
The latest version in [docker-hub](https://hub.docker.com/r/crossbario/crossbar/tags) is 18.11.2

**Comment by oberstet** [comment]
v19.1.1:

• https://cloud.docker.com/u/crossbario/repository/docker/crossbario/crossbar
• https://cloud.docker.com/u/crossbario/repository/docker/crossbario/crossbar-aarch64
• https://cloud.docker.com/u/crossbario/repository/docker/crossbario/crossbar-armhf
