### ISSUE TITLE
crossbar with pm2 

### ISSUE THREAD

**Issue by AmmarMohamed** [crossbario/crossbar#1476]
How to run the crossbar using pm2 ?

**Comment by AmmarMohamed** [comment]
How to run the crossbar using pm2 ?

**Comment by AmmarMohamed** [comment]
@oberstet  
Can you answer my question ? 
How to run the crossbar pm2 what is the config to run using pm2

**Comment by meejah** [comment]
Please use IRC, google-groups or gitter to ask questions. this is a bug tracker.
