### ISSUE TITLE
psutil: Could not find a version that satisfies the requirement psutil>=5.2.2 (from crossbar) (from versions: )

### ISSUE THREAD

**Issue by telatoa** [crossbario/crossbar#1479]
**Environment**

    Crossbar version: 19.1.2
    pip version: 19.0.1
    Python version: 2.7.15
    OS: Windows Server 2016

**Description**

    **Crossbar** is not installable

**Expected behavior**

    Correctly installs the **Crossbar** package

**How to Reproduce**

    1) Download the Crossbar version 19.1.2 into the "C:\Temp\Crossbar" folder
    2) pip install --no-warn-script-location --no-index --find-links "C:\Temp\Crossbar" crossbar

**Output**

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Looking in links: C:\ProgramData\Eona\Teveo\Crossbar
Collecting crossbar
Collecting txtorcon>=0.19.3 (from crossbar)
Collecting h2<4.0,>=3.0 (from crossbar)
Collecting cbor>=1.0.0 (from crossbar)
Collecting incremental>=17.5.0 (from crossbar)
Collecting u-msgpack-python>=2.4.1 (from crossbar)
Collecting psutil>=5.2.2 (from crossbar)
  Could not find a version that satisfies the requirement psutil>=5.2.2 (from crossbar) (from versions: )
No matching distribution found for psutil>=5.2.2 (from crossbar)

**Comment by om26er** [comment]
@telatoa We don't support Crossbar on Python 2 anymore, please try installing using Python 3.

**Comment by telatoa** [comment]
Hi,

We still use **2.7.15** Python version as it's the last release with an **MSI** file (used in an InstallShield project), isn't?

**Comment by om26er** [comment]
yeah, I just opened https://www.python.org/downloads/windows/ and it seems that's true.

**Comment by oberstet** [comment]
please use python 3 - as mentioned, python 2 is not supported

**Comment by telatoa** [comment]
Ok thank you for your reply.

I created an new request in Python project in order to have the Windows x86 & 64 MSI installers for latest Python Releases [#1382](https://github.com/python/pythondotorg/issues/1382)
