### ISSUE TITLE
cryptography: Could not find a version that satisfies the requirement cryptography>=1.9 (from crossbar) (from versions: ) 

### ISSUE THREAD

**Issue by telatoa** [crossbario/crossbar#1480]
**Environment**

Crossbar version: 19.1.2
pip version: 19.0.1
Python version: 3.7.2
OS: Windows Server 2016

**Description**

**Crossbar** is still not installable even with **Python = 3.7.2**

**Expected behavior**

Correctly installs the **Crossbar** package

**How to Reproduce**

1) Install **Python = 3.7.2**
2) Download the **Crossbar** version **19.1.2** into the "C:\Temp\Crossbar" folder:

`pip download -d "C:\Temp\Crossbar" crossbar==19.1.2`

3) Install **Crossbar**:

`pip install --no-warn-script-location --no-index --find-links "C:\Temp\Crossbar" crossbar`

**Output**

Looking in links: C:\ProgramData\Eona\Teveo\Crossbar
Collecting crossbar
Requirement already satisfied: setuptools>=36.0.1 in c:\program files\python37\lib\site-packages (from crossbar) (40.6.2)
Collecting treq>=17.3.1 (from crossbar)
Collecting bitstring>=3.1.5 (from crossbar)
Collecting pyopenssl>=17.1.0 (from crossbar)
Collecting netaddr>=0.7.19 (from crossbar)
Collecting cbor>=1.0.0 (from crossbar)
Collecting txaio>=18.8.1 (from crossbar)
Collecting click>=6.7 (from crossbar)
Collecting pytrie>=0.3 (from crossbar)
Collecting service-identity>=17.0.0 (from crossbar)
Collecting pygments>=2.2.0 (from crossbar)
Collecting incremental>=17.5.0 (from crossbar)
Collecting constantly>=15.1.0 (from crossbar)
Collecting watchdog>=0.8.3 (from crossbar)
Collecting autobahn>=18.12.1 (from crossbar)
Collecting mistune>=0.7.4 (from crossbar)
Collecting idna<2.6,>=2.5 (from crossbar)
Collecting u-msgpack-python>=2.4.1 (from crossbar)
Collecting attrs>=17.2.0 (from crossbar)
Collecting pyasn1-modules>=0.0.9 (from crossbar)
Collecting pyqrcode>=1.2.1 (from crossbar)
Collecting setproctitle>=1.1.10 (from crossbar)
Collecting txtorcon>=0.19.3 (from crossbar)
Collecting cryptography>=1.9 (from crossbar)
  Could not find a version that satisfies the requirement cryptography>=1.9 (from crossbar) (from versions: )
No matching distribution found for cryptography>=1.9 (from crossbar)

**Comment by oberstet** [comment]
>No matching distribution found for cryptography>=1.9 (from crossbar)

https://pypi.org/project/cryptography/#files

and: building crossbar from source on windows is not exactly easy - you can use our docker images or the EXE I posted on the other issue.
