### ISSUE TITLE
best way for callee parallelism - wampsharp / .net core

### ISSUE THREAD

**Issue by CapAdv** [crossbario/crossbar#1494]
Hi,

I am quite new to wampsharp .. am having some probs with the parallelism/concurrency aspect. I create a wampsharp router console app under win 10/C# (.net core 2.2), and run it. Works fine. Then I run another console app which acts as the callee (callee RPC functions are registered using c# reflection). Also fine. Finally I make a third console app which is the caller. It uses C# Parallel.Invoke to fire 3 calls to the callee on different threads. There's one 'long' call to function 'longrunner' which just loops for 5 seconds then returns the length of a string parameter, and a small call 'add2' which adds 2 ints and returns the result. In the parallel invoke, I sleep 2 instances of the call to Add2 for 20 and 10ms so that the 'LongRunner' starts first. On the callee, we see that all callee functions run on the same thread and run sequentially, which is also easy to see from the fact that the whole call group return no data until 'LongRunner' finishes, then all results come back very quickly. I understand that wampsharp's router can use multi-cores (correct?) but obviously that doesnt help if the callee serializes everything.

So , what is the right way to ensure that the short calls don't wait for the 'LongRunner' ? All my RPC functions will be CPU intensive (its computing some financials, so not many connections but heavy cpu processing per RPC call), so not sure about the benefits of the async approach or whether my use of the reflection approach causes the issue. I actually want the RPC calls to fire up different threads somehow so I can utilize the server multi-core architecture. I have read other posts here on similar issues but still dont exactly see the answer. Anyone got any pointers here ? (code below)

// ROUTER
class Program
    {
        static void Main(string[] args)
        {
            const string location = "ws://127.0.0.1:8080/";
            using (IWampHost host = new DefaultWampHost(location))
            {
                IWampHostedRealm realm = host.RealmContainer.GetRealmByName("realm1");

                // Host WAMP application components

                host.Open();

                Console.WriteLine("Server is running on " + location);
                Console.ReadLine();
            }
        }
    }

// CALLEE

namespace WampSharpCallee
{
    public interface IArgumentsService
    {
        [WampProcedure("com.arguments.ping")]
        void Ping();

        [WampProcedure("com.arguments.add2")]
        int Add2(int a, int b);
       
        [WampProcedure("com.arguments.longrunner")]
        string LongRunner(string big, int waitMs);          
    }

    public class ArgumentsService : IArgumentsService
    {
        public void Ping()
        {
        }

        public int Add2(int a, int b)
        {
            Console.WriteLine($"Thread:{Thread.CurrentThread.ManagedThreadId}");  
            return a + b;
        }

        public string LongRunner(string str, int waitMs)
        {
            Console.WriteLine($"Thread:{Thread.CurrentThread.ManagedThreadId}");  
            DateTime d = DateTime.Now;
            while (DateTime.Now < d.Add(TimeSpan.FromMilliseconds(waitMs)))
            {
                int x = 1;
            }

            return str.Length.ToString();
        }
    }

    internal class Program
    {
        public static void Main(string[] args)
        {
            const string location = "ws://127.0.0.1:8080/";

            DefaultWampChannelFactory channelFactory = new DefaultWampChannelFactory();

            IWampChannel channel = channelFactory.CreateJsonChannel(location, "realm1");

            Task openTask = channel.Open();

            // await openTask;
            openTask.Wait();

            IArgumentsService instance = new ArgumentsService();

            IWampRealmProxy realm = channel.RealmProxy;

            Task<IAsyncDisposable> registrationTask = realm.Services.RegisterCallee(instance);
            // await registrationTask;
            registrationTask.Wait();

            Console.ReadLine();
        }
    }
}

// CALLER

namespace MyNamespace
{
    public interface IArgumentsService
    {
        [WampProcedure("com.arguments.ping")]
        void Ping();

        [WampProcedure("com.arguments.add2")]
        int Add2(int a, int b);
        
        [WampProcedure("com.arguments.longrunner")]
        string LongRunner(string big, int waitMs);       
        
    }

    internal class Program
    {
        public static void Main(string[] args)
        {
            DefaultWampChannelFactory factory =
                new DefaultWampChannelFactory();

            const string serverAddress = "ws://127.0.0.1:8080/ws";

            IWampChannel channel =
                factory.CreateJsonChannel(serverAddress, "realm1");

            channel.Open().Wait(5000);

            IArgumentsService proxy =
                channel.RealmProxy.Services.GetCalleeProxy<IArgumentsService>();

            Parallel.Invoke(           
                ()=>
                {   Console.WriteLine($"Thread:{System.Threading.Thread.CurrentThread.ManagedThreadId}");         
                    Console.WriteLine(proxy.LongRunner(@"sdfsghsf fs f s fs df sf",5000));
                },
                ()=>
                    
                {   Console.WriteLine($"Thread:{System.Threading.Thread.CurrentThread.ManagedThreadId}");  
                    Thread.Sleep(20);
                    Console.WriteLine(proxy.Add2(3,2).ToString());
                },
                () =>
                   
                {   Console.WriteLine($"Thread:{System.Threading.Thread.CurrentThread.ManagedThreadId}");  
                    Thread.Sleep(10);
                    Console.WriteLine(proxy.Add2(3,12).ToString());
                }
            
            );
        }
    }
}

**Comment by oberstet** [comment]
Here are 2 ways to realize a parallelized WAMP procedure:

a) find out how to receive a WAMP call in wampsharp (a callee), but run the implementation on a background thread - without blocking the main thread that is waiting in an async fashion. this is sth to ask the wampsharp guys .. @darkl ;)
b) or, keep your WAMP client single-threaded and simply start multiple instances of the client on a multi-core machine. this works using _shared registrations_: https://github.com/crossbario/crossbar-examples/tree/master/scaling-microservices

**Comment by CapAdv** [comment]
Thanks for the response but it doesnt help at all. This is because by posting here I was obviosuly looking for an answer/help to point (a) and thought this is the place to 'ask the wampsharp' guys (isnt it ?). I am also aware of option b and do it already, but it's not the architecture I was hoping for - what if you want many rpc's to run in parallel ? .. running scores of callee processes doesn't seem very maintainable or efficient. 

Can it be that the wampsharp implementation forces us into either fully single threaded, or single-threaded/multiple-process modes , with no single-process+multi-threaded callee possibility ?

**Comment by oberstet** [comment]
> and thought this is the place to 'ask the wampsharp' guys (isnt it ?)

no, I'm afraid the right place to file issues and ask questions is here: https://github.com/Code-Sharp/WampSharp

> what if you want many rpc's to run in parallel

yes, I would agree: in this case spawning threads rather than processes can have avantages.

that being said, if the main goal would be to utilize all CPU cores, then processes are just fine.

also processes have advantages like higher isolation compared to threads etc

anyways: I get it, you want thread level parallelism. I simply don't know how to do that in C# using wampsharp, sorry. @darkl is original developer of wampsharp - so he will know;)
