### ISSUE TITLE
XSS: http://localhost:8080/?redirect=//x:1%0D%0AContent-Type:text/html%0D%0AX-XSS-Protection%3a0%0D%0A%0D%0A%3Cscript%3Ealert(document.domain)%3C/script%3E

### ISSUE THREAD

**Issue by nadavvin** [crossbario/crossbar#1496]
you can put any content to be in response include scripts:

http://localhost:8080/?redirect=//x:1%0D%0AContent-Type:text/html%0D%0AX-XSS-Protection%3a0%0D%0A%0D%0A%3Cscript%3Ealert(document.domain)%3C/script%3E

**Comment by om26er** [comment]
This issue doesn't contain any useful information, could you please add some more details ?

**Comment by nadavvin** [comment]
@om26er I update the ticket with more details so please reopen the ticket

**Comment by oberstet** [comment]
invalid: just tested (the URL I used was `http://localhost:8080/ws?redirect=//x:1%0D%0AContent-Type:text/html%0D%0AX-XSS-Protection%3a0%0D%0A%0D%0A%3Cscript%3Ealert(document.domain)%3C/script%3E`):

![bildschirmfoto von 2019-02-13 14-50-37](https://user-images.githubusercontent.com/233340/52716304-c3edf180-2f9e-11e9-99bc-5745ccf8ca21.png)

**Comment by nadavvin** [comment]
Try this example config:
https://gist.github.com/nadavvin/ca604ed34da769c2fadde9537129b369

Notice that port is 9091 and I don't have anything in:
../web/
../../../_shared-web-resources
../client.php

So just create ne folder and put the config in it.

**Comment by nadavvin** [comment]
https://imgur.com/a/FuYnFgK

Also opeating system is windows if it related

**Comment by nadavvin** [comment]
It reproduce to me only in firefox! in chrome it redirect the page to http://x:1/

**Comment by oberstet** [comment]
try this, which disables info page rendering and redirection on a websocket endpoint:

```
"ws": {
    "type": "websocket",
    "options": {
        "enable_webstatus": false
    }
}
```

**Comment by oberstet** [comment]
Disabling web status is something which we probably should recommend for production in the docs, also for privacy reasons) .. there is also an explicit **redirect** web service that can be configured on Web paths, which we should also investigate in this regard.

**Comment by oberstet** [comment]
rgd the webstatus feature of a autobahn websocket listening endpoint, the respective code is here: https://github.com/crossbario/autobahn-python/blob/4b4227aa9365f971d7a8f566f25f81f749fdc8a1/autobahn/websocket/protocol.py#L2594

**Comment by nadavvin** [comment]
@oberstet Thanks, it solved the problem
