### ISSUE TITLE
HttpOnly for Cookie Authentication

### ISSUE THREAD

**Issue by manuelmager** [crossbario/crossbar#1511]
# Goal
Mitigate XSS attacks by preventing client javascript from accessing the Authentication Cookie content.

# Why is this important for you
We want to use the cookie to remember that a user is already authorized so as to allow the user to not provide credentials with every connection. Storing this information in a non-HttpOnly cookie is a security risk when it comes to cross site scripting.

# Proposed Solutions
## Recommended: always HttpOnly
Add `;HttpOnly` when creating a cookie in the `cookiestore.py`. I know of no use case that requires having the cookie accessible for client-side javascript, so from my point of view it seems to be a good idea to always set Cookies to be HttpOnly.

Replace
https://github.com/crossbario/crossbar/blob/1e18ceef1b444f60bca118cd5e57eb7ffbd8f2bf/crossbar/router/cookiestore.py#L137
with
`return cbtid, '%s=%s;max-age=%d;HttpOnly' % (self._cookie_id_field, cbtid, cbtData['max_age'])`

## Alternative: configurable HttpOnly
Add an optional configuration parameter `http_only` to allow defining whether the cookie should be inaccessible to client-side javascript. In case there is a use case for not using HttpOnly.

**Comment by oberstet** [comment]
this needs to be added here: https://github.com/crossbario/crossbar/blob/master/crossbar/router/protocol.py#L254

it would be trivial to add 2 lines to set `HttpOnly`, `SameSite` and such - however, we might want to have knobs to control setting of these headers in the node config - so it will be "a couple of lines" instead of just 2.

**Comment by dshymanskyi-vivasg** [comment]
Hi i created [pull request](https://github.com/crossbario/crossbar/pull/1753), please check it out as soon as you have time for it.

**Comment by yankos** [comment]
Does this issue resolved?

**Comment by oberstet** [comment]
yeah, it's solved!
