### ISSUE TITLE
[snap]: missing host dependencies in v19.3.1

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1521]
Latest crossbar installs `autobahn[all]` as well as `vmprof`, which need the following on the host:

```
      # needed for compression
      - libbz2-dev
      - libsnappy-dev

      # needed for vmprof
      - libunwind-dev
```

The snap build currently fails because it doesn't have above yet.

```
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -I/usr/include/python3.6m -fPIC -I/build/crossbar/parts/crossbar/install/usr/include/python3.6m -c snappy/snappymodule.cc -o build/temp.linux-x86_64-3.6/snappy/snappymodule.o
  snappy/snappymodule.cc:31:10: fatal error: snappy-c.h: No such file or directory
   #include <snappy-c.h>
```

**Comment by om26er** [comment]
fyi, `vmprof` isn't supported on `ppc64le` and `aarch64`, so the build there fails and `libunwind` isn't available on `s390x` (Well, we should really disable builds for s390x, as I assume not many are going to need that).

I think among the arches above, aarch64 is the only arch we *actually* care about.

**Comment by oberstet** [comment]
oh, I see!

yeah, for `ppc64le` and `s390x`: deactivate those builds for now is good.

for `aarch64`: is `libunwind` currently only unavailable as a snap, or as an apt package altogether?

**Comment by om26er** [comment]
> for `aarch64`: is `libunwind` currently only unavailable as a snap, or as an apt package altogether?

`libunwind` doesn't seem to be available for `aarch64` as deb packages.

**Comment by om26er** [comment]
Sorry for the confusion: libunwind is indeed available for aarch64 in Ubuntu. Its vmprof that isn't

**Comment by oberstet** [comment]
thanks for clarification! I guess then we would like to add vmprof for aarch64 somehow .. some near future. but for now, yeah, +1 on the PR ^ just merged
