### ISSUE TITLE
crossbar http - how to know json format for rpc

### ISSUE THREAD

**Issue by CapAdv** [crossbario/crossbar#1528]
When making an RPC over crossbar via HTTP, how can you know how to format the json correctly so that it can be parsed correctly into the parameters for the callee ? I have several callees registered by python and c# services. Now I want to call one of these callees over http, but it has parameters which are non-trivial (dictionaries of lists in a python callee for example). I can probably guess the json format but I wondered if there's a way to log existing requests that pass through crossbar in their json format, so I can see what format is used ? Otherwise, knowing how to see the json at the callee end in python and/or c# might help also.

**Comment by oberstet** [comment]
as an app developer, you use WAMP on 2 ends (eg caller and callee), in 2 languages, using 2 WAMP client libraries. you don't need to know the "JSON format", as the WAMP client libraries take care of that. if you want to write your own WAMP client library (or router), you would need to dive into the WAMP spec that describes the wire protocol
