### ISSUE TITLE
Crossbar fails to start on MacOS

### ISSUE THREAD

**Issue by rrueth** [crossbario/crossbar#1543]
I'm attempting to upgrade an old version of Crossbar (v17.10.1) to v19.3.5 on MacOS v10.13.3.  When I attempt to start crossbar v19.3.5 on MacOS, I get the following error:
```
2019-03-25T12:28:33-0700 [Controller  53978] Could not start node: Traceback (most recent call last):
  File "/Users/ryan/Projects/server/env_crossbar/lib/python3.7/site-packages/twisted/internet/base.py", line 447, in _continueFiring
    callable(*args, **kwargs)
  File "/Users/ryan/Projects/server/env_crossbar/lib/python3.7/site-packages/crossbar/node/main.py", line 878, in start_crossbar
    d = node.start()
  File "/Users/ryan/Projects/server/env_crossbar/lib/python3.7/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/Users/ryan/Projects/server/env_crossbar/lib/python3.7/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/Users/ryan/Projects/server/env_crossbar/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/Users/ryan/Projects/server/env_crossbar/lib/python3.7/site-packages/crossbar/node/node.py", line 362, in start
    self._router_session_factory.add(self._controller, authrole=u'trusted')
  File "/Users/ryan/Projects/server/env_crossbar/lib/python3.7/site-packages/crossbar/router/session.py", line 879, in add
    self._app_sessions[session] = RouterApplicationSession(session, self._routerFactory, authid, authrole)
  File "/Users/ryan/Projects/server/env_crossbar/lib/python3.7/site-packages/crossbar/router/session.py", line 110, in __init__
    self._session.onConnect()
  File "/Users/ryan/Projects/server/env_crossbar/lib/python3.7/site-packages/crossbar/node/controller.py", line 118, in onConnect
    NativeProcess.onConnect(self, False)
  File "/Users/ryan/Projects/server/env_crossbar/lib/python3.7/site-packages/crossbar/common/process.py", line 180, in onConnect
    self._pmonitor = ProcessMonitor(self.WORKER_TYPE, {})
  File "/Users/ryan/Projects/server/env_crossbar/lib/python3.7/site-packages/crossbar/common/monitor.py", line 156, in __init__
    self._p.io_counters()
builtins.AttributeError: 'Process' object has no attribute 'io_counters'
```

Our current configuration is pretty basic:

```
{
    "version": 2,
    "controller": {},
    "workers": [
        {
            "type": "router",
            "realms": [
                {
                    "name": "realm1",
                    "roles": [
                        {
                            "name": "anonymous",
                            "permissions": [
                                {
                                    "uri": "",
                                    "match": "prefix",
                                    "allow": {
                                        "call": true,
                                        "register": true,
                                        "publish": true,
                                        "subscribe": true
                                    },
                                    "disclose": {
                                        "caller": false,
                                        "publisher": false
                                    },
                                    "cache": true
                                }
                            ]
                        }
                    ]
                }
            ],
            "transports": [
                {
                    "type": "web",
                    "endpoint": {
                        "type": "tcp",
                        "port": 8090
                    },
                    "paths": {
                        "/": {
                            "type": "static",
                            "directory": ".."
                        },
                        "ws": {
                            "type": "websocket"
                        }
                    }
                }
            ]
        }
    ]
}
```

The [`psutil` documentation](https://psutil.readthedocs.io/en/release-3.4.2/#psutil.Process.io_counters) says that `io_counters()` is not supported on MacOS :
> Return process I/O statistics as a namedtuple including the number of read and write operations performed by the process and the amount of bytes read and written. For Linux refer to /proc filesysem documentation. On BSD there’s apparently no way to retrieve bytes counters, hence -1 is returned for read_bytes and write_bytes fields. OSX is not supported.

- Is there a way somewhere higher up the stack that avoids going down this flow on Mac?
- Or possibly a configuration option?  https://github.com/crossbario/crossbar/issues/1333 was a similar issue where a specific configuration to the `cpu_affinity` was suggested.

**Comment by hnle** [comment]
I got the exact same problem on my macOS High Sierra version 10.13.6 with basic configuration like the above.

**Comment by oberstet** [comment]
we need to deactivate that line of code on OSX

@rrueth nope, we need to fix that in the code (there is no config option that would make it work right now)

sorry, none of our developers is on OSX. we have added CI for OSX already (see https://travis-ci.org/crossbario/crossbar) - but it's not yet armed to break a build

**Comment by rrueth** [comment]
Thanks, @oberstet.  I made an attempt at a fix: #1550.  I'm happy to made edits if there is a better place to make the change.

**Comment by oberstet** [comment]
fixed via https://github.com/crossbario/crossbar/pull/1561 - @rrueth pls let me know if it works as expected (the CI does run osx already, but currently still has some other unrelated issues)

**Comment by rrueth** [comment]
Sorry for the delay on fixing up the PR.  I just pulled master, built, and tested it locally.  Everything look good to me.  Thanks for the fix!

Do you know when the next Crossbar release will be?

**Comment by oberstet** [comment]
Thanks for testing! Good to hear it works for you now. Next release: maybe april, latest in may .. we don't have a pre-planned schedule, but follow / aim for a "master is always good, can be run in production" approach and release every couple of weeks when some new stuff has accumulated.

**Comment by rrueth** [comment]
Thanks, @oberstet!  We're looking forward to the next release so that we can proceed with upgrading to the latest Crossbar (now that our local Mac development will work =).
