### ISSUE TITLE
Ignoring "cache" option from dynamic authorization

### ISSUE THREAD

**Issue by gendalf** [crossbario/crossbar#1549]
**Any news or plans to implement ?**
Crossbar is ignoring "cache" option from dynamic authorization.
Authorization function called before every call/publish.
It's makes have much more traffic and double load on server. 
authorization config:
```
roles: [...{
     "name": "somerole",
     "authorizer": "com.custom.authorizer"
}]
```
authorization function answer :
```
{ "allow": true, "cache": true, "disclose": true }
```
Version:
```
Crossbar.io        : 19.3.5
   txaio            : 18.8.1
   Autobahn         : 19.3.3
     UTF8 Validator : wsaccel-0.6.2
     XOR Masker     : wsaccel-0.6.2
     JSON Codec     : stdlib
     MsgPack Codec  : msgpack-0.6.1
     CBOR Codec     : cbor-1.0.0
     UBJSON Codec   : ubjson-0.12.0
     FlatBuffers    : flatbuffers-1.10
   Twisted          : 18.9.0-EPollReactor
   LMDB             : 0.94/lmdb-0.9.22
   Python           : 3.7.2/CPython
```

On hundreds published events per seconds, I get hundreds authorizations for the same originator session and same destination.

Each event worse time while additional call to authorization will completed. It's not problem on small load, but is very felting when you have many messages per second.

**Comment by oberstet** [comment]
dup of https://github.com/crossbario/crossbar/issues/212
