### ISSUE TITLE
Calls are registered with session ID null when session left before authenticator returned

### ISSUE THREAD

**Issue by manuelmager** [crossbario/crossbar#1576]
When a client connects to the router using a dynamic async router and disconnects before the authenticator returned, we see the appended error in the crossbar log. Some of the calls to the authenticator receive sessionId `null`. Removing the registered calls using `wamp.registration.remove_callee` fails. This prevents the client from registering its calls.

```
Unhandled error in Deferred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/autobahn/wamp/protocol.py", line 888, in onMessage
    txaio.resolve(on_reply, msg.args[0])
  File "/usr/local/lib/python3.6/dist-packages/txaio/tx.py", line 468, in resolve
    future.callback(result)
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 460, in callback
    self._startRunCallbacks(result)
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/crossbar/router/dealer.py", line 441, in on_authorize_success
    self._session_to_registrations[session].add(registration)
builtins.KeyError: <crossbar.router.session.RouterSession object at 0x7f653abfaef0>
```

`crossbar version`:
```
 Crossbar.io        : 19.3.5
   txaio            : 18.8.1
   Autobahn         : 19.3.3
     UTF8 Validator : autobahn
     XOR Masker     : autobahn
     JSON Codec     : stdlib
     MsgPack Codec  : msgpack-0.6.1
     CBOR Codec     : cbor-1.0.0
     UBJSON Codec   : ubjson-0.13.0
     FlatBuffers    : flatbuffers-1.10
   Twisted          : 19.2.0-EPollReactor
   LMDB             : 0.94/lmdb-0.9.22
   Python           : 3.6.7/CPython
 Frozen executable  : no
 Operating system   : Linux-4.15.0-47-generic-x86_64-with-Ubuntu-18.04-bionic
 Host machine       : x86_64
```

We are working on a script to reproduce this error more easily. As the only way to recover is to drop **all** clients and restart crossbar, the issue is quite pressing for us.

**Comment by thePunIssuer** [comment]
Checking if the session still has a `_session_id` when authenticator returns seems to solve this issue. We added 
```
           # not register call if session disconnected in the meantime.
            if session._session_id == None:
                self.log.info("Session gone, not registering '{uri}'.", uri=register.procedure)
                return
```
to the checks in `on_authorize_success`.

**Comment by thePunIssuer** [comment]
(almost) minimal example:
[config.json.txt](https://github.com/crossbario/crossbar/files/3103477/config.json.txt)
[index.js.txt](https://github.com/crossbario/crossbar/files/3103480/index.js.txt)

**Comment by meejah** [comment]
Just to be clear, I think you mean "authorize" in several places above where you say "authenticate", right? (Authentication is "can this connection succeed" and authorization is "can this one call / subscribe etc be allowed")

**Comment by meejah** [comment]
(But also, the authentication/authorization confusion was good because I found a couple edge-cases in authentication too :)
