### ISSUE TITLE
Document use of "extra" with router-embedded components

### ISSUE THREAD

**Issue by someApprentice** [crossbario/crossbar#1579]
According to the [example](https://github.com/crossbario/crossbar-examples/blob/master/authorization/dynamic/container/app.py#L7) ApplicationSession [component](https://github.com/crossbario/crossbar-examples/blob/master/authorization/dynamic/container/.crossbar/config.json#L83-L96) calls the `join(...)` function and passes a connection arguments to it.
On the other hand, there is an [example](https://github.com/crossbario/crossbar-examples/blob/master/authentication/cryptosign/dynamic/client.py#L78-L81) in which `extra` data is passed to this function as `authextra`.
Would like to combine these two approaches, but in practice, in a component, this function does not pass arguments to the actual session.

Steps to reproduce:

config.json
```
"components": [
    {
        "type": "class",
        "classname": "app.AppSession",
        "realm": "realm1",
        "role": "anonymous",
        "extra": {
            "KEY": "VALUE"
        }
    }
]
```

app.py
```
from autobahn.twisted.wamp import ApplicationSession

class AppSession(ApplicationSession):

    def onConnect(self):
        print("APP CONNECTED")

        print("CONFIG: ")
        print(self.config)

        self.join(self.config.realm, ['anonymous'], 'anonymous', authextra=self.config.extra)

    def onJoin(self, details):
        print("APP JOINED")
        print("DETAILS: ")
        print(details)
```

crossbar start
```
2019-05-06T23:10:11+0700 [Router       5044] APP CONNECTED
2019-05-06T23:10:11+0700 [Router       5044] CONFIG:
2019-05-06T23:10:11+0700 [Router       5044] ComponentConfig(realm=<realm1>, extra={'KEY': 'VALUE', 'cbdir': '...\\crossbar_component_join\\.crossbar'}, keyring=None, controller=None, shared=None, runner=None)
2019-05-06T23:10:11+0700 [Router       5044] started component: app.AppSession id=7844604167355148
2019-05-06T23:10:11+0700 [Router       5044] APP JOINED
2019-05-06T23:10:11+0700 [Router       5044] DETAILS:
2019-05-06T23:10:11+0700 [Router       5044] SessionDetails(realm=<realm1>, session=7844604167355148, authid=<None>, authrole=<anonymous>, authmethod=None, authprovider=None, authextra=None, resumed=None, resumable=None, resume_token=None)
```

As you can see in the SessionDetails, the `authextra` property is empty.

Changing arguments such as `authmethods`, `authrole` and `authextra` do not affect anything, but if you change the `realm`, it changes.

If you start the `app.py` by yourself from the console, [as is done in the example above](https://github.com/crossbario/crossbar-examples/blob/master/authentication/cryptosign/dynamic/client.py#L146-L147), everything will work as it should.

Version
```
    :::::::::::::::::
          :::::          _____                      __
    :::::   :   :::::   / ___/____ ___   ___  ___  / /  ___ _ ____
    :::::::   :::::::  / /__ / __// _ \ (_-< (_-< / _ \/ _ `// __/
    :::::   :   :::::  \___//_/   \___//___//___//_.__/\_,_//_/
          :::::
    :::::::::::::::::   Crossbar v19.3.5

    Copyright (c) 2013-2019 Crossbar.io Technologies GmbH, licensed under AGPL 3.0.

 Crossbar.io        : 19.3.5
   txaio            : 18.8.1
   Autobahn         : 19.3.3
     UTF8 Validator : autobahn
     XOR Masker     : autobahn
     JSON Codec     : stdlib
     MsgPack Codec  : msgpack-0.6.1
     CBOR Codec     : cbor-1.0.0
     UBJSON Codec   : ubjson-0.13.0
     FlatBuffers    : flatbuffers-1.11
   Twisted          : 19.2.0-IOCPReactor
   LMDB             : 0.94/lmdb-0.9.22
   Python           : 3.6.8/CPython
 Frozen executable  : no
 Operating system   : Windows-10-10.0.17763-SP0
 Host machine       : AMD64
 Release key        : RWTugc8VlQqH/Fr5WgYYPCRo6CqsJuXOlLN0ZcEQpM8JXbj3g8KN6Aww
```

**Comment by meejah** [comment]
So, the `extra` thing in the config isn't an "authentication extra" because these kinds of components don't authenticate -- they're running "in" the router, and are trusted because you put them in the config. That is, I don't believe you need the `onConnect` override at all?

The `extra` dict is available via `self.config.extra` in your `ApplicationSession` subclass, as your code above makes clear. Perhaps the documentation could make all this more clear?

The documentation should also make clear that running a thing "in-router" like this can be a little more "dangerous" than other ways: if your code crashes, you could in principal also crash the router process. It also must be written in Twisted.

Also, are you saying in the last linked example that "extra" ends up being passed as "authextra"? (I don't see where in the code that might happen).
