### ISSUE TITLE
Allow authid in anonymous auth config items

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1596]
We currently only allow to configure the `authrole`, but not the `authid` in static anonymous authenticators. Eg see:

* https://github.com/crossbario/crossbar/blob/1359c5bd430fb0a15a5364cacf7a5a86dd63a34d/crossbar/common/checkconfig.py#L557
* https://github.com/crossbario/crossbar/blob/1359c5bd430fb0a15a5364cacf7a5a86dd63a34d/crossbar/router/auth/anonymous.py#L59

**Comment by meejah** [comment]
Doesn't that second line imply that it'll accept a `authextra={"authid": "foo"}` ..? or am I misreading that code?

**Comment by oberstet** [comment]
Yes, that's right

revisiting this now, I'm not sure if that is desirable in all cases. here are some policies:

* "let the client choose freely"
* "let the client choose from given list"
* "do not let the client choose, but assign randomly"
* "do not let the client choose, but assign fixed"
* ...

**Comment by meejah** [comment]
How terrified I am about those different options also greatly "depends on the transport" -- that is, "let the client choose freely" sounds bad for TCP, WebSocket but "probably fine" for unix-socket or pipes, etc :/

But also I guess the config just provides the gun; you provide the foot and the trigger-finger? ;)

**Comment by oberstet** [comment]
> But also I guess the config just provides the gun; you provide the foot and the trigger-finger? ;)

hahahah =) yeah, exactly

**Comment by oddjobz** [comment]
Maybe this leaves scope for a small Crossbar security utility that does a tiny penetration test / assessment every time Crossbar runs and advises a user of any potential security weaknesses they may have configured? .. and as Mike says, limiting the scope of this option(s) to UDS/pipe might be good, I'm not sure I can think of a use-case for this sort of thing on a TCP connection (?)

**Comment by meejah** [comment]
A user might decide it's fine to use "private IP space" because it's "behind a firewall" or something...? Or maybe you're using containers but they're talking via TCP instead of Unix.

I mean, maybe there's even some reason/usecase to allow it from all connections (e.g. maybe "authid" isn't special in your system and it's just for human-names or something? but why) .. are there any features that a "assessment" thing would do that couldn't be done by just parsing the config (for a sufficiently-advanced value of "parsing")? If we believe that some of these options shouldn't be allowed via TCP, then we should just deal with that during "checkconfig" time (IMO).

**Comment by oddjobz** [comment]
> A user might decide it's fine to use "private IP space" because it's "behind a firewall" or something...?

yeah .. the Darwin awards spring to mind ... ;)

> we should just deal with that during "checkconfig" time (IMO).

Absolutely. But then when you build a new building, you build according to specifications and do everything right and by the book .. but you still need to get a building standards certificate and a health and safety certificate before you can put people in it. i.e. if you do it as you go along, it's probably fine, but a fresh pair of eyes viewing from a different angle is often useful to catch bugs etc. Let's say for example chkconfig passes the config but a bug in the code writes the wrong permissions on the socket .. no way to pick that up without actually looking at the deployed system, and a 666 on a superuser socket for example would leave the entire system open to local abuse. (incidentally looking at sockets on my box here, 666 does "seem" to be the default)

**Comment by meejah** [comment]
The default permissions on newly created files will follow your `umask` I think?

**Comment by oddjobz** [comment]
Mmm, I'm not sure that's the whole story ....
```
.crossbar$ ls -la
total 22432
drwxrwxr-x 13 gareth gareth     4096 Jun 12 22:42 .
drwxrwxr-x 12 gareth gareth     4096 Jun  5 18:01 ..
-rw-rw-r--  1 gareth gareth 11404853 Jun  6 11:57 .crossbarfx-ui.zip
drwxr-xr-x  2 gareth gareth     4096 Apr  5 16:47 .db-controller
-rw-------  1 gareth gareth      338 Feb 19 20:16 key.priv
-rw-r--r--  1 gareth gareth      233 Feb 19 20:16 key.pub
-rw-rw-r--  1 gareth gareth      493 Jun 12 22:33 node.pid
srw-rw-rw-  1 gareth gareth        0 Jun 12 22:33 sock1
srw-rw-rw-  1 gareth gareth        0 Jun 12 22:33 sock2

```

**Comment by oberstet** [comment]
So this is coming via:

* https://github.com/crossbario/crossbar/pull/1598/files#diff-3faa60155112823ccd29336678a15916

> I also removed the ability to plainly define the authid/authrole from the client on anonymous connections completely (for now) - which removes the question of the various options also

**Comment by oberstet** [comment]
CB 19.6.2 ships with this
