### ISSUE TITLE
Does TLS websocket transport require client authentication?

### ISSUE THREAD

**Issue by lynchs61** [crossbario/crossbar#1617]
I have a websocket transport set up with TLS.

```
{
  "type": "websocket",
  "endpoint": {
    "type": "tcp",
    "port": 8743,
    "tls": {
      "key": "wamp.key.pem",
      "certificate": "wamp.cert.pem",
      "ca_certificates": [
        "root-ca.cert.pem",
        "intermediate-ca.cert.pem"
      ]
    }
  }
}
```

But when I try to connect (using autobahn.js) the connection is said to be 'unreachable' and the router logs show:

```
[Router         16] SSL error: peer did not return a certificate (in tls_process_client_certificate)
```

This seems to say that the TLS connection requires client certificate authentication. Is that true? I'd like to just have anonymous access with the encrypted TLS connection.

**Comment by meejah** [comment]
This is a bug-tracker; please use IRC or our forums to ask questions: https://forum.crossbar.io/

(It's more likely you client doesn't know about those roots).

**Comment by vaibhav-rbs** [comment]
tried to join IRC channel

07:47 <freenode> CTCP-query VERSION from freenode-connect
07:47 <freenode> Error(477): #autobahn Cannot join channel (+r) - you need to be identified with services - see https://freenode.net/kb/answer/registration
07:48 <freenode> Error(404): #autobahn Cannot send to nick/channel

I tried to register https://freenode.net/kb/answer/registration but the name was not resolving ? 

maybe I am missing something ?
