### ISSUE TITLE
Remove redundant dependencies

### ISSUE THREAD

**Issue by om26er** [crossbario/crossbar#1651]
Crossbar has a lz4 depends, but the code does not use it. Shall we remove that ?

**Comment by om26er** [comment]
autobahn-python and crossbarfx also have that dependency but I dont see a code that actually uses it. @oberstet is that an implicit dependency for some other package ?

**Comment by om26er** [comment]
Crossbar also depends on [requests](https://github.com/crossbario/crossbar/blob/14e20560a2fb4ca25360ecae6c6efa37e2d2cbe0/requirements.txt#L391) but the code does not seem to use it in anyway ==> CrossbarFX does use it however.

**Comment by om26er** [comment]
We need to get rid of the direct dependency on `six` as well, crossbar is python3.5+.

**Comment by oberstet** [comment]
> Crossbar has a lz4 depends, but the code does not use it. Shall we remove that ?

no, it is currently needed by `autobahn[compress]` https://github.com/crossbario/autobahn-python/blob/897c349952ead7f69f6e720183a2b4c17987a64b/setup.py#L87

> Crossbar also depends on requests 

it must be an indirect dep resulting from https://github.com/crossbario/crossbar/blob/master/requirements-min.txt, and materializing in https://github.com/crossbario/crossbar/blob/master/requirements-pinned.txt

> We need to get rid of the direct dependency on six as well (in code), crossbar is python3.5+.

no, too much work and no gain
