### ISSUE TITLE
"ImportError: cannot import name 'MsgPackObjectSerializer'" when running `crossbar init`

### ISSUE THREAD

**Issue by zrneely** [crossbario/crossbar#1654]
This is an unusual error that's been happening in CI only. Luckily, since it's on CI, it's fully reproducible and the environment is well documented.

If you'd prefer to just look at the output of the whole job, one example of a failing run is here:
https://travis-ci.org/zrneely/wamp-proto/jobs/608272333

I'm explicitly using crossbar 19.10.1, which is installed via the following section in my CI configuration script:

    export PATH=$HOME/.local/bin:$PATH
    pip3 install wheel
    pip3 install --user crossbar==19.10.1 autobahn==19.10.1

`python3 --version` produces "Python 3.5.2" and `pip3 --version` produces "pip 8.1.1 from /usr/lib/python3/dist-packages (python 3.5)". The test machine is configured to run Ubuntu Xenial.

The test runs `crossbar init --appdir <temp path>`, which consistently fails with the following output and exit code 1:

```
Traceback (most recent call last):
  File "/home/travis/.local/bin/crossbar", line 11, in <module>
    sys.exit(run())
  File "/home/travis/.local/lib/python3.5/site-packages/crossbar/__init__.py", line 177, in run
    _personalities = personalities()
  File "/home/travis/.local/lib/python3.5/site-packages/crossbar/__init__.py", line 215, in personalities
    from crossbar import personality as standalone
  File "/home/travis/.local/lib/python3.5/site-packages/crossbar/personality.py", line 44, in <module>
    from crossbar.worker import transport
  File "/home/travis/.local/lib/python3.5/site-packages/crossbar/worker/transport.py", line 48, in <module>
    from crossbar.bridge.mqtt.wamp import WampMQTTServerFactory
  File "/home/travis/.local/lib/python3.5/site-packages/crossbar/bridge/mqtt/wamp.py", line 54, in <module>
    from autobahn.wamp.serializer import JsonObjectSerializer, MsgPackObjectSerializer, CBORObjectSerializer, UBJSONObjectSerializer
ImportError: cannot import name 'MsgPackObjectSerializer'
```

**Comment by oberstet** [comment]
our CI is green: https://travis-ci.org/crossbario/crossbar

**Comment by zrneely** [comment]
@oberstet - Unfortunately that's not too helpful in this case; I'm trying to use crossbar as part of CI for one of my own projects, not replicate your CI configuration.

To me this seems to be a fairly serious and novel issue - basically, `pip install crossbar && crossbar init` is failing, which is a scenario most people would expect to work out of the box.

**Comment by om26er** [comment]
@zrneely I was able to reproduce the issue you are facing. please install the package `msgpack` with pip and things should work fine for you. In the meantime I'll to see why that issue is happening.

Note: the issue was reproduced on Ubuntu 16.04 in a LXD container.

**Comment by om26er** [comment]
@zrneely OK, the problem is with your CI. You are trying to force a specific version of autobahn on crossbar, I see the line
```
pip3 install --user crossbar==19.10.1 autobahn==19.10.1
```
Please change that to
```
pip3 install --user crossbar==19.10.1
```
Also you are missing some build dependencies as well, please make sure to install these packages
```
build-essential gcc libffi-dev libssl-dev make libbz2-dev libsnappy-dev libunwind-dev
```

**Comment by zrneely** [comment]
@om26er Thanks for your help! Adding those dependencies and adding `pip3 install msgpack` to the before_script fixed my issues.

By the way, I found the list of packages to install in crossbar documentation - that's definitely on me for missing them.
