### ISSUE TITLE
payload limit

### ISSUE THREAD

**Issue by CapAdv** [crossbario/crossbar#1664]
I am trying to understand where the WAMP/websocket payload limit is being applied in a crossbar/wamp/rpc setup, and find out if it is now user configurable. The callee registered using autobahn 19.11.1 / Py 3.7 on Win,  as follows 

    runner = ApplicationRunner(url="ws://127.0.0.1:8080/", realm='realm1'
                                ,max_retries=-1, initial_retry_delay=10, max_retry_delay=10
                                ,retry_delay_growth=0
                               )

.. also tried these which had no effect :

                               #  ,extra={'maxOutgoingFramePayloadSize': 0
                               #      , 'maxOutgoingMessagePayloadSize': 0
                               #      , 'maxFramePayloadSize' : 0
                               #      , 'maxMessagePayloadSize' : 0
                               #      }
                               # )

.. brings error:

"tried to send WebSocket message with size 3341943 exceeding payload limit of 1048576 octets"

... so how to increase the payload limit a little ? is it configurable at router level on crossbar, or at callee level, (if so how) ... or is this an outstanding issue ? 

I have read some related discussions but didn't find the answer.

**Comment by oberstet** [comment]
You can configure WebSocket message and frame payload limits like this:

* https://crossbar.io/docs/WebSocket-Options/#available-options

Here is an example:

* https://github.com/crossbario/crossbar-examples/blob/master/stats/.crossbar/config.json#L121

**Comment by CapAdv** [comment]
Thanks.
