### ISSUE TITLE
Monthly online meetup

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#167]
<worrelsik> Something else: tips for community building:
<worrelsik> 1) Like cfengine.com/community: offer some sort of hang-out meeting on a monthly basis. Possibly #irc is too difficult for some, BigBlueButton or Skype or Hangouts might be useful for sharing screens.
<worrelsik> 2) Maybe such a meeting could turn into an online mini-sprint if a theme is attached to it, e.g. improving docs together, or running through all the examples, or …
<worrelsik> (Maybe a dojo-meeting might be a more appropriate naming)

**Comment by oberstet** [comment]
@goeddea pls check google hangouts .. how does this stuff work? etc

**Comment by zavg** [comment]
Hi guys! Please feel free to check out new service to hold regular online meetups using Google Hangouts on Air: webmeetups.net.

The service automatically reminds about meetup start in a day and in an hour, deals with time zones, allows you to select active participants and watchers if there are more then 10 attending people. You get rid of Hangouts url and Youtube url copy-pasting, it automatically handles all these things. Also it nicely embeds all YouTube videos in your meetup history.

I am service founder and we just came to production, so I warmly invite you to check out our service. Do not hesitate to ask any questions!

**Comment by oberstet** [comment]
http://webmeetups.net/ was suggested to me by Sergey. it looks nice. now we only need to "do it".
