### ISSUE TITLE
QRCode takes too much screen space

### ISSUE THREAD

**Issue by om26er** [crossbario/crossbar#1680]
I just ran `crossbar keys` and it covered my whole terminal, would likely make sense to reduce the size of the QRCode.
![Screenshot_20200117_005640](https://user-images.githubusercontent.com/6350837/72558397-66f06f00-38c4-11ea-9d04-5a24839606be.png)

**Comment by om26er** [comment]
We could potentially use https://pypi.org/project/qrcode/ as a replacement for the mostly unmaintained PyQRCode https://pypi.org/project/PyQRCode/ that we currently use. Which prints QR Codes in sane sizes.

Note: PyQRCode does not have a hard-dependency on Pillow so we can only pure-python implementation.

**Comment by om26er** [comment]
Attached image of qrcode created using the new library
![Screenshot_20200117_025301](https://user-images.githubusercontent.com/6350837/72565827-81324900-38d4-11ea-93ec-2a5163c9ddff.png)

**Comment by oberstet** [comment]
> Which prints QR Codes in sane sizes.

the size is deliberately largish to allow for robust scanning from smartphone (it can be used eg for master node registration and node pairing from an admin app .. if we had one;)
