### ISSUE TITLE
Cleanup legacy string literals

### ISSUE THREAD

**Issue by om26er** [crossbario/crossbar#1684]
One candidate for change is/are `u"my_string"` (single and double quoted variants)

Since crossbar has been Py3+ only for over a year, I see there is very little legacy code. Are there any other instances that anyone could think of ?

**Comment by oberstet** [comment]
yes, but I wouldn't touch that other code (now) ;)

real answer:

eg one could propose changing `@inlineCallbacks` to `async def`. for this specific example, I wouldn't support that until/unless we have a) added our performance tests to the CI and b) demonstrate no adverse effect on the PRs' CI run then. 

IOW: it really depends for the cases other then the one you listed (string literals) .. fixing that is harmless and of course cool! it further cleans up the code a bit - which is always a nice thing=)
