### ISSUE TITLE
Guest workers should support "stop command"

### ISSUE THREAD

**Issue by om26er** [crossbario/crossbar#1689]
Guest workers allow for starting external processes with Crossbar, this helps with deployments. What's missing is to be cleanly stop the externally started process.

Crossbar should implement a way to gracefully close those processes.

In my case, I am running an authenticator component as a guest because its based on asyncio, I want to cleanly close that component.

**Comment by oberstet** [comment]
this is implemented https://github.com/crossbario/crossbar/blob/ecc8b4e0d9f8fa3efa7d59755cb2e16151055870/crossbar/node/controller.py#L393
