### ISSUE TITLE
proxy worker: web service of type "static" non-working

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1696]
I tested https://github.com/crossbario/crossbar-examples/tree/master/proxy a bit .. in particular the web services defined in the node config:

1. [x] [http://localhost:8443](http://localhost:8443): **path "/", type "static"** - static web files
1. [x] [http://localhost:8443/info](http://localhost:8443/info): **path "info", type "info"** - node info page
1. [x] [http://localhost:8443/ws](http://localhost:8443/ws): **path "ws", type "websocket-proxy"** - websocket endpoint (of listening proxy)
1. [x] [http://localhost:8443/autobahn/autobahn/autobahn.js](http://localhost:8443/autobahn/autobahn/autobahn.js): **path "autobahn", type "archive"** - ZIP archive resource
1. [x] [http://localhost:8443/autobahn/autobahn-xbr/autobahn-xbr.js](http://127.0.0.1:8443/autobahn/autobahn-xbr/autobahn-xbr.js): **path "autobahn", type "archive"** - ZIP archive resource (same archive file, but different contained file referenced)

of above, all (checked) resources work for me .. all but the `static` resource which merely returns

```
this is the proxy-worker web content. it worked
```

> I slightly changed the configuration of the `archive` web service .. this change is on an unrelated work PR of mine .. pls see https://github.com/crossbario/crossbar-examples/blob/63f671656a1abc550ed638369c1c72c152e136e2/proxy/.crossbar/config.json

**Comment by oberstet** [comment]
ok, for convenience, here is the config change I did in the example:

```
"autobahn": {
    "type": "archive",
    "archive": "autobahn-v20.1.1.zip",
    "origin": "https://github.com/crossbario/autobahn-js-browser/archive/v20.1.1.zip",
    "object_prefix": "autobahn-js-browser-20.1.1",
    "default_object": "autobahn.min.js",
    "download": true,
    "cache": true,
    "hashes": [
        "a7e898a6a506c8bffe9a09d7e29b86a8adb90a15859024835df99cc7be82274a"
    ],
    "mime_types": {
        ".min.js": "text/javascript",
        ".jgz": "text/javascript"
    }
}
```

> this makes use of a bunch of other archive web service features .. unneeded here, but that's just my "standard config block";)

**Comment by meejah** [comment]
Okay, I took a look and I think that output from `/` (the static) stuff is actually working correctly -- at least, that's the content that's in https://github.com/crossbario/crossbar-examples/tree/master/proxy/web

**Comment by meejah** [comment]
Hrrmmmm, I'm also seeing some weird behavior with the `archive` resource though -- it seems to work fine when I have "debug" level logs but 404's when I have info level logs

**Comment by meejah** [comment]
seems to be this line: https://github.com/crossbario/crossbar/blob/master/crossbar/webservice/archive.py#L155

**Comment by meejah** [comment]
Ahhhh, I think it's a race between the two proxies and one has the resource but one doesn't...

**Comment by meejah** [comment]
https://github.com/crossbario/crossbar-examples/pull/135

**Comment by meejah** [comment]
Okay, so we could put different content into `web/index.html` but the actual crossbar proxy / static feature is working properly as far as I can see.

**Comment by oberstet** [comment]
ok, static seems to work for me now! great=)

fiddling around a bit with http://localhost:8443/info, as in loading that page from different browsers, I also can see different PIDs in the fotter rendered in that page

```
Served for 127.0.0.1:14768 from Crossbar.io router worker with PID 22147.
```

which kinda demonstrates the feature:

* scale-up of web services (such as `static` or `archive` .. any of our web service types?)
* scale-up of the incoming WAMP-WebSocket connections
