### ISSUE TITLE
proxy worker: add CI test

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1697]
one approach to automatically test the *web resource* part of proxy workers could work similar to

* https://github.com/crossbario/crossbarfx/blob/69a162f9f385559068bfb6504485972986425ffb/test/functests/cfctests/test_cfc_shared.py#L67

this issues a large number of HTTP requests, and tracks the worker PID by parsing the PID from the info page rendered by the worker

the result printed is:

* https://travis-ci.com/crossbario/crossbarfx/jobs/282180388#L8592

```
{'7566.': 16, '7525.': 16, '7509.': 11, '7539.': 18, '7560.': 13, '7530.': 24, '7578.': 11, '7545.': 21, '7550.': 15, '7520.': 13, '7515.': 19, '7555.': 15}
```

above are the number of requests served by PID (12 workers in total)

> besides testing the *web resource*  par of proxy workers, we of course want to test the WAMP reverse-proxying main feature of proxy workers as well;) above is only an idea for web resources ..

**Comment by meejah** [comment]
fixed per https://github.com/crossbario/crossbarfx/pull/499 (re-open if it needs more tests)
