### ISSUE TITLE
Guest workers reconnection

### ISSUE THREAD

**Issue by far** [crossbario/crossbar#1714]
I got this case only once, guest worker was disconnected.
Is it any way to make it reconnectable ? I didnt find anything in documentation
And unfortunately didnt save traceback.

**Comment by oberstet** [comment]
any wamp connection a guest worker might open to a router worker is soley the responsibility of the guest worker. the router worker will only notice the guest worker presence by the incoming wamp connection (if any).

a guest worker process that fails and exits will be noticed by the node controller and respective log lines printed.

there are options to make the node controller shutdown the whole node upon one worker failing https://github.com/crossbario/crossbar/blob/da2f136734a6e3a35d3400da8be73948a3ef7f84/crossbar/common/checkconfig.py#L72

further, currently, there is no option that would make the node controller automatically restart a failed guest worker

we do have such options for container workers, controlling both shutdown and (auto-)restart behavior: https://github.com/crossbario/crossbar/blob/da2f136734a6e3a35d3400da8be73948a3ef7f84/crossbar/common/checkconfig.py#L2750
