### ISSUE TITLE
'FrontendProxyProtocol' object has no attribute 'close'

### ISSUE THREAD

**Issue by om26er** [crossbario/crossbar#1720]
I have seen that appear in logs, the relevant code is https://github.com/crossbario/crossbar/blob/fbdc8c758532acdc2d93b4cd4a7203748e1548f7/crossbar/worker/proxy.py#L298 -- Shall we call `sendClose()` instead ?

(sorry for not having complete log)

**Comment by om26er** [comment]
attempted https://github.com/crossbario/crossbar/pull/1718#issuecomment-591620519

**Comment by oberstet** [comment]
> Shall we call sendClose() instead ?

no, as sendClose is specific to WebSocket .. eg RawSocket doesn't have it. Proxy workers should in principle work with both WebSocket and RawSocket as frontend protocol (even though we likely only need/want WebSocket on the demo instances eg) .. "close should work" ..

**Comment by meejah** [comment]
Just so I remember, this bug is for when the frontend-to-backend is using a WebSocket..
