### ISSUE TITLE
proxy worker: backend connect failure handling

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1729]
Here is a proxy worker failing on connecting to a backend upon accepting an incoming websocket connection. The connection client is stuck in the websocket opening handshake in the meantime ..

```
crossbarfx_config1_1  | 2020-03-18T09:13:37+0000 [Proxy          17] Starting factory <autobahn.twisted.rawsocket.WampRawSocketClientFactory object at 0x000000000299d210>
crossbarfx_config1_1  | 2020-03-18T09:13:37+0000 [Proxy          17] fail: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectError'>: An error occurred while connecting: 2: No such file or directory.
crossbarfx_config1_1  | 2020-03-18T09:13:37+0000 [Proxy          17] ]
```

**Comment by oberstet** [comment]
> An error occurred while connecting: 2: No such file or directory.

this is over UDS .. hence "file" I guess. the strange thing is, this only occurs sometimes .. eg have a look at this client side log, where a client is justed restarted without modification:

![Screenshot from 2020-03-18 10-32-26](https://user-images.githubusercontent.com/233340/76946197-f4bbfb00-6903-11ea-9bb4-3c93417fb881.png)

**Comment by oberstet** [comment]
this is invalid (I had another (!) node running via docker, and the listening ports are opened "shared" so effectively a mix of 2 proxy worker groups with different configs (!) were running at the same time. this is an evil trap;)

**Comment by meejah** [comment]
Ah, okay :)
That said, there may certainly be scope to improve the failure propagation and/or messages ..
