### ISSUE TITLE
Proxy workers: fix cryptosign-proxy backend authentication

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1744]
Proxy workers now (landed in https://github.com/crossbario/crossbar/pull/1741) work with all frontend authentication methods.

Eg here is an example [config3](https://github.com/crossbario/crossbar-examples/blob/86dbf561aa976d19741944562266a2d565a4ef1a/proxy/Makefile#L13)

However, besides frontend authentication, we also need to support two methods of backend authentication:

* [x] **anonymous-proxy**: [config3](https://github.com/crossbario/crossbar-examples/blob/86dbf561aa976d19741944562266a2d565a4ef1a/proxy/Makefile#L13)
* [ ] **cryptosign-proxy**: [config4](https://github.com/crossbario/crossbar-examples/blob/86dbf561aa976d19741944562266a2d565a4ef1a/proxy/Makefile#L16) example

However, there still seems to be a bug during backend session establishment, as the client will hang and never join ..

**Comment by oberstet** [comment]
To test, run CB from https://github.com/crossbario/crossbar-examples/tree/master/proxy:

``` 
make run_config3
```

and run the test clients

``` 
make run_subscribe_ws_cbor
make run_subscribe_rs_cbor
make run_subscribe_ws_json
make run_subscribe_rs_json
make run_publish_ws_cbor
make run_publish_rs_cbor
make run_publish_ws_json
make run_publish_rs_json
```

**Comment by oberstet** [comment]
![Screenshot from 2020-04-05 22-24-32](https://user-images.githubusercontent.com/233340/78509151-3bc34080-778c-11ea-91e3-dd97e8fef043.png)

**Comment by meejah** [comment]
So, when the proxy connects to the backend, it puts `pubkey` into `authextra` (here: https://github.com/crossbario/crossbar/blob/master/crossbar/worker/proxy.py#L298 ) but then when the `cryptosign-proxy` auth is doing hello (seehttps://github.com/crossbario/crossbar/blob/master/crossbar/router/auth/cryptosign.py#L260) , it replaces the authextra with the proxy_authextra from the actual client (which won't have pubkey) .. and then the auth fails.

It seems there also some error-propagation stuff that could be better (because you don't see e.g. "no user1" just "authentication failed").

So is the goal to give the actual backend auth *access* to the proxy's real information, or to overwrite the details used to authenticate into the backend. (Because to make the example work we have to switch https://github.com/crossbario/crossbar-examples/blob/master/proxy/.crossbar/config4.json#L75 to say "user1" too because of similar overwriting ..)

**Comment by oberstet** [comment]
> it replaces the authextra with the proxy_authextra from the actual client (which won't have pubkey) .. and then the auth fails.

ahh, right

> It seems there also some error-propagation stuff that could be better (because you don't see e.g. "no user1" just "authentication failed").

yeah, that would have helped, definitely. didn't saw anything .. hang. we need to catch all such errors to properly respond with ABORT

**Comment by meejah** [comment]
I have a partial patch for that but was also sometimes getting two `Abort`s so it might be ... more complex ;) I added a dynamic-auth version to the proxy example too. I think basically though we *don't* want to be over-writing authid/role etc with the proxy details, but merely *provide* them for use by any dynamic auth stuff .. which means the "usual" case is easy to config statically: no authid at all, and add all pubkeys for all your nodes in cryptosign `authorized_keys` (or just use Unix sockets).

**Comment by oberstet** [comment]
> which means the "usual" case is easy to config statically: no authid at all, and add all pubkeys for all your nodes in cryptosign authorized_keys (or just use Unix sockets).

yes, exactly!

so on the backend router transport (the UDS .. or a private TCP), the authentication configuration

```json
"auth": {
    "cryptosign-proxy": {                            
        "type": "static",
        "principals": {
            "node1": {
                "authorized_keys": [
                    "feae7b53b1aa85f3aec09302fb800d40416df069a233b8c72833eca38cf59117"
                ]
            }
        }
    }
}
``` 

was supposed to mean, authenticate the incoming connection from the frontend worker under `authid==node1`, _but_ the actual client incoming to the frontend worker should get `authid==user1` (as it was authenticated using WAMP-CRA against the frontend).

maybe the router should accept the frontend with `autextra=={"client_authid": "user1", "client_authrole": "user", "client_realm": "realm1"}` ? and the frontend could then pick out those actual credentials, and use and return them for the client?

kinda the reverse of the `proxy_authid` etc attributes ..

**Comment by oberstet** [comment]
> was supposed to mean, authenticate the incoming connection from the frontend worker under authid==node1

mmh, after re-reading this: a principal of that authid - or at least, authrole - doesn't need to exist on the router .. in which case, it doesn't make sense to expose 

```
"principals": {
            "node1": {
```

at all in the config, only `authorized_keys` .  is that what you meant with

> no authid at all, and add all pubkeys for all your nodes in cryptosign authorized_keys

?

**Comment by meejah** [comment]
> at all in the config, only authorized_keys . is that what you meant with

Yes, exactly, you just need ```"dont_care": {"authorized_keys": [ ...every node's pubkey ]}``` basically.

**Comment by meejah** [comment]
If the backend wants to do "fancy" stuff based on the real client information, they do something like this: https://github.com/crossbario/crossbar-examples/blob/master/proxy/dynauth.py#L13

**Comment by meejah** [comment]
And yeah, we could have the "inverse" things coming back out .. so that a dynamic authorizer can return `client_*` as you suggest above to override what we assign to the real client, ultimately.

**Comment by meejah** [comment]
This is done now, right?
