### ISSUE TITLE
Memory issue crossbar FX master node 20.4.2

### ISSUE THREAD

**Issue by boinalibo** [crossbario/crossbar#1770]
Hello,

I am not sure that is the right repository to used for this issue.
We are using the docker image delivered by the Docker Hub for running a Crossbar FX master node (version 20.4.2).
The memory used  increase anormally (over 1Go) and never decrease. It is normal ? Can you help us, please ?

Best regards
B. B

**Comment by oberstet** [comment]
yeah, this repo here and the issue tracker are only for Crossbar.io OSS. to file support requests for Crossbar.io FX under your support contract, please visit:

https://crossbar.zendesk.com/

![Bildschirmfoto von 2020-05-19 14-54-44](https://user-images.githubusercontent.com/233340/82328869-b664ba00-99e0-11ea-9108-07f7f2f1d957.png)

---

for convenience, rgd your specific question: in short, I wouldn't worry (if "1Go" means ~1GByte RAM). The master node maps its embedded database into RAM (and relies on OS vmem page management). Also, measuring actual RAM usage is not straight forward ...

**Comment by boinalibo** [comment]
Thanks for your answer. I am not worried about that RAM memory exceeds 1Go. I am worried about that it never decrease.

**Comment by meejah** [comment]
When the Python allocator grabs memory, it doesn't immediately release it back to the operating system when Python-level memory allocations go away. You can still use the system resident size as a hint that you "might" be leaking memory, however the CPython interpreter does seem quick to allocate and slow to de-allocate system memory.

If you *do* believe you've found a memory leak, showing that system resident RAM constantly increases and really does *never* go down might help show that .. but it would still be necessary to run python-level memory profiling to see how much of the RAM that CPython has allocated is really still in-use :/

**Comment by markope** [comment]
I observed a similar behaviour: Here is our crossbar on kubernetes container memory history: 
Last restart (manual) was on May 13th right at the last peak.
(Memory limit in the container is set to 0=unlimited)

![image](https://user-images.githubusercontent.com/1944925/82840605-82533280-9ed3-11ea-8183-b1c8094379bd.png)

The crossbar has nothing to do 90% of the time in our platform.

**Comment by oberstet** [comment]
>  I am worried about that it never decrease.

python does the right thing: mem once allocated might be garbage collected within the interpreter, but not released to the system. put differently: without memory pressure on the system (outside py), this behavior is exactly right. it saves cycles that would have been needed to OS-free. if you have RAM not needed elsewhere, why free it once you got it?

rgd GC: on crossbarfx, you can force GC cycles via management API. but I don't believe above memory numbers are meaningful anyways. eg "RSS" in the context of program that use mmap (as does crossbar). not measuring free mem and system mem pressure and so on.
