### ISSUE TITLE
REST Subscriber Support for Dynamic Wildcard/Regex Topics

### ISSUE THREAD

**Issue by azcoppen** [crossbario/crossbar#1772]
It's currently very difficult (almost impossible) to subscribe to topics a client or broker app might create. For example, let's say i want each user to have their own channel, maybe tracking their e-com orders, or location.

The topic might be `com.app.users.{id}` or `channels.orders.order-{id}`

The REST publisher can obviously create whatever topic it likes, but the REST subscriber *must* specify a static topic identifier. That's great for public channels, or perma-channels, but if the topic is created on the fly, how can the REST subscriber know about it?

If a topic must be specified, would it be possible to use wildcards or regular expressions? To use something like the config below?

```
{
    "type": "class",
    "classname": "crossbar.bridge.rest.MessageForwarder",
    "realm": "realm1",
    "extra": {
        "subscriptions": [
            {
                "url": "https://subscriber.app/orders",
                "topic": "com.myapp.orders.*"
            },
            {
                "url": "https://subscriber.app/any",
                "topic": "\b[a-z]."
            },
            {
                "url": "https://subscriber.app/users",
                "topic": "^users."
            }
        ],
        "method": "POST",
        "expectedcode": 200,
        "debug": true
    },
    "transport": {
        "type": "websocket",
        "endpoint": {
            "type": "tcp",
            "host": "127.0.0.1",
            "port": 8080
        },
        "url": "ws://127.0.0.1:8080/ws"
    }
}
```

**Comment by azcoppen** [comment]
Is there a might-want-to-be-a-little-friendlier-to-developers-who-appreciate-and-want-to-use-our-software label?

**Comment by oberstet** [comment]
fair enough=) sorry, didn't want to be rude. just save time as it happened so many times and I grew tired of writing text again and again

rgd your question, here is how to do that:

```json
{
   "type": "class",
   "classname": "crossbar.bridge.rest.MessageForwarder",
   "realm": "realm1",
   "extra": {
      "subscriptions": [
            {
               "url": "https://httpbin.org/post",
               "topic": "com.myapp.",
               "match": "prefix"
            }
      ],
      "method": "POST",
      "expectedcode": 200,
      "debug": true
   },
   "transport": {
      "type": "websocket",
      "endpoint": {
            "type": "tcp",
            "host": "127.0.0.1",
            "port": 8080
      },
      "url": "ws://127.0.0.1:8080/ws"
   }
}
```

this will setup a prefix-subscription. you can also use "wildcard" instead of "prefix".

eg

```json
{
     "url": "https://httpbin.org/post",
     "topic": "com..topic1",
     "match": "wildcard"
}
```

**Comment by azcoppen** [comment]
Thank you @oberstet ! I was being playful so thanks for taking it that way. I posted both questions on the forum (mailing list is dead) but they're still in moderation and it doesn't look like there's anyone doing anything on there.

**Comment by oberstet** [comment]
the forum was historically on google groups but moved to https://forum.crossbar.io/ - and I've approved your posts
