### ISSUE TITLE
Ticket based dynamic authentication does not work properly

### ISSUE THREAD

**Issue by duybinh0208** [crossbario/crossbar#1796]
Hi, I am using the dynamic ticket based authentication but seems it does not work correctly.

I see that when the **authenticate(realm, authid, details)** method cannot verify/authenticate clients credential then the code raise an **ApplicationError**, and from this point the **authenticator** just loose the connection to the **crossbar** (_The authenticator just leave the session but it should not do that_). As a result, the **authenticator** keeps re-connect to the **crossbar** and the clients keep receiving the **no callee** registered for the **"com.example.authenticate"** error.

I just wonder if this example code handles the **authentication** correctly or not? How can we reject clients in case their credential are not correct? Instead of using **raise ApplicationError** can we just **return None**?

```
class AuthenticatorSession(ApplicationSession):

   @inlineCallbacks
   def onJoin(self, details):

      def authenticate(realm, authid, details):
         ticket = details['ticket']
         print("WAMP-Ticket dynamic authenticator invoked: realm='{}', authid='{}', ticket='{}'".format(realm, authid, ticket))
         pprint(details)

         if authid in PRINCIPALS_DB:
            if ticket == PRINCIPALS_DB[authid]['ticket']:
               return PRINCIPALS_DB[authid]['role']
            else:
               raise ApplicationError("com.example.invalid_ticket", "could not authenticate session - invalid ticket '{}' for principal {}".format(ticket, authid))
         else:
            raise ApplicationError("com.example.no_such_user", "could not authenticate session - no such principal {}".format(authid))

      try:
         yield self.register(authenticate, 'com.example.authenticate')
         print("WAMP-Ticket dynamic authenticator registered!")
      except Exception as e:
         print("Failed to register dynamic authenticator: {0}".format(e))
```

**Comment by oberstet** [comment]
you can find a complete example with authenticator and client here https://github.com/crossbario/crossbar-examples/blob/fbc60b2dcbd848e9a1da8d5381f3700507e557f9/authentication/cryptosign/dynamic/authenticator.py#L84
