### ISSUE TITLE
Crossbar AMI is no longer available in AMI Marketplace on AWS

### ISSUE THREAD

**Issue by sesh** [crossbario/crossbar#181]
The AMI referenced [here](http://crossbar.io/docs/Setup-on-Amazon-EC2/) can no longer be found in the AMI Marketplace (searching for "crossbar") and cannot be referenced by id when attempting to launch a new instance.

**Comment by ramlez** [comment]
Hi @goeddea it looks like AMI is not available for some regions again. I wasn't able to find it in: 

- EU - London
- EU - Ireland

I was able to find it in **EU Frankfurt** which seems to be the central EU location.
