### ISSUE TITLE
LICENSE file at root

### ISSUE THREAD

**Issue by cameronelliott** [crossbario/crossbar#1824]
Hi, Crossbar and WAMP are very impressive.

I am investigating Crossbar for an application, but could not find a LICENSE file at the root.

After a while of searching around I did find crossbar/LICENSE

Please consider creating a LICENSE in the root, this will cause github to show badges on the project page,
and will help people understand this is really open source.

Thanks
Cameron

**Comment by oberstet** [comment]
yeah, that's a good idea .. actually github should then show the license as a tag automatically? let's see .. coming via https://github.com/crossbario/crossbar/pull/1825

**Comment by oberstet** [comment]
mmh, ok, better than before:

![Bildschirmfoto von 2020-11-09 07-57-28](https://user-images.githubusercontent.com/233340/98509441-7c72c300-2261-11eb-83dd-da887a04f13a.png)

the LICENSE file is now a symlink in the rotot folder pointing to the LICENSE file within the Python package. GitHub detects that and autolinks the file in the "About" section to the right.

however, GitHub doesn't seem to recognize that the license is standard AGPL3.

comparing to AutobahnPython, which is MIT, and where the root LICENSE is a file, not a symlink

![Bildschirmfoto von 2020-11-09 07-57-36](https://user-images.githubusercontent.com/233340/98509644-db383c80-2261-11eb-9b89-ca92f93aaf96.png)

so it might be that GitHub fails to detect the AGPL3 license text, or that it fails to process symlinked license files ...

**Comment by oberstet** [comment]
it was the symlink indeed. after merging https://github.com/crossbario/crossbar/pull/1827 it now works!

![Bildschirmfoto von 2020-11-09 08-06-02](https://user-images.githubusercontent.com/233340/98509921-6d404500-2262-11eb-9e14-c256b0b89854.png)

**Comment by cameronelliott** [comment]
Awesome!
