### ISSUE TITLE
vmprof option not working on arm64

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1828]
pls see https://github.com/vmprof/vmprof-python/issues/192

**Comment by fijal** [comment]
I think this should be fixed (it landed in default on pypy, waiting for buildbots to merge to 3.7)

**Comment by oberstet** [comment]
fantastic! big step. could you add a link to the merge on pypy pls? that'll actually provide a way to "backtrack" from the close of the issue here to the actual soluation (with was of course the merge in pypy repo) ...

**Comment by fijal** [comment]
This is the merge to 3.7 branch (which is what we care about):

https://foss.heptapod.net/pypy/pypy/-/commit/4f926cc678126b9a1b405761f03d16241d52edec

**Comment by oberstet** [comment]
from the very surface (I have zero clue), the additions seem very clean and nicely small to add arm64 to vmprof .. or the changes required in pypy for vmprof. cool, thanks!
