### ISSUE TITLE
pypy-3.7-nightly / ubuntu 20.03 / arm64: libffi.so.6 missing

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1842]
> I have added ARM64 to the CI here https://github.com/crossbario/crossbar/blob/753ee1b29b46b680e83c690a35bf01ccb4ae814d/.github/workflows/main.yml#L139 - this is using a self-hosted runner (an AWS Graviton instance) connected & driven from to GitHub Actions. However, it does not yet work .. the issue here. Also CPython/ARM64 needs to be added as well (unrelated to this specific issue here).

this system (aws graviton instance for self-hosted runner - GH actions):

![Bildschirmfoto von 2021-01-09 16-33-30](https://user-images.githubusercontent.com/233340/104095668-71a3d100-5298-11eb-98b2-5c6ca274fefc.png)

does not have libffi.so.6, only libffi.so.7:

![Bildschirmfoto von 2021-01-09 16-33-05](https://user-images.githubusercontent.com/233340/104095671-76688500-5298-11eb-9c2f-281694956d4f.png)
----

what is also needed, is install this old package:

```
sudo add-apt-repository universe
sudo apt-get install -y libncurses5
```

**Comment by oberstet** [comment]
I also tried
```
# https://stackoverflow.com/a/61876234/884770
sudo ln -s /usr/lib/aarch64-linux-gnu/libffi.so.7 /usr/lib/aarch64-linux-gnu/libffi.so.6
```

but pypy detects that at run-time (cannot be fooled like this). it really wants libffi.so.6 - and only that version

**Comment by om26er** [comment]
It depends on the specific case, but one easy way out could be to have Ubuntu 18.04 on that instance instead of 20.04, which does have the "expected" libffi.

**Comment by oberstet** [comment]
yeah, I guess that would be one option .. let's see, maybe there is a simpler way (at this point, I would like to avoid starting from fresh again) ..

**Comment by oberstet** [comment]
* FIX test on ARM64: https://github.com/crossbario/crossbar/blob/a08142b7e0018de6002dec55206d4263467ca4c5/.github/workflows/main.yml#L140
* ADD Docker image building for ARM64: https://github.com/crossbario/crossbar/blob/master/.github/workflows/docker.yml

**Comment by fijal** [comment]
This should be fixed by now
