### ISSUE TITLE
404 page displays wrong directory repr

### ISSUE THREAD

**Issue by fijal** [crossbario/crossbar#1844]
Right now the 404 page displays:

This is a static Web endpoint of your Crossbar.io node serving from base directory

b'/node/web'

Presumably the b'' prefix should be stripped

**Comment by oberstet** [comment]
yeah, that could be improved. quick comments:

* you can enable `enable_directory_listing` in `options` of the Web service configured
* the 404 is rendered from here https://github.com/crossbario/crossbar/blob/496fd0d5dd279773e8426a79bacf59451983eb49/crossbar/webservice/base.py#L61
