### ISSUE TITLE
Create a build process so crossbar is available as a black box

### ISSUE THREAD

**Issue by sametmax** [crossbario/crossbar#187]
A lot of people are afraig of crossbar people it's Python, or because it's Python 2.7 only.

It would help to be able to just homebrew/yum install/apt-get/exe it and forget about it.

It would help create this idea that it's just like Apache/Nginx for HTTP, but for WAMP.

**Comment by bradws** [comment]
That would be good. As a developer with no prior experiance with Python, I did manage to get it up and running under windows and have javascript browser clients and C# clients all talking. It wasn't too dificult to do, however there were quite a few steps and a bit of a learning curve (for me anyway). I don't have enough experience with *nix, but I can see myself doing more in this area. There is nothing like this in the .NET world, and I'm really quite excited about it.

**Comment by oberstet** [comment]
@bradws creating *nix packages (rpm, deb, ..) is quite easy. creating a full-fledged Crossbar.io msi for Windows is a lot more tricky.

I'd be interested about your opinion as a Windows developer rgd the following options to ease starting with Crossbar.io:

1. Just start with our hosted/free Crossbar.io "as-a-service": *nothing* to install
2. We could quite easily provide a virtual application that you can boot on VirtualBox/Windows
3. A full-fledged Windows MSI installer (within everything bundled including Python)

**Comment by bradws** [comment]
Hi there,

Most of us would go with option 1 (easiest for application developers!).

Cheers,
Brad.

On Sat, Jan 17, 2015 at 11:45 PM, Tobias Oberstein <notifications@github.com

**Comment by meejah** [comment]
To get things into Debian, it can be as simple as filing a "Request to Package" (RTP) bug and hoping some Debian developer picks it up. https://www.debian.org/devel/wnpp/

Then, it would ultimately end up in Ubuntu as well. Of course, providing your own `.deb` archive is good as well. Obviously this gives more control over how rapidly releases are available etc...

I bet it's much easier if you first get a Debian developer excited about WAMP/crossbar ;)

**Comment by hawkowl** [comment]
We now do have black-box packages on http://crossbar.io/docs/Installation-on-Ubuntu/ , http://crossbar.io/docs/Installation-on-CentOS/ , and http://crossbar.io/docs/Installation-on-FreeBSD/ -- but nothing in the case of Windows.

**Comment by oberstet** [comment]
Closing this issue now - as @hawkowl  mentions, we now have binary packages. (I added an issue rgd Windows installer on the cb packaging repo).

**Comment by xgdgsc** [comment]
@oberstet Is there a single exe file I can bundle to my application on windows? Or is there any documentation on how to build one using pyinstaller?

**Comment by meejah** [comment]
@xgdgsc see https://github.com/crossbario/crossbarpackage/issues/16

**Comment by xgdgsc** [comment]
@meejah  Thanks for replying, but that' s a dead link.

**Comment by hawkowl** [comment]
Oh, yeah, it's a private repo.

On Windows: I haven't tried anything with pyinstaller yet, unfortunately. If you need a .exe for your own deployments then it might work if you just try and do a simple package with pyinstaller, and most if not all of our dependencies ship Windows wheels, so you shouldn't need to do anything much...

**Comment by xgdgsc** [comment]
@hawkowl Thanks. I just don' t know on which file to run pyinstaller on. I' ve tried `pyinstaller crossbar.exe` but it gave me some errors.

**Comment by meejah** [comment]
Sorry about the private link; it is a feature-bug about eventually providing an MSI installer for Crossbar.

As to PyInstaller, I've never used it -- but if there are crossbar bugs preventing its use please do report back :)
