### ISSUE TITLE
Is netaddr a unused dependency?

### ISSUE THREAD

**Issue by suliuzh** [crossbario/crossbar#1880]
Hi
I noticed that _netaddr_  was removed from source code in pull #1315. At the same time, _ipaddress_ was used.  But in configuration files such as requirements-min.txt,  netaddr is still listed as a direct dependency. So is netaddr a unused dependency? Should ipaddress be listed as a direct dependency?
![image](https://user-images.githubusercontent.com/27858725/120914395-a6de0f00-c6d0-11eb-8345-0c8d564c58a8.png)

**Comment by oberstet** [comment]
above code is indeed now using a Python stdlib package https://docs.python.org/3.9/library/ipaddress.html

however, other dependencies of crossbar still use netaddr - *indirectly*:

```
(cpy39_10) (base) oberstet@intel-nuci7:~/scm/crossbario/crossbar$ pipdeptree --reverse --packages netaddr
Warning!!! Possibly conflicting dependencies found:
* crossbar==22.3.2.dev4
 - werkzeug [required: >=0.14.1,<2, installed: 2.0.3]
 - MarkupSafe [required: >=1.1.1,<2, installed: 2.1.1]
------------------------------------------------------------------------
netaddr==0.8.0
  - crossbar==22.3.2.dev4 [requires: netaddr>=0.8.0]
  - multiaddr==0.0.9 [requires: netaddr]
    - ipfshttpclient==0.8.0a2 [requires: multiaddr>=0.0.7]
      - web3==5.28.0 [requires: ipfshttpclient==0.8.0a2]
        - cfxdb==22.3.1 [requires: web3>=5.28.0]
          - crossbar==22.3.2.dev4 [requires: cfxdb>=22.3.1]
        - crossbar==22.3.2.dev4 [requires: web3>=5.13.1]
```

IOW: it is correct as it is

**Comment by NJUJisq** [comment]
how about urllib3?
is it an indirect dependency?
