### ISSUE TITLE
Crossbar components

### ISSUE THREAD

**Issue by sametmax** [crossbario/crossbar#191]
Making crossbar more and more component oriented would make it easier to test, to reuse and to contribute to.

I identified several parts of crossbar that could be improved regarding this:

- the routing;
- the WAMP protocol;
- the crossbar init.

The wamp protocol is already a separated project in the form of autobahn, but lacks of documentation on how to use it. Documention should show how to create a basic router with it and explain the internal of the stuff. It will incitate contributors. Maybe something to add to my todo list ?

The crossbar init is right now just the dump of the json configuration file into a big method (https://github.com/crossbario/crossbar/blob/master/crossbar/crossbar/controller/node.py)  but it should be possible to do it in pure Python without knowing all the details of this method content. And you want to document it. People may want to embed crossbar in their application, and right now it's hard to do so. It's probably not even because it's not easy, but because it's not obvious how.

But the most important point : the routing.

I think they woule be a big gain to make the routing engine a separate project.

Indeed, a router is not specific to crossbar, it's always the same stuff : 

- data is inputed in a pipeline 
- callables extract things from the data
- other callables test this data to decide the route
- at the end of the route, another callable is called with the extracted data

This work for crossbar : 

- data is inputed : RPC name/PUB topic + params + session info
- callables extract things from the data : if you got a wild card, make something out of it
- other callables test this data to decide the route  : you check the registered clients
- at the end of the route, another callable is called with the extracted data : you send that to the client

But it works for AMQP too : 

- data is inputed : routing key payload
- callables extract things from the data :  if you got a wild card, make  something out of it
- other callables test this data to decide the route (you check the registered queues
- at the end of the route, another callable is called with the extracted data : you send that to the queue

And it works also for any kind of HTTP URL routing : 

- data is inputed : HTTP request with URL, headers and body
- callables extract things from the data : extract masks from the URL pattern
- other callables test this data to decide the route  : you check the registered callbacks
- at the end of the route, another callable is called with the extracted data : you call the controller callback with url and let it does his job

But it works also for PUB/SUB in redis, in django signals... Any stuff applying the observer pattern really.

Making a really generic and flexible but high performance router is hard, and you are already doing that. If you remove it from crossbar and make it a separate component used by crossbar, you would get : 

- potential contributors that are not related to crossbar but will use it for other routing and will want to improve it.
- easiness of testing, isolation, and tuning for perfs.
- easiness to reuse and make small WAMP routers out of it.

The last point is important : i noticed you removed the router from autobahn. But if you let the opportunity and the tools for people to create something with your libs, you will eventually get new things created for dev and debugging from the community. A dev router, a routing debugger, a routing monitor...

**Comment by oberstet** [comment]
No, I disagree on most of above. We won't split out the routing into a separate project - the routing core is already and will be more and more interwoven with other code inside Crossbar.io
