### ISSUE TITLE
rlinks: existing events not forwarded

### ISSUE THREAD

**Issue by asimfarooq5** [crossbario/crossbar#1914]
This is very similar to https://github.com/crossbario/crossbar/issues/1909 but for events.

The same configuration can be used to reproduce the bug.

* Start Instances A
* Subscribe to a topic on instance A.
* Start instance B
* Subscribe to the same topic on instance B.
 * Publish event to instance A, it would be forwarded to instance B.
 * Publish event to instance B, it would not be forwarded to instance A.

Just to confirm, the rlink config have both `forward_local_events` and `forward_remote_events` set to true.

**Comment by om26er** [comment]
Great work, I can reproduce that issue as well. Luckily this should be a simple fix.

**Comment by asimfarooq5** [comment]
Just verified, issue fixed in the linked PR.
