### ISSUE TITLE
rlinks: duplicate events after resubscribe

### ISSUE THREAD

**Issue by asimfarooq5** [crossbario/crossbar#1920]
I've found a sub bug similar to #1916

* instance A connected to instance B
* Subscribe to a topic (let's call it `com.test`) on instance B
* subscribe/unsubscribe to that topic multiple times
* publish on topic `com.test` on instance A

Result:
Instance B receives that single published event multiple times.

**Comment by om26er** [comment]
Thanks, this is reproducible. It actually results in N events (depending on the number of subscribe and unsubscribes)

**Comment by oberstet** [comment]
> It actually results in N events (depending on the number of subscribe and unsubscribes)

the rlink should process the remote meta API event "on-sub-created" - not "on-sub-added", which is fired on every subscribe to an already existing subscription in the remote broker ..

**Comment by om26er** [comment]
@asimfarooq5 I can no longer reproduce this issue. Please try Crossbar from master and let me know if it's fixed for you as well.

**Comment by asimfarooq5** [comment]
It seems to be fixed
