### ISSUE TITLE
rlinks: define i) test topologies/configurations, ii) tested wamp communications and iii) failures

### ISSUE THREAD

**Issue by asimfarooq5** [crossbario/crossbar#1921]
* instance A connected to instance B and  B to A
  * forward_local_events: true 
  * forward_remote_events: true
* subscribe to a topic (let's call it com.test) on instances A and B
* publish on topic com.test on instance A
  * Instance A receives single result
  * Instance B receives duplicate results
* publish on topic com.test on instance B
  * Instance B receives single result
  * Instance A receives duplicate results

**Comment by oberstet** [comment]
sure, this is expected. IOW: not every topology and flag combination makes sense. eg in this case here, if you establish bidirectional links, you cannot have both flags true ...

I think it would make sense to first define the scenarios we would like to configure and test, and then expose those to failure & recovery tests (eg a node being shut down, and then reconnecting, is everything workging again?) - @om26er any comments?

**Comment by asimfarooq5** [comment]
It doesn't matter whether both flags are true or false,

* instance A connected to instance B
  * forward_local_events: true
  * forward_remote_events: false
* instance B connected to instance A
  * forward_local_events: false
  * forward_remote_events: true
* subscribe to a topic (let's call it com.test) on instances A and B
* publish on topic com.test on instance A
  * Instance A receives single result
  * Instance B receives no result
* publish on topic com.test on instance B
  * Instance B receives single result
  * Instance A receives duplicate results
