### ISSUE TITLE
Dynamic Proxy Workers

### ISSUE THREAD

**Issue by om26er** [crossbario/crossbar#1928]
Assume there is a logical grouping of 5 crossbar nodes and they have two type of realms on them.

* Type 1 is the "system" realm where new users connect to sign up, make changes to their account etc.
* Type 2 is specific to a user and is named after them (bob)

"bob" realm is running only on 1 out of the 5 crossbar nodes/workers. It would be helpful if the proxy workers were made dynamic, where We could programmatically redirect an connection request to the specific node's IP

**Comment by oberstet** [comment]
This is already implemented: the master node can dynamically configure via `start_proxy_realm_route`:

* https://github.com/crossbario/crossbar/blob/c5184c74d9bc23a1f1f51bee72c9b954ea701fef/crossbar/worker/proxy.py#L880
* https://github.com/crossbario/crossbar/blob/c5184c74d9bc23a1f1f51bee72c9b954ea701fef/crossbar/worker/proxy.py#L1269
* https://github.com/crossbario/crossbar/blob/c5184c74d9bc23a1f1f51bee72c9b954ea701fef/crossbar/worker/proxy.py#L1563

**Comment by oberstet** [comment]
forgot to link the actual code in the master node that does indeed call into above:

https://github.com/crossbario/crossbar/blob/c5184c74d9bc23a1f1f51bee72c9b954ea701fef/crossbar/master/arealm/arealm.py#L351

is configuring proxy worker routes via "workergroup_placements"

https://github.com/crossbario/crossbar/blob/c5184c74d9bc23a1f1f51bee72c9b954ea701fef/crossbar/master/arealm/arealm.py#L384
