### ISSUE TITLE
PyPI release of version 22.1.1?

### ISSUE THREAD

**Issue by Bastian-Krause** [crossbario/crossbar#1942]
Hi,

[v22.1.1](https://github.com/crossbario/crossbar/releases/tag/v22.1.1) is not released on [PyPI](https://pypi.org/project/crossbar/). Is there a reason for that?

Thanks!

**Comment by oberstet** [comment]
PR is here https://github.com/crossbario/crossbar/pull/1943

**Comment by oberstet** [comment]
alright:

* https://pypi.org/project/crossbar/22.1.1/
* https://github.com/crossbario/crossbar/tree/v22.1.1

@om26er I have reverted your change https://github.com/crossbario/crossbar/commit/712d9da9173829be7df3ecba5dbb7981dd648fcd#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R45

this is wrong, and finding out did cost me a couple of hours:( but not your fault ultimately. python packaging is pretty fucked up. I want to move to Rust.
