### ISSUE TITLE
Docker image size gotten really big

### ISSUE THREAD

**Issue by hvanoch** [crossbario/crossbar#1952]
I noticed that the docker image size has grown since last year, from 160MB to 526MB now.

I believe there should be some optimisations done. 
We currently use crossbar in the field for 100's of units connected over 4G. This size makes a huge impact on the limited bandwidth available.

**Comment by oberstet** [comment]
> I believe there should be some optimisations done.

Who do you believe should do that?

**Comment by om26er** [comment]
> Who do you believe should do that?

I can help with that as that's something of interest to us as well

**Comment by oberstet** [comment]
@om26er sure! best would be 1) gather support to make that into an enhancement proposal https://github.com/wamp-proto/wamp-proto/tree/master/wep#wep-list, and then 2) collect money in the DAO to fund
