### ISSUE TITLE
EuroPython2016

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#199]
* PyCon 2015 will be in Canada in April: https://us.pycon.org/2015/
* EuroPython 2015 will be in Bilbao, Spain: http://www.europython-society.org/post/106049286320/europython-2015-will-be-in-bilbao-spain

Proposal phase for talks at PyCon 2015 is closed already: https://us.pycon.org/2015/speaking/cfp/

**Comment by touilleMan** [comment]
Hi,

PyCon 2016 registration is live and call for proposal (https://ep2016.europython.eu/en/call-for-proposals/) deadline is march 6th.
Judging by the 2015 edition and it numerous talks on asyncio, realtime web services and microservices I think a talk on crossbar would be really appreciated ! ;-)

What do you think ?

**Comment by oberstet** [comment]
@touilleMan We've submitted a talk proposal on microservice with Crossbar.io, as well as a proposal for a workshop on IoT apps using Crossbar.io =) Let's see. But in any case, we'll be on Europython this year!

**Comment by oberstet** [comment]
We'll be at https://ep2016.europython.eu/en/, and I'll reopen this issue to track related, Crossbar.io community stuff;)

**Comment by touilleMan** [comment]
That's an awesome news ! I'll see you this summer in Bilbao then ;-)

**Comment by oberstet** [comment]
@touilleMan Will be fun, yay! See you;)

**Comment by oberstet** [comment]
I'll be talking about "Scaling Microservices with Crossbar.io": https://ep2016.europython.eu/conference/talks/scaling-microservices-with-crossbario
