### ISSUE TITLE
Make the crossbar module executable by adding a __main__.py file

### ISSUE THREAD

**Issue by sametmax** [crossbario/crossbar#200]
__main__.py should have the save code than the crossbar command. This si especially useful in Windows, where the Scripts directory may not be added to the system path. It allows crossbar to be invoked anyway doing : 

```
    python -m crossbar
```

Or using the new py command : 

```
   python -2.7 -m crossbar
```

**Comment by oberstet** [comment]
You mean the following?

* http://stackoverflow.com/questions/4042905/what-is-main-py
* https://docs.python.org/2/using/cmdline.html

**Comment by oberstet** [comment]
On Windows, the path to Python itself isn't on the PATH as well by default. Adding PATH to Python and Scripts directory is clearly documented: http://crossbar.io/docs/Installation-on-Windows/
