### ISSUE TITLE
forum.crossbar.io closed intentionally?

### ISSUE THREAD

**Issue by readingtype** [crossbario/crossbar#2001]
Hi

I notice the forum is no longer available and I wonder if it is going to go back online.

I'm having a bit of  trouble with running the code in /crossbar-examples/authentication/wampcra/static and I was hoping to use historical posts to help me debug. Of course this is not the only way. I can see recent changes in the config.json and I will look at the commit history.

My current error is: 

`crossbar.common.checkconfig.InvalidConfigException: WAMP-Anonymous configuration - encountered unknown attribute 'realm'`

but this would be a different ticket :-)

Thanks,
Ben

**Comment by readingtype** [comment]
Hi

I found the secondary bug: the example code is too new for the crossbar version installed by pip today (22.3.1). Put it another way, 22.3.1 does not accept 'realm' as part of the specification of an anonymous transport. 

It's always difficult to keep sample code in sync with published code -- could I suggest pip freeze -r /crossbar-examples/requirements.txt -- or (not very palatable) make the examples into a package?

Ben

**Comment by om26er** [comment]
The new forum now lives at https://crossbar.discourse.group/, please direct your queries there.

**Comment by readingtype** [comment]
@om26er Thank you very much!

**Comment by readingtype** [comment]
@oberstet Thank you.

I am pushing my luck a bit, I know, but could you suggest a release version that you think will work with the example code? I cannot easily fix the problem I reported in this ticket by upgrading Crossbar since that code has not reached this repository yet. I noticed some other issues (eg changes in Werkzeug 2.1 that break imports) which also make running the examples non-trivial.

Ben

**Comment by ScrapingBoot** [comment]
Please change the forum address of your official website to the latest one！

**Comment by readingtype** [comment]
@ScrapingBoot I found out that (depending on where you look) it has already changed. For example, the markdown documentation source in the examples repository has the new forum link in HEAD whereas the checked-out HTML page does not. So it is presumably working its way gradually from the dev team to the wider world...
