### ISSUE TITLE
Provide recent arm64 Docker containers

### ISSUE THREAD

**Issue by aparcar** [crossbario/crossbar#2040]
Hi, your docker containers seem fairly outdated for arm64, am I missing something?

**Comment by oberstet** [comment]
yeah, true:( we have build scripts for both, but it still needs to be run manually - and it takes a long time, and I am lazy and impatient. anyways, I've started the builds, and - if everything works - should be done ready for upload tomorrow .. I'll post here

**Comment by oberstet** [comment]
btw, we also have snaps! which are quite nice, in particular for embedded stuff. but those are manually triggered as well. we need to automate all this .. anyways, here

![Bildschirmfoto von 2022-07-31 02-55-12](https://user-images.githubusercontent.com/233340/182005109-00429a7c-2980-4fc0-af00-718c73e1b1b3.png)

**Comment by oberstet** [comment]
here you go: `docker run --rm crossbario/crossbar:cpy-slim-arm64v8-22.7.1.dev1 version`

the published image is: **crossbario/crossbar:cpy-slim-arm64v8-22.7.1.dev1@sha256:cbe1292c3803404a5702224142b711737644ac4483d0d711b1afb18b3eaf09a9**

![Bildschirmfoto von 2022-07-31 13-56-58](https://user-images.githubusercontent.com/233340/182025315-18090c15-b3a8-4546-86cb-db478423f4c6.png)

-------

note: this is cpy/arm64. the pypy/arm64 build currently has some issue: https://gist.github.com/oberstet/99402f51a7108ec52c87125aceda1f36
