### ISSUE TITLE
Keeping crossbar in Debian bookworm

### ISSUE THREAD

**Issue by bgermann** [crossbario/crossbar#2054]
As the maintainer of the [crossbar Debian package](https://tracker.debian.org/pkg/crossbar) I would like to have your opinion on the following matter:
The current package version based on 21.3.1 [does not build anymore](https://buildd.debian.org/status/fetch.php?pkg=crossbar&arch=all&ver=21.3.1%2Bdfsg-4&stamp=1664558948&raw=0) since (I guess) the python-autobahn update from 22.1.1 to 22.7.1.
I would like to import the current version but that has a lot of new dependencies, including web3 with many transitive dependencies that are not in Debian yet. I do not think I have time to package them all until January (booworm freeze).
Instead I would like to backport the necessary changes so that the package can build with the newer python-autobahn. Can you help me to identify those changes or do you have any other suggestion how to deal with this?

**Comment by oberstet** [comment]
> I would like to import the current version but that has a lot of new dependencies, including web3 with many transitive dependencies that are not in Debian yet. I do not think I have time to package them all until January (booworm freeze).

Debian doesn't have web3? That will have implications not only for users that want crossbar but lots of other packages.

> Instead I would like to backport the necessary changes so that the package can build with the newer python-autobahn.

mmh ... it'll be messy ...

> do you have any other suggestion how to deal with this?

if you insist on both of:

1. latest/new crossbar as debian package
2. web3 (and related) not available as a debian package

then you will have to fork crossbar.

I usually recommend dropping 1., and just `pip install crossbar` into a venv.

personally, I'm also using cpython from a pure upstream source build, but using cpython from debian would work as well. 

https://github.com/crossbario/crossbar/blob/master/docs-cfx/DEVELOPERS.md#building-a-venv

other options for users are docker or snap builds of crossbar, which we publish.

I do understand that doesn't help you:(

how about hiring more hands to package web3 etc? whatever company does really need crossbar, and crossbar as a debian package, might contribute/pay? if they don't need it, or don't want to pay, cool! they still could migrate to our docker or snap binary packages. and not only receive free software source code, but also free binary packages.

**Comment by Bastian-Krause** [comment]
Wouldn't it be possible to split these new dependencies into extras and limit the Debian package to a minimum? Maybe similar to autobahn xbr?

**Comment by oberstet** [comment]
> Wouldn't it be possible to split these new dependencies into extras and limit the Debian package to a minimum? Maybe similar to autobahn xbr?

"possible": sure
"is it a goal": no. because other that autobahn, crossbar is a complete, wrapped, server application, not a library to be linked in many different client application contexts
"will this change": unlikely, as there is no upside, but only work/effort

**Comment by bgermann** [comment]
I have removed crossbar from Debian.
