### ISSUE TITLE
web3 dependency error on install

### ISSUE THREAD

**Issue by josh-yang92** [crossbario/crossbar#2064]
Hi guys,

I am currently trying to install crossbar on docker. It used to work fine before (perhaps a couple of months ago) but all of the sudden I am getting the following error.

`ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
autobahn depends on web3[ipfs]@ git+https://github.com/ethereum/web3.py.git#v6.0.0-beta.9#egg=web3`

I have a very simple requirements.txt file where the crossbar version is 22.6.1. I have also tried doing a simple `pip install crossbar` and the results were the same.

Has anyone seen this before and if so, have you managed to solve it?

Thank you!

**Comment by oberstet** [comment]
This is a limitation of PyPI. However, we publish Docker images, hence just use

https://hub.docker.com/r/crossbario/crossbar/tags?page=1&name=23.1.2

Alternatively, run (in your Dockerfile)  `pip install "web3[ipfs]@ git+https://github.com/ethereum/web3.py.git#v6.0.0-beta.9#egg=web3"`
