### ISSUE TITLE
Publish from an event handler (Python)

### ISSUE THREAD

**Issue by activeperception** [crossbario/crossbar#208]
Hi,

Is it possible to publish an event from within an event handler?

Example:
def doit():
    ....do some work...

   ...notify that work is done by publishing another event...
   (I tried appSession.publish(WORKDONE)...but it does not seem to work)

yield self.subscribe(doit, DOIT)

Thanks,
Raffaele

**Comment by goeddea** [comment]
This is an issue tracker - not a help forum. Please ask questions on the [mailing list](https://groups.google.com/forum/#!forum/crossbario).

In principle: as long as your event handler has access to the session object, you can publish from it.
