### ISSUE TITLE
fix regexp bug in checkconfig.py

### ISSUE THREAD

**Issue by dimddev** [crossbario/crossbar#210]
Hello, 

yesterday I found and resolved one little bug, 

here is the pull request

https://github.com/dimddev/crossbar/commit/0d31e7448ad13fc20eee49eba8170de5229925d3

**Comment by oberstet** [comment]
ah, right. thanks for noticing.

If you want me to merge, we would need https://github.com/crossbario/crossbar/wiki/Contributing-to-the-project

You only need to do that once (and can contribute then), but if you don't want to go through that, I'll fix it without merging, as it is a really small change.

**Comment by dimddev** [comment]
Hello

I trying to download the "Contributor Assignment Agreement" file from the above link but i get 404 error

https://github.com/crossbario/crossbar/raw/master/docs/legal/individual_caa.pdf

I will be happy to support this project

**Comment by oberstet** [comment]
Uups, Link fixed, here https://github.com/crossbario/crossbar/raw/master/legal/individual_caa.pdf

**Comment by oberstet** [comment]
Thanks, we got the CAA! Can you do a clean PR only containing https://github.com/dimddev/crossbar/commit/0d31e7448ad13fc20eee49eba8170de5229925d3, since you other PR contains some noise ..

**Comment by oberstet** [comment]
fixed
