### ISSUE TITLE
debug_traffic Not Accepted As valid transport attribute

### ISSUE THREAD

**Issue by Skully17** [crossbario/crossbar#2112]
I noticed that protocol.py stores the attribute debug_traffic from the config which it uses to log transport information about connected clients. I tried adding the attribute to the config to get this logging but got the unknown attribute error on line 2268 in checkconfig.py.
There is an attribute "debug". I'm not sure if this has a separate purpose or if it's actually what debug_traffic was named and wasn't changed (or something similar)?

**Comment by oberstet** [comment]
well, this is an internal private attribute which shouldn't be exposed to users ..

**Comment by Skully17** [comment]
Oh, ok. in that case, what is the intended way to set this attribute to True?

**Comment by oberstet** [comment]
> what is the intended way

it never was intended for external (user/developer) consumption, but as an internal development flag, a "quick hack", the fact that it is "visible" is simply a consequence of the code base being open source - everything is "visible" in that sense

"making it" a public flag, in the sense of intended for user/developer consumption, in my eyes would require a lot more thought  - which it hasn't gotten, at least not from my side

if you want to use it, change it, do whatever you like, that is totally fine! this is OSS - on your own decision and risk

I personally just don't want to take up even more burden, I consider every "public" API actually more than "an offer", but a responsibility and liability, both initially (give it thourough thought, and over time, keep it going) and I have absolutely enough on my plate, sorry:(

**Comment by Skully17** [comment]
Fair enough, thank you for the explanation :+1: 

The function is very useful as we're trying to reduce the amount of traffic going over crossbar and it's difficult to know if the changes are having much of an effect. I agree tho that if it was not already intended to be public that it's very low priority; fixing the GitHub CI checks is much more pressing for example (which I'm currently working on getting passing so PRs can be merged again :slightly_smiling_face:)

**Comment by oberstet** [comment]
> I agree tho that if it was not already intended to be public that it's very low priority; fixing the GitHub CI checks is much more pressing  ...

absolutely! I agree 100%. and just to conclude here: I _will_ "come back" / help / make "it work" (CI etc). I am using this stuff (Crossbar.io) myself. and I am (still) convinced WAMP in general and Crossbar.io is "done right". I just need to pay bills as well, sort out my life, etc. unfortunately, I don't have gazillions of $$ at my hands, so need to face the world as it is, not as I would like it to be. thanks for your understanding!
