### ISSUE TITLE
Ultra-quick Getting Started

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#214]
The Crossbar.io docs entry page should have an inline "Getting Started" that shows how to do browser based dev with our Crossbar.io public demo instance.

Means:
* **no** Crossbar.io installation at all
* no client library installation at all
* only requires a browser - nothing else

**Comment by goeddea** [comment]
Added section for this. Demands download of two HTML pages to be run locally. Could equally/alternatively be served by us, but that somehow felt less real.
