### ISSUE TITLE
Render API documentation from WAMP API definition

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#215]
Experimental, incomplete code is here:

* https://github.com/crossbario/crossbar/blob/master/crossbar/crossbar/worker/router.py#L1033
* https://github.com/crossbario/crossbar/blob/master/crossbar/crossbar/twisted/resource.py#L494
* https://github.com/crossbario/crossbar/blob/master/crossbar/crossbar/web/templates/cb_schema_overview.html

**Comment by RaitoBezarius** [comment]
Links are dead, can you fix them?

**Comment by meejah** [comment]
- https://github.com/crossbario/crossbar/blob/master/crossbar/worker/router.py#L1033
- https://github.com/crossbario/crossbar/blob/master/crossbar/twisted/resource.py#L494
 - https://github.com/crossbario/crossbar/blob/master/crossbar/web/templates/cb_schema_overview.html
