### ISSUE TITLE
Ask about multi-core features

### ISSUE THREAD

**Issue by oanhnn** [crossbario/crossbar#221]
I have a system consists of 2 routers implement WAMP protocol v2 with PHP ([voryx/thruway](https://github.com/voryx/Thruway)).
These are running on 192.168.1.2:9090 and 192.168.1.3:9090, and using load balance for load sharing.
However, it seems these are working independently of each other. Can you help me config to link them? I tried searching and found that multi-core features of crossbar.
P/S: Sorry about my English ^^

**Comment by mbonneau** [comment]
Hi @oanhnn ,

Right now Thruway does not support load balancing in that way.

If you explain more of what you are looking for (probably in an issue over on voyrx/thruway), I would be glad to help figure out a solution.

Matt

**Comment by oanhnn** [comment]
Thank @mbonneau for reply.

I want link 2 or more routers to respond to multiple clients ( over 100000). 
Eg, I have case: 
client a1 connect with router A and client b1 connect with router B.
client a1 register procedure `com.example.procedure1` and subscribe topic `com.example.topic1`
1. Client b1 want call a procedure `com.example.procedure1` of client a1
2. Client b1 publish to topic `com.example.topic1` and client a1 want receive published message.

I think router A can connect to the router B as one internal client and vice versa.
