### ISSUE TITLE
Support for dynamic HTTP resources

### ISSUE THREAD

**Issue by digulla** [crossbario/crossbar#227]
In a nutshell, I want to build an application using Crossbar.io to connect the components and [Polymer](https://www.polymer-project.org/) to handle the UI part.

The key feature is that the application is built from independent components (that includes HTML snippets, JavaScript and CSS) which discover each other using RPC.

To do this, I need three things:

- A way to add the import for the element to the DOM
- A way to pass the HTML code for the element to the component which serves HTTP requests
- A way to connect the element with the WAMP session

I think the first one is possible by using an RPC call into JavaScript in the client to add the element import to the DOM.

For the second part, I need a way to hook a RPC into the Twisted Web based transport. Basically, I want to be able to register URLs which should invoke methods in my Autobahn component which in turn return HTML code, JavaScript and CSS that Crossbar must send to the client.

For the third item, I need an efficient way to access the connection which triggered the component. With my design, I'm 100% sure that the "open" event has fired since that will trigger the core app which in turn look for registered app components to build the UI.

Example: I have a text editor component. The app connects that with some kind of storage service. It also connects the storage service with a tree UI. The tree allows me to select which file to edit. To create the HTML, the tree component talks to a small piece of JavaScript which registers the Polymer-base tree component in the DOM. This triggers a HTTP request which the tree component intercepts to return the HTML resources (CSS, JavaScript and HTML template) to the browser.

A click on the tree sends a message to the editor to refresh itself with the data from the storage component. Again, the editor needs to send an HTML template to the client.

Lastly, I have a log service. Many components use it as a central place for all log messages. A log UI component connects to it which also needs to be able to intercept HTTP requests.

I've looked at the code in `crossbar/worker/router.py` and I think I could implement the necessary functionality with a bit of help. I think what I need is similar to the `PusherResource`.

In __init__(), I'd register a RPC which allows other components to define URLs they want to serve.

In `render()`, I need to check the registered URLs and call the registered RPC to get the code to send back.

Is that correct?

**Comment by oberstet** [comment]
In general, it would be better to take this to the mailing lists (https://groups.google.com/forum/#!forum/autobahnws, https://groups.google.com/forum/#!forum/crossbario). This is a very broad question, probably asking for feedback on the ideas you scratch, but not a Crossbar.io issue.

My perspective on this is: it's overly complex. Have your UI built as a single-page app with all the HTML/CSS/JS just static files. Polymer works great for this, and it is easy to hook up your Web components via WAMP for *data* communication (e.g. a list UI component can call via WAMP to get it's data and updates via PubSub. The code/css/html for that component *itself* should not be dynamically generated).
