### ISSUE TITLE
'/' should not be mandatory in  Web transport configuration

### ISSUE THREAD

**Issue by sametmax** [crossbario/crossbar#229]
Starting crossbar with this configuration:
```
         "transports": [
            {
               "type": "web",
               "endpoint": {
                  "type": "tcp",
                  "port": 8080
               },
               "paths": {
                  "ws": {
                     "type": "websocket"
                  },
                  "/notify": {
                     "type": "pusher",
                     "realm": "realm1",
                     "role": "anonymous"
                  }
               }
            }
         ]
```

Raises: 

```
 Exception: missing mandatory path '/' in 'paths' in Web transport configuration
```
But you may want '/' to return a 404, or just want to put nginx in front wich will serve '/' himself and proxy pass the rest, or put varnish in front and do the same. Having to put an artificial value here for crossbar to work doesn't seem right.

**Comment by oberstet** [comment]
Technically, there MUST be a Twisted Web root resource. We can make that a 404 though if there isn't any path `/` configured.

**Comment by shaworth** [comment]
I agree with the 404 solution.
