### ISSUE TITLE
Conflicting disclose options

### ISSUE THREAD

**Issue by Paranaix** [crossbario/crossbar#233]
Currently there is no special treatment for the situation where a caller wants to be not disclosed but a calle wants so. In that case the calle gets the identity nevertheless: `if discloseCaller or call.discloseMe:`

This should not be possible. In case a caller wants to hide his identity but a callee requires it, an error should be sent to the caller.

PS: autobahn.wamp.types.RegisterOptions lacks proper documentation. The whole CallDetails stuff should also be included in the guides IMO.

**Comment by goeddea** [comment]
What would be your use case for anonymous callers? Just trying to better understand your need.

**Comment by Paranaix** [comment]
I personally don't need such a thing, but the protocol and autobahn obviously. Notice that this is not a feature request but a bug report.

**Comment by oberstet** [comment]
A bug is something that does not work as expected. Where did you read about what you expect in the behavior you describe?

Anyway: a) it's not finalized in WAMP AP and b) there are 3 entities involved (a caller that wants to hide might still be enforced to be disclosed by the router when the callee requests disclosure). What clients request are just hints to the router.

**Comment by oberstet** [comment]
This is now handled uniformly across subscriptions and registrations. The publisher or caller requests it's disclosure. The router will include the publisher/caller WAMP session ID in the event/invocation forwarded. A subscriber/caller will then receive the originator session ID.
