### ISSUE TITLE
CallDetails not correct

### ISSUE THREAD

**Issue by Paranaix** [crossbario/crossbar#234]
The documentation for autobahn.wamp.types.CallDetails states:
> caller (int) – The WAMP session ID of the caller, if the latter is disclosed.

This is currently not the case with crossbars implementation:
```
else:
    caller = None
```

PS: It might be worth considering adding a `disclosed` attribute to CallDetails. Checking against such an attribute would be much more straightforward. Would require a change in the WAMP protocol though.

**Comment by oberstet** [comment]
@Paranaix I agree: we first need to sort this all out in the spec .. it's clearly underdefined. Who is requesting what, and how is it decided what actually gets disclosed. If you have ideas or proposal, come over to the WAMP repo .. would be welcome!

Fixing the code in Crossbar.io for whatever we come up in the spec is then another task.

**Comment by oberstet** [comment]
This is implemented as it is supposed to work: if the caller requested to be disclosed, disclose the caller. Otherwise, don't disclose. https://github.com/crossbario/crossbar/blob/master/crossbar/crossbar/router/dealer.py#L381
