### ISSUE TITLE
Make it possible to configure a number of spawned worker for the WSGI container

### ISSUE THREAD

**Issue by sametmax** [crossbario/crossbar#236]
Serving Django or Flask with crossbar right now is still not competitive with other solutions such as gunicorn, because you usually need to tweak the number of workers to match your server setup.

You can pass along the thread pool when building the WSGIResource (http://twistedmatrix.com/documents/10.1.0/web/howto/web-in-60/wsgi.html), so it would be a nice touch to be able to configure the number of workers used by the pool in config.json.

**Comment by oberstet** [comment]
Yep, useful. Easy.
