### ISSUE TITLE
Polish up Django tutorial

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#237]
The complete code is here:

https://github.com/crossbario/crossbarexamples/tree/master/django/realtimemonitor

The tutorial is here:

https://github.com/crossbario/crossbar/wiki/Adding-Real--Time-to-Django-Applications

===

* review the tutorial (try it) and tutorial text (english)
* polish up the code syntax high-lighting etc

**Comment by goeddea** [comment]
also: 
is there django newsletter/user group? - look for places to promote the article
