### ISSUE TITLE
implement pattern_based_subscription in broker

### ISSUE THREAD

**Issue by tardyp** [crossbario/crossbar#238]
If I read the code correctly, only exact matching is implemented in broker.

https://github.com/tavendo/WAMP/blob/master/spec/advanced.md#pattern-based-subscriptions
This would be important feature for buildbot.

**Comment by oberstet** [comment]
Yep, correct. There are 2 levels of pattern-based subscriptions in the WAMP AP:

* prefix matching
* wildcard matching

You need both?

**Comment by tardyp** [comment]
I need wildcard matching.

We have not identified yet usecases for prefix matching

**Comment by oberstet** [comment]
Ok. The relevant part of the spec is https://github.com/tavendo/WAMP/blob/master/spec/advanced.md#wildcard-matching, and it provides wildcards for _whole_ URI components.

This feature isn't hard (maybe 3-4 days work for me incl. testing and docs).

**Comment by tardyp** [comment]
FYI, code in buildbot implementing a hacky workaround.

https://github.com/tardyp/buildbot/commit/cfec7e7fd7dcce95f93e83c0e294591a53ed3235#diff-70e45c760cd25c5734d4cd2578cc59f8R27

**Comment by oberstet** [comment]
Oh, I see;) this is "creative". But it seems you are already quite deep inside buildbot .. cool.

**Comment by oberstet** [comment]
implemented on trunk
