### ISSUE TITLE
Cookie

### ISSUE THREAD

**Issue by drtzack** [crossbario/crossbar#242]
Can't find any doc for Cookie. Is there any example?

**Comment by oberstet** [comment]
Unfortunately not. We need to document:

* cookie tracking of WAMP connections
* cookie based WAMP authentication

**Comment by oberstet** [comment]
there are now (draft) docs for this:

* http://crossbar.io/docs/Cookie-Tracking/
* http://crossbar.io/docs/Cookie-Authentication/
