### ISSUE TITLE
Generate the list of topics

### ISSUE THREAD

**Issue by Vayel** [crossbario/crossbar#245]
It would be interesting for documentation purposes to be able to generate the list of all topics automatically. The command would return something like that:
<table>
    <tr>
        <td>Topic</td>
        <td>Type</td>
        <td>From</td>
        <td>To</td>
    </tr>
    <tr>
        <td>com.app.rpc</td>
        <td>RPC</td>
        <td>module.file1.Class</td>
        <td>module.file2.Class</td>
    </tr>
    <tr>
        <td>com.app.pubsub</td>
        <td>PubSub</td>
        <td>module.file1.Class</td>
        <td><ul><li>module.file2.Class</li><li>module.file3.Class</li></ul></td>
    </tr>
</table>

That command could also list the arguments of the destinations, by:

* using the `inspect` module
* doing something like Sphinx

I don't know if it's possible or even judicious. With components registered in the `config.json` file, it probably is. But what about manually-launched components?

**Comment by Paranaix** [comment]
The WAMP protocol already has a feature called reflection exactly for this usecase: https://github.com/tavendo/WAMP/blob/master/spec/advanced.md#predefined-meta-procedures

As WAMP components can be written in any language, can connect and disconnect and are in general only loosely coupled generating a documentation can prove difficult.

**Comment by Vayel** [comment]
Thanks!
