### ISSUE TITLE
Add generic Twisted Web resource as Web service

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#247]
Crossbar.io has a configurable Web transport (for WAMP routers) which is able to host static files, CGI and also WSGI Python apps on Web subpaths (`"/foobar/some_wsgi"`).

http://crossbar.io/docs/Web-Transports-and-Services/

It would be nice to be able to serve and configure *any Twisted Web* resource on a subpaths. Like e.g. serving a Klein-based HTTP endpoint on `/foobar/some_klein`.

This is trivial, since we don't need to create a Twisted resource even - but merely import it from the app: 

```
app = Klein()
resource = app.resource()
```

All we need in Crossbar.io is import `resource` and hook that into the Twisted Web resource tree served.

**Comment by meejah** [comment]
Might be nice to include Cyclone.io apps as well since they're also Twisted based (they'd be similar to klein to support, I think).

**Comment by oberstet** [comment]
My problem with this issue (and already the wsgi feature): it exposes a public "API" (a feature supported via config) that depends on Twisted. What if we rewrite Crossbar.io in a different language? Ideally we want to have only features that would allow that.
