### ISSUE TITLE
Cache control on static web resources

### ISSUE THREAD

**Issue by taion** [crossbario/crossbar#251]
Currently static resources are served via `t.w.s.File`. This doesn't set any response headers related to caching, which means that most browsers end up caching the static resources indefinitely.

In general it'd be nice to have some non-infinite cache timeout on files. Especially when running with `--debug` it'd be ideal to disallow caching static assets by the browser entirely.

**Comment by oberstet** [comment]
Yes, I agree. Cache control headers would be useful ..

**Comment by taion** [comment]
What do you think is an appropriate default cache timeout? Flask uses 12 hours by default for static assets (even when running in debug mode, apparently, which I wasn't previously aware of).

**Comment by oberstet** [comment]
@taion I sane finit default seems to be better than infinite. But we could do even better I think (make it configurable)

Static file serving resources are created here:

* https://github.com/crossbario/crossbar/blob/master/crossbar/crossbar/worker/router.py#L660
* https://github.com/crossbario/crossbar/blob/master/crossbar/crossbar/worker/router.py#L870

Config for static service is checked here:

* https://github.com/crossbario/crossbar/blob/master/crossbar/crossbar/common/checkconfig.py#L594

Settings cache headers is done like this:

* https://github.com/tavendo/AutobahnPython/blob/master/autobahn/autobahn/twisted/longpoll.py#L589

We could have an option that is an integer: If negative, no caching at all. If 0, infinite caching. Else, caching time in seconds or what. Probably steal ideas of what Nginx or Apache allows here ..

**Comment by taion** [comment]
That was my plan. I was actually going to go with 0 for no caching (cache for 0 seconds) and negative (or maybe null) for infinite duration caching.

I believe it's considered best practice to set both the `Expires` and `Cache-Control` headers, though.

I'll get a PR up when I get a chance.

**Comment by oberstet** [comment]
@taion awesome! yeah, I think your value mapping makes more sense (less suprise for users). `null` instead of negative is what I like even more. and when cache value is missing in the config, we can use a sane finite default (like some hours or what)

**Comment by shaworth** [comment]
I like where this is headed.  I would argue that a missing value should
result in no caching.  IMHO this is less likely to trip up new developers.

**Comment by taion** [comment]
I don't really care that much what the default is. I think 12 hours is reasonable, because that's what Flask does. Using 0 would be dangerous in production, but you should probably use nginx or something to serve static assets anyway. The unlimited caching is just causing issues for me right now.

**Comment by taion** [comment]
Thanks for merging!
