### ISSUE TITLE
Way to check if a process is really a crossbar node

### ISSUE THREAD

**Issue by Paranaix** [crossbario/crossbar#253]
It sometimes happens that crossbar exists uncleanly and leaves the *.pid* file. This would actually not be a big deal if not other unrelated processes can get the same PID resulting in crossbar unable to restart as it assumes that there is still a node running (this already occured multiple times to me!). An user then has to remove the *.pid* file manually.

To fix this issue I suggest to implement a way to check whether a process is really a crossbar node.
https://github.com/giampaolo/psutil might provide the required functionality.

**Comment by herm** [comment]
This is a big problem when trying to start crossbar using systemd. After an unclean shutdown crossbar sometimes starts and sometimes doesn't start. As the order in which services are started is not fixed  sometimes a service with the same pid crossbar had last time is already running.  

Test case: 
```
echo '{"pid": 1}' > .crossbar/node.pid 
crossbar start
Crossbar.io is already running from node directory /root/crossbar-apps/.crossbar (PID 1).
```

**Comment by Paranaix** [comment]
After considering this a bit more I think we also need a way to check whether a process is a SPECIFIC crossbar node. This need arises if we got multiple nodes running on the same host. Maybe using some form of IPC is maybe better as we might need it for other features as well.

**Comment by oberstet** [comment]
This is how it works right now: upon startup, Crossbar.io checks if there is a PID file. If there is, it checks if there is a process with PID equal to the one written in the PID file. If there is, it assumes that Crossbar.io already runs.

Is there a way to get the executable of a process running under a given PID? This would allow us to improve robustness.

**Comment by meejah** [comment]
/proc/PID/exe links to the executable running, but that's not cross-platform of course. And this will just be the python interpreter. ``psutil`` includes ability to examine the command-line -- the second arg should be the path to the crossbar script. I'm not sure how cross-platform this may be, though.

**Comment by hawkowl** [comment]
@meejah can we close this, it seems to work on trunk?

**Comment by meejah** [comment]
Yes, this can be closed I think (for the record, #322 was introduced by this enhancement, but that was fixed already at least for the linux platforms I tested).

**Comment by KrishnaPG** [comment]
Facing this problem in the latest docker image:

![image](https://cloud.githubusercontent.com/assets/4610831/16520340/1e271512-3fad-11e6-81bb-7a40ed32b34d.png)

**Comment by sebastianwahn** [comment]
I found a workaround for the problem occurring in Docker:

If you use docker-compose and `docker kill` the containers, the problem with the claimed PID is occurring. Instead, you should use `docker-compose down` to stop your environment. This will gracefully stop the crossbar.io server and the node.pid file is removed properly.
