### ISSUE TITLE
Shutdown node upon worker exit

### ISSUE THREAD

**Issue by Airborn22** [crossbario/crossbar#257]
Hello,

I've recently created an upstart script which starts crossbar for me and restarts it if necessary. After the service is started I see 4 processes running:
* `sudo -u crossbar /home/crossbar/pypy-venv/bin/crossbar start --cbdir /home/crossbar/hello/.crossbar/ --logdir /home/crossbar/hello/.crossbar/log`
 * This is the command started by upstart
* `crossbar-controller`
* `crossbar-worker [router]`
* `/usr/bin/node hello.js`

I was playing around and tried to kill the processes to see if everything is restarting and I noticed a few things:
* The `sudo ...` command was started again after I killed it. I guess upstart is keeping track of this but I think it tries then to start crossbar again which is already running.
* After killing `crossbar-controller` it is restarted but a new instance of `/usr/bin/node hello.js` appeared.
* After stopping the service everything is killed but each instance of `/usr/bin/node hello.js` was kept running.
* After killing `crossbar-worker [router]` it was not started again so the application died.
* And `/usr/bin/node hello.js` was not started as well but the application was still functioning after that.

The upstart script I'm using:
```
description "Start script for the crossbar hello example"
author "Alex Major"

start on startup
stop on shutdown
respawn

exec sudo -u crossbar /home/crossbar/pypy-venv/bin/crossbar start \
	--cbdir /home/crossbar/hello/.crossbar/ \
	--logdir /home/crossbar/hello/.crossbar/log
```

There is a pypy virtualenv under `/home/crossbar/pypy-venv`. I'm running crossbar from there. I don't know if this upstart method is correct but it would be good to have a solution which solves the issues above.

What I want to achieve is if I run crossbar in production then all the services will run forever. If a worker dies for example then it is getting restarted and so on.

**Comment by meejah** [comment]
Recently, shutdown behavior was improved (see #294) -- does this work more nicely now for your use-case? (This should kill off the workers nicely if crossbar itself is killed).

As to the Router process: I believe if the Router worker dies for any reason, crossbar should probably itself exit if it can't successfully restart the router process. A quick test indicates that it just logs...

**Comment by oberstet** [comment]
I think for CB in standalone mode, the right behavior is to: start workers as from local config, when any worker exits uncleanly or with error status code, then the controller will stop all workers and exit with error itself. when all workers have closed (cleanly and successfully), the controller exit successfully.

**Comment by gerrat** [comment]
I have what I *think* is a related issue (but I'm not positive).

First, this happens (will come back to this):
`Aug 27 13:27:11 ubuntu kernel: [242633.229653] traps: pypy[20915] general protection ip:7fa4f7b7987b sp:7fff9b5fcd50 error:0 in libpypy-c.so[7fa4f57c7000+298d000]`

This causes the following:
```2015-08-27 13:27:11-0400 [Controller      1] Worker 12: Process connection gone (A process has ended with a probable error condition: process ended by signal 11.)
2015-08-27 13:27:11-0400 [Controller      1] Error invoking onClose():
2015-08-27 13:27:11-0400 [Controller      1] Traceback (most recent call last):
2015-08-27 13:27:11-0400 [Controller      1]   File "/opt/pypy-2.6.0-linux64/site-packages/autobahn/wamp/websocket.py", line 80, in onClose
2015-08-27 13:27:11-0400 [Controller      1]     self._session.onClose(wasClean)
2015-08-27 13:27:11-0400 [Controller      1]   File "/opt/pypy-2.6.0-linux64/site-packages/crossbar/router/session.py", line 382, in onClose
2015-08-27 13:27:11-0400 [Controller      1]     self._router.detach(self)
2015-08-27 13:27:11-0400 [Controller      1]   File "/opt/pypy-2.6.0-linux64/site-packages/crossbar/router/router.py", line 115, in detach
2015-08-27 13:27:11-0400 [Controller      1]     raise Exception("session with ID {} not attached".format(session._session_id))
2015-08-27 13:27:11-0400 [Controller      1] Exception: session with ID 42046597602599 not attached```

At this point, my "Container" (Worker?) is still running, looping and trying to publish events to subscribers, but every "self.publish" just fails.  Does this mean that the router worker has died?  If so, it would be helpful if crossbar restarted it (as meejah mentioned).

For the signal 11/memory issue that caused this, I seem to have a slow memory leak somewhere, but can't seem to nail down what is causing it (I am using pypy, so will try to see if switching to CPython fixes anything).

**Comment by oberstet** [comment]
@meejah > I believe if the Router worker dies for any reason, crossbar should probably itself exit if it can't successfully restart the router process. A quick test indicates that it just logs...

yeah, I believe this should be generally the case: as all processes but the controller are spawned by the controller, any spawned process exciting

* either "only when uncleanly" or
* "uncleanly, with sucess and error"

should make the controller shut down all other processes and itself also. probably we can reuse code here .. the shutdown sequence. Gonna change the issue title to reflect that.

**Comment by meejah** [comment]
@gerrat That looks like probably a separate issue (or two). It looks like you've found a (probable) bug in pypy (the fault) but also a way to make crossbar believe a disconnecting session isn't actually connected (could be related to the pypy fault, but maybe not). If you have any way to repeat the latter one, please file a separate issue with any further details.

**Comment by oberstet** [comment]
Ok, I have tested killing any one of 3 processes running with a CB node and a router and a container worker.

In each case, the remaining processes take notice and exit.

Moreso, in all case but killing the controller, a sane log output is produced.

So this is done.

**Comment by Airborn22** [comment]
Thank you guys! :)
