### ISSUE TITLE
ImportError: No module named pkg_resources

### ISSUE THREAD

**Issue by vchav73** [crossbario/crossbar#260]
After following the installation instructions for Linux at the crossbar.io web site I tried creating a hello application but got the error below. Seems I'm missing a Python module? I'm running on a CentOS 6 installation which has both Python 2.6 and 2.7 installed. Anyone seen this before?

[syncalt@Analytics ~]$ crossbar init --template hello:php --appdir www/presentation/hello
Traceback (most recent call last):
  File "/usr/bin/crossbar", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
[syncalt@Analytics ~]$

**Comment by goeddea** [comment]
Yes, you're missing a Python module. `pkg_resources` is part of `setuptools` - so it should be easiest to just install these again. 

Try 

```sh
curl https://bootstrap.pypa.io/ez_setup.py | python
```

(as per this [StackOverflow answer](http://stackoverflow.com/a/10538412/1077987))
