### ISSUE TITLE
Unable to test PostgreSQL access from Python/Twisted-based WAMP example

### ISSUE THREAD

**Issue by funnydoggie** [crossbario/crossbar#271]
Followed the guide: http://crossbar.io/docs/Database-Programming-with-PostgreSQL/ using psycopg2 as database driver.
Although that guide doesn't mention how to run the example, or how to assemble the source files from working with Crossbar I assume I need the three files: server, html and config.json and that I make a  directory structure from other crossbar examples for remote procedures.

I tried both twisted adbapi and txpostgres (I'd prefer txpostgres so database connections are in "asynchronous mode").
What I tried and the directory structure I created:
created directory ~/hello with sub-directories .crossbar and web
- saved config (listed at end of article) as ~/hello/.crossbar/config.json
- saved server ~/hello/hello.py
- saved client ~/hello/web/index.html
In the ~/hello folder, I try /opt/crossbar/bin/crossbar start --cbdir ~/hello/.crossbar, it terminates "ImportError: No module named txpostgres" and with adbapi example, "No module named psycopg2"
Tried both as $home user and sudo su, but same error.

What I double-checked:
psycopg2-2.6 (latest) installed from source and all tests run successfully. Pip install txpostgres, tested fine txpostgres examples of module usage from http://txpostgres.readthedocs.org/en/latest/usage.html
It's like my crossbar binary can't see that I've installed psycopg2 and txpostgres

**Comment by oberstet** [comment]
moved to https://github.com/crossbario/crossbarexamples/issues/24
