### ISSUE TITLE
Authenticator based on path

### ISSUE THREAD

**Issue by Paranaix** [crossbario/crossbar#274]
Currently one can only define one (dynamic) authenticator per authmethod per transport. This means, that e.g if one needs two different authenticators (which do slightly different things) for two different kind of peers (e.g users and services), one has to set up another transport on another port. So peers which try to authenticate against e.g `localhost:8080` are dealt with by `AuthenticatorA` and peers why try to authenticate against `localhost:9090` are dealt with by `AuthenticatorB`.

While its currently possible to achieve such authentication mechanisms as shown (another approach would be to deal with both kind of peers in one authenticator), its not really nice. Instead I propose that one can configure authenticators based on the path. So `localhost:8080/user` and `localhost:8080/service` would delegate authentication requests to different authenticators.

I hope this makes sense. If not, feel free to ask.

**Comment by oberstet** [comment]
You specific example is already possible today: just define a router worker with a transport of type "web", having 2 path services of type "websocket" configured on 2 paths:

```json
{
   "workers": [
      {
         "type": "router",
         ...
         "transports": [
            {
               "type": "web",
               ...
               "paths": {
                  ...
                  "ws1": {
                     "type": "websocket",
                     "auth": {
                        "wampcra": {
                           "type": "dynamic",
                           "authenticator": "com.example.authenticate1"
                        }
                     }
                  },
                  "ws2": {
                     "type": "websocket",
                     "auth": {
                        "wampcra": {
                           "type": "dynamic",
                           "authenticator": "com.example.authenticate2"
                        }
                     }
                  }
               }
            }
         ]
      }
      ...
   ]
}
```

**Comment by oberstet** [comment]
@Paranaix it's unclear where the `localhost:8080/user` URL part `/user` would come from. since eg with RawSocket WAMP transports, there is no initial HTTP opening handshake, which could carry a URL part.
