### ISSUE TITLE
Exceptions when constructing an ApplicationSession are silently ignored

### ISSUE THREAD

**Issue by rafzi** [crossbario/crossbar#276]
We have configured a workers.components with type class and this class is deriving from ApplicationSession.

Our constructor may throw if some essential initialization fails.

Crossbar seems to catch all exceptions and ignore them. Just like it never happened.

I would expect that the crossbar instance closes after outputting the exception message.

**Comment by meejah** [comment]
I have repeated this; simply throwing ``RuntimeError`` from ``__init__`` completely swallows the error; this should be logged.

Currently, Crossbar itself doesn't exit if a worker exits, but it should be logging details about the worker exiting.

Exiting is kind of tricky: I suspect different use-cases would require different policies about having crossbar exit on errors. If you're running many workers and one of them exits/crashes, what should happen? Crossbar itself runs one or more workers as well, so either these have to be treated as "special" processes, or it's always the case that "1 of N" processes has errored, where N > 1. Perhaps the process should be restarted? (How many times?) etc.

What about adding an ``essential=true/false`` configuration option to workers (defaulting to "true"?) meaning to exit crossbar if that process dies. Would probably also want ``retries=N`` or similar, too.

**Comment by meejah** [comment]
For now, you can add ``"debug_wamp": true`` to your component's "transport" option to get exceptions like this printed out/logged.

**Comment by meejah** [comment]
If a transport fails to start (e.g. something is already listening on a port) then crossbar exits with an error -- seems like this should fall into the same category and just exit if we can't construct an application component...

**Comment by oberstet** [comment]
@rafzi this works now. please see the example here https://github.com/crossbario/crossbarexamples/tree/master/containers/failures#class-instantiation-failed-failure-3
