### ISSUE TITLE
Can't start crossbar as non-root user

### ISSUE THREAD

**Issue by Paranaix** [crossbario/crossbar#277]
This issue comes from `pkg-resources` and I'm not really sure whether this is a bug or by design, but since the recent crossbar versions depend on `pkg-resouces` I can't start crossbar as non-root any longer:

``` python
Traceback (most recent call last):
  File "/usr/local/bin/crossbar", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1367, in <module>
    class MarkerEvaluation(object):
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1371, in MarkerEvaluation
    'python_full_version': platform.python_version,
AttributeError: 'module' object has no attribute 'python_version'
```

If I start crossbar as root though, everything works fine.

**Comment by meejah** [comment]
It looks to me like something broken with your distutils/setuptools install, perhaps?

The "crossbar" script itself is autogenerated by setuptools when you run "pip install crossbar" or "python setup.py install".

**Comment by Paranaix** [comment]
A colleague of mine had the same problem, however he could resolve it after reinstalling crossbar using pip (we're both have the repo on our hd, so i assume, that yonder reinstall simply upgraded some dependencies). I already tried to update crossbar and I already tried to update setuptools directly, both didn't have any effect. Currently im setting up a fresh install, to make sure I don't have any corrupted packages or something.

**Comment by oberstet** [comment]
FWIW, I haven't seen this before. I don't think it's related to Crossbar.io code itself, but some installation issue. Having a plain vanilla Python with only pip and virtualenv around, and then installing Crossbar.io only into virtualenvs is what I often do.

**Comment by oberstet** [comment]
Crossbar.io starts as normal user and as root. Can't reproduce ..
