### ISSUE TITLE
content-based publish/subscribe middleware

### ISSUE THREAD

**Issue by dhaowoods** [crossbario/crossbar#290]
Is wamp fall into category of topic-based publish-subscribe middleware? how is different from content-based publish/subscribe middleware like [padres](http://msrg.utoronto.ca/projects/padres/index.php) and [IBM Gryphon](http://www.research.ibm.com/distributedmessaging/gryphon.html) ?

**Comment by goeddea** [comment]
This is an issue tracker, not a forum for general questions. 

WAMP is both PubSub & **routed** RPCs - see http://wamp.ws/why
