### ISSUE TITLE
authenticate() takes exactly 3 arguments (2 given) (dynamic)

### ISSUE THREAD

**Issue by frank-social** [crossbario/crossbar#293]
autobahn.js gives the Python Authenticator just 2 arguments.

def authenticate(realm, authid, details):

is not calling because autobahn.js give just 2 arguments.

When I do this: def authenticate(authid, details):

It works. But not right. In authid is the realm in details is the username.

In my Opinion the autobahn.js send to les paramaters to the server.

**Comment by Paranaix** [comment]
Could you please provide us with more concrete infos? Especially, what are you doing exactly, how is crossbar configured and the part of the code which invokes above method.

**Comment by frank-social** [comment]
Hallo,

I use your standard functionality what I got from your dynamic example.

I also have cloned you git example and let it run. Same error.

I use Python 2.7 on Mac but by the way I try it today in my Windows Virtual Machine just in case that the Environment is the problem. But I don’t think so.

Thank Frank


![image](https://cloud.githubusercontent.com/assets/9342588/6996693/d3788ec6-db8d-11e4-9881-4a340a81e644.png)

**Comment by goeddea** [comment]
Just checked with current version of the example (`authenticate/wampcradynamic/python`) and this works (at least the authentication part does). Need more information to be able to replicate the problem.

**Comment by frank-social** [comment]
I did it too. But i got the same error.

>>> print(sys.version)
2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

When I use Windows I got an other error. But it pass the function.
So it looks like is an Mac OS X Issue

**Comment by oberstet** [comment]
could you attach the output from `crossbar version`?

**Comment by frank-social** [comment]
Yes of course

rossbar.io                  : 0.9.12-2

  Autobahn|Python            : 0.9.4-2
    WebSocket UTF8 Validator : autobahn
    WebSocket XOR Masker     : autobahn
    WAMP JSON Codec          : stdlib
    WAMP MsgPack Codec       : -
  Twisted                    : 14.0.2-KQueueReactor
  Python                     : 2.7.9-CPython

OS                           : Darwin-14.0.0-x86_64-i386-64bit
Machine                      : x86_64

**Comment by oberstet** [comment]
Your Crossbar.io is too old (does not have the 3rd parameter). Please do `pip install --upgrade crossbar`

**Comment by frank-social** [comment]
I test it today on my Development system an it's running. Tomorrow I'll try it on the pre-production System what is running under windows.

Thank you very much. It was a key component for me.
