### ISSUE TITLE
No 32 bit version is specified in package manifest

### ISSUE THREAD

**Issue by basz** [crossbario/crossbar#296]
While installing crossbar from a deb package I run into the following issue:

Failed to fetch http://package.crossbar.io/ubuntu/dists/trusty/InRelease  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)

Apparently my system tries to install the 32 bit version (don't know why as I have 64 bit) and that is not specified in release file.

http://askubuntu.com/questions/432834/how-to-serve-deb-files-compiled-for-amd64-without-receiving-errors-that-i386-d

Please note that installation completes successfully, but that this error/warning ripples through to nightly emails and failing with ansible playbooks.

**Comment by oberstet** [comment]
@hawkowl could you have a look?

**Comment by hawkowl** [comment]
Hi @basz I've added the i386 release file (but no packages, since we're only supporting 64bit), could you verify that this is working fine now?

Multiarch systems will download both amd64 and i386 release files, so, I guess we just need to have both there, even if we just have 64bit packages :)

**Comment by basz** [comment]
verified! thanks
