### ISSUE TITLE
Call timeouts and canceling of calls

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#299]
1. timeout (call|options.timeout > 0)
2. interrupt invocations (INTERRUPT message)
3. active cancel (CANCEL message)

**Comment by oberstet** [comment]
connected:

* #1382
* #1377

**Comment by noisyboiler** [comment]
Hiya @oberstet 
Can we have an update on this issue please as it has been open for some time.
I'm specifically interested in whether Crossbar now implements the [call timeouts](https://wamp-proto.org/_static/gen/wamp_latest.html#call-timeouts).
Thanks

**Comment by oberstet** [comment]
@meejah do you happen to know where we are on this? I seem to remember that you worked on call timeouts in the past? not sure .. maybe I'm mixing it up

**Comment by oberstet** [comment]
also see https://github.com/crossbario/crossbar/pull/1694

**Comment by meejah** [comment]
We have both timeouts and (active) cancelling now, so I'm closing this. If there are bugs in the implementations probably new tickets are better anyway.
