### ISSUE TITLE
Crossbar Doesn't Send Subscribers Match Request To Authorizor

### ISSUE THREAD

**Issue by motosota** [crossbario/crossbar#304]
With dynamic authorization configured, the authorization service doesn't seem to receive the requesting subscriber's match request (prefix / wildcard).

It seems it would be useful for the authrorizor to allow / deny based on this together witht the uri.

Checked on the issues list and this was the closest https://github.com/crossbario/crossbar/issues/280 but is for static authorization

**Comment by oberstet** [comment]
Duplicate of https://github.com/crossbario/crossbar/issues/430
