### ISSUE TITLE
crossbar version does not show masker/validator version

### ISSUE THREAD

**Issue by rtp-calpoly** [crossbario/crossbar#306]
I am installing autobahn and crossbar directly from the repository given in the installation guide for Ubuntu 14.04.2 LTS (http://crossbar.io/docs/Installation-on-Ubuntu/). The problem that I have is that just after installation, I check the version for crossbar and no XOR masker and/or UTF8 validator appear as installed:

    Crossbar.io package versions and platform information:
    Crossbar.io                  : 0.10.4
    Autobahn|Python            : 0.10.3
        WebSocket UTF8 Validator : ?
        WebSocket XOR Masker     : ?
        WAMP JSON Codec          : stdlib
        WAMP MsgPack Codec       : msgpack-python-0.4.6
    Twisted                    : 15.1.0-EPollReactor
    Python                     : 2.7.8-PyPy

    OS                           : Linux-3.16.0-34-generic-x86_64-with-debian-jessie-sid
    Machine                      : x86_64

What am I doing wrong?

**Comment by oberstet** [comment]
You aren't doing anything wrong .. that's a non-critical, "display issue": reanming issue

**Comment by rtp-calpoly** [comment]
Ok, thanks for the quick reply. Anyhow, when the same thing happens during the installation in a virtualenvironment, I just have to install wsaccel and ujson in order to "fill those blanks". I try to do the same with the Ubuntu installation (this is, I try to install wsaccel and ujson through "sudo pip install") but crossbar does not seem to find those dependencies).

Any ideas about how to solve this? Might I have to recompile by myself the whole crossbar application after satisfying those dependencies locally?

**Comment by oberstet** [comment]
In short: if you run under PyPy (as your output above suggest): using ujson or wsaccel will likely **decrease performance** - yes, I've measured this (which is the reason these packages are only installed when running under CPython). Just leave it as is. That's just fine.

**Comment by rtp-calpoly** [comment]
Ok, thank you so much for the help.
