### ISSUE TITLE
underscore not allowed in path

### ISSUE THREAD

**Issue by rejoc** [crossbario/crossbar#308]
regular expression used to match a path does not allow underscore (nor - or $...). So the following configuration fails for `download_file`.
```
    paths:
      /: {directory: ../web, type: static}
      ws:
        auth:
        type: websocket
        debug: true
      download_file:
        type: wsgi
        module: wsgi_calls
        object: download_file
```

`Exception: invalid value 'download_file' for path in Web transport configuration - must match regular expression ^([a-z0-9A-Z]+|/)$`

**Comment by oberstet** [comment]
works as designed

**Comment by rejoc** [comment]
So is there a way to respond to an url such as `http://myhost/download_file/12345` ?

**Comment by rejoc** [comment]
the doc (http://crossbar.io/docs/Web-Transports-and-Services/) says "The keys in paths MUST be proper (atomic) components from the HTTP URI scheme"

_ - or $ are authorized characters in the path of an HTTP URI. Aren't they ?
