### ISSUE TITLE
add path type "call"

### ISSUE THREAD

**Issue by rejoc** [crossbario/crossbar#309]
a path type `call` (or `rpc`) would issue a wamp `call` to a remote procedure.
Parameters to the rpc would be at least the environment variable (in the same way we get it on a wsgi call) and results would be returned either through a dict containing status, headers and payload or by sending progressive results (first one could be status+headers, then the raw data in multiple calls)  

```
"paths": {
   "/": {
      "type": "static",
      "directory": ".."
   },
   "ws": {
      "type": "websocket",
   },
   "my_function": {
      "type": "call",
      "procedure": "my.remote.procedure",
      "role": "backend"
   }
}
```

A browser calling http://localhost/my_function?x=1&y=2
would get result from a rpc call to my.remote.procedure...

**Comment by meejah** [comment]
Does this help for your use-case?

http://crossbar.io/docs/HTTP-Bridge-Services/

**Comment by rejoc** [comment]
No, in my case it would be something like this

```
+---------+                   +----------+                        +--------------+
|         | --> http --(1)--> |          | ---> wamp call --(2)-> |              |
| browser |                   | crossbar |                        | guest worker |
|         | <---- (4)-------- |          | <-------(3)----------- |              |
+---------+                   +----------+                        +--------------+

```
1: the browser send an http request 
2: this request is forwarded to a rpc in a guest worker
3: the guest worker answsers
4: crossbar forward the answer

**Comment by meejah** [comment]
That looks nearly exactly like the "caller" endpoint from the link I pointed out above. (1) would be a POST of ``application/json`` containing ``procedure`` and ``args`` keys (just plain HTTP). This would call whatever is registered for that procedure (i.e. (2) above) and the results from (3) are returned as JSON in (4). No websockets (except between crossbar and the guest, depending on the config).

**Comment by rejoc** [comment]
Thanks Meejah for your explaination.

What I need is mainly to use crossbar as a web server for a few urls. So (1) can be a HTTP GET and (4) can be anything from a dynamic web page or plain text to a raw file (and xls file for example).

My exact use case is the following : 
I'm rewritting an application using angularjs + autobahn on websockets (used to be angularjs + turbogears on http). This application also generates files and send the url to the file by email. The file is stored in a database and the url contains a uid for the file.
Currently, I've written a WSGI application that retreive the file and send it to the user. It works great BUT... the wsgi application is "linked" to crossbar and I'd like to keep crossbar as a pure router and have all applicative code guest workers whether (calls, subscribes) I use through websockets or code to answer http calls.

**Comment by oberstet** [comment]
already implemented

**Comment by rejoc** [comment]
Great :-) Can you give me any pointer ?

**Comment by rejoc** [comment]
Ok, thanks. I still can't see in the configuration file how you associate an url with the procedure uri to be called. And then how you can return something that does not fit in a json structure.

As I wrote before, in my use case, the urls already exist, are HTTP/GET and must return files (binary data, the content-type must be specified for each file).

**Comment by oberstet** [comment]
@rejoc the docs are here: http://crossbar.io/docs/HTTP-Bridge-Services/ => section "HTTP Caller"

**Comment by rejoc** [comment]
Thanks Tobias,

All the examples I saw in the doc are about doing an HTTP/POST to trigger a call to a procedure named in the POST message. 

My scenario/need is more : 
 - send a HTTP GET (for example: wget http://myhost/download/f1&a=1) to crossbar
 - crossbar has a path to `download` to a caller and this caller has a  predifined procedure uri 
 - crossbar analyses the url and get the paramters as `args=['f1']` and `kwargs={'a': '1'}`
 - crossbar calls the procedure uri
 - the result of this call is the result of the wget... 

Maybe, a default content-type could be also specified in the caller path definition or the result of the called procedure could have specific items like `headers`, `body`, ... that would be used to build the final answer.
Of course, it could also work for POSTs. There are cases where you can't change the way HTTP requests are made (request made from existing applications, from other "manufacturers") so you can't always add specific items to the requests.

I've had a look to the code (CallerResource, _CommonResource, etc). I will try to make changes to fit my needs as an example

We could then use crossbar as a plain web server :)

**Comment by oberstet** [comment]
Well, the REST bridge works fine as is. I dont see much value in changing POST to GET

**Comment by rejoc** [comment]
I went through all the examples here https://github.com/crossbario/crossbarexamples/tree/master/rest but could not find a way to this : 
do a `wget http://host/photo/1234` (a HTTP GET call) and have it to call a wamp procedure `my.procedure` with `1234` as the fisrt parameter and get the file content : a jpeg image.
Please give me some hints.

The issue is not why changing a POST to a GET. Suppose you have a device or an application you can't change (you did not write it/don't have the code...) that issues GETs (and you can't change anything in those GETs) and want to know if a wamp/crossbar application could answer those GETs. 
There is a way that works : setup a WSGI application and plug it to crossbar. But, as I said before, it links the WSGI application to the crossbar router and so you loose the modularity of guest workers distincts from the router. 
Is there a way to have a WSGI application running in a guest worker ?

**Comment by oberstet** [comment]
@rejoc > Is there a way to have a WSGI application running in a guest worker ?

Sure. But you can't have it on the same port as WAMP routing then.
