### ISSUE TITLE
Npm throws an illegal instruction exception

### ISSUE THREAD

**Issue by shaworth** [crossbario/crossbar#313]
There is a bug in the binaries provided by the official node download site.  The solution is to use this binary instead: http://node-arm.herokuapp.com/  This works on the R Pi B+.  I would be happy to amend the crossbar.io docs, but I can't find the sources.

**Comment by meejah** [comment]
Thanks for the report, the docs are in a separate repository: https://github.com/crossbario/crossbarwww

**Comment by oberstet** [comment]
@shaworth is this still relevant?
