### ISSUE TITLE
Details passed to wamp.session.on_join subscribed asyncio method have bytes keys

### ISSUE THREAD

**Issue by meejah** [crossbario/crossbar#316]
As reported by @terrycojones in the Autobahn|Python repository [ticket 338](https://github.com/tavendo/AutobahnPython/issues/388):

If I have a python2 router session that subscribes to `wamp.session.on_join`, the associated method is called with a details `dict` whose keys are strings.

However, I just converted the same code to be a python3 session and was surprised to get `KeyErrors`. It turns out that the details passed to the method have bytes keys:

```
{b'authid': 'coordinator',
 b'authmethod': 'wampcra',
 b'authprovider': 'dynamic',
 b'authrole': 'coordinator',
 b'realm': 'realm1',
 b'session': 978859022,
 b'transport': {b'http_headers_received': {'cache-control': 'no-cache',
                                           'connection': 'Upgrade',
                                           'host': '127.0.0.1:8080',
                                           'pragma': 'no-cache',
                                           'sec-websocket-key': 'Zb3bDO+efx133r1EOMriQQ==',
                                           'sec-websocket-protocol': 'wamp.2.msgpack.batched,wamp.2.msgpack,wamp.2.json.batched,wamp.2.json',
                                           'sec-websocket-version': '13',
                                           'upgrade': 'WebSocket',
                                           'user-agent': 'AutobahnPython/0.10.3'},
                b'http_headers_sent': {},
                b'peer': b'tcp4:127.0.0.1:64774',
                b'protocol': b'wamp.2.msgpack.batched',
                b'type': b'websocket'}}
```

I could probably fix this, but I don't know where to look. Grepping for `wamp.session.on_join` and `on_join` didn't turn up anything obvious.

**Comment by meejah** [comment]
Hmm, actually this only happens using msgpack; json serializers are fine.

**Comment by terrycojones** [comment]
Hi @meejah, thanks for the reply.

I don't think I'm using msgpack.  My code is a slight simplification of that found in the example at https://github.com/tavendo/AutobahnPython/blob/master/examples/asyncio/wamp/basic/client.py with the "websocket" transport. Roughly:

```python
from autobahn.asyncio.wamp import ApplicationSessionFactory
from autobahn.asyncio.websocket import WampWebSocketClientFactory
from autobahn.wamp import types

session_factory = ApplicationSessionFactory(types.ComponentConfig(realm=args.realm))
session_factory.session = MyComponent  # My session app.

transport_factory = WampWebSocketClientFactory(session_factory, url=args.url, debug_wamp=args.debug)
transport_factory.setProtocolOptions(failByDrop=False)

loop = asyncio.get_event_loop()
coro = loop.create_connection(transport_factory, args.host, args.port)
loop.run_until_complete(coro)
```

**Comment by meejah** [comment]
Thanks for the details. I'll try with that method of starting. For what it's worth, this is how I was starting the py3 guests (which work fine with json but not with msgpack):

```
        from autobahn.asyncio.wamp import ApplicationRunner
        runner = ApplicationRunner("ws://127.0.0.1:8080/ws", "realm1")
        runner.run(MyComponent)
```

**Comment by meejah** [comment]
Okay, I can confirm starting the guests the way you posted also shows the same behavior: msgpack ends up with byte keys, json gives string keys. (So ``pip uninstall msgpack-python`` would be a workaround for now, giving json encoding).

I can also confirm my "fix" works in this case, but I'm now even less convinced it's the "right" answer :/

**Comment by meejah** [comment]
On Python 3, msgpack is turning keys into byte-strings:

```
import msgpack

orig = dict(foo='bar')                                                                                                                        
data = msgpack.packb(orig)
post = msgpack.unpackb(data)

print(orig)
print(data)
print(post)
```

The above prints:

```
{'foo': 'bar'}
b'\x81\xa3foo\xa3bar'
{b'foo': b'bar'}
```

**Comment by meejah** [comment]
@agronholm points out the following:

```
>>> import msgpack
>>> orig = dict(foo='bar')
>>> data = msgpack.packb(orig, use_bin_type=True)
>>> post = msgpack.unpackb(data, encoding='utf-8')
>>> post
{'foo': 'bar'}
>>> 
```

(we're actually using ``use_bin_type=True`` in autobahn):

**Comment by meejah** [comment]
So, with `use_bin_type=True` then "plain" strings in Python2 are encoded as binary-strings by msgpack (hard to see what else it could/should do) which will then be deserialized as binary.

So the #317 PR is "correct" as far as this bug goes. However, it would be more-correct to have Autobahn's msgpack serializer at least ensure you're not passing `dict` instances with non-unicode keys (or re-map all keys through `str()` but that would basically make an extra copy of any serialized dict, which sounds really bad).

Using syntax like `dict(foo='bar')` in Python2 gives you binary keys, effectively, so this would mean the only way to properly encode a dict for serialization through Autobahn would be syntax like `{u"foo": 42}`

It would also be possible to simply pass `use_bin_type=False` when encoding in Python2...but that probably has wider implications I'm not aware of...

**Comment by meejah** [comment]
My test-case works after #390 in AutobahnPython -- @terrycojones can you confirm?
Sorry for "moving" the ticket here -- it was an Autobahn bug after all ;)

**Comment by terrycojones** [comment]
Will check later today - thanks!

**Comment by terrycojones** [comment]
Hi @meejah 

I just did a `git pull` on the latest AutobahnPython to pick up the latest, and have run my code with the git repo in my PYTHONPATH. I immediately got a `KeyError` on `b'authid'` which seemed like a good thing (almost a failing test :-)). So I changed the key to be just `'authid'`, expecting it to work, but that *also* failed!  I print out the `session` details that are being passed to the `'wamp.session.list'` call, and here's what I see:

```
{"b'authid'": 'coordinator',
 "b'authmethod'": 'wampcra',
 "b'authprovider'": 'dynamic',
 "b'authrole'": 'coordinator',
 "b'realm'": 'light-matter',
 "b'session'": 697322573,
 "b'transport'": {"b'http_headers_received'": {'cache-control': 'no-cache',
                                               'connection': 'Upgrade',
                                               'host': '127.0.0.1:8080',
                                               'pragma': 'no-cache',
                                               'sec-websocket-key': '4KcTXDpp8UxSzkoMHHVIzg==',
                                               'sec-websocket-protocol': 'wamp.2.msgpack.batched,wamp.2.msgpack,wamp.2.json.batched,wamp.2.json',
                                               'sec-websocket-version': '13',
                                               'upgrade': 'WebSocket',
                                               'user-agent': 'AutobahnPython/0.10.4'},
                  "b'http_headers_sent'": {},
                  "b'peer'": b'tcp4:127.0.0.1:64322',
                  "b'protocol'": b'wamp.2.msgpack.batched',
                  "b'type'": b'websocket'}}
```

The key are e.g., `"b'authid'"`. I.e., double quotes around the `b'authid'`!  When I change my code to examine `session["b'authid'"]` there's no `KeyError`.

So it looks like you're double quoting the raw string representation of a byte string.

In the tests in your patch, I think you should check the values of the keys, not just that they are strings.

Thanks!

**Comment by oberstet** [comment]
@meejah not sure where we are on this .. I assign it to 0.11.0 milestone.

**Comment by meejah** [comment]
Works for me on master with both Python2 -> Python3 and Python3 -> Python2 (that is, the session listening for ``wamp.session.on_join`` is either Python 2 or 3, and same for the session that's joining to cause the on_join event).

@terrycojones can you confirm? There are some related commits to master after your May 9 comment.

**Comment by meejah** [comment]
See discussion in https://github.com/tavendo/AutobahnPython/issues/388

**Comment by oberstet** [comment]
Seems this needs to be addressed in places like these:

https://github.com/crossbario/crossbar/blob/master/crossbar/router/protocol.py#L255

Dicts created in CB to be sent must use Unicode keys: `u'http_headers_received': request.headers` instead of `'http_headers_received': request.headers` for Python2/3 compatibility.

**Comment by terrycojones** [comment]
@meejah - just did a pull on crossbar & autobahn masters and ran crossbar. No problem. That's all Python3, but that's where I got the original error and also the ongoing (double-quoted byte repr) issue on May 9.

@oberstet - I saw some other byte keys (no in `onJoin`, but in the arg passed to something else, it may have been internal to autobahn as I was debugging in there) a couple of days ago but forgot to note where. Sounds like you know what to do already. If I run across it again I'll let you know.

Thanks!

**Comment by meejah** [comment]
I believe what's left for this ticket is to audit crossbar to ensure all keys in all dicts that might end up in an autobahn message are specified like ``{u"key": ...}``. Anything automatic as far as ensuring this should be discussed/implemented in https://github.com/crossbario/autobahn-python/issues/461

We should probably open a documentation bug, too, to add to the programming guide that if you want python2+3 code, you MUST write dictionaries like the above (and, specifically, *not* like ``dict(key=..)``).

**Comment by oberstet** [comment]
in short (mobile net): yep, agreed!

**Comment by meejah** [comment]
Some things I'm not quite sure about:

- ``adapter/postgres/publisher.py``: I don't know if the keys will always be unicode, but I *believe* so because they come from a ``json.loads`` from something postgres published via NOTIFY. (around lines160-172)
- ``adatper/rest/webhook.py``: (line 73) similar to above, for same reason
- ``adapter/rest/publisher.py``: (line 69) ditto

I grep'd the whole crossbar code base for dict-creation and ``.publish`` events. So, I'm pretty confident that the pull-request (https://github.com/crossbario/crossbar/pull/617) covers all outstanding keys. The trickier-to-audit things are when RPC calls return data (although I did look at them too).

**Comment by oberstet** [comment]
I think this is already a leap forward and good to close
