### ISSUE TITLE
Specification of a scheduler component for crossbar.io

### ISSUE THREAD

**Issue by markope** [crossbario/crossbar#319]
## Scheduling Component for crossbar.io

This is a suggested spec for a scheduling component which enables time dependent triggering of crossbar RPC calls and publish actions.
### Definitions

A `schedule` consists of a tuple:
- a name identifying the schedule
- a set of points in time the `time-schedule`
- the action type (one of rpc or publish)
- the action uri
- the action payload 
- an options JSON

The `scheduling engine` is a process which manages all the schedules in its scope.
### The API

Schedules can be created and deleted through RPC calls itself. e.g. autobahnJS

``` javascript
absession.call("crossbar.scheduler.create", shedule_name, schedule_string, action_type, action_string, action_payload, options )
```

Here the options object can be used to controll a few things

``` javascript
options = {
   start_now: true,
   repeat_behaviour: skip / buffer,
   retry_count: 100,
   retry_interval: 1s,
 /* only for RPC*/
   after_failure: stop / continue,
   publish_success_uri: myuri,
   publish_failure_uri: myerr
}
```

If a scheduled rpc returns with a failure then the engine retries to issue the rpc again according to the retry settings above. If the `retry_count` is exceeded then the schedule is stoped and a warning will be noted in the log.

If the `repeat_behaviour` is _skip_ then the engine should skip execution of an rpc in the schedule if the previous rpc of the same schedule is still pending to return. If the `repeat_behaviour` is _continue_ the next scheduled rpc should be issued regardles if the previous returned already.

If an rpc call issued by the scheduler engine returns succsessfully its payload should be published under the `publish_success_uri`. If the rpc returns with a failure, then the payload should be published under the `publish_failure_uri`.  

Creating a schedule with an existing name overwrites the existing schedule.
A schedule can be stopped or started. When initially created it is stopped unless sepcified differently in the options.

``` javascript
absession.call("crossbar.scheduler.start", 'regexpattern')
absession.call("crossbar.scheduler.stop", 'regexpattern')
```

Deleting a schedule

``` javascript
absession.call("crossbar.scheduler.delete",'regexpattern')
```
##### Meta calls

The engine should allow to list all schedules:

``` javascript
absession.call("crossbar.scheduler.list", regexpattern)
```

The scheduler should show the list of the next 50 upcoming actions with exact times (even when stopped).

``` javascript
absession.call("crossbar.scheduler.show_times",schedule_name, [number_of_events default 50])
```

The log can be shown for a schedule showing the past 100 actions (failed or not) for a schedule:

``` javascript
absession.call("crossbar.scheduler.show_log", 'regexpattern', options)
```

The options here can be used to control the output

```
options = {
   numer_of_events: [number of events to show],
   failed_only: true/false
}
```
##### The time-schedule syntax

The time-schedule should be configurable through a string which encodes the regular intervals at which a certain action should be performed.

The time schedule is an object:

``` javascript
time_schedule = {
     start: [ISO date notation string],
     interval: '1 year 2 month 3 day 2 hour 13 minute 4 second 10 msec',
     end: [ISO date notation string] 
}
```

If the `start` is not specified or null then the schedule starts immediately. If the `end` is not specified or null then the interval should repeat infinitely.
### The Engine

The engine should issue the defined action according to the points in time defined by the time-schedule.
The engine should be able to handle different schedules concurrently.
### Privileges

The scheduling engine is associated with a realm. Authorization is handled through the regular authorization mechanism regarding the scheduler URI pattern`^crossbar\.scheduler\..`.

**Comment by gregkeys** [comment]
I think this could be a really good idea.

we have built a micro service to accomplish something similar for triggering imports and exports at set times each day. it's basically this [cron npm module](https://www.npmjs.com/package/cron) wrapped into a simple micro service.

One complication we have come up against though is that scaling our service (as well as adding failovers) requires modifying the scaled up services to not include the scheduler micro service otherwise it triggers the import/export too many times.

also if we need the schedulers on multiple realms the we have to open more connections it would be nice if the router could handle this instead.

it would also be handy if this could work in conjunction with clustering so that as the system scales up the scheduler only ever triggers events one time.

**Comment by oberstet** [comment]
migrated to https://github.com/crossbario/crossbarfx/issues/279

reason: this should work cross-node, as in: the master node (of crossbarfx) should be responsible for storing, executing and overseeing scheduled calls/publishes
