### ISSUE TITLE
Serving static files is broken in master branch

### ISSUE THREAD

**Issue by aldarund** [crossbario/crossbar#320]
I tried to install crossbar from master and when serving static files using:

"static": {
                            "type": "static",
                            "directory": "../staticfiles"
                        }

Static files become total mess with totaly messed up content within a file, like aт end of file in center of file  etc.
same code works fine with version from pypi

**Comment by meejah** [comment]
I tried with a729afd on Debian with a random 1GB file several times and never saw any differences from the original; can you post more details about your setup?

**Comment by aldarund** [comment]
Hm. I was using it on windows.
But i tried to change back to master again - and now it works fine.
The files was just simple javascript, and they become broken than they even dont parse thats why i noticed. Have no idea why it happened and how to reproduce, since its fine now. But it was like i described and i didnt change anything.

**Comment by goeddea** [comment]
Also just gave this a go on Windows - current Crossbar.io from master serves the Crossbar.io Web page without any problems.
@aldarund - Since you yourself can't replicate, I'm closing this for now.
