### ISSUE TITLE
Exception arg is bytes instead of str for Python3 client

### ISSUE THREAD

**Issue by terrycojones** [crossbario/crossbar#321]
I have a Python 3 crossbar client that makes a call to a non-existent procedure. The error message that's returned in the raised exception is `bytes`, whereas it should probably be a `str`. Here's the client output from just calling `print()` on the exception instance:

```
Error: ApplicationError('wamp.error.no_such_procedure', args = (b"no callee registered for procedure 'shutdown'",), kwargs = {})
```

The relevant server-side code is in `crossbar/router/dealer.py`, though that uses autobahn so I'm not sure whether this issue is a crossbar one or an autobahn one.

Possibly related to #316?

**Comment by oberstet** [comment]
@terrycojones could you recheck if the issue persists with current trunk? This commit should have fixed it https://github.com/crossbario/crossbar/commit/b2bd0054ae7aa703fa0ef9bf95e5099376007fd8

**Comment by terrycojones** [comment]
@oberstet Confirmed as fixed. Nice to have to `pip install -U twisted` to pick up the use of the new logger :-)  Thanks!

**Comment by oberstet** [comment]
@terrycojones thanks for checking!

**Comment by terrycojones** [comment]
@oberstet np, & thanks to you, too :-)
