### ISSUE TITLE
Start components in OS containers

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#332]
[LXC](https://linuxcontainers.org/lxc/introduction/) is part of the [Linux containers project](https://linuxcontainers.org/) and provides the low-level OS container technology in Linux.

`python-lxc` comes with LXC and provides Python 3 bindings for LXC. On Ubuntu, `python-lxc` can be installed like this:

``` console
sudo apt-get install lxc lxc-dev python3-lxc
```

and will then be available for importing in `/usr/bin/python3`.

**Comment by hawkowl** [comment]
We support Python 3 now, so this is something we can do.

**Comment by om26er** [comment]
If this is something we still care about, I'd like to take this on (voluntarily or otherwise). I have worked with LXD for quite a few years and have also used its python bindings (pylxd) for test automation, so I know my way around it.

Though not really sure if this issue is relevant for us in the all-things-docker world.

**Comment by meejah** [comment]
If crossbar itself is running in a Docker container, it could still start components in their own (sub-) containers, right?

**Comment by oberstet** [comment]
The original idea was to start CB workers as OS containers and continue talking WAMP-WebSocket over pipes, as we do with regular OS process workers today.

This won't fly (eg pls see my comments/replies here https://github.com/rkt/rkt/issues/3639) with a regular Docker/rkt setup.

And it doesn't cut it anyway I now would say, as what is even more desirable (since hugely more univeral) is to let Crossbar.io Fabric nodes control the Docker/snapd daemon running on the host. However, then this here isn't the right place to go after that (see https://github.com/crossbario/crossbar-fabric/issues/19).
