### ISSUE TITLE
Reverse Web proxy service

### ISSUE THREAD

**Issue by garethbult** [crossbario/crossbar#334]
I'm working on fairly extensive application using AutoBahn, JS, Python, CrossBar and Klein. Everything is  being served via port 80 following an authenticated WS connection. However, I'm left with connections prior to authentication, and callbacks to display images still needing HTTP. This all works nicely but I'm left with one issue that pains me, that is that I need to use the WSGI module to server HTTP requests via port 80, and the default mechanism is via Flask. This is "ok" up to the point where I find that WSGI requires that code be be loaded "with" crossbar, so every time I update this code I need to restart crossbar. This is a problem. I can use a "redirect", but then I end up not serving via port 80, I'm either using a different address or port number.

So, the question following my horribly long winded explanation is; how can I serve HTTP requests off port 80 using a "client", without that client being an integral part of Crossbar, such that I can develop and debug it without continually restarting crossbar? I guess that question translates into, how do I make crossbar "proxy" instead of "redirect" ?

I know I can run this behind Apache or NGINX, but this is another layer of technology that I don't really want, and technically, shouldn't really need (??)

**Comment by meejah** [comment]
So you're after something that will simply forward a request arriving at a particular sub-path to some other endpoint (presumably something running as a guest/container so it's in its own process)? That is, like an nginx "reverse proxy" configuration?

**Comment by garethbult** [comment]
Yes .. it is (essentially) already able to do this, but only when the endpoint is built-in to crossbar .. I want to separate it from crossbar .. in the same way WAMP clients are separated ...

**Comment by oberstet** [comment]
@garethbult yes, when you run WSGI resource under CB, it will run in a router worker, since the WSGI resource lives on the pseudo Web transport of that router. When you change code in your WSGI thing, that will require restarting the hosting worker - the router process.

> Sidenote: I once started (unfinished) code within CB that will automatically restart a container worker when code changes in component hosted in the container worker are detected. Useful for dev. - but in your case, that would then automatically restart the while router worker .. not only the WSGI bits.

Another idea: during dev, just use a different port and develop/start your WSGI thing outside of CB. When done, move the WSIG to CB.

Finally, what @meejah suggest: yes, we could have a "reverse proxy" resource which would forward HTTP requests to your WSGI thing, which then would need to listen on non-80.

You then can create the WSGI thing using plain Flask (blocking) and have it started by CB as a guest worker for prod.

> If you still would use Twisted Web to serve your WSGI thing, we could probably even do the reverse proxying not over loopback TCP, but Unix domain sockets.

**Comment by garethbult** [comment]
Ok, all sounds very do-able, but we're still dancing around the issue a little. Separating business logic from routers seems to be a fundamental principle here, not least when it comes to load balancing and resilience, and whereas I can see the logic behind having to integrate my authentication code with the router, having other stuff (for example code to service image GET requests) could do with being modular as with other WAMP based code. I'd serve images via WAMP, but my impression is that I lose  various features (like caching) only available if I load via HTTP.

Something that has occurred to me as I type, it should be possible to forward HTTP requests to RPC calls and have requests serviced by modular (remote) code over WAMP (I guess this is "an" implementation of a proxy) .. which means one generic routine built into the router and all requests handled via RPC. I don't suppose this is something that's on the roadmap?

... I think I may have solved my own problem unless there's something on the roadmap that's going to provide equivalent / better functionality?

**Comment by oberstet** [comment]
> Separating business logic from routers seems to be a fundamental principle here

Absolutely. we stick to this principle rigorously. router code must not be mixed with app code. however, this applies to the code .. it's "ok" to have both router code and app code _run_ in the same process - as long as there is no coupling.

> I'd serve images via WAMP ...

I can't find it now, but somewhere we had that discussion of adding a WAMP-controlled Web server built into CB. The idea was, that you dynamically add **static** resources (files) via WAMP calls to URLs, and that would cache the resource and serve it via HTTP.

> it should be possible to forward HTTP requests to RPC calls and have requests serviced by modular (remote) code over WAMP (I guess this is "an" implementation of a proxy) 

This is yet **another** idea. Essentially, you would expose a single WAMP procedure in your component, e.g. "com.myapp.serve_http_request", and hook that into the CB Web transport. Upon receiving a HTTP request on the configured URL path, CB would forward the request as a WAMP call to your component and respond via HTTP with the stuff received from your WAMP proc.

**Comment by garethbult** [comment]
>This is yet another idea.

Indeed! Essentially this is what I think I was asking for. I've found that although I would like to server "everything" via port 80/WAMP there are a number of caveats which make the solution "unclean". One is serving images (which I do from a MongoDB) , another is interfacing with plugins that are pre-disposed to use things like "POST" for upload, and another is stuff that needs to be presented pre-authentication.

Everything else (including authentication) I'm getting away with via WAMP, indeed I no longer actually do any HTTP authentication. I think I'll have a crack at the HTTP/WAMP proxy idea when I get a few minutes, that could solve most if not all of my issues in this area.

If you get bored / have 5 minutes to kill (bearing in mind this is very experimental and had "just" undergone a massive untested upload); http://chat.linux.uk/
("all" Autobahn/Crossbar with a little bit of Flask)

**Comment by oberstet** [comment]
Part of the discussion above is related to https://github.com/crossbario/crossbar/issues/390, which asks for a reverse Web proxy service

**Comment by oberstet** [comment]
This is implemented

**Comment by oddjobz** [comment]
This is the "call" endpoint ??

**Comment by goeddea** [comment]
Documentation for the reverse proxy service is now at http://crossbar.io/docs/Reverse-Proxy-Service/

**Comment by oddjobz** [comment]
Mmm, I knew it was going to be difficult to explain. The core issue for me was to separate out code such that I didn't need any "business logic" linked directly into Crossbar, in such a way that if the business logic changed, Crossbar would need to be changed and restarted.

The HTTP reverse proxy will do this, but it still required another HTTP server elsewhere, which just moves the issue onto a different node. What I was really for was a redirect to an RPC endpoint.

I did find a way of doing this that works very well. What I have in config.json is;
```json
"options" : { "access_log": false },
          "paths": {
            "/": { "type": "wsgi", "module" : "wsgi", "object" : "app" },
            "call": {"type":"caller","realm":"ionman","role":"anonymous"},
```
Then in the WSGI code I have;
```python
def handle_proposal(token):
    try:
        payload = {u'procedure':'my.topic'}
        payload[u'args'] = [{'token':my_token}]
        headers = {u'Content-Type':u'application/json'}
        r = requests.post(u'https://localhost:'+str(conf.PORT)+'/call',data=json.dumps(payload),headers=headers,verify=False)
        res = r.json()
        response = make_response()
        response.headers = res['args'][0]
        return response
    except:
        log.err()
```
And somewhere in the backend code I can sit some code on a topic with;
```python
    @wamp.register(u'my.topic')
    def my_topic(self,argv,details):
        ....
        return result
```
So I can write fixed code in WSGI/Crossbar and fire it up - with the actual code existing elsewhere, outside of Crossbar.  Obviously the topic "can" be dynamic, so it's a way for WSGI to be used to call a topic, and passing a single use authentication token can be used to cross-reference session data.

So implemented, yes, but "Reverse-proxy" and "call", so far as I can see, two very different things ... :)

**Comment by oberstet** [comment]
A "HTTP Reverse Proxy" is an established term for a HTTP endpoint that receives HTTP requests, which it doesn't answer directly, but forwards the requests to another HTTP endpoint, gets the response from there, and then answers the original request with that response. This is precisely what `"type": "reverseproxy"` provides. So its HTTP in and HTTP out. I was under the impression that is what you wanted;)

But yes, the "HTTP Bridge" (http://crossbar.io/docs/HTTP-Bridge/) is different from above, yes. Eg `"type": "caller"`: this receives HTTP/POST requests and turns them into WAMP calls. So this is HTTP in and WAMP out.

> Mmm, I knew it was going to be difficult to explain. 

I still don't get it to be honest;)

Why do you need the WSGI thing to receive the HTTP request, only to forward that again to the HTTP bridge `caller` service? Why can't the latter directly receive it?

**Comment by oddjobz** [comment]
Mmm, historically I wasn't using caller, so I was terminating on WSGI and calling code directly linked into Crossbar. When I discovered "caller", I redirected the target from code in Crossbar to an RPC endpoint. It would be great to cut-out the WSGI stuff .. I suppose I should be able to do the parameter work in JS and go directly to the "call" .. thanks, I'll give that a try .. :)

**Comment by oberstet** [comment]
@oddjobz cool. let me know if you run into issues. the HTTP bridge is supposed to cover your use case (if I get it) .. if not, we are doing it wrong;) and will adjust.

**Comment by oddjobz** [comment]
No, it looks to be working well for the moment .. :) .. on the verge of taking live customers so it'll get more of a soak test shortly .. :)
