### ISSUE TITLE
HTTP-Bridge-Services-Caller no response or procedure call

### ISSUE THREAD

**Issue by Braynid** [crossbario/crossbar#346]
I'm using crossbar and [voryx/Thruway](https://github.com/voryx/Thruway/) and want to integrate an existing PHP app with crossbar.

I think the best way of doing this would be to use [HTTP-Bridge-Services-Caller](http://crossbar.io/docs/HTTP-Bridge-Services-Caller/) by calling remote procedures in other components directly form my non-long-running app.

I've set a caller path in my config.json as follows:
```
                        "callsigned": {
                            "type": "caller",
                            "realm": "site_updates",
                            "role": "updates_trigger",
                            "options": {
                                "debug": true
                            }
                        }
```

The problem is that whatever I do, I get no response when POST-ing to that endpoint and the remote procedure is not called. In fact I see no change in the crossbar process output.

Sample curl call:
```
curl -H "Content-Type: application/json" -d '{"procedure": "com.domain.add_deposit", "args": [1, 2, 3]}' -v "http://192.168.33.11:5051/callsigned?timestamp=2015-06-03T13:15:30Z&seq=123"
```
Curl response:
```
* About to connect() to 192.168.33.11 port 5051 (#0)
*   Trying 192.168.33.11...
* connected
* Connected to 192.168.33.11 (192.168.33.11) port 5051 (#0)
> POST /pushsigned?timestamp=2015-06-03T13:15:30Z&seq=123 HTTP/1.1
> User-Agent: curl/7.26.0
> Host: 192.168.33.11:5051
> Accept: */*
> Content-Type: application/json
> Content-Length: 65
>
* upload completely sent off: 65 out of 65 bytes
* Empty reply from server
* Connection #0 to host 192.168.33.11 left intact
curl: (52) Empty reply from server
* Closing connection #0
```

I'm using the following crossbar and software versions:
````
Crossbar.io package versions and platform information:
Crossbar.io                  : 0.10.4

  Autobahn|Python            : 0.10.4
    WebSocket UTF8 Validator : ?
    WebSocket XOR Masker     : ?
    WAMP JSON Codec          : stdlib
    WAMP MsgPack Codec       : msgpack-python-0.4.6
  Twisted                    : 15.2.0-EPollReactor
  Python                     : 2.7.5-CPython

OS                           : Linux-3.10.0-123.el7.x86_64-x86_64-with-centos-7.0.1406-Core
Machine                      : x86_64
```

**Comment by oberstet** [comment]
![bildschirmfoto vom 2015-06-04 14 38 26](https://cloud.githubusercontent.com/assets/233340/7984191/8a227958-0ac7-11e5-8f94-5ebab92e05db.png)

works for me

**Comment by Braynid** [comment]
Thanks for the help.

The issue was the protocol used: http instead of https.

**Comment by FirefighterBlu3** [comment]
Tangent note for future viewers of this issue number; the URL in the initial post is no longer the correct URL. Instead, visit https://crossbar.io/docs/HTTP-Bridge/
