### ISSUE TITLE
Remove use of twisted.python.log and twisted.python.compat

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#352]
* `twisted.python.log` should be replaced with the new logging.
* `twisted.python.compat` should be replaced with `six`

**Comment by oberstet** [comment]
@hawkowl: agree? want to do it?

**Comment by hawkowl** [comment]
@oberstet Yep, I can take point on this.

**Comment by oberstet** [comment]
@hawkowl should be fixed, right?

**Comment by hawkowl** [comment]
Still a handful of `twisted.python.log` using modules:

```
crossbar//adapter/rest/subscriber.py:from twisted.python import log
crossbar//controller/guest.py:from twisted.python import log
crossbar//router/role.py:from twisted.python import log
crossbar//twisted/tlsctx.py:from twisted.python import log
crossbar//worker/container.py:from twisted.python import log
crossbar//worker/worker.py:from twisted.python import log
```
I can sort that out, though.

**Comment by oberstet** [comment]
@hawkowl thx! I am trying to collect all open ends in the 0.11.0 milestone that relate to: logging, error handling, and cleanups like these. but I want to do a release soon ..

**Comment by hawkowl** [comment]
#400 and #401 should close this up.

**Comment by hawkowl** [comment]
I think that's it? grep returns the following things importing from `twisted.python`:

```
crossbar/_logging.py:from twisted.python.constants import NamedConstant
crossbar/_logging.py:from twisted.python.reflect import qual
crossbar/controller/cli.py:from twisted.python.reflect import qual
crossbar/twisted/resource.py:    from twisted.python.filepath import FilePath
crossbar/twisted/sharedport.py:from twisted.python.runtime import platformType
crossbar/worker/process.py:    from twisted.python.reflect import qual
```

No more logs, no more compat, no more tears :)

**Comment by oberstet** [comment]
very good;) thanks!
