### ISSUE TITLE
CLI log options naming

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#353]
The `loglevel` option currently takes `none,quiet,standard,verbose,trace`. These are named differently from the methods on the new logger like e.g. `self.log.warn`. This at least confuses me .. which CLI level corrsponds to which logger level? Shouldn't we just name the CLI values exactly as the logger methods?

A 2nd thing: "colour" instead of "color" (guess similar to "behavior" vs "behaviour"?). I am not a native speaker, but this looks funny to me;)

@hawkowl @meejah ?

**Comment by hawkowl** [comment]
The CLI values don't map directly -- quiet is warn+error, standard is warn+error+info, verbose is warn+error+debug, trace is warn+error+debug+special debug entries.

The difference between verbose and trace is not actually the log level but a key -- `cb_trace`, which marks some debug messages as being incredibly noisy -- for example, raw WAMP messages are a 'trace' message. For an example, see https://github.com/crossbario/crossbar/blob/5ebcb162a3747b409599bef4c1dd1bd091c7b069/crossbar/router/router.py#L142

I am not sure if making them match the names in the logger will cause confusion, because "info" would also show warnings and such.

Also, "colour" is the British English spelling -- color is the American spelling. American English likes removing the "u"s.

**Comment by meejah** [comment]
Another thing with the log-levels: these are all different from the ones in the latest release (which were `('trace', 'debug', 'info', 'warn', 'error', 'fatal')` versus `('none', 'quiet', 'standard', 'verbose', 'trace')`).

**Comment by oberstet** [comment]
>  because "info" would also show warnings and such.

That is expected (at least I would .. from knowing other systems): `loglevel` would be the "most verbose log level logged (including any less verbose log levels)".

Regarding log levels and naming - the [new logger](https://twistedmatrix.com/documents/15.2.0/api/twisted.logger.Logger.html) seems to have 5 log levels:

* debug
* info
* warn
* error
* critical

There also is `log.failure()` which I guess will implicitly log at level critical?

There is no `none` / `quite` nor is there `trace`.

We definitely would like to have `none` / `quiet` for `loglevel`, so there can't be an exact correspondence between CLI log levels and `Logger` log levels. But that's fine. We could get away with exactly this additional pseudo log level `none`, which would just silence the log output.

The question is about `trace`: this was originally thought as enabling extremely verbose, wire-level / single-message tracing.

In a way, while all the other log levels also have different semantics (like "fatal" is unrecoverable), levels "trace" and "debug" are really just about different amounts of debug output.

Further, since there is no `Logger.trace`, how would we output at that log level from CB code?

One option would be the following. Allow to use levels "debug1" = "debug", "debug2", ..., "debug9" (similar to PostgreSQL), set log level "debug", and a new attribute "tracelevel" set with 1, .., 9.

And then have that attribute extracted from structured log, like when I do

`self.log.debug("Bytes on wire: {hexdata}", hexdata="...", tracelevel=5)`

**Comment by oberstet** [comment]
Btw, I also think it would be useful if we had a recommendation when to use which log level (because of the implied/suggested semantics). Like, if the information can't be expected to be useful to users, then it's "debug". When it's unrecoverable, it must be "fatal" etc.

I took a peek at https://twistedmatrix.com/documents/15.2.0/api/twisted.logger.Logger.html but it doesn't suggest when to use which level.

**Comment by oberstet** [comment]
It seems, PostgreSQL assigns pretty elaborate semantics with various log levels http://www.postgresql.org/docs/9.4/static/runtime-config-logging.html#RUNTIME-CONFIG-SEVERITY-LEVELS

Maybe we could just steal / adapt that? Would that be useful?

**Comment by hawkowl** [comment]
Because we're going to need a custom logger wrapper to turn debug calls into no-ops, I can make `log.trace` a thing.

As far as levels, I'll do up a recommendation of levels in the logger documentation, which we can tweak. I'm not sure we need 5 log levels (because then it gets way too complex to decide what goes where), so I think if we start off with a `.trace`, we can decide if we need the extra trace levels later on.

**Comment by meejah** [comment]
So far, the "application developer" isn't really exposed to the crossbar logging system, right? Essentially, the "customer" for the `self.log.{trace,debug,info,etc}` APIs are crossbar-developers, and the application developer is essentially left to do whatever they please? Or is the intent here to expose a logging API that application developers can use too?

Maybe it's better to focus on use-cases?

Completely off the top of my head (stuff in brackets is supposed to represent what you'd do pre-new-logger):

1. you're running crossbar in production ("normal"/"info"); you just want to see *errors*.
2. you're doing development of some application code ("verbose"/"debug", and want to see warnings)
3. you're trying to find a problem in some application code ("app_debug", "traceback_app", custom log/print statements in your application code, etc)
4. you're trying to find a problem in crossbar itself. ("trace", and/or debug on a specific module/class, and or setting `self.debug=True` in certain classes, plus new log/print() statements)

From an application-developer perspective, mostly I just care that "something isn't working, and I want more information" and will turn up the log-level until I get enough. Or, e.g., I'm filing a bug report so I turn it to 11 and dump everything.

From a crossbar-developer perspective, I want to know how far the user needs to turn the knob before they see the information I'm logging (e.g. "info" I expect anyone to see vs. "warn" I expect 1 knob-turn vs. "debug" at lest 2 knob-turns etc). I really doubt anyone wants "trace" besides crossbar-developers (or an application-developer who has probably run across a crossbar-bug).

**Comment by hawkowl** [comment]
There is now a `log.trace()`, and the levels are "none", "critical", "error", "warn", "info", "debug", "trace". I still need to do up the recommendation docs.

**Comment by hawkowl** [comment]
See crossbar/crossbarwww#76

**Comment by hawkowl** [comment]
Also https://github.com/crossbario/crossbarexamples/pull/30
