### ISSUE TITLE
Override loglevel on a per-component basis in config

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#354]
In the past, we had code like this all over the place:

``` python
if self.debug:
    log.msg("XYZ Class/component: bla blub")
```

and `self.debug` could be (sometimes) controlled from the node configuration for _that_ component.

With the new logging, the idiom is

``` python
self.log.debug("bla blub")
```

and the logging class will be (should be) added to the log output automatically, and all those `if self.debug` disappear. **This is much better**.

However, to get debug log output from component XYZ, the user/dev now needs to set `--loglevel=verbose` (which is fine), but that will turn on debug output for **everything** - which makes things again harder to read when one is only interested in XYZ, since there is a lot of output.

Ideally, I could override the loglevel being applied for XYZ messages **only**, from the node configuration.

E.g.

``` json
      "transports": [{
         "type": "web",
          ...
         "paths": {
           ...
            "ws": {
               "type": "websocket",
               "options": {
                   "loglevel": "verbose"
               }
            }
...
   }]
```

This would generally log at default log level (unless overridden from CLI), but for the "ws" component, it would log "verbose".

**This would be the holy grail of logging from my POV;)**

**Comment by oberstet** [comment]
@hawkowl @meejah thoughts?

**Comment by oberstet** [comment]
Is something like this possible?

```python
from crossbar._logging import make_logger

class XYZ:
     log = make_logger()

     def __init__(self):
          if <node config for this XYZ says "log verbose">:
               self.log.set_log_level("verbose")
```

**Comment by hawkowl** [comment]
@oberstet The thing that currently controls the log output is the log observer, not the emitter. Maybe the observer should instead have the option, rather than components having to have extra code to support it. Maybe like `--spewfor=crossbar.controller.node.Node,<someotherclass>` which would enable debugging for the comma-separated list of classes, regardless of the log level given by `--loglevel`?

**Comment by oberstet** [comment]
thinking about it, it's probably a bigger issue than I thought: the fact that log output is controlled by the observer not the emitter.

That means, I can't use `self.log.debug` in hot code paths, since it will be a performance issue.

I think we should create our own logger class which allows us to control logging at the emitter ..

**Comment by oberstet** [comment]
in other words: when log level is "standard" (whereever that comes from .. global option or component config), `self.log.debug` must be a no-op (eligible to be optimized away by pypy eg)

**Comment by hawkowl** [comment]
The log output being controlled by the observer is the "better" way, if not the faster way, because it means that many observers can listen to what they want to hear. But because of the structured logging, the debug calls are cheap and are essentially all a no-op, because nothing consumes it (and nothing renders the log message, which is the most expensive part).

A logger class that turns `log.debug` more directly into a no-op could be a good idea, though.

**Comment by hawkowl** [comment]
(That is to say, debug calls with the old logger are far slower than the new logger, because `.format` was called when the log message was emitted, which is the expensive part, while in the new logger, `.format` is only called by the observers -- so a log message that is never observed is very cheap)

**Comment by oberstet** [comment]
> are cheap and are essentially all a no-op

Huh? For all worker processes, the log goes over pipes.

> that many observers can listen to what they want to hear

There is only 1 observer we need. I don't buy that "observer stuff" ..

**Comment by oberstet** [comment]
Let me put it like this: if `self.log.debug` is not a no-op whenever loglevel>debug, then I would stick to our original idiom .. for performance reasons.

**Comment by hawkowl** [comment]
Oh, true, I forgot we had worker processes. So the log is always being observed...

Yeah, I think the no-op will be a good idea. I'll look into it. :)

**Comment by oberstet** [comment]
@hawkowl great!

IMO, the goals should be:

- being able to override global log level on a per-class basis from the class constructor (no, I don't want to specify it on the CLI, but the node config)
- any of the `self.log.xxx` methods should be a no-op if either the global log level, or the object's log level are set higher than xxx.

> Also, we need to be able to change both the global and per-component log levels dynamically via management API.

**Comment by oberstet** [comment]
Another note: when a native worker is started, it will be started using command line args specifying e.g. reactor to use. Do we forward the loglevel set when CB was started also?

**Comment by hawkowl** [comment]
Cool.

- I think that the API from previous example is a good idea -- `set_log_level` makes it easier to do via management API
- Just to clarify -- if this means the global level is info, and the component level is debug, it will print debug info?
- The global log level being the one set by --loglevel? Also, what would the per-component log level look like -- would the component have to support a command to change the log level?
- It doesn't, yet, but it's trivial to make it do so, to initiate the worker's logger with.

At the end of this, we'll end up with:

- A non-debug log level being given will turn all debug commands into no-ops, same for info, etc
- If a component has debug turned on, it will log debug entries even if the global log level is not debug
- The management API can change the global log level, or the log level of components dynamically

Correct?

**Comment by oberstet** [comment]
Yep, essentially. Guess we need to approach it in steps .. I don't have the full picture yet ..

My immediate pain was: consider this https://github.com/crossbario/crossbar/blob/master/crossbar/twisted/resource.py#L83

It's using the old-style ad-hoc poor man's logging.

The `options` argument to that class constructor gets this https://github.com/crossbario/crossbarexamples/blob/master/fileupload/.crossbar/config.json#L48

Within that `options`, I'd like to replace the `debug` attribute with a `loglevel` attribute.

And then do:

```python
class FileUploadResource(Resource):

    # uses the global log level by default (and that global log level can change over time)
    log = make_logger()

    def __init__(self,
                 upload_directory,
                 temp_directory,
                 form_fields,
                 upload_session,
                 options=None):

        if 'loglevel' in options:
            # override the global log level
            self.log.set_log_level(options['loglevel'])
```

>  global level is info, and the component level is debug, it will print debug info?

Yes, it will print debug level messages for that component, but only info level messages for everything else.

> The global log level being the one set by --loglevel?

Something like:

- There is a global, hard-wired default log level ("standard" currently).
- The former can be overridden from node config:
```json
{
    "controller": {
       "options": {
            "loglevel": "info"
       }
    }
}
- This can be dynamically changed via management API exposed by node controller (not yet there).
- The global log level can be overridden on a component-basis (from node config or via management API) - `"options": {"loglevel": "debug"}`.

**Comment by oberstet** [comment]
wait, my example above .. `self.log.set_log_level` will override the loglevel for all instances of that class, right? if so, that's not what I really want, since I might have multiple instances and want to have different log levels.

maybe:

```python
class FileUploadResource(Resource):

    def __init__(self,
                 upload_directory,
                 temp_directory,
                 form_fields,
                 upload_session,
                 options=None):

        # override instance log level if options['loglevels'] is set
        self.log = make_logger(options.get('loglevel'), None)
```

**Comment by hawkowl** [comment]
Sounds reasonable -- we make a logger, it's per-instance, and it has its own log level.

**Comment by oberstet** [comment]
great! let's try that approach ..

**Comment by meejah** [comment]
FWIW, I agree it would be really nice to be able to turn up the log-level on specific things...

Related to this, IMO we should kill anything like this:

```
try:
    # something
except:
    if self.debug:
        traceback.print_stack()
```

That's somewhat simplified from some of the "real" code, but what I mean is I don't think there's ever a good reason to eat exceptions even from "internal" stuff as (sometimes) things like simple typos that result in `SyntaxError` being thrown are just eaten. This can be especially bad if "half" a method runs, then hits a simple error of some sort and essentially just bails out (silently).

**Comment by oberstet** [comment]
> IMO we should kill anything like this

Oh yes! Those are I guess mostly remains of getting some stuff "quickly done", skipping errors or conditions that would have required more thought / work on handling correctly.

**Comment by oberstet** [comment]
won't fix
