### ISSUE TITLE
REST bridge denying valid content-type

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#364]
When a HTTP/POST has a content type `application/json; charset=utf-8`, the REST bridge will deny that, as it looks for `application/json` - and only that.

**Comment by MichaelKetchel** [comment]
Do we have an update on this? This is crippling a custom authentication system I'm trying to write :(

**Comment by hawkowl** [comment]
Hi @MichaelKetchel, I'm back from PyCon AU now, so this is something I'll fix up soon. Sorry for the delay!
