### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by foxmask** [crossbario/crossbar#368]
Hi,

Currently I use wamp (Pub/Sub) to do this kind of stuff : 

Get Feeds, Read the Items, publish the content in Evernote and Twitter

Sometimes thoses things happen : 

I meet a rate limit raised by Evernote because of too many calls of the Evernote API in one hour.
When publishing stuff on twitter, we flood our followers who dont appreciate that very much.

So It would be nice to have a rate limit for the worker (to try) to avoid those behavior. 
It could also be usefull, to do a pause each 'n' "publishing"

I saw this kind of feature in celery : 

* https://celery.readthedocs.org/en/latest/userguide/workers.html?highlight=rate_limit#std:control-rate_limit
* https://celery.readthedocs.org/en/latest/userguide/tasks.html?highlight=rate_limit#Task.rate_limit (if you need an example)
* https://celery.readthedocs.org/en/latest/reference/celery.app.task.html?highlight=rate_limit#celery.app.task.Task.rate_limit

Regards

**Comment by gdassori** [comment]
Hi, assuming i've understand your needs, I don't understand why you simply
don't implement a semaphore by yourself.
Cheers
Il 18/giu/2015 14:39, "FoxMaSk" <notifications@github.com> ha scritto:

**Comment by meejah** [comment]
If you're using Twisted, there's already http://twistedmatrix.com/documents/current/api/twisted.internet.defer.DeferredSemaphore.html too

So the idea would be you have an "Evernote" semaphore that you .acquire() before each API-request, and that gets reset every hour or however they count usage (e.g. is it "number of requests from 11:00 -> 12:00" or is it a running average or something?)

If rate-limiting publish()es were a crossbar feature, what would be the behavior if you hit the limit? I could imagine: 

 - save the publish() and do it when allowed
 - above, but with  maximum saved-publish queue length
 - error

Perhaps all that collapses to a configurable "queue-length": 0 means always error if the rate-limit was been hit any other number is the maximum queue length (and "unlimited" is not an option). I suspect you'd also want a "bucket name" or similar (e.g. "the evernote rate-limit", "my wonky internal server rate-limit", etc).

**Comment by foxmask** [comment]
As you can imagine i dont know that could exist with twisted. And to say everything, twisted/asyncio are too low API/lib for me. I'm just able to make things speak between each other from the exemples i could read here and there. Even if i'm very exciting by using crossbar when i successfuly can make things work, there are stuff i still dont understand and here even if i understand that twisted provide s what i'm looking for , i wont be able to do it before à long time ;)
Thank for your replies, you can close that request

**Comment by meejah** [comment]
@foxmask Just because you *can* do it yourself doesn't mean it won't be a feature in Crossbar ;)

**Comment by foxmask** [comment]
I understand. But now its not a priority ;)

**Comment by oberstet** [comment]
@foxmask Thx for filing this issue! Please keep it open ..

**Comment by oberstet** [comment]
we need to prioritize. and as @meejah mentions, it's unclear what a generic CB behavior here would look like.
