### ISSUE TITLE
Subscribe to auto_ping events like wamp meta events?

### ISSUE THREAD

**Issue by singlecheeze** [crossbario/crossbar#370]
Hi All,

I'm wondering if it is possible to subscribe to auto_ping events like wamp meta events?

I am using custom authentication/authorization from python 3 guest workers that are disconnecting from the router after some time. I'm guessing their connections are getting killed by mid-stream routers after 20 minutes which is typical on the internet, if they don't pass some traffic in that time. Hence, I was pleased to find the auto_ping capability but would like some print in the console of the router when the ping payload is sent.

http://crossbar.io/docs/Session-Metaevents-and-Procedures/

An old reference of similar type:
https://github.com/tavendo/WAMP/issues/90

Config (Websocket) options I'm referring to:
http://crossbar.io/docs/WebSocket-Options/

auto_ping_interval: Send a WebSocket ping every this many ms (default: null)
auto_ping_timeout: Drop the connection if the peer did not respond to a previously sent ping in this many ms (default: null)
auto_ping_size: Payload size for pings sent, must be between 4 and 125 (default: null)

Thanks for any help!

Dave

**Comment by meejah** [comment]
It is not currently possible to do that.

Ultimately, the auto-ping functionality comes from Autobahn's websocket implementation. If you're experimenting, you *can* turn on ``.debugCodePaths`` and you'll get some output for autoping events *BUT* of course a bunch of other output.

If an auto-ping does timeout, the connection will be immediately aborted. It might be nice if crossbar provided a meta-event when this happens. Arguably, Autobahn should probably log something as well.

To be clear, though, you're actually interested in when every ping goes out?

**Comment by singlecheeze** [comment]
Just some way to know if they are actually responded to. 

A meta event from crossbar would do on disconnect as that would aid troubleshooting, and some way to ensure that you are actually subscribed (a way to send a faux request or something). Ultimately, something is killing my connection over the internet and I know that could be a million things but then again I am over https/SSL so I know it shouldn't be a proxy or something.

Any idea where in the router code this event could "bubble up" from Autobahn?

**Comment by oberstet** [comment]
doesn't make sense
