### ISSUE TITLE
Outbound/reversed websockets for WAMP

### ISSUE THREAD

**Issue by bradmcl** [crossbario/crossbar#372]
Per a brief IRC with meejah, we have an unusual use case:

We're moving towards using WAMP to connect multiple devices at various physical locations to a central cloud server; both for data transfer from those devices to the central server, and for configuration and management commands back to the devices.  This is working well using AutobahnPython, crossbar.io, and wamp ApplicationSessions at both the "server" and the "client" ends, registered with crossbar.io.  In this model, https connections are used over the internet.

We would like to extend this to a legacy product that currently operates using HTTP polling over VPN connections.  In this environment, the central server makes outbound http connections to devices in the field.  The networking configuration is such that the field devices can only receive HTTP connections, and not initiate them. Changing the network configuration would require a large number of renegotiations between multiple organization's IT and security departments, and is thus undesirable.

We would like to be able to have a standalone ApplicationSession on the field device that listens for an inbound WebSocket connection.  In this scenario, we would want to configure crossbar.io to initiate these outbound connections, and then proceed per normal with the field devices using the usual WAMP API after the WebSocket is established.

We could imagine this capability also used for connecting two crossbar.io instances to each other, perhaps across organizational boundaries, although this is not a requirement for us.

It appears that this might intersect / utilize / inform the work here: https://github.com/tavendo/AutobahnPython/issues/409

**Comment by meejah** [comment]
After landing more-configurable transports from tavendo/AutobahnPython#409 it shouldn't be very hard to add the concept of a "listening" (instead of "connecting"/client) transport for ApplicationSession; this would require parallel configuration for crossbar.io whereby you could specify a component that had a "connecting"/client transport (instead of a listening one like now).

I don't believe there would be any deeper issues reversing the roles like this...
/cc @oberstet ?

As far as "federating" two crossbar.io instances, that would be outside the scope of this (but certainly that is on the [roadmap](http://crossbar.io/docs/Roadmap/#multi-core-and-multi-node-support)).

**Comment by oberstet** [comment]
This is a very special, unusual use case indeed. Also, the description suggests it's more about "reverse WAMP-over-HTTP-Longpoll" and not WebSocket (as the title suggests), which makes it even more special. There are no "deep issues", but it's more involved still. Sidenote: federation or clustering with Crossbar.io won't use HTTP, but WebSocket (or RawSocket).

@bradmcl If you are interested in having this feature developed and integrated into AutobahnPython and Crossbar.io, we could certainly provide that under a custom development contract. Please contact me at "tobias dot oberstein at tavendo dot de" if this is an option for your project/company.

**Comment by bradmcl** [comment]
@oberstet To be clear, we're only interested in doing WebSockets in this case, so "reverse WAMP over WebSocket" is accurate.  I mention the existing HTTP connections only for clarity as to why we want to reverse.  I should have been clearer that we're talking about restrictions on the direction in which connections over port 80 or 443 are permitted, but no intention of sticking with HTTP / Longpoll.

**Comment by oberstet** [comment]
wont implement (no time)
