### ISSUE TITLE
Cookie tracking and authentication is broken

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#375]

**Comment by goeddea** [comment]
Updated docs to reflect this.

**Comment by hawkowl** [comment]
I'll have a look at this -- not sure what's broken, do we have what it's desired behaviour is somewhere?

**Comment by oberstet** [comment]
I believe I fixed that already .. but will recheck.

**Comment by oberstet** [comment]
There is a complete working example here https://github.com/crossbario/crossbarexamples/tree/master/authenticate/cookie

I have added a proper README there.

**Comment by oberstet** [comment]
Just pushed cosmetic changes touching this. But it works definitely on trunk.
