### ISSUE TITLE
side-by-side components not working (across all examples)

### ISSUE THREAD

**Issue by goeddea** [crossbario/crossbar#382]
* tried to run authenticate/ticketdynamic, authenticate/cookie, demos/votes/python
* get the following error:

```
[Controller   7024] ApplicationError: ApplicationError('crossbar.error.invalid_configuration', args = ("ERROR: invalid router
 component configuration ('module' object has no attribute 'check_component')",), kwargs = {})
```

`check_component` was split up into `check_router_component` and `check_container_component` and this change wasn't propagated to the relevant bit of code (wherever that is).

**Comment by petercsmith** [comment]
For what it's worth, I'm blocking on this issue too.

**Comment by hawkowl** [comment]
I'll take point on this.

**Comment by hawkowl** [comment]
#388 should fix this issue.
