### ISSUE TITLE
list resources by type doesn't work

### ISSUE THREAD

**Issue by mfojtak** [crossbario/crossbar#394]
Crossbar does not seem to support following procedures:

wamp.reflection.topic.list
wamp.reflection.procedure.list
wamp.reflection.error.list

I am doing something wrong or those are not implemented yet?
It is an essential functionality for me to be able to determine what is registered on a router.

Thank you.

Michal

**Comment by oberstet** [comment]
The WAMP spec rgd meta procs/events isn't finished, and above is outdated.

Crossbar.io implements a superset of the respective functionality:

http://crossbar.io/docs/Session-Metaevents-and-Procedures/
http://crossbar.io/docs/Subscription-Meta-Events-and-Procedures/
http://crossbar.io/docs/Registration-Meta-Events-and-Procedures/

As said, the WAMP spec in this area isn't stable yet.

**Comment by mfojtak** [comment]
I see what you mean. The functionality I need can be achieved by the combination of

       wamp.registration.lookup( uri, { match: "prefix" } )

                                      and

       wamp.registration.get( registrationId )

I assume that wamp.reflection.list functions is a dead end and will never be implemented.
