### ISSUE TITLE
Auto-realms

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#417]
It would be handy if CB had a mode where realms would be created on the fly - as requested by clients. A realm would be configured with anonymous access and allow everything. Hence, a most permissble setup.

In the end, we should get away with something like the following as a default config:

``` json
{
   "workers": [
      {
         "type": "router",
         "options": {
             "auto-realms": true
          },
         "transports": [
            {
               "type": "web",
               "endpoint": {
                  "type": "tcp",
                  "port": 8080
               },
               "paths": {
                  "/": {
                     "type": "static",
                     "directory": ".."
                  },
                  "ws": {
                     "type": "websocket"
                  }
               }
            }
         ]
      }
   ]
}
```

**Comment by oberstet** [comment]
or we could have a global devmode option which does auto-realms and potentially more. and without devmode, we have a strict "nothing runs, nothing is allowed by default" policy and users have to explicitly configure every service / permission?

**Comment by gregkeys** [comment]
+1

**Comment by meejah** [comment]
crossbar should probably also display a Fearsome Warning on startup if this is enabled.

Perhaps also (future enhancement?) accept a ``dict`` for "auto_realms" (as well as True) and if that's specified, it must be a valid realm configuration and is used instead of "allow everything".

**Comment by Usui22750** [comment]
If it is possible to create on the fly a realm, Have you consider the possibility to create a role on the fly?

**Comment by meejah** [comment]
Technically, it's possible and fairly easy to create anything that's in the config on the fly. So, "on demand" roles wouldn't really be any different from realms. What would be the use-case?

**Comment by Usui22750** [comment]
My use case:
Component Authenticator => authenticator
New component B => onChallenge:
{ publish: [b.an_event, b.another_event], register : [b.a_func, b.another_func ...] ...}

The Authenticator create and add the role that match this permission and return it.

**Comment by meejah** [comment]
So rather than "auto-magic" realm creation, maybe what  you really want is a WAMP API to create realms (and/or roles in realms) from within your custom authenticator?

**Comment by gregkeys** [comment]
this would be a great feature, it would certainly solve some issues we are
having with adding clients.

we want to use realms but we have to reboot to add them, also realms
require a dedicated connection from our micro services so for each realm
our services need to open a new connection.

it world be nice if we could have one connection capable of switching
between realms as needed.

**Comment by Usui22750** [comment]
@meejah yes exactly, what I need is an API that allowed me to insert a role, a realm ...

**Comment by gregkeys** [comment]
an api for roles and realms would be  great it would allow the dynamic authorizer to be a better acl system, i imagine we'd build a gui that an admin wound use to create acl levels and rules enforced by the roles,  manager, user, guest, admin, super admin, with microservices the need to add rules and realms on the fly is very important

**Comment by oberstet** [comment]
the management API now (well, loong) allows to dynamically manage realms and roles. fixed
