### ISSUE TITLE
File synch service

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#421]
Provide a service in CB with appropriate API that caches files retrived via HTTP locally on the node. This allows to distribute user components and assets that should be available on the local node.

A HTTP(S) URL is provided, which CB will HTTP/GET from a list of triples:

```
web/static/img/foobar.png:76385c5e8b665edbf47d38456fc64920ab2ef669:http://somewhere.com/something/foobar.png
web/static/img/crap.png::
```

> `::`: delete this file locally

For each triple, CB will check the fingerprint and see if the file was already retrieved, locally stored and if the fingerprint is still the same. If any of these conditions fails, the file is retrieved via the URL in the triple. The information from the triples is saved in LMDB.

**Comment by oberstet** [comment]
Or have a parameter with file refresh list provided as a parameter to the node API call directly:

``` json
[
    {
       "file": "web/static/img/foobar.png",
       "sha1": "76385c5e8b665edbf47d38456fc64920ab2ef669",
       "url": "http://somewhere.com/something/foobar.png"
    }
]
```

**Comment by meejah** [comment]
Since SHA1 is broken this should probably use SHA256 (or better).

**Comment by oberstet** [comment]
@meejah absolutely.

also, maybe multiple hashes (finding parallel collisions in multiple hash functions is considered to be super hard).

https://github.com/multiformats/multihash

**Comment by meejah** [comment]
For bonus points, BLAKE2 "should" have won SHA-3 contest by many people's accounts. I believe it's in `cryptography` library now.

**Comment by oberstet** [comment]
crossbarfx has an `archive` resource that goes beyond above, allowing to dynamically download and directly serve static web stuff from eg a locally cached ZIP file
