### ISSUE TITLE
Basic node monitoring

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#423]

**Comment by taueres** [comment]
Do you have any plan on how to implement the monitoring?
It would be nice to expose an unix socket for data retrieval.
In this way the monitoring application is decoupled from Crossbar itself.

**Comment by siscia** [comment]
:+1: 

I really like the idea of the unix socket, it let also 3rd parties develop it own monitoring tool if necessary, without adding complexity...

**Comment by oberstet** [comment]
Node monitoring will work via Crossbar.io DevOps Center (CDC). Crossbar.io nodes connect to CDC which will provide monitoring UI, but also exposes a WAMP based API for 3rd party tools.

**Comment by oberstet** [comment]
crossbarfx (what in above is refered to as CDC) has that now: edge nodes maintain a management uplink to a master node from which _all_ nodes (even when those sit behind firewalls/NATs) can be monitored (via a WAMP based API)
