### ISSUE TITLE
Add options for register decorator

### ISSUE THREAD

**Issue by singlecheeze** [crossbario/crossbar#429]
Not sure if this has already been addressed, but the @wamp.register decorator does not include args for Register Options: http://crossbar.io/docs/Shared-Registrations/

Also, at the link above, I could only get shared registrations working for a python 3 guest on Crossbar 10.4 with this:
``` python
self.register(self.parse, 'com.example.parse', options=RegisterOptions(invoke='roundrobin'))
```
Not this, like it states in the docs, (I know that it shows a JS example, but I would think the args order would be the same for continuity sake):
``` js
session.register("com.myapp.procedure1", procedure1, { invoke: "roundrobin"});
```
Please add this capability:
``` python
@wamp.register('com.example.parse', options=RegisterOptions(invoke='roundrobin'))
    def parse(self, fname, reg):
```
Or like this:
``` python
@wamp.register('com.example.parse', { invoke: "roundrobin"})
```
This allows for all registrations in a file much easier:
``` python
@asyncio.coroutine
    def onJoin(self, details):
        res = yield from self.register(self)
```
Here:
``` python
def register(uri):
    """
    Decorator for WAMP procedure endpoints.
    """
    def decorate(f):
        assert(callable(f))
        if not hasattr(f, '_wampuris'):
            f._wampuris = []
        f._wampuris.append(Pattern(uri, Pattern.URI_TARGET_ENDPOINT))
        return f
    return decorate
```

**Comment by meejah** [comment]
You can already pass options to the ``self.register(self, options=...)`` call but of course then all the @-decorated registrations get the same options. Not quite as flexible of course.

Something like your above suggestion could probably be made to work as well, so leave this ticket open as an enhancement.

**Comment by oberstet** [comment]
yes, it would be consequent if possible: this is an AutobahnPython issue, pls see https://github.com/tavendo/AutobahnPython/issues/336
