### ISSUE TITLE
Duplicate subprotocols in page http://crossbar.io/docs/WebSocket-Options/

### ISSUE THREAD

**Issue by Budulianin** [crossbario/crossbar#437]
(currently one or more of wamp.2.json, wamp.2.msgpack, wamp.2.json.batched, wamp.2.json.batched)

**Comment by oberstet** [comment]
yes, that is correct. it's the set of accepted subprotocols

**Comment by oberstet** [comment]
but maybe that isn't clear from the wording?

**Comment by oberstet** [comment]
ah, crap. it's getting late: your are right, this isn't the serializers allowed (which is one or more), but the subprotocol, which can only be one. https://github.com/crossbario/crossbardocs/issues/39

**Comment by oberstet** [comment]
@Budulianin https://github.com/crossbario/crossbardocs/blob/master/pages/docs/administration/router/transport/WebSocket-Options.md

better?

**Comment by Budulianin** [comment]
Actually I thought it should be look as `This can be one or more from wamp.2.json, wamp.2.msgpack, wamp.2.json.batched. `

**Comment by oberstet** [comment]
The option itself has type `boolean` and can be `true` or `false`. The "one or more" refers to the list of subprotocols WebSocket clients announce.
