### ISSUE TITLE
Travis/PyPy is broken

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#440]
Travis runs PyPy 2.5 still. This isn't compatible with cryptography 1.0: https://github.com/travis-ci/travis-ci/issues/4756

I'll deactivate, and leave this issue open ..

**Comment by hawkowl** [comment]
We can pin our Cryptography dependency at <=0.9 in the meantime -- it's what we've done for Treq.

**Comment by hawkowl** [comment]
For Travis, that is. We could do a conditional direct dependency in our `setup.py` so that users don't get busted installs on earlier PyPys...

**Comment by oberstet** [comment]
another option: cryptography itself does install a newer pypy for travis: https://github.com/pyca/cryptography/blob/master/.travis/install.sh#L54

**Comment by oberstet** [comment]
Travis is still lagging .. needs to be fixed there
