### ISSUE TITLE
Callee disclose_caller support

### ISSUE THREAD

**Issue by stopthatcow** [crossbario/crossbar#447]
Per the wamp spec [here](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Ftavendo%2FWAMP%2Fblob%2Fmaster%2Fspec%2Fadvanced%2Fcaller-identification.md&sa=D&sntz=1&usg=AFQjCNGhABIjpnSddfu4gw_9OlqEPM_hhQ) there is the concept of allowing a callee to request caller identification via the "disclose_caller" detail being set to true. It appears that this is not currently supported by Crossbar, some googling indicates that it may have been at one point. I would very much like to make use of this ability because it is the callee that is the one who needs the information.

I understand that there might be some conflict with callers wishing to not be disclosed, in this case I should think that crossbar should fail the call if the caller specifically wished to remain anonymous. (By setting 'disclose_me' to False) In lieu of having this set, I think it should be up to the callee to tell crossbar whether or not the caller session ID information is needed as the callee is the one processing that data. 

Without this feature each caller is required to set "disclose_me" to True which seems cumbersome.

**Comment by oberstet** [comment]
This feature, innocent and straight forward on surface, turned out to have various aspects and consequences we first (and soon) will sort out in the WAMP spec. The spec will change.

> CB has gone through various stages and variants rgd this feature. We will adjust CB when the spec is fixed.

**Comment by oberstet** [comment]
This first needs final revise of the definition in the WAMP spec - leaving open for now

**Comment by oberstet** [comment]
This has now been implemented .. please see the example here https://github.com/crossbario/crossbarexamples/tree/master/disclose
