### ISSUE TITLE
Empty authid results in NoneType argument for custom authenticators

### ISSUE THREAD

**Issue by Paranaix** [crossbario/crossbar#452]
Consider the following AutobahnJs code where `authid == ""` (empty string):

    connection = new autobahn.Connection({
         url: wsUrl,
         realm: "main",
         authmethods: [requestedMethod],
         authid: authid,
         onchallenge: onChallenge
    });

Furthermore I have a custom authenticator implemented in python:

    @Register(uri = u"replay.internal.authenticate.user.wampcra")
    @inlineCallbacks
    def Authenticate(self, realm, authid, details, _wampDetails = None)

With the authid being an empty string, yonder authenticator doesn't get an empty string passed as authid though but authid is `None` in the authenticator.

**Comment by oberstet** [comment]
An empty string for `authid` should probably be disallowed anyway. It's not in the WAMP spec, but probably should be.

Do you have a special reason to use an empty, non-null string for `authid`?

**Comment by Paranaix** [comment]
> Do you have a special reason to use an empty, non-null string for authid?

Currently not verifying user input at clientside :P

My point is rather that `None` is a much huger party bummer than an empty string and totally unexpected.

**Comment by oberstet** [comment]
It is now possible to start a WAMP authentication (send HELLO) with an empty `authid`. A dynamic authenticator can determine an `authid` and set that on the principal returned. Crossbar.io will then override (the empty) `authid` with the one returned from the authenticator.

> Note: it's even possible now to also send empty "realm"! Again, authenticators can dynamically map, and Crossbar.io will join the client on the respective realm (which is also returned in WELCOME, so the client knows on which realm it has been joined). You can also redirect: client requests to join "vip", but gets joined to "standard".
