### ISSUE TITLE
Stale WAMP Sessions are not cleaned up when clients have ungracefully dropped their connection

### ISSUE THREAD

**Issue by haroldfredshort** [crossbario/crossbar#456]
Steps to duplicate:
1. Start Crossbar with a websocket endpoint
2. On a separate machine, connect with an Autobahn client (I have used both JS and Python)
3. Have the client register a callee with a fixed name (ex. "hello")
4. Disable the network adapter on the client side - this will leave the session on the server, it does not get cleaned up
5. Reboot the client machine (not necessary for duplicating on Windows)
6. Re-enable the network adapter on the client side
7. Reconnect with the client to the server
8. Try to have the client register a callee with the same name as before
9. This will fail because the name is already in use. The original session and any associated callees are not cleaned up until crossbar is restarted

I have duplicated this on both Windows 10 and Ubuntu 14.04

More realistic disconnection scenarios would involve a client going out of wifi range, or the battery of a client machine dying. With a long running crossbar router, combined with clients that may not always gracefully disconnect, the number of obsolete sessions can build up. When this happens it prevents clients from re-using previously registered callee names associated with the prior session. Currently there does not seem to be any way to detect or clean up stale sessions in Crossbar.

**Comment by meejah** [comment]
I haven't tried to replicate yet, but how long did you wait before re-connecting?

Some TCP timeouts can be quite long (especially, e.g., if there is no traffic trying to be sent down the connection).

**Comment by oberstet** [comment]
That is expected as long as you dont turn on websocket ping pong and auto timeoutnon that.

If you plug out a cable, this no different from a very slow connction. Thats howntcp workd

**Comment by haroldfredshort** [comment]
Ah, so I need to learn about and then enable ping pong and auto-timeout. Thanks!

**Comment by oberstet** [comment]
Yep, this http://crossbar.io/docs/WebSocket-Options/

Eg at the end, there is a section production settings. The timeouts are adjustable. The thing is: on a tcp connection, if you dont send anything and expect a reply, you cant distinguish a plugged cable from a very slow link.

There is another trap: if another client connects faster than the timeout on tje first, the router will not yet have cleaned up the former and registration still fails.

We could do sth about that also, but it gets more tricky: upon the router recognizing a dup ref, instead of failing, it could immediately check the other session for zombie

Am 11.09.2015 10:23 nachm. schrieb Harold Short <notifications@github.com>:

Ah, so I need to learn about and then enable ping pong and auto-timeout. Thanks!

**Comment by haroldfredshort** [comment]
Awesome! I have tried the production settings from that page and it results in the behavior I am looking for. Thanks again.

**Comment by Dencgik** [comment]
Dear Tobias, I apologize that the question isn`t associated with commit. We use the crossbar in our project where clients have a bad dial-up connection (ppp over 2g network).  I can`t find a solution. When call client`s RPC from server and client  breaks the connection. After that my procedure stopped and i have this error :

Traceback (most recent call last):
  File "/home/dencgik/Dropbox/prj/.ps-crossbar/local/lib/python2.7/site-packages/autobahn/wamp/websocket.py", line 95, in onMessage
    self._session.onMessage(msg)
  File "/home/dencgik/Dropbox/prj/.ps-crossbar/local/lib/python2.7/site-packages/crossbar/router/session.py", line 470, in onMessage
    raise ProtocolError(u"Received {0} message, and session is not yet established".format(msg.__class__))
ProtocolError: Received <class 'autobahn.wamp.message.Yield'> message, and session is not yet established


I can`t cath it.
