### ISSUE TITLE
CB does not start on Windows with Python 3.5

### ISSUE THREAD

**Issue by goeddea** [crossbario/crossbar#462]
A twisted issue with Python 3.5 on Windows results in

```
C:\Anaconda3\Scripts>crossbar version
Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\crossbar.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\lib\site-packages\crossbar\controller\cli.py", line 822, in run
    reactor = install_reactor(options.reactor, debug)
  File "c:\anaconda3\lib\site-packages\autobahn\twisted\choosereactor.py", line 133, in install_reactor
    import txaio
  File "C:\Users\coro\AppData\Roaming\Python\Python34\site-packages\txaio\__init__.py", line 110, in <module>
    from txaio.tx import *  # noqa
  File "C:\Users\coro\AppData\Roaming\Python\Python34\site-packages\txaio\tx.py", line 28, in <module>
    from twisted.internet.defer import maybeDeferred, Deferred, DeferredList
  File "c:\anaconda3\lib\site-packages\twisted\internet\defer.py", line 29, in <module>
    from twisted.python import lockfile, failure
  File "c:\anaconda3\lib\site-packages\twisted\python\lockfile.py", line 52, in <module>
    _open = file
NameError: name 'file' is not defined.
```

See this mailing list discussion: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/crossbario/XnHmfy_sF2s/gn0We55xCwAJ

where this Twisted issue is referenced: https://www.google.com/url?q=https%3A%2F%2Ftwistedmatrix.com%2Ftrac%2Fticket%2F7626&sa=D&sntz=1&usg=AFQjCNGKMBi-ovel7b75ukBu92T5krAzjg

**Comment by hawkowl** [comment]
Twisted doesn't support Python 3 on Windows. We're (Twisted) looking into it.

**Comment by tlausch** [comment]
Hey Amber,

there are a lot of changes to run twisted on py3 since the zope 
interfaces decorator
changed in py3, which results in a lot of code changes without change of 
functionality.
from

class XYZ():
     implements(...)

to

@implementer(...)
class XYZ():

and after resolving all file issues, and fixing all the Exception raises 
that are written for py2
there is still the twisted.internet.iocpreactor.iocpsupport missing or 
not yet fully working for windows.
that's where i gave up.

Regards,
Tobias

**Comment by hawkowl** [comment]
Yeah we have a lot of updating to do. We don't yet have a Windows Py3 buildbot to test things on.

Python 3.4+ has inbuilt support for IOCP, so hopefully we can use those bindings...

**Comment by hawkowl** [comment]
We can't fix this directly, but we can prevent people falling over it by bailing out in setup.py.

**Comment by hawkowl** [comment]
I have created a ticket on the Twisted tracker to fix this: https://twistedmatrix.com/trac/ticket/8023

**Comment by hawkowl** [comment]
Verified on a Python 3 on Windows that it does not install:

```
C:\Users\hawkowl>pip install https://github.com/crossbario/crossbar.git
Collecting https://github.com/crossbario/crossbar.git
Operation cancelled by user

C:\Users\hawkowl>pip install https://github.com/crossbario/crossbar/archive/master.zip
Collecting https://github.com/crossbario/crossbar/archive/master.zip
  Downloading https://github.com/crossbario/crossbar/archive/master.zip
     - 610kB 70kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\hawkowl\AppData\Local\Temp\pip-dwqaqj64-build\setup.py", line 42, in <module>
        raise RuntimeError("Crossbar does not support Python 3 on Windows.")
    RuntimeError: Crossbar does not support Python 3 on Windows.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\hawkowl\AppData\Local\Temp\pip-dwqaqj64-build
```

I think we can close this for now; we can re-open it to make sure it works on Windows when we have upstream support.
