### ISSUE TITLE
running 'crossbar' fails (0.11.1, Debian Jessie, Python3)

### ISSUE THREAD

**Issue by petri** [crossbario/crossbar#463]
In a virtualenv created using ```pyvenv --system-site-packages``` (trying to stick to official debian packages where possible), running ```crossbar``` produces:
```
(crossbar) root@zeoserver:/opt/crossbar# crossbar
Automatically choosing optimal Twisted reactor
Running on Linux and optimal reactor (epoll) was installed.
Traceback (most recent call last):
  File "/opt/crossbar/bin/crossbar", line 9, in <module>
    load_entry_point('crossbar==0.11.1', 'console_scripts', 'crossbar')()
  File "/opt/crossbar/lib/python3.4/site-packages/crossbar/controller/cli.py", line 834, in run
    options.func(options, reactor=reactor)
AttributeError: 'Namespace' object has no attribute 'func'
```
First running ```crossbar init```followed by ```crossbar start```works fine though :) So this is a minor issue, thankfully.

However some users might because of this issue conclude that "it does not work" and drop the whole thing which would be a shame...

**Comment by hawkowl** [comment]
Crossbar requires much newer versions of packages than Debian packages, and we don't support running with them. We package an Ubuntu 14.04 package that contains its own PyPy and its own dependencies (down to the latest OpenSSL -- 1.0.2d), and I believe its only dependency (libc) is compatible with Jessie. You can find instructions for installing it here: http://crossbar.io/docs/Installation-on-Ubuntu/

Also, with my Twisted Release Manager hat on -- please don't use Debian versions of Python packages. They're usually outdated, sometimes have random (and downright wrong) patches applied to them, and aren't actually meant to be used by users directly. They're meant to be used for system utilities (things installed though apt) and not third party, non-Debian packaged applications.

**Comment by petri** [comment]
Thanks for explaining!

**Comment by hawkowl** [comment]
No problem. If you run into any issues (the Py3 port is new, and even though the tests pass, there may be lurking bugs) please file another issue. Thanks for using Crossbar! :)

**Comment by petri** [comment]
(For what it's worth, just found out this also happens with a virtualenv that's NOT using system packages installed via apt-get)

**Comment by hawkowl** [comment]
That's... very strange. I can actually reproduce it locally (on py3).

**Comment by hawkowl** [comment]
Sorry, it didn't have anything to do with the site packages at all! I'll fix this.

**Comment by hawkowl** [comment]
Yeah, this is using the stdlib options parser -- I thought it was an older version of click, but the core CLI hasn't been ported to fully use click.

Thanks for this issue, and sorry for misdiagnosing it so quick...

**Comment by hawkowl** [comment]
Yeah, it's an undocumented change with two unfixed bugs about it on the Python issue tracker -- http://stackoverflow.com/questions/23349349/argparse-with-required-subparser . Easy fix (for us) though.
