### ISSUE TITLE
Is File Upload Service documentation error?

### ISSUE THREAD

**Issue by morfair** [crossbario/crossbar#465]
I do File Upload Service follow documentation http://crossbar.io/docs/File-Upload-Service/. It say `"type": "fileupload"` in config.json file, but when I try start Crossbar get error:

```
2015-09-18T12:29:09+0300 [Controller  22142] *** Configuration validation failed ***
2015-09-18T12:29:09+0300 [Controller  22142] invalid type 'fileupload' for sub-path service in Web transport path service 'upload' configuration
```
-
UPD: In Crossbar.io examples repository I found  complete example (https://github.com/crossbario/crossbarexamples/tree/master/fileupload). Need change `type` from `fileupload` to `upload`.
I have another question. How I can make something with uploaded files? I suppose I need in some appropriate ApplicationSession. Right?

**Comment by goeddea** [comment]
Fixed in the documentation (will be deployed shortly). Thanks for pointing this out!

Regarding the question what you can do with the uploaded files: You could e.g. serve them using the integrated Web server, access them from an application session - or from any other processes/applications.

**Comment by morfair** [comment]
Where I can set ApplicationSession class that will be handle successfully uploaded file (resize image, convert audio, store info in DB)?
