### ISSUE TITLE
Need callback for File Upload Service

### ISSUE THREAD

**Issue by morfair** [crossbario/crossbar#466]
Where I can set ApplicationSession class that will be handle/serve successfully uploaded files (resize image, convert audio, store info in DB, generate unique filename etc.)?

**Comment by goeddea** [comment]
Do I understand you correctly: You want some way for Crossbar.io to trigger/notify after a file upload has completed.

In my opinion, triggering actions based on a completed file upload should be handled entirely at the application level. The action to take, and whether to take an action at all, depends on what the file upload is to be used for. The component doing the upload is the correct place to trigger anything - and this just sends a WAMP message to which the handling component reacts. 

Alternatively: There is also the possibility to watch the upload directory and then trigger things based on that.

**Comment by morfair** [comment]
Yes, you understood correctly. Can I see example?

**Comment by meejah** [comment]
The documentation points to this example in the crossbarexamples repository: https://github.com/crossbario/crossbarexamples/tree/master/fileupload

What @goeddea means I think is that you can, on the client-side, .publish() an event when the upload is completed. So, in a JS client, you'd want to ``.publish(u"com.example.file_uploaded", fname)`` by using the Resumable hooks that tell you when the upload has completed.

**Comment by singlecheeze** [comment]
I see a gap here...

One, what if client disconnects after upload completes before a publish or call can be sent? I know the window is small but it could happen.

Two, since there is already a progress publish, and I'm assuming when that get to 100 you could trigger something from the client, why not add a completion publish as well?
```js
session.subscribe('com.example.upload.on_progress', function (args) {
            var pinfo = args[0];
            console.log('upload event received', pinfo.status, pinfo.chunk, pinfo.remaining, pinfo.total, pinfo.progress);
         });
```

**Comment by goeddea** [comment]
@singlecheeze - The URL to publish to is passed as part of the creation of the Resumable. There is no default URL - if nothing is passed, then there are no progress publishes. 

Regarding your original question: I see now what you mean in practice. You want a callback "on_success" in addition to "on_progess". This makes sense.

@markope - is this something you could add?

**Comment by singlecheeze** [comment]
```text
     __  __  __  __  __  __      __     __
    /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
    \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
                                        
 Crossbar.io        : 0.11.2
   Autobahn         : 0.10.9
     UTF8 Validator : autobahn
     XOR Masker     : autobahn
     JSON Codec     : stdlib
     MsgPack Codec  : -
   Twisted          : 15.4.0-EPollReactor
   Python           : 3.4.0/CPython
 OS                 : Linux-3.19.0-28-generic-x86_64-with-Ubuntu-14.04-trusty
 Machine            : x86_64
```

**Comment by markope** [comment]
Would'nt it be a solution to just subscribe to the progress topic and check if the payload contains a key/value: `status: "finished"` ? That's your on_success event.

Even thought the topic is specified by the resumable session it is used only by a service session in crossbar. I believe that doesn't go down even if the resumable session goes down. So a file upload success would still get delivered I assume.

**Comment by goeddea** [comment]
@markope - My bad for not actually trying things out. That, of course, works!

**Comment by singlecheeze** [comment]
Thanks guys, sorry for the cycles on this, I would have probably seen that too, just got to get it working on python 3 first ;)

**Comment by markope** [comment]
no problem. I'm happy if my contribution is useful :-)
