### ISSUE TITLE
Worker Connection to Router over WSS

### ISSUE THREAD

**Issue by ericchapman** [crossbario/crossbar#469]
Hey guys,
I have a centralized router behind an NGINX SSL termination.  I have no issues connecting external clients to the router over WSS.  I also have no issues connecting using an ApplicationRunner over WSS  The issues I have arise when I try to connect a crossbar client.  Here is my configuration file

```
{
   "controller": {
   },
   "workers": [
      {
         "type": "container",
         "options": {
            "pythonpath": [".."]
         },
         "components": [
            {
               "type": "class",
               "classname": "src.app_session.AppSession",
               "realm": "realm1",
               "transport": {
                  "type": "websocket",
                  "endpoint": {
                     "type": "tcp",
                     "host": "example.com",
                     "port": 8080
                  },
                  "url": "**wss**://example.com:8080/ws"
               }
            }
         ]
      }
   ]
}
```

I observed the following error during the connection

```
failing WebSocket opening handshake ('WebSocket connection upgrade failed (400 - BadRequest)')
```

Usually these sort of issues point to SSL in some fashion.  I verified this by doing the following

  - Changed "wss" to "ws".  The same error occurred
  - I connected to the same router via "ws" bypassing the NGINX SSL termination and this worked

I know TLS is not fully implemented yet but this is not full TLS, this is just a WSS (SSL) connection.  Am I misunderstanding something or is this an issue?  Is XBAR ignoring the "WSS" in the "url" path of the config?

**Comment by meejah** [comment]
Can you try putting: ``"tls": {}`` in the ``endpoint`` dict?

By "crossbar client" do you just mean the component in the above, or is the posted config for a second crossbar instance...?

**Comment by ericchapman** [comment]
@meejah It worked!!  Thanks.

I meant the component in the above.  I may be using the wrong terminology.  A "container"?

**Comment by goeddea** [comment]
@ericchapman - "client running in a container" would probably be our terminology, since containers can also run non-WAMP client code.
