### ISSUE TITLE
Node.js console.log not working in 0.11.0

### ISSUE THREAD

**Issue by malytic** [crossbario/crossbar#471]
```console.log("foo bar")``` normally shows as ```2015-09-28 17:00:00+0000 [Guest 2688] foo bar```
With the new logger in 0.11.0 you get ```2015-09-28T17:00:00+0000 [Guest 2688] 'foo bar\n'```

Objects like ```console.log({ foo: "bar" })``` shows up as errors:

```2015-09-28T17:00:00+0000 [Guest        2688] Unable to format event {'cb_namespace': 'FD1', 'log_system': 'Guest        2728', 'log_logger': <Logger 'crossbar.controller.processtypes.GuestWorkerProcess'>, 'log_level': <LogLevel=info>, 'log_namespace': 'crossbar.controller.processtypes.GuestWorkerProcess', 'log_source': None, 'log_format': '"{ foo: \'bar\' }\\n"', 'log_time': 1443459804.929515}: u' foo'```

**Comment by goeddea** [comment]
Just tried this and with the 0.11.0 release I get the "\n" lines, but no actual errors in logging. With current trunk (tried both on Windows and Ubuntu) logging works as expected. 

Could you please try running current trunk and see if the problem persists for you?

**Comment by oberstet** [comment]
@malytic also, please try with current release: 0.11.1, not 0.11.0

**Comment by malytic** [comment]
Unfortunately I've not been able to install from source and test on 0.11.1 yet.

This is what I've tried so far:

Clean install of 0.11.0 official binary packages for Ubuntu 14.04 LTS.
```
 Crossbar.io        : 0.11.0
   Autobahn         : 0.10.7
     UTF8 Validator : autobahn
     XOR Masker     : autobahn
     JSON Codec     : stdlib
     MsgPack Codec  : msgpack-python-0.4.6
   Twisted          : 15.4.0-EPollReactor
   Python           : 2.7.10/PyPy-2.6.1
 OS                 : Linux-3.13.0-52-generic-x86_64-with-debian-jessie-sid
 Machine            : x86_64
```

Install the hello demo `crossbar init --template hello:nodejs --appdir hello`

Replace `console.log("published to 'oncounter' with counter " + counter)` 
with `console.log({foo: "bar"})` in `node/hello.js`

```
2015-10-02T17:53:58+0000 [Guest       31370] Unable to format event {'cb_namespace': 'FD1', 'log_system': 'Guest       31370', 'log_logger': <Logger 'crossbar.controller.processtypes.GuestWorkerProcess'>, 'log_level': <LogLevel=info>, 'log_namespace': 'crossbar.controller.processtypes.GuestWorkerProcess', 'log_source': None, 'log_format': '"{ foo: \'bar\' }\\n"', 'log_time': 1443808438.33891}: u' foo'
```

**Comment by goeddea** [comment]
Checked on Ubutuntu - 0.11.0 installed from binary packages gives me the error, but it's fixed on 0.11.1 installed from trunk.

**Comment by malytic** [comment]
Installed 0.11.1.1 from binary packages on Ubuntu 14.04.3 and it's the same errors.
```
 Crossbar.io        : 0.11.1
   Autobahn         : 0.10.9
     UTF8 Validator : autobahn
     XOR Masker     : autobahn
     JSON Codec     : stdlib
     MsgPack Codec  : msgpack-python-0.4.6
   Twisted          : 15.4.0-EPollReactor
   Python           : 2.7.10/PyPy-2.6.1
 OS                 : Linux-3.19.0-30-generic-x86_64-with-debian-jessie-sid
 Machine            : x86_64
```
It's not only a cosmetic issue with quotation marks and newline characters, the big problem is that the logs get concatenated when there is much logging going on. Like so:
```
for (i = 1; i < 15; i++)
   console.log("loop"+i)
```
```
2015-10-11T21:53:42+0200 [Guest        8201] 'loop1\n'
2015-10-11T21:53:42+0200 [Guest        8201] 'loop2\n'
2015-10-11T21:53:42+0200 [Guest        8201] 'loop3\n'
2015-10-11T21:53:42+0200 [Guest        8201] 'loop4\nloop5\nloop6\nloop7\nloop8\nloop9\nloop10\nloop11\nloop12\nloop13\nloop14\n'
```

**Comment by oberstet** [comment]
This is expected, as Crossbar.io will not split the output received from the worker into separate lines for logging. Maybe we can do better, as I can see this is a little annoying. But it's cosmetics. @hawkowl ?

**Comment by malytic** [comment]
Found a solution, none of the errors occur when using `console.error` instead of `console.log`. The difference is that `console.error` prints to stderr. Maybe this could be included in [Logging-in-Crossbar.io](http://crossbar.io/docs/Logging-in-Crossbar.io/), otherwise I think it's safe to say that this matter can be closed.

**Comment by oberstet** [comment]
@hawkowl does logging from guests behave differently when done over stderr vs stdout?
