### ISSUE TITLE
amqp bridge

### ISSUE THREAD

**Issue by tardyp** [crossbario/crossbar#472]
There is a lot of support for amqp connectors in various applications.
e.g:
https://wiki.jenkins-ci.org/display/JENKINS/RabbitMQ+Build+Trigger+Plugin

That would be nice to have support for a crossbar.io to forward wamp pub messages to an amqp queue.

Is this something in the roadmap?

**Comment by oberstet** [comment]
We don't have AMQP bridging on the roadmap (the queue is more than full ..), but in principle, yes, I can see the use case.

In general, Crossbar has a sophisticated REST bridge to integrate with other systems, please see [here](http://crossbar.io/docs/HTTP-Bridge/).

In particular, the Webhooks service lets you integrate with other systems using configuration only! E.g. here is how to receive GitHub hooks as WAMP events.

**Comment by tardyp** [comment]
My usecase was more the opposite. having Jenkins to fire on buildbot's wamp messages.
Thanks anyway!

**Comment by oberstet** [comment]
Ah, ok. Does Jenkins provide any kind of REST API to trigger off stuff? Or only AMQP?

**Comment by tardyp** [comment]
yes it does. it is not really REST, but that could work.
https://wiki.jenkins-ci.org/display/JENKINS/Remote+access+API

**Comment by oberstet** [comment]
@tardyp Its highly unlikely that we find the resources to add a full-blown AMQP bridge anytime soon. But your concrete use case (trigger Jenkins from WAMP) is something we definitely had in mind with the HTTP Bridge Services in Crossbar.io .. so migrated to https://github.com/crossbario/crossbarexamples/issues/70
