### ISSUE TITLE
Long Polling reset connection

### ISSUE THREAD

**Issue by norn** [crossbario/crossbar#477]
I ran longpoll from crossbarexamples and found the following issue.
If I raise sleep timer to 5 instead of 1, it resets the connection and do subscribe things again and again. 

After debugging I've found that request_timeout is applied to the HTTP connection and it resets after default timeout 2000ms. I pass 60000ms request_timeout to transport and everything goes well.

Obviously 2s is not enough for such connection. So the default timeout should be changed or docs should be updated with this information.

![lp](https://cloud.githubusercontent.com/assets/90081/10316767/4c6b6e8e-6c61-11e5-81ae-c730d1c78066.jpg)

**Comment by goeddea** [comment]
If I understand you correctly:

The [documentation on long-poll](http://crossbar.io/docs/Long-Poll-Service/) states that the default timeout for requests is 10 seconds, but the default timeout which is actually applied is 2 seconds.

Where do you get the 2 seconds timeout from?

**Comment by norn** [comment]
Oh, sure, I had to point out AutobahnJS.
To solve the problem it should be initialized with request_timeout:
```
transports:[{
                  'type': 'longpoll',
                  'url': <url>,
                  'request_timeout': 60000
}]
```
because of the following in **autobahn.js**

```
<skipped>
      var txseq = 0;
      var rxseq = 0;

      var options = {'protocols': ['wamp.2.json']};
      var request_timeout = self._options.request_timeout || 2000;
<skipped>
```

To replicate the problem you can run **longpoll** example from **crossbarexamples** and set _yield sleep(5)_ in **backend.py**

**Comment by oberstet** [comment]
There are 2 timeouts being applied to long poll requests: a router side timeout, which indeed is 10s (https://github.com/crossbario/crossbar/blob/master/crossbar/worker/router.py#L1065), and a client side timeout, which in AB JS is indeed 2s.

The router timeout works like this: when there is nothing to be received for the client, the router with **nevertheless** return from the long-poll request after 10s. With nothing. This is necessary to prevent intermediaries to timeout the whole connection.

The client timeout works like this: when the client does a HTTP long-poll, and it doesn't return after 2s, bail out.

The bugs here are:

1. docs
2. the default on the client should be larger than the default on router. eg. make it 15s in AB JS

**Comment by goeddea** [comment]
So I've increased the timeout in Autobahn|JS to 12 s, and added a reference to client timeouts being a separate issue to the Crossbar docs.

What I have no idea about is how increasing the timeout in Crossbar.io may fix anything with a client.-side timeout.

**Comment by norn** [comment]
Great, thanks
