### ISSUE TITLE
DH is broken?

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#482]
https://freedom-to-tinker.com/blog/haldermanheninger/how-is-nsa-breaking-so-much-crypto/

**Comment by meejah** [comment]
For 1024-bit DH, particular primes in common use are probably broken.

Re-generating ``dhparams.pem`` on most SSL deployments should be sufficient to fix them against this. Or use elliptic-curves.

**Comment by oberstet** [comment]
Yeah, I've skimmed over the article (not the paper), and it seems (as you say) that only particular primes could have been broken.

Crossbar.io does not use a hard-coded DH params but [requires](https://github.com/crossbario/crossbar/blob/master/crossbar/twisted/tlsctx.py#L290) an explicit `dhparams` file, and [explains](http://crossbar.io/docs/Secure-WebSocket-and-HTTPS/#diffie-hellman) how to generate a deployment specific one .

What I wanted to reassess is: is above enough? I the `dhparam` file generated really about those primes used?

The answer [here](http://security.stackexchange.com/a/38207/46922) seems to say so .. but.

FWIW, Crossbar.io also **only** enables exactly 6 ciphers per default (in this order):

1. ECDHE-RSA-AES128-GCM-SHA256
2. DHE-RSA-AES128-GCM-SHA256
3. ECDHE-RSA-AES128-SHA256
4. DHE-RSA-AES128-SHA256
5. ECDHE-RSA-AES128-SHA
6. DHE-RSA-AES128-SHA

At the time I wrote that code (tlsctx.py), I "hand-selected" those .. and they still seem to make sense. Not sure about the _order_ though. Maybe put all EC ones before the DH ones.

**Comment by oberstet** [comment]
I now remember, that I once even thought about generating a DH params file on a background thread periodically .. 

With EC, the question of "which curve?" arises .. FWIW, Crossbar.io uses NIST P-256, and I spent some time talking to crypto guys on this https://github.com/crossbario/crossbar/blob/master/crossbar/twisted/tlsctx.py#L206 too ..

Does cryptography support djb's Curve25519 nowerdays? Not that it would work in practice (browsers) ..

**Comment by meejah** [comment]
I don't believe cryptography.io supports 25519. I think https://github.com/agl/curve25519-donna is probably the preferred Python bindings? Then for signatures, there's https://github.com/warner/python-ed25519

But, yeah, I think it's basically "NIST curve or nothing" for browser compatibility :(

Re-generating dhparams periodically should keep you pretty safe, so the instructions as they exist I think are fine. They could perhaps benefit from some statement/link explaining this? With 2048-bit keys, *not* regenerating them should also "probably" be fine. For bonus points, the shell-snippet could be upgraded to use 4096 bits.

That said, I am not a cryptographer ;)

**Comment by oberstet** [comment]
> With 2048-bit keys, not regenerating them should also "probably" be fine. For bonus points, the shell-snippet could be upgraded to use 4096 bits.

Done: http://crossbar.io/docs/Secure-WebSocket-and-HTTPS/#diffie-hellman
