### ISSUE TITLE
Postgres Callee Support

### ISSUE THREAD

**Issue by Kostronor** [crossbario/crossbar#495]
I am trying to integrate PostgreSQL into my application and found that the callee features are a stub at the moment:

https://github.com/crossbario/crossbar/blob/master/crossbar/adapter/postgres/callee.py

What are the plans there? When to expect what and can I help?

**Comment by goeddea** [comment]
We are planning to implement further integration, but cannot give you a timeline. 

Contributions are always welcome! If you want to implement this then I would suggest giving a heads up about how you want to do so here. Better to have initial discussions than to send a pull request and come across problems we see with a particular approach only then.

**Comment by Paranaix** [comment]
Could someone maybe explain to me what the purpose/goal of yonder callee is?

**Comment by oberstet** [comment]
@Paranaix The PG callee role allows to expose database stored procedures as WAMP procedures to be called transparently from any WAMP client.

**Comment by oberstet** [comment]
The PostgreSQL integration will live in its own project https://github.com/crossbario/autobahn-postgres
