### ISSUE TITLE
Create a crossbar-postgresql binary package

### ISSUE THREAD

**Issue by Kostronor** [crossbario/crossbar#496]
The official documentation links to an ubunto repository:
http://crossbar.io/docs/Installation-on-Ubuntu/

But the repo `deb http://package.crossbar.io/ubuntu trusty main` does not contain extras like PostgreSQL support. 

Can this be added?

**Comment by meejah** [comment]
@hawkowl does this make sense to add?

**Comment by Kostronor** [comment]
@meejah @hawkowl perhaps add a crossbar-extra package, so people have a choice? That would be a quick solution I think.

**Comment by oberstet** [comment]
Support for external databases like PostgreSQL requires a driver. Bundling that with the standard Crossbar.io package doesn't really make sense in my view. Its different with the embedded LMDB Crossbar.io will use for session and message persistence. You can enable support by pip install X for the db driver and CB will enable respective features automatically.

**Comment by Kostronor** [comment]
@oberstet Is there a possibility to have a second package that includes drivers? For people like me for whom pip does not work?

**Comment by oberstet** [comment]
Not in general. If the database driver allows redistribution in binary form, then yes. Which the PostgreSQL driver libpq and eg psycopg2 allow for, but not eg the Oracle driver. cx_oracle yes, but not the required Oracle thin driver package. At least not without being required to fulfil some strings we don't want to be bound to. So it could only be a specific crossbar-postgresql package.

Am 30.10.2015 10:14 nachm. schrieb Marvin Hofmann <notifications@github.com>:

@oberstet<https://github.com/oberstet> Is there a possibility to have a second package that includes drivers? For people like me for whom pip does not work?

**Comment by Kostronor** [comment]
@oberstet A crossbar-postgresql package seems like the way to go then.

**Comment by oberstet** [comment]
Yep, I agree that would be nifty.

Am 30.10.2015 11:29 nachm. schrieb Marvin Hofmann <notifications@github.com>:

@oberstet<https://github.com/oberstet> A crossbar-postgresql package seems like the way to go then.

**Comment by oberstet** [comment]
closing, as this won't live in CB itself, but here https://github.com/crossbario/autobahn-python
