### ISSUE TITLE
Single Server setup - How to connect User with requests?

### ISSUE THREAD

**Issue by Kostronor** [crossbario/crossbar#497]
I am writing an Application where there is a server component receiving rpc calls from clients. 

What is the canonical way of getting the username/userid/etc on each procedure call to associate this call with the user? 

I tried setting `disclose_me` to true, but sadly in jawampa there is no way to get to that information (Matthias247/jawampa#74) and even then I only have a session id, how can I get the username from there, since session id's are not persistent?

**Comment by goeddea** [comment]
@Kostronor - This is an issue tracker, not a support forum. Questions like this belong on the mailing list - https://groups.google.com/forum/#!forum/crossbario

`disclose_me` currently sends the sessionID (though we may add authID and authRole soon).

This is indeed ephemeral. You can retrieve information about the session by using the session meta api and call `wamp.session.get`. This will give you information about how the client was authenticated.

How you correlate this with actual users is then an app-level question, and depends how you identify the user during authentication and how you authenticate.

**Comment by Kostronor** [comment]
Thanks a lot for the reply!

Will send such requests to the mailing list next time, sorry!

I will try to submit a pull request adding authID and authRole to `disclose_me`
