### ISSUE TITLE
component cannot be started with `role` in config

### ISSUE THREAD

**Issue by goeddea** [crossbario/crossbar#507]
from http://stackoverflow.com/questions/33504822/how-to-set-component-role-in-autobahn

The documentation claims that a role can be set on a router component through the attribute `role` in the config. This, however, does not pass a config check.

To replicate, just add `role` to hello:python

```
{
           "type": "class",
           "classname": "hello.hello.AppSession",
           "realm": "realm1",
           "role": "anonymous",
```
and then do `crossbar check`

**Comment by meejah** [comment]
I believe the "role" is only valid for "in-router" components? Not for components in a container. For example, see the ``authenticate/wampcra`` router configuration in crossbarexamples.

It's not completely clear in the stackoverflow question which case this is.

In any case, the documentation should be clarified on this point :)

**Comment by meejah** [comment]
For components in containers, you would assign the role via authentication.

**Comment by meejah** [comment]
I'm going to leave this open for now, as I think all the authentication documentation needs a bit of an overhaul. For one thing, you have to dig into "Administration" to find it -- there should at least be a pointer in the "programming guide" describing both sides ("client" and "server"/router). Probably as its own heading alongside Pub/Sub and RPC?

Orthogonal to the above, it would probably be nice to provide a way to "merely configure" the client-side credentials. Currently, you have to put in quite a bit of boilerplate, overriding ``onConnect`` and ``onChallenge`` just to put in your secret -- a way to add "authid" and "secret" or similar to the component configuration somewhere would be a big win here, I think (and be analogous to the "static" credentials on the router side).

**Comment by meejah** [comment]
Related: https://github.com/crossbario/autobahn-python/pull/491 (although I don't think the details of how the secrets are configured in that PR are necessarily very good).

**Comment by oberstet** [comment]
> I believe the "role" is only valid for "in-router" components? Not for components in a container.

correct
