### ISSUE TITLE
Exceptions from side-by-side components broken?

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#513]
Add the following to `RouterServiceSession` in `service.py`:

```python
    @wamp.register(u'wamp.test.exception')
    def test_exception(self):
        raise ApplicationError(u'wamp.error.history_unavailable')
```

and call that from a client. It seems, the exception doesn't get through to the client. Which would be bad for the WAMP meta API. Or anything running as side-by-side?

**Comment by slav0nic** [comment]
```python
            raise ApplicationError('error1')
            raise ApplicationError('error', message="error2")
            raise ApplicationError('error', "error3")
```
only error3 raised correct
as result ApplicationError doesn't work in standard crossbar RPC: https://github.com/crossbario/crossbar/blob/063741119acbe045df3775a47531883a6c063e9b/crossbar/router/service.py#L138 for example not raised

**Comment by meejah** [comment]
see https://github.com/crossbario/autobahn-python/pull/565

**Comment by meejah** [comment]
@slav0nic to follow-up, the ApplicationError('error.uri', message=) form isn't actually the API that ApplicationError gives; the message should be the first arg. I've changed crossbar to reflect this, see #541
