### ISSUE TITLE
send authid + authrole as part of caller identification

### ISSUE THREAD

**Issue by goeddea** [crossbario/crossbar#514]
We currently only provide the sessionID to save on wire traffic. Several users have asked for more information to be provided. `authID` and `authrole` are the most request and should cover 80%+ of those cases.

We've discussed this internally and there seems to be no good reason not to add these two pieces of information. 

WAMP issue for this: https://github.com/wamp-proto/wamp-proto/issues/57

**Comment by oddjobz** [comment]
Hi, it would be *fantastic* to have these fields back again .. my stuff fell apart previously when it was removed and I feel like I've been jumping through hoops to compensate ever since ...

**Comment by Paranaix** [comment]
This could be made optional.

**Comment by oddjobz** [comment]
See my comments on; 
> WAMP issue for this: wamp-proto/wamp-proto#57

:)

**Comment by oberstet** [comment]
This is now implemented: both for caller and for publisher disclosure. Both now get 3 pieces of info:

* sessionid
* authid
* authrole

**Comment by agronholm** [comment]
Excellent news. But this needs support in Autobahn as well, right?

**Comment by oddjobz** [comment]
Ok, this will be good .. will aim to try this on Friday ...

**Comment by oberstet** [comment]
It's supported in AutobahnJS and AutobahnPython trunk already. Please see crossbarexamples/disclose.

We'll add black/whitelisting based on aurhid/role too. Probably expand the WAMP meta API in CB as well.
