### ISSUE TITLE
Cluster / Scalability?

### ISSUE THREAD

**Issue by KrishnaPG** [crossbario/crossbar#515]
Any documentation / info on Crossbar.io peformance and scalability possibilities?

How easy / difficult it is to cluster multiple crossbar.io servers (to achieve something similar to mqtt bridges) so that,
*   clients can connect to closest (geographically) server automatically, and
*   auto fault-tolerance / failover is achieved in case of server failures, and
*   dynamic instances can be spawned to offload new clients to the new server instances (handling spikes in traffic)

If currently these auto-failover scenarios are not available, are they in the plan for future versions?

For example, two crossbar io instances, one handling only pub-sub and other handling only rpc, but each failover to the other in case of any one going down.

**Comment by oberstet** [comment]
This is a bug tracker

**Comment by jonahzheng** [comment]
What about this question?
Any documentation / info.

**Comment by goeddea** [comment]
@KrishnaPG - so please address your questions to e.g. the mailing list - https://groups.google.com/forum/#!forum/crossbario
