### ISSUE TITLE
Error in error reporting on missing file referenced in config

### ISSUE THREAD

**Issue by rafzi** [crossbario/crossbar#517]
Crossbar logs:
>2015-11-19T18:01:32+0100 [Controller   2275] Could not start node: 'int' object has no attribute 'strip'

Seems to originate from node.py "start" function.
>"for line in e.args[0].strip().splitlines():"

When looking in the debugger the exception being processed is:
`<twisted.python.failure.Failure autobahn.wamp.exception.ApplicationError: ApplicationError('wamp.error.runtime_error', args = (2, u'No such file or directory'), kwargs = {})>`

So the code applies ".split" to the integer "2".

The error seems to be caused by missing TLS files like tls.key, tls.crt, dhparam.pem.

Bonus: It would be useful to further specify which file is missing to tell the user what is wrong.

**Comment by meejah** [comment]
Hmm, yeah that's bad. We really shouldn't depend on the type of the args to exceptions (nor how many of them there are, actually).

**Comment by meejah** [comment]
@rafzi can you post the config-snippet that was giving you problems? The config should actually be validated properly before we even try to ``start()`` so that's a problem as well

**Comment by rafzi** [comment]
The router config.json referenced here causes the error if the files "ws.key", "ws.crt" and "dhparam.pem" are missing.

https://github.com/crossbario/crossbar/issues/499
