### ISSUE TITLE
Debug_wamp on Router

### ISSUE THREAD

**Issue by alvistar** [crossbario/crossbar#526]
Hi,
I noticed debug_wamp was removed in router/protocol.py. 
It used ton be:
        websocket.WampWebSocketServerFactory.__init__(self,
                                                      factory,
                                                      serializers=serializers,
                                                      url=config.get('url', None),
                                                      server=server,
                                                      externalPort=externalPort,
                                                      debug_wamp=self.debug)

This disable the possibility to log wire traffic on WAMP. Is this on purpose? If yes, why?

**Comment by hawkowl** [comment]
Hi,

You can use the new `--loglevel=trace` to display individual WAMP messages being sent. Is this what you're looking for, or are you wanting the actual bytes sent over the wire to be logged?

**Comment by alvistar** [comment]
Thanks. I just checked and this should be enough for logging.

Is there a way also to debug the bytes on wire?

**Comment by meejah** [comment]
Looks like this came with #339 removing the ``debug`` config item. There doesn't appear to be a way to set this currently (but formerly, setting ``debug`` to true would ultimately turn on ``logOctets`` in the underlying Autobahn classes, I believe).

Obviously, you could use ``wireshark`` or similar, but...there is no longer a ``debug`` option is the point.
