### ISSUE TITLE
Caller is not notified about callee disconnection during the call execution

### ISSUE THREAD

**Issue by nj4x** [crossbario/crossbar#532]
Hello!

To reproduce this issue I've used standard code from crossbarexamples-master\hello\csharp

gist: https://gist.github.com/nj4x/ee1bd3df790bc0c74136

Steps
a) start crossbar.io router using .crossbar\config.json from the gist above
b) compile and start callee (c#)
c) run index.html and check JavaScript console

In short time callee (serving Add2 demo method) will block on its response
Caller prints ''add2() - No Result!'' message until it gets a result or error
When you kill callee - nothing will happen, but error at client side is expected.

Please advise correct configuration of crossbar.io (I've already tried to use "production settings" from http://crossbar.io/docs/WebSocket-Options/) or accept this issue as a bug.

**Comment by nj4x** [comment]
ignored?

**Comment by nj4x** [comment]
Dear crossbar.io team,

Please leave your comment at least.

Thanks!

**Comment by goeddea** [comment]
What do you mean by "killing he callee"? In case of an orderly shutdown this should close the connection cleanly and return an error. If you e.g. remove the cable, or do a hard shutdown of the machine the callee is on, then, without a proper shutdown, Crossbar cannot distinguish a severed connection from a very, very slow one. If you're talking about the later, then enable WebSocket pings in the router so that Crossbar.io can detect the severed connection.

**Comment by nj4x** [comment]
By "killing the callee" I mean that callee is crashed for some reason or
network conection became unavailable.

I'll try your suggestinos, thanks!

**Comment by nj4x** [comment]
Enabled WebSocket pings:

                  "ws": {
                     "type": "websocket",
                     "options": {
                         "auto_ping_interval": 1000,
                         "auto_ping_timeout": 2000,
                         "auto_ping_size": 64
                      }                  
                   }

Result is the same, caller gets hanged on callee disappearing during the call

**Comment by nj4x** [comment]
Do you say that crossbar.io router does not detect that callee gets disconnected?

**Comment by oberstet** [comment]
There are 2 different scenarios:

Callee disappears, while no invocation is currently in-flight to that callee => this is definitely detected with the ping/pong settings above. Crossbar.io will automatically unregister any procedures registered by the disappeared callee, and subsequent calls will fail ("no callee registered for proc ..").

Callee disappears, while an invocation is in-flight: that is, a caller was doing a call, Crossbar.io forwarded the call to a callee (=> invocation), but _before_ that invocation returns from the callee, the callee disappears.

Are you referring to the first or second scenario?

**Comment by nj4x** [comment]
I'm referring to the second scenario

**Comment by oberstet** [comment]
I think this is a bug in Crossbar.io: when a client session disappears, all subscriptions/registrations are automatically dissolved, but invocations already in-flight should lead to the original calls to be failed.

**Comment by nj4x** [comment]
thanks!

**Comment by mattcorona84** [comment]
Hi everybody,
I've exactly the same problem (scenario 2) using crossbar version 0.13.2.
Is this bug still unsolved in this version or maybe could be something wrong in my config.json file?
this is the part that could be wrong. Hope you can help!!!Thanx a lot. Matteo

"transports": [
        {
          "type": "web",
          "endpoint": {
            "type": "tcp",
            "port": 80
          },
          "paths": {
            "/": {
              "type": "static",
              "directory": "../../web"
            },
            "ws": {
              "type": "websocket",
              "auth": {
                "anonymous": {
                  "type": "dynamic",
                  "authenticator": "com.example.authenticate"
                },
                "ticket": {
                  "type": "dynamic",
                  "authenticator": "com.example.authenticate"
                }
              }
            }
          },
          "options": {
            "auto_ping_interval": 5000,
            "auto_ping_timeout": 5000,
            "auto_ping_size": 4
          }
        },
        {
          "type": "websocket",
          "endpoint": {
            "type": "tcp",
            "port": 9000
          },
          "serializers": [
            "json"
          ],
          "options": {
            "auto_ping_interval": 5000,
            "auto_ping_timeout": 5000,
            "auto_ping_size": 4
          }
        }
      ],

**Comment by goeddea** [comment]
@mattcorona84 - Could you test with the current version (0.15.0) and report back whether this is still a problem?

**Comment by mattcorona84** [comment]
crossbar 0.15.0 won't work on my system.
Output for crossbar check :

Traceback (most recent call last):
  File "/usr/local/bin/crossbar", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/crossbar/controller/cli.py", line                                  972, in run
    if options.cdc:
AttributeError: 'Namespace' object has no attribute 'cdc'
---------------------------------------------------------------------------------------------------------------
output for crossbar version:

 Crossbar.io        : 0.15.0
 Autobahn         : 0.15.0 (with JSON, MessagePack, CBOR, UBJSON)
 Twisted          : 16.3.0-EPollReactor
 LMDB             : 0.89/lmdb-0.9.18
 Python           : 2.7.9/CPython
 OS                 : Linux-3.16.0-4-amd64-x86_64-with-debian-8.5
 Machine            : x86_64
--------------------------------------------------------------------------------------------------------------
- Have someone been able tu run this version with success?
- Is crossbar 0.15.0 now able to handle the "scenario 2" situation with success?

Thanx a lot,
Matteo

**Comment by meejah** [comment]
I have tested this on master and in-flight requests (scenario 2) definitely do not get cancelled/errrored. I'm working on a patch. I guess `wamp.error.canceled` is the right error to use?

**Comment by oberstet** [comment]
this should be long fixed via above PR
