### ISSUE TITLE
Configuration conversion fails on Python 3

### ISSUE THREAD

**Issue by agronholm** [crossbario/crossbar#535]
```
$ crossbar convert
...
Error: the JSON object must be str, not 'bytes'
```
This happens because the source and destination files are, for some reason, opened in binary mode, even though JSON and YAML are both text formats. Changing `crossbar.common.checkconfig.convert_config_file()` to open the files in text mode fixes the problem.

**Comment by hawkowl** [comment]
Looks like this was fixed. Closing!
