### ISSUE TITLE
checking for TLS certificates fails

### ISSUE THREAD

**Issue by goeddea** [crossbario/crossbar#538]
The check introduced with 8066e5aa942f0aafa51f3fe3743ffed2296caa12 fails for me when the TLS certificates are present.

Tested on Ubuntu and Windows, with the files which are checked for in the Crossbar config directory and maximum permissions given. Identical result whether I try with my own config or with the example in Crossbarexamples - I always get:

```
Path 'server_key.pem' doesn't exist for 'key' in TLS config
```

**Comment by meejah** [comment]
Ah, yes in my PR for #128 I found relative paths checks don't work properly; I'll port over just the fix for that as it's pretty minor.

**Comment by meejah** [comment]
Looks like #537 got merged, so this should now work on master; @goeddea can you re-try?

**Comment by meejah** [comment]
Actually, this still fails for "crossbar check" but see PR #551

**Comment by oberstet** [comment]
This works now
