### ISSUE TITLE
Use pegged dependencies

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#543]
Here is a suggestion (by @meejah), which should avoid issues like https://github.com/crossbario/crossbar/issues/542 in the future:

> also (and I guess @hawkowl would know best) but I think the usual advice is "open-ended requirements for library like autobahn>=0.10.0, but pegged requirements for programs like autobahn==0.10.2
​> that is, it's ​probably​ best to have crossbar declare exact dependencies, so that autobahn (or txaio) can be upgraded + released w/o affecting crossbar

**Comment by oberstet** [comment]
It makes sense to have that distinction between "libraries" and "programs". And yes, Crossbar.io is a program, in particular when installed from our binary packages (the recommended way).

The only thing to remember: when a user install Crossbar.io into a shared Python environment, and/or wants to host AB Py app components in routers / containers, the AB version pinning will extend to those components as well. But as the user components then will run along CB code, it's probably better to pin anyway.

So I am +1. But @hawkowl will have more experience here I guess.

**Comment by meejah** [comment]
Absolutely I defer to @hawkowl's experience ;) but I suspect the best advice is for people releasing a component to treat it like a library (open-ended requirements). The problems arise when more than 1 thing pins to "a" version (and those versions differ). So, if crossbar.io is pinning, components shouldn't (or, if they must pin they should pin to a crossbar version, not e.g. an autobahn version).

**Comment by hawkowl** [comment]
That sounds good to me :)

**Comment by oberstet** [comment]
Actually, I think we should go further, and not only pin CB's direct dependencies, but all indirect deps as well.

Would it be enough if we'd check in the output of pip freeze from a fresh installation of CB into a fresh virtualenv? Mmh. I guess platform dependent, dynamic imports make that tedious. The requirements file would need to be the superset over all platforms, and have the platform specific stuff guarded in conditionals.

I am wondering about this general question: is there a way to make sure that when I do "pip install X" today and in 2 weeks, that I do get the same package versions of everything? A repeatable install.

**Comment by waterbug** [comment]
I suggest checking out the use of "conda" as a package manager:
http://conda.pydata.org/docs/index.html

It has many advantages over pip, being capable of installing
specified versions of python, set up its own virtualenvs, and
keep all library dependencies isolated from system libraries.

One of conda's features, relevant here, is its capability to
"pin" specific versions of packages in an environment -- see:
https://www.continuum.io/blog/developer/advanced-features-conda-part-1

(But note that conda packages are different from "wheels".)

Our sysadmins (NASA/GSFC Software Engineering Division) love
conda and avoid pip whenever possible.

Cheers,
Steve

**Comment by oberstet** [comment]
This issue about if we want to pin dependencies, and if so, to what extent. We don't consider moving to different install tools.

Note: in general, the recommended way of installing Crossbar.io is via our own binary packages. These come with everything bundled, including PyPy, and is isolated from everything else (but the C library and a bunch of other basic system libs).

**Comment by meejah** [comment]
If we're going to pin all dependencies  then we could *also* take advantage of the hash-checking stuff that was somewhat-recently ported from "peep". Thus, if you got a signed tag for crossbar (with a setup.py with the hashes in it), you can be sure you're getting precisely the dependencies we happened to have when packaging.

See: https://pip.pypa.io/en/stable/reference/pip_install/#hash-checking-mode

I'm not sure if this *requires* a recent-enough (post-8.x) pip, or if it's just "not checked, but works" on older pips ... :/

**Comment by oberstet** [comment]
This sounds great! I think, that alone is a good reason to pin all direct _and_ indirect deps ..

So for packaging (eg when we bake the debs), we could do

```
cd crossbar
pip install --require-hashes -r requirements.txt -e .
```

and get the same bits installed - repeatable, right?

**Comment by meejah** [comment]
Yes. Also, some amount of protection from MitM type things, too (if you trust the source of the requirements.txt -- e.g. from a signed git tag, etc).

**Comment by oberstet** [comment]
bumping this to bug level .. we should pin everything (direct and indirect)

**Comment by oberstet** [comment]
@meejah this seems to work https://github.com/crossbario/crossbar/pull/707

**Comment by oberstet** [comment]
seems like these lines in our `setup.py` are the last ones hindering us from moving to pure `requirements.txt`?

```python
# enforce use of CFFI for LMDB
if PYPY:
    os.environ['LMDB_FORCE_CFFI'] = '1'

# enforce use of bundled libsodium
os.environ['SODIUM_INSTALL'] = 'bundled'
```

@meejah @hawkowl Do you know how we could solve that? Or should we "relax" and just set these env vars from outside when we build our binary packages?

**Comment by oberstet** [comment]
this has landed on master
