### ISSUE TITLE
Recent Py 3 issues

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#545]
Currently, some unit tests fail on Py 3 for different, obscure reasons: https://travis-ci.org/crossbario/crossbar

> The PyPy fails are due to https://github.com/travis-ci/travis-ci/issues/4756, https://github.com/travis-ci/travis-ci/issues/5027

**Comment by hawkowl** [comment]
We're cding to a path made by `TestCase.mktemp()` which is rather long -- so we should make it elsewhere.

**Comment by oberstet** [comment]
I don't get it. why does it work on py2 then? are OS paths on py3 unicode (=more bytes) vs str in py2?

> Linux has a maximum filename length of 255 characters for most filesystems (including EXT4), and a maximum path of 4096 characters.

could that be a travis (docker?) thing?

```
oberstet@thinkpad-t430s:~/scm/crossbario/crossbar$ cpy3_1 
(python342_1)oberstet@thinkpad-t430s:~/scm/crossbario/crossbar$ python
Python 3.4.2 (default, Jan 19 2015, 01:21:22) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from twisted.trial.unittest import TestCase
>>> tc = TestCase()
>>> p = tc.mktemp()
>>> p
'twisted.trial._asynctest/TestCase/runTest/stzdig8n/temp'
>>> import os
>>> os.path.abspath(p)
'/home/oberstet/scm/crossbario/crossbar/twisted.trial._asynctest/TestCase/runTest/stzdig8n/temp'
>>> 
```

and is the trigger actually the chdir or the abspath? because (from travis):

```
Traceback (most recent call last):

  File "/home/travis/build/crossbario/crossbar/crossbar/controller/test/test_run.py", line 87, in setUp

    self.cbdir = os.path.abspath(self.mktemp())

  File "/home/travis/build/crossbario/crossbar/.tox/py34-twtrunk-abtrunk/lib/python3.4/posixpath.py", line 361, in abspath

    cwd = os.getcwd()

builtins.OSError: [Errno 34] Numerical result out of range
```

**Comment by meejah** [comment]
Hmm, I added an ``os.chdir`` for the TLS stuff, so relative-paths could be verified -- I wonder if that's making the paths extra-long, somehow...? It also isn't maybe a *great* idea; the alternative is basically passing ``cbdir`` around to all the ``check_*`` functions.

**Comment by hawkowl** [comment]
I think it's fixed on master now. the chdir was happening, and new temp dirs were made relative to cwd -- meaning that with each test, it got longer, and longer, and longer... The fix is a TestCase that restores the original directory as cleanup.
