### ISSUE TITLE
test shared registrations from a single session

### ISSUE THREAD

**Issue by goeddea** [crossbario/crossbar#555]
client A registers procedure P1 as a shared registration.

What happens when it then attempts a second registration for P1 with the same invocation policy?

**Comment by oberstet** [comment]
@goeddea could you test that? eg from a JS component ..

**Comment by goeddea** [comment]
From a JS component, additional registrations are accepted by CB. 
Only on registration, the last one, is stored and called.
This is irrespective of the invocation policy - the last one registered is called with "random" and "roundrobin"  just as with "first" or "last".

(Registering with different invocation policies fails as it should.)
