### ISSUE TITLE
Implement HPKP?

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#561]
We should support TLS listening endpoint configuration to at least set headers for pinning the TLD domain the TLS certificate is for to a specific (root or intermediary) CA, such as e.g. Let's Encrypt. Clients are supposed to check received certificates to be actually issued by the pinning CA.

We _might_ also support pinning server certificates to specific public keys. But that seems questionable, as e.g. we are hosting multiple instances behind the same hostname (latency-based DNS), and each instance has it's own public-private key pair, but the same shared hostname as _alternative_ subject name, in addition to it's instance specific hostname the certificate has as the primary subject.

Above is for increased security, as it prohibits rogue CAs issue certificates for server they shouldn't.

But, see the following;)
- https://en.wikipedia.org/wiki/HTTP_Public_Key_Pinning#cite_note-4
- http://www.chromium.org/Home/chromium-security/security-faq#TOC-How-does-key-pinning-interact-with-local-proxies-and-filters-
- http://security.stackexchange.com/a/49510/46922

**Comment by oberstet** [comment]
I am wondering if it's possible to get at the certificate meta info from JavaScript .. probably not, by design. Mmh.

**Comment by meejah** [comment]
See also: https://www.imperialviolet.org/2011/05/04/pinning.html

**Comment by meejah** [comment]
This isn't "pinning", but related somewhat: https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security

This allows you to declare that an address shouldn't be accessed by anything other than HTTPS

**Comment by oberstet** [comment]
HSTS: yeah, we already support that!

**Comment by oberstet** [comment]
So as mentioned above, we do have HSTS for quite a time now.

There is another thing called HPKP, which is about pinning keys, but this seems to have serious practical issues: https://blog.qualys.com/ssllabs/2016/09/06/is-http-public-key-pinning-dead

So I am changing the title, but we may choose NOT to implement it.

**Comment by oberstet** [comment]
won't implement (doubts about if it actually makes things more secure / is practically feasible)
