### ISSUE TITLE
Improve code quality metrics 

### ISSUE THREAD

**Issue by rogererens** [crossbario/crossbar#564]
Hi,

open source projects can sign up for free for these tools offered on:
https://landscape.io/
and/or
https://www.quantifiedcode.com/

Might be interesting to see what they come up with.

**Comment by oberstet** [comment]
We already have Tox, Travis, Codecov. Plus

Landscape wants these GH rights

* Repository webhooks and services (Admin access)
* Commit statuses (Read and write access)

and Quantified code wants

* Repository webhooks and services (Admin access)

No way.

**Comment by oberstet** [comment]
Also: Landscape seems to lack a free plan, and both services want to hook me into some non-standard, closed-source code analysis thing, where there are PyLint, PEP8, PyFlakes, ..

**Comment by rogererens** [comment]
I understand your reservations about them. As a follow up I did some more
homework:

   - Landscape.io does have a free plan (for open source, see blue button
   at the bottom of their page)
   - It's underlying tool is Prospector (hosted on the same closed-source
   github as your code: https://github.com/landscapeio/prospector) which
   apparently is a thin(?) wrapper around the tools you mention, and more: (
   http://prospector.landscape.io/en/master/supported_tools.html)
   - The access rights for the webhooks is probably just to get notified of
   changes in your repo, to kick off their analysis. I think your code is not
   at risk. But I agree that this should be explained better by the author of
   landscape.
   - I signed up for a free trial, and the tool sees which repositories I
   have, and which are forked. It let me choose which repo of my collection to
   monitor. I chose a recent fork of autobahn-python. It scored a 'Exellent!'
   90% health check, whatever that means :-) Many duplicate messages, which
   you probably also see using pylint or pyflakes. Although defaulting to
   checking for python2, still not recognizing xrange() (unknown for python3).

So all in all, at its current state, maybe just a tool for individual
developers (explanations of errors, style breaks, or code smells available
via links nearby in the text)

Cheers,

Roger

2015-12-23 9:55 GMT+01:00 Tobias Oberstein <notifications@github.com>:

**Comment by oberstet** [comment]
Hi Roger,

Ah, never mind, I am probably often too sceptical. But cool! Sounds you can analyse the code also from your own account, and get some nice results;) Best would be pointing the tools to the crossbario/txai, autobahn-python and crossbar repositories. These repos combined essentially make up the Crossbar.io code (on top of Twisted, Python and many libs of course). Do you have a link to the final reports to share? Maybe there is something we can profit from their automated code analysis ..

**Comment by rogererens** [comment]
Hi Tobias,

unfortunately, the reports are afaict only accessible when logged in via a
Github-account.
Maybe a separate github account could be created (e.g.
statler-and-waldorf@tavendo.com) that forks those repos from crossbario.
But I don't know how forks get updated; probably will take some manual
steps which defies the purpose of automated code analysis.
It is possible though to clone the prospector code and run that tool
in-house which I might take a stab at over the Xmas holidays (but it's
fully booked already, to be honest...)
I can also offer you some screen sharing session during some evening.
(Might take the least amount of time in total).

Finally, the guy _did_ make an honest effort in explaining the whys for the
github-permissions: https://docs.landscape.io/githubperms.html (highly
dependent on the current state of affairs offered by github).

2015-12-23 18:56 GMT+01:00 Tobias Oberstein <notifications@github.com>:
