### ISSUE TITLE
Shared port hack lacks TLS support

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#566]
The sharing TCP sockets between multiple worker processes all listening on the same port is possible using a socket option, but that option isn't currently exposed by Twisted.

Hence, we have [SharedPort](https://github.com/crossbario/crossbar/blob/master/crossbar/twisted/sharedport.py#L103).

This is used in [create_listening_port_from_config](https://github.com/crossbario/crossbar/blob/master/crossbar/twisted/endpoint.py#L300), which has two code paths for depending on the value of the `shared` option.

However, above is for one a "hack", and more so, it lacks support for TLS.

For that, a custom version of [t.i.ssl.Port](http://twistedmatrix.com/documents/current/api/twisted.internet.ssl.Port.html) would be needed.

**Comment by oberstet** [comment]
@hawkowl @meejah any ideas? getting rid of the shared socket option hack would _and_ being able to use endpoints and TLS the standard way would of course be best, but it's not there and hacking `ssl.Port` now also seems ugly. Mmh

**Comment by meejah** [comment]
Looking (very briefly) at sharedport.py, it seems like it should be possible to create a wrapper that sets the shared option. Something like (in completely untested Python pseudo-code ;) and removing all the checking etc):

```
port = ...
if config.get('shared', False):
    orig = port.createInternetSocket
    def wrapper(*args, **kw):
        s = orig(*args, **kw)
        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)
        return s
    port.createInternetSocket = wrapper
return port
```

**Comment by meejah** [comment]
Essentially all I mean is that instead of writing a custom tcp.Port subclass, write code that wraps any Port object and sets the appropriate object.

**Comment by oberstet** [comment]
Since I want to move on, I've expanded the hack https://github.com/crossbario/crossbar/blob/master/crossbar/twisted/endpoint.py#L407

Tested with https://github.com/crossbario/crossbarexamples/blob/master/authenticate/client_tls/.crossbar/config_shared_tls.json and `wrk`.
