### ISSUE TITLE
SSL3 Error with IOS Safari

### ISSUE THREAD

**Issue by Ninerian** [crossbario/crossbar#580]
Hello,

i'm running a crossbario server and have a problem, connection with IOS. When I establish a connection, the following error is logged:

```
[Router 23066 crossbar.router.protocol.WampWebSocketServerProtocol]   
Connection to/from tcp4:80.153.247.137:59858 lost (<class 'OpenSSL.SSL.Error'>): [('SSL routines', 'SSL3_READ_BYTES', 'ssl handshake failure')])
[Router      23066 crossbar.router.protocol.WampWebSocketServerProtocol] 
_connectionLost: [Failure instance: Traceback: <class 'OpenSSL.SSL.Error'>: [('SSL routines', 'SSL3_READ_BYTES', 'ssl handshake failure')]
/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py:252:_disconnectSelectable
/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py:273:readConnectionLost
/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py:293:connectionLost
/usr/local/lib/python2.7/dist-packages/twisted/protocols/tls.py:473:connectionLost
--- <exception caught here> ---
/usr/local/lib/python2.7/dist-packages/twisted/protocols/tls.py:360:_flushReceiveBIO
/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py:1320:recv
/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py:1187:_raise_ssl_error
/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py:48:exception_from_error_queue
]
```

I use certificates from letsencrypt. The Connections are working on desktop and android. 
Do you have some tip, how I could solve this?

**Comment by Ninerian** [comment]
It seems, thats a problem with the missing chain file. Unfortunately, the version I had installed, didn't support the chain_file argument in the config. And I didn't get a version with it to run.

**Comment by oberstet** [comment]
Our own demo instance at https://demo.crossbar.io/ uses Let's Encrypt certificates. Indeed, this requires to set chain certificates like here https://github.com/crossbario/crossbarexamples/blob/master/demos/_demo_launcher/.crossbar/config_prod_cdc.json#L132

**Comment by oberstet** [comment]
Ah, above "chain certs" config option is not yet in a released version, only on trunk
