### ISSUE TITLE
Static WAMP-CRA example doesn't work on Python 3

### ISSUE THREAD

**Issue by merrellb** [crossbario/crossbar#586]
When running crossbarexamples/authentication/wampcra/static/client.py on Python 3.5.1 (Debian 8.2) I get several errors related to Python 3 bytes and unicode such as:

```
  File "/home/brian/venv/python35/lib/python3.5/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "client.py", line 64, in onChallenge
    challenge.extra['keylen'])
  File "/home/brian/venv/python35/lib/python3.5/site-packages/autobahn/wamp/auth.py", line 186, in derive_key
    assert(type(secret) == bytes)
builtins.AssertionError:  
```
I was able to address these with the following changes:
```
--- a/authentication/wampcra/static/client.py
+++ b/authentication/wampcra/static/client.py
@@ -58,8 +58,8 @@ class ClientSession(ApplicationSession):
 
          if u'salt' in challenge.extra:
             # salted secret
-            key = auth.derive_key(USER_SECRET,
-                                  challenge.extra['salt'],
+            key = auth.derive_key(USER_SECRET.encode('utf8'),
+                                  challenge.extra['salt'].encode('utf8'),
                                   challenge.extra['iterations'],
                                   challenge.extra['keylen'])
          else:
@@ -67,10 +67,10 @@ class ClientSession(ApplicationSession):
             key = USER_SECRET
 
          # compute signature for challenge, using the key
-         signature = auth.compute_wcs(key, challenge.extra['challenge'])
+         signature = auth.compute_wcs(key, challenge.extra['challenge'].encode('utf8'))
 
          # return the signature to the router for verification
-         return signature
+         return signature.decode('utf8')
 
       else:
          raise Exception("Invalid authmethod {}".format(challenge.method))
```
Given that at least some of the incorrect types (signature as bytes, challenge as unicode, etc) seem to be coming from Autobahn itself I wonder if the "fix" belongs in the example client or Autobahn.

**Comment by meejah** [comment]
I tried to repeat this (with all-``master`` versions) but got a different problem with differences between Python3 and 2 with ``os.environ`` values (for the ``MYSECRET`` env-var).

Did you get the above problems using a particular version, or master?

**Comment by merrellb** [comment]
I was using the Crossbar version on PyPI, 0.11.2 and crossbarexamples from master.  I did not use environment variables so I didn't explore the os.environ codepath.

**Comment by meejah** [comment]
Works for me out-of-the-box with master crossbarexamples and python 3.5.0 after doing "pip install crossbar" (giving me 0.11.2) on Debian.

Is it possible you have installed your own Autobahn version, or similar? If you're using Autobahn master, can you try again with crossbar master?

**Comment by merrellb** [comment]
I am also using the Pypi version of Autobahn 0.11.0.  Will give the master version of autobahn and crossbar a try.

**Comment by meejah** [comment]
Which Python version? (and/or just paste the output of "crossbar version" for the thing that was failing)

**Comment by merrellb** [comment]
Crossbar.io        : 0.11.2
   Autobahn         : 0.11.0
     UTF8 Validator : autobahn
     XOR Masker     : autobahn
     JSON Codec     : ujson-1.34
     MsgPack Codec  : -
   Twisted          : 15.5.0-EPollReactor
   Python           : 3.5.1/CPython
 OS                 : Linux-3.16.0-4-amd64-x86_64-with-debian-8.2
 Machine            : x86_64

**Comment by merrellb** [comment]
@meejah I just tried the latest autobahn master and this problem seems to have been addressed.  Apologies for the false alarm.  Looking forward to when this gets pushed out on PyPI
