### ISSUE TITLE
Write OTP Authentication documentation

### ISSUE THREAD

**Issue by ghanbari** [crossbario/crossbar#587]
Hi, how can i use OTP authentication?
exists any document for it?

**Comment by meejah** [comment]
Not currently: http://crossbar.io/docs/OTP-Authentication/

**Comment by oberstet** [comment]
@ghanbari There are complete working examples here https://github.com/crossbario/crossbarexamples/tree/master/authentication/ticket

**Comment by oberstet** [comment]
migrated to https://github.com/crossbario/crossbardocs/issues/69
