### ISSUE TITLE
Better error message when crossbar cannot import component

### ISSUE THREAD

**Issue by sametmax** [crossbario/crossbar#59]
I had a strange error during my tests : 

    2014-05-31 22:27:04+0700 [Controller   7767] Unhandled error in Deferred:
    2014-05-31 22:27:04+0700 [Controller   7767] Unhandled Error
	Traceback (most recent call last):
	Failure: autobahn.wamp.exception.ApplicationError: ApplicationError(wamp.error.runtime_error, ['tuple index out of range'] {}

My session class was not imported, but it took me a long time, digging in the crossbar source code, to figure it out.

Since this is an error that will likely happen to anybody at least once (wrong import, changing a name, refactoring, commenting, forgetting if __name__ == "__main__", etc), we need a much more explicit error message.

**Comment by hawkowl** [comment]
I'll take point on this...

**Comment by hawkowl** [comment]
I think #402 cleans this up -- it'll print the stack trace of whatever it was, and be consistent whether it's in a container or side-by-side with a router.

**Comment by sametmax** [comment]
Confirmed on my side.
