### ISSUE TITLE
file corruption with file upload on certain file sizes

### ISSUE THREAD

**Issue by goeddea** [crossbario/crossbar#590]
see https://groups.google.com/forum/#!topic/crossbario/5oxG0RFJeFg - states that files of size greater than 2x chunk size get corrupted.

@markope  - could you take a look at this?

**Comment by singlecheeze** [comment]
I think this maybe fixed with the pending patch for twisted filepath FYI

**Comment by markope** [comment]
could you share a link to that patch you are refering to?

**Comment by oberstet** [comment]
cannot reproduce
