### ISSUE TITLE
Logging docs

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#598]
rgd https://github.com/crossbario/crossbar/pull/573

@hawkowl Hi, I nearly forgot again that you did already add this;) Could you probably add a small section "best practices with CB logging for CB devs" here https://github.com/crossbario/crossbar/blob/master/DEVELOPERS.md?

Also @meejah Another thing someone was asking me (and I was waving hands): how to do logging "correctly" for app developers using AutobahnPython ApplicationSession via txaio .. would be cool to have a doc page in AutobahnPython on logging too: https://github.com/crossbario/autobahn-python/tree/master/doc

**Comment by meejah** [comment]
Yes, good idea.

I believe the right answer is to use the idioms found in AB/crossbar. Namely, ``log = txaio.make_logger()`` and use it more-or-less like the Twisted new logger: ``self.log.error("{some_arg} is bad", some_arg='foo')``

...but, it should also be possible to interop with old-style twisted logging or Python ``logging`` built-in logging. However, "green field" code should use the structed-logger style like the first paragraph. Also, for error formatting etc there are ``txaio.failure_*()`` functions that should be used on the txaio failure instances you get in the errbacks...

**Comment by oberstet** [comment]
Sounds good! Probably add more reference like logging docs to http://txaio.readthedocs.org/en/latest/, and more usage oriented docs to the AutobahnPython docs?

**Comment by hawkowl** [comment]
also adding a note here to remind myself to document the new `log_category` changes

**Comment by Paranaix** [comment]
Question: Whats the reasoning behind the crossbar logging module being private? 
Whats the best-practice for logging for applications built on top of crossbar. 
Whats the best-practice if more sophisticated logging is required (e.g log security relevant stuff to an extra file)?

**Comment by meejah** [comment]
@Paranaix see http://txaio.readthedocs.org/en/latest/programming-guide.html#logging

**Comment by oberstet** [comment]
@Paranaix The new shiny structured logging is now part of the public API of txaio, and hence usable for all. Docs are in above

**Comment by FirefighterBlu3** [comment]
txaio logging is unable to handle content that has braces in it:

```python
            resp = {
                'realm': principal['realm'],
                'role':  principal['role'],
                'extra': {
                    'roleAdmin':   principal['roleAdmin'],
                    'jpegPhoto':   '<suppressed>',
                    'department':  principal['department'],
                    'displayName': principal['displayName']
                }
            }

self.log.info("WAMP-Ticket authentication success: {}".format(resp))
```
results in:

```python
[Router      17628] Unable to format event {'log_logger': <Logger 'autobahn.wamp.protocol.ApplicationSession'>, 'log_source': None, 'log_format': "WAMP-Ticket authentication success: {'realm': ['misty'], 'role': 'Provider', 'extra': {'roleAdmin': [], 'jpegPhoto': '<suppressed>', 'department': [], 'displayName': []}}", 'log_time': 1488262081.92916}: "'realm'"
```

**Comment by meejah** [comment]
@FirefighterBlu3 You shouldn't interpolate the strings yourself. Do this:

```python
self.log.info("WAMP-Ticket authentication success: {resp}", resp=resp)
```
