### ISSUE TITLE
The log_category param to CrossbarLogger should only accept Unicode

### ISSUE THREAD

**Issue by hawkowl** [crossbario/crossbar#602]
This makes it better when it is serialised, as it is unambigiously and neatly serialised for transport. Attempting to use bytes should raise an assertion error.

**Comment by oberstet** [comment]
Yep, that's good! Both keys and value in https://github.com/crossbario/crossbar/blob/master/crossbar/_log_categories.py#L34 should be unicode

**Comment by oberstet** [comment]
as we only support python 3 anymore, the issue seems void now anyways
