### ISSUE TITLE
Explicitly configured anonymous authentication does not work

### ISSUE THREAD

**Issue by agronholm** [crossbario/crossbar#607]
This only happens in latest master, not the release version.
If authentication configuration is presented to crossbar, it breaks anonymous authentication even if it's explicitly present in the configuration. The reason for this is that in `crossbar.router.session.RouterSession.onHello()` [(here)](https://github.com/crossbario/crossbar/blob/4a1185409d5df714f879aeb5d53c7aaa8fe03fd0/crossbar/router/session.py#L599), it checks the authentication methods against `AUTHMETHOD_MAP` which does not include `anonymous` and exits the current iteration. Therefore it never gets to the section later in the block which would have checked for the `anonymous` authentication method.

**Comment by oberstet** [comment]
Ok, I not only fixed the issue, but also added WAMP-Anonymous dynamic. Works for me on both Python 2 and 3.

Please see: https://github.com/crossbario/crossbarexamples/tree/master/authentication/anonymous

You need all trunk (txaio, autobahn, crossbar)
