### ISSUE TITLE
Service readiness notification

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#612]
When running Crossbar.io under `systemd`, there is often the need to have dependent services start, when Crossbar.io has **fully started**.

However, this is not possible right now, since even when adding a respective dependency to the service unit, `systemd` will start the dependent service immediately when the Crossbar.io **process has started**.

There is a systemd mechanism for this situation call **service readiness notification**. 

Here is a Python example: https://github.com/openstack/oslo.service/blob/master/oslo_service/systemd.py

**Comment by bb4242** [comment]
This functionality would be great to have.  I created #637 to address this; please let me know what you think.  Also, if there is a good place to add documentation about this feature (possibly in [crossbardocs](https://github.com/crossbario/crossbardocs)?), please let me know and I'll be happy to add some.

**Comment by oberstet** [comment]
@bb4242 awesome!! also nice: not exactly a lot of code for a quite useful feature;) Before I can merge, may I ask you to check out http://crossbar.io/docs/Contributing-to-the-project/#send-us-a-contributor-assignment-agreement ? because we would need (but only once) a contributor agreement. yeah, I know .. forms;)

**Comment by bb4242** [comment]
Sure thing, I just submitted a contributor agreement to service@tavendo.de.

**Comment by oberstet** [comment]
@bb4242 yep, received. thanks! closing via merged https://github.com/crossbario/crossbar/pull/637

**Comment by bb4242** [comment]
Great, thanks!
