### ISSUE TITLE
Don't log deliberate exceptions from user/service code

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#616]
Raising exceptions from service sessions (`crossbar.router.service.RouterServiceSession`) should NOT be logged. This is similar to running user sessions/components inside a router/container. Such user code explicitly raising should also not log. An exception raised from user code often is used as a valid means to signal call errors.

E.g. consider https://github.com/crossbario/crossbar/blob/master/crossbar/router/service.py#L531

This code may very well raise `wamp.error.history_unavailable` -- and we don't want to clutter the log with:

```console
2016-01-29T14:20:49+0100 [Controller  12617] Router 'worker1': transport 'transport1' started
2016-01-29T14:20:51+0100 [Router      12621] wamp.error.history_unavailable: 
```

**Comment by meejah** [comment]
I'll take a look, but I *think* all you should have to do is override ``onUserError`` to be a no-op (or ignore specific ApplicationError URIs) in ``RouterServiceSession``.

**Comment by oberstet** [comment]
Ah, right. Thanks! I will try that. Essentially, all errs derived of ApplicationError should just go through unlogged, while anything else should be logged .. because it needs fixing, because it should be treated explicitly and use ApplicationError

**Comment by meejah** [comment]
See the PR.

You will of course still get a log if the client-session doesn't handle the exception (that is, the thing doing ``yield call(u"wamp.subscription.get_events", ..)`` needs to handle the exception).
