### ISSUE TITLE
RPC already registered even after disconnect

### ISSUE THREAD

**Issue by ctsdevmumbai** [crossbario/crossbar#619]
I have a strange and what may seem to be a random issue. I have my clients (Android) register some rpcs with crossbar. The client re-registers the rpcs on disconnect and here is the where the issue arises, crossbar says the rpc is already registered. 
I now that after a dirty disconnect, crossbar will remove all registered rpcs after a ping is lost. But in this case it doesn't. 
And when I fire (post ping lose) 'wamp.registration.list_callees' I get response as [null] and if I fire 'wamp.registration.count_callees' I get 1 as response. 

I digged into the python code for the above rpcs and it seems that the 'callee._session_id' seems to be null on line number 424 of sservice.py

I can't reproduce the issue in a definite way so can't provide any steps to reproduce.
This is affecting the communication of the server with the client. Could you please check and provide a solution or workaround? Let me know if you need any more info

**Comment by oberstet** [comment]
This is an issue tracker. Please use the mailing lists to ask questions. Thanks!
