### ISSUE TITLE
Client prints {msg}: {traceback} if the router dies

### ISSUE THREAD

**Issue by sametmax** [crossbario/crossbar#627]
I'm playing with the new release and I'll take time to report stuff as I encouter them.

I have the following client code:

```
import asyncio

from os import environ
from autobahn.asyncio.wamp import ApplicationSession, ApplicationRunner

class Component(ApplicationSession):

    async def onJoin(self, details):

        counter = 0

        while True:
            print("publish: mon.uri.pour.un.event")
            self.publish('mon.uri.pour.un.event', counter)
            counter += 1
            await asyncio.sleep(1)


if __name__ == '__main__':
    runner = ApplicationRunner("ws://127.0.0.1:8080/ws", "realm1")
    runner.run(Component)
```

I wanted to check if the automatic reconnection was implemented for Python in this release. Doing so, I killed crossbar and noticed my client started to print:

```
publish: mon.uri.pour.un.event
publish: mon.uri.pour.un.event
publish: mon.uri.pour.un.event
publish: mon.uri.pour.un.event
publish: mon.uri.pour.un.event
publish: mon.uri.pour.un.event
publish: mon.uri.pour.un.event
{msg}: {traceback}
{msg}: {traceback}
```

I don't think it's a big deal, but maybe it hides something more important.

**Comment by meejah** [comment]
Looks like a formatting string that's not getting "interpolated" (i.e. replaced with whatever msg and traceback are)...

**Comment by oberstet** [comment]
> I wanted to check if the automatic reconnection was implemented for Python in this release.

The sad truth is: it's not yet implemented (in AutobahnPython). But I have written up the status in this ticket https://github.com/crossbario/autobahn-python/issues/588, which we definitely resolve for the next AutobahnPython release.

**Comment by sametmax** [comment]
@meejah : confirmed. Errors in the client are not printed, only the string template for format is. It's not just on disconnection but on ordinary exceptions such as AttributeError or NameError.

**Comment by meejah** [comment]
I thought I'd confirmed this, *but* it seems it only happens if you have a mismatched crossbar vs autobahn -- so if you have crossbar master but v0.12.1 autobahn it won't work (and vice-versa). @sametmax is this what you're seeing, too?

**Comment by meejah** [comment]
Hmm, actually this is python3 specific -- with a python3 non-router component, I can repeat @sametmax's issue (to a crossbar running in python2 or python3)

**Comment by sametmax** [comment]
I have: 

```
>>> import crossbar

>>> crossbar.__version__
'0.12.1'

>>> import autobahn

>>> autobahn.__version__
'0.12.1'
```

And yes, using Python 3.

**Comment by meejah** [comment]
Also, I tried with a twisted version of the code posted in the original report, and that does *not* exhibit the symptoms. So, it's python3 + asyncio only.

**Comment by meejah** [comment]
Okay, looks like it's really an autobahn bug: ``ApplicationRunner`` for asyncio doesn't ever call ``start_logging`` (like ``twisted.wamp.ApplicationRunner`` does).

@sametmax: if that's really the route of your original problem, adding: ``txaio.start_logging(level='info')`` before calling ``.run()`` should make it work for you. I filed https://github.com/crossbario/autobahn-python/issues/589

**Comment by sametmax** [comment]
Cheers
