### ISSUE TITLE
Exceptions in onJoin() of a component are silently swallowed

### ISSUE THREAD

**Issue by Paranaix** [crossbario/crossbar#632]
Self-explaining

**Comment by oberstet** [comment]
No, not self-explaining;)

**Comment by Paranaix** [comment]
Ok, by trying to create a SSCCE I've stumbled about the real issue: Exceptions thrown in `onUserError()` are silently swallowed.

Also regardless of that: If there is an exception in `onJoin()` or `onUserError()` the component will keep running. Is this intented behaviour? I as a user would definitely not expect that tbh.

**Comment by meejah** [comment]
I think an exception from ``onUserError`` should *not* be fatal. And yes, currently any exception coming out of it is swallowed -- probably these should be logged instead. Can I ask what your use-case is to over-ride ``onUserError`` at all?

I could probably be convinced that an exception from ``onJoin`` should be fatal to the component. But, I don't hold that opinion very strongly ;) @oberstet?

**Comment by oberstet** [comment]
This is the wrong repo for this discussion. Errors that result from user code overriding `onUserError` are indeed swallowed, but logged:

* https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/protocol.py#L368
* https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/protocol.py#L406

Making the component fail upon some triggers could of course be done in the default implementation of `onUserError` - but I'm not sure.

That would require another parameter to `onUserError` (`source` being `u"on_join"`, `u"on_event`, ..). I recently had code like that, but then threw it away again.

Anyway: it's an AutobahnPython question, not Crossbar.io

**Comment by Paranaix** [comment]
> Errors that result from user code overriding onUserError are indeed swallowed, but logged.

No that's not true. I've created a SSCCE and uncaught exceptions in `onUserError` are definitely not logged.

I think an exception in `onUserError` should not be fatal, however an exception in `onJoin` definitely should be, atleast thats my opinion.

**Comment by meejah** [comment]
Yes, any error in ``onUserError`` itself is currently swallowed silently: https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/protocol.py#L408
