### ISSUE TITLE
asyncio + multiprocessing

### ISSUE THREAD

**Issue by kamikaze** [crossbario/crossbar#651]
Sorry, didn't found a way to communicate with crossbar community. So I'm writing my question here:
It is good that asyncio helps with concurrency in I/O aspect. But it is still a single process. Wouldn't it be a great idea to spawn multiple processes for crossbar (equal to CPU/core count)? I think it may give some profit.

**Comment by oberstet** [comment]
https://github.com/crossbario/crossbar/blob/master/README.rst
