### ISSUE TITLE
Unnecessary field "allow" in new authorization struct

### ISSUE THREAD

**Issue by Paranaix** [crossbario/crossbar#652]
The new authorization struct which has to be returned is supposed to be a dict with a boolean `allow` field indicating whether the authorization was succesful.

This field however is not required. The fact that a dict has been returned would already be sufficient to indicate that authorization was successful. More importantly, the current change breaks backward compatibility.

So what do I propose? Treat `None`, `False` and anything else that if passed into `bool()` evaluates to False as failed authorization. E.g dealer.py#L380 `if not authorization[u'allow']:` becomes `if not authorization:` (looks familiar? ;) ).

On top of that, assume that `authorization` might not be a dict. So e.g dealer.py#L414 `if authorization[u'disclose']:` becomes `if isinstance(authorization, dict) and authorization.get(u'disclose', False):`. Therefor, a `return True` can again be used by a dynamic authorizer to authorize an action.

With these changes we would get rid of an unnecessary field AND **restore full backward compatibility**.

**Comment by oberstet** [comment]
No, we need an extensible dict here.

**Comment by Paranaix** [comment]
Have you actually read this issue? This is not about removing the dict but about removing the `allow` field.

**Comment by oberstet** [comment]
There already is backwards compat: https://github.com/crossbario/crossbar/blob/master/crossbar/router/router.py#L274

But: this stuff might change before the next release (pls consider trunk "experimental").

Essentially, we'll have a single "namespace" with configurable options (like there is for "permissions" today), but not only for "allow/deny", but other options as well. And dynamic authorizers should be able to override/set all these options - hence they no longer are "authorizers" only, but are able to dynamically configure the URI namespace.

One idea I am considering is removing the `action` parameter from dynamic authorizer invocations, and require the latter to return a dictionary essentially identical to the dicts configured on static configs.

E.g an authorizer is called with `(realm, role, uri)` and supposed to return a dict like:

```
{
   "allow": {
      "call": true,
      "register": true,
      "publish": false,
      "subscribe": false
   },
   "disclose": {
      "caller": true,
      "publisher": false
   },
   "cache": true
}
```

**Comment by Paranaix** [comment]
I have already noticed that code, even if unused, and actually hoped for it to stay unused. It just overloads an actually simply function. While such a structure of course makes sense for config it's not really advantageous for a programmatic approach. It violates single responsibility and results in more complicated and bloated code IMO.

Truth to be told, I totally fail to see the motivation for this. I can only imagine it to be perfomance related (querying one time opposed to querying 4 times). That however would be a really bad reason. Running an authorizer remotely is already plainly insane performance wise. Reducing the number of queries in that case would of course improve performance, but it would be just a drop in the bucket as overall the performance would still be cataclysmal. If ran locally however, removing all the indirections (e.g instead of wamp call, a regular method call) and async code and introducing one single LUT cache would be way more effective.

**Comment by oberstet** [comment]
> e.g instead of wamp call, a regular method call

There is no such thing as a Python-level API in Crossbar.io

> Running an authorizer remotely is already plainly insane performance wise. 

Why? The roundtrip time for a WAMP call on a locally switched Ethernet is in the ballpark of 400-1000 microsecs. The usual RTT for a WAN connection (browser to CB) is 30-300ms, depending on network. So the added latency is negligible.

--

Also note the new (not yet implemented) `cache` attribute. That will make CB cache the info returned from a dynamic authorizer (or dynamic namespace configurator .. need to find a better name).
