### ISSUE TITLE
Implement authid/authrole based black-/whitelisting for pubsub

### ISSUE THREAD

**Issue by esso23** [crossbario/crossbar#656]
I was browsing the specification last week and I stumbled upon black/white-listing using authroles/authid. In our application we have a router and many clients connecting to it and each client exposes a common interface. This interface is usable by administrator client for controlling and monitoring. The problem is, we don't want RPCs from this interface to be accessible by regular (or front-end) clients. Black/white listing using session IDs is not applicable in this case as the clients connecting do not know about other clients (in fact that is the core principle of routed rpc/pubsub so I cannot imagine any use case for this feature).

So my question is, are there any plans on implementing this feature in the near future?

Thanks
Esso

**Comment by oberstet** [comment]
Yes, we will have that feature soon.

> Note that bw-listing is about pubsub, not rpc. If you want to restrict rpc, that can be done by authenticating an admin UI frontend under a different role than regular UI frontends.

**Comment by Paranaix** [comment]
This can already be achieved by now. However you might have to write some utility functions on your own to make this productive.

Just include some identifier representing the principal to which multiple peers belong (e.g an userid) within the uri.  E.g `com.example.notification_for_user.42`. Setup a custom authorizer, extract the userid from the uri and map wamp_session_id -> userid. If they match, allow the action (e.g subscribe or publish) if not prohibit it.

**Comment by izderadicka** [comment]
Current status is bit problematic - we can use this option in autobahn python in publish - but it's ignored by crossbar - and sends events to all subscribers  - could at least CB return error when publishing with this option?  This is potential security issue -  no error is given so client  believes that events are published only to limited subscribers.

**Comment by markope** [comment]
+1 waiting for feature

**Comment by oberstet** [comment]
this has been implemented long ago now:

* `exclude_authid`
* `exclude_authrole`
* `eligible_authid`
* `eligible_authrole`
