### ISSUE TITLE
What's included/missing in the minimal installation?

### ISSUE THREAD

**Issue by ecorm** [crossbario/crossbar#658]
The installation documentation refers to `crossbar` and `crossbar[all]` packages, with `crossbar` having "minimal dependencies".

What extra features are available in `crossbar[all]`? I cannot seem to find a description in the documentation.

I'm attempting to install crossbar on an ARM device using the instructions for the Raspberry Pi. I decided to install the `crossbar[all]` variant because I wanted to make sure that I had all the security and encryption options available for the router. If I knew that I would have a fully functional router with the minimal install, that would be good to know. :smile:

**Comment by ecorm** [comment]
I found the `install_requires` variable in [setup.py, line 64](https://github.com/crossbario/crossbar/blob/master/setup.py#L64), which give me an idea of the features available in the minimal install. I still think there should be a description in the documentation of what added in `crossbar[all]`.

**Comment by meejah** [comment]
The documentation should be fixed; currently [all] just adds the development requirements, so it doesn't really change any available features/security in crossbar -- i.e. all installs get TLS, PyNaCl, cbor, msgpack.

**Comment by ecorm** [comment]
FYI, here are the Python packages that were installed using `pip install crossbar`:

```
Successfully built crossbar zope.interface twisted autobahn pytrie pyyaml shutilwhich psutil lmdb msgpack-python cbor cryptography pynacl setproctitle pyinotify wsaccel ujson txaio MarkupSafe enum34 cffi pycparser
Installing collected packages: click, zope.interface, twisted, six, txaio, autobahn, netaddr, pytrie, MarkupSafe, jinja2, mistune, pygments, pyyaml, shutilwhich, psutil, lmdb, msgpack-python, cbor, idna, pyasn1, enum34, ipaddress, pycparser, cffi, cryptography, pyOpenSSL, pyasn1-modules, attrs, service-identity, pynacl, requests, treq, setproctitle, pyinotify, wsaccel, ujson, crossbar
```

**Comment by oberstet** [comment]
Yes, @meejah is right: "all" nowerdays only installs dev/test dependencies .. which isn't for users. CB nowerdays has all dependencies required, so there is no "minimal" installation (anymore). Migrated to https://github.com/crossbario/crossbardocs/issues/66
