### ISSUE TITLE
A hostname of empty string causes Crossbar to fail to start up

### ISSUE THREAD

**Issue by hawkowl** [crossbario/crossbar#660]
An empty hostname (for example, on the official FreeBSD 10.2 Vagrant box) causes the following:

```
2016-02-28T13:49:49+0000 [Controller   1162] Unable to format event {'log_logger': <Logger 'crossbar.controller.native.NativeWorkerClientProtocol'>, 'log_level': <LogLevel=critical>, 'log_namespace': 'crossbar.controller.native.Nat
iveWorkerClientProtocol', 'log_source': None, 'log_format': 'Traceback (most recent call last):\n  File "/opt/crossbar/site-packages/autobahn/wamp/websocket.py", line 88, in onMessage\n    for msg in self._serializer.unserialize(pa
yload, isBinary):\n  File "/opt/crossbar/site-packages/autobahn/wamp/serializer.py", line 131, in unserialize\n    msg = Klass.parse(raw_msg)\n  File "/opt/crossbar/site-packages/autobahn/wamp/message.py", line 2534, in parse\n
procedure = check_or_raise_uri(wmsg[3], u"\'procedure\' in REGISTER", allow_empty_components=allow_empty_components, allow_last_empty=allow_last_empty)\n  File "/opt/crossbar/site-packages/autobahn/wamp/message.py", line 160, in ch
eck_or_raise_uri\n    raise ProtocolError(u"{0}: invalid value \'{1}\' for URI (did not match pattern {2}, strict={3}, allow_empty_components={4}, allow_last_empty={5}, allow_none={6})".format(message, value, pat.pattern, strict, a
llow_empty_components, allow_last_empty, allow_none))\nProtocolError: \'procedure\' in REGISTER: invalid value \'crossbar.node..worker.worker1.start_manhole\' for URI (did not match pattern ^([^\\s\\.#]+\\.)*([^\\s\\.#]+)$, strict=
False, allow_empty_components=False, allow_last_empty=False, allow_none=False)\n', 'log_time': 1456667389.630209}: tuple index out of range
```

So, there's two issues here -- the error message does not format properly, and Crossbar fails hard when there is no hostname to make the nodename from. We should at least give a useful error message.

**Comment by meejah** [comment]
I think in general we need to do a bit of a audit for using ``.failure`` incorrectly; I've seen + fixed at least a couple spots where we do ``log.failure(failure_instance)`` which should instead be, IIUC, ``log.failure("Some message", failure=failure_instance)``.

**Comment by hawkowl** [comment]
@meejah also, a bit non-obvious, but if you do `log.failure(None, failure=failure_instance)` then it'll just print the traceback.

**Comment by oberstet** [comment]
@meejah 

> I think in general we need to do a bit of a audit for using .failure incorrectly; 

Yep, agreed. Actually, go over all the logging usage places ..

@hawkowl 

Could we have a test that verifies that when log level = X, then all calls to log() with level < X a **no-ops** (really, no-ops). And that this is the case for the node controller, router workers as well as container workers.

Because we had this issue twice now: CB performance collapse because of the logging traffic between workers and the node controller running out of control ..

**Comment by oberstet** [comment]
I _think_ this is fixed via above PR
