### ISSUE TITLE
invalid grant in role permissions ... unknown attribute 'register'

### ISSUE THREAD

**Issue by FirefighterBlu3** [crossbario/crossbar#671]
the example config.json found at https://github.com/crossbario/crossbarexamples/blob/master/authentication/advanced/.crossbar/config.json for advanced authentication no longer works. would somebody mind updating us please?

```log
2016-03-08T04:05:56+0000 [Controller  27940] Running from node directory '/var/vse/MS/.crossbar'
2016-03-08T04:05:56+0000 [Controller  27940] Controller process starting (CPython-EPollReactor) ..
2016-03-08T04:05:56+0000 [Controller  27940] Invalid node configuration
2016-03-08T04:05:56+0000 [Controller  27940] invalid grant in role permissions - encountered unknown attribute 'register'
[non-root@gen4-lab MS]$ grep register .crossbar/config.json
                                    "register": true
```

**Comment by meejah** [comment]
After running ``crossbar upgrade`` this example starts up for me with master. What version are you using? (A new version of configuration was introduced but is not in any released version AFAIK).

**Comment by FirefighterBlu3** [comment]
virgin install of master/HEAD from march 8th, two days ago

**Comment by iscriptology** [comment]
same problem here... when running `crossbar upgrade` it says 
> Configuration already is at latest version 2 - nothing to upgrade
need help guys..!

**Comment by meejah** [comment]
Can you try with the above branch?

**Comment by iscriptology** [comment]
I found in the crossbar source-code that I should put the permission dict under the "allow" sub-key.
I think it's not proper to upgrade to a new version before updating the documentation on http://crossbar.io
But I guess you are working on that, thank you for a great product :)
(I will be glad to contribute myself, in a few weeks when I'm done with the current project.)

**Comment by iscriptology** [comment]
by the way, having a readthedocs site is far more convenient than the current approach. (even for versioning purposes) would you consider that?

**Comment by oberstet** [comment]
@iscriptology no, the docs for Crossbar.io do not live on RTD

**Comment by FirefighterBlu3** [comment]
this is fixed with the "crossbar upgrade" modifications performed on config.json
