### ISSUE TITLE
Should JSON Base64 string arguments be automatically converted to MsgPack BIN objects?

### ISSUE THREAD

**Issue by ecorm** [crossbario/crossbar#679]
Per [section 14](https://tools.ietf.org/html/draft-oberstet-hybi-tavendo-wamp-02#section-14) of the WAMP spec:

> Binary data follows a convention for conversion to JSON strings.
> 
>    A *byte array* is converted to a *JSON string* as follows:
> 
>    1.  convert the byte array to a Base64 encoded (host language) string
> 
>    2.  prepend the string with a "\0" character
> 
>    3.  serialize the string to a JSON string
> 

Should such JSON-encoded binary data be automatically converted to MsgPack OBJ when Crossbar performs a JSON-to-MsgPack translation, and vice-versa?

**Comment by oberstet** [comment]
Please see https://github.com/crossbario/autobahn-python/issues/574
