### ISSUE TITLE
systemd "sd-notify" support

### ISSUE THREAD

**Issue by meejah** [crossbario/crossbar#690]
I have some test-cases that start crossbar subprocesses. One thing they do is monitory the logs to look for different configured transports starting up -- in other words, to know when the crossbar process is "ready enough to accept a connection".

systemd has a protocol for something similar: https://www.freedesktop.org/software/systemd/man/sd_notify.html#Notes (namely, sending "READY=1" to systemd to tell it that your service is ready). There is a python library for it, too: https://github.com/bb4242/sdnotify

The enhancement here would be to add a crossbar command-line option to do notifications (and probably respect $NOTIFY_SOCKET?). My test-cases could then instead provide such a socket and away crossbar saying "READY=1" -- which should be emitted after all configuration has been acted upon (namely: all transports and components will be started up at that point).

**Comment by oberstet** [comment]
Crossbar.io already implements systemd notification: https://github.com/crossbario/crossbar/blob/master/crossbar/controller/node.py#L515

**Comment by meejah** [comment]
Ah! Neat :)
