### ISSUE TITLE
Installation on generic systems not working

### ISSUE THREAD

**Issue by billybennett** [crossbario/crossbar#691]
crypto install fails with a message that it will not work with python versions less than 2.6, I believe the version installed with pypy as specified in the generic linux instructions (http://crossbar.io/docs/Installation-on-Linux/) is 2.5; I have installed the pypy 5.0.1 package and the install works but logging appears to be broken and port 8080 is not served. 

I'm using centos 6.6
When I go to the system from my laptop via telnet, i get nothing out, even if i put in a non-existent file.
The same steps on my server running on port 80 works as it should (file is returned or 404).

**Comment by billybennett** [comment]
Forgot to mention I also have this installed on a local system for development (a mac), works fine.  Here's the output from each (sans banner):  I installed pypy on my other mac to compare performance, both work fine, and both output logs.

crossbar@srv hello]$ crossbar version
Automatically choosing optimal Twisted reactor
Running on Linux and optimal reactor (epoll) was installed.

 Crossbar.io        : 0.13.0
   Autobahn         : 0.13.0 (with JSON, MessagePack, CBOR)
   Twisted          : 16.0.0-EPollReactor
   LMDB             : 0.89/lmdb-0.9.18
   Python           : 2.7.10/PyPy-5.0.1
 OS                 : Linux-2.6.32-431.17.1.el6.x86_64-x86_64-with-centos-6.6-Final
 Machine            : x86_64


$ crossbar version
Automatically choosing optimal Twisted reactor
Running on *BSD or MacOSX and optimal reactor (kqueue) was installed.

 Crossbar.io        : 0.13.0
   Autobahn         : 0.13.0 (with JSON, MessagePack, CBOR)
   Twisted          : 16.0.0-KQueueReactor
   LMDB             : 0.89/lmdb-0.9.18
   Python           : 2.7.10/CPython
 OS                 : Darwin-15.3.0-x86_64-i386-64bit
 Machine            : x86_64

**Comment by oberstet** [comment]
> crypto install fails with a message that it will not work with python versions less than 2.6

Crossbar.io does not support Python 2.6

**Comment by billybennett** [comment]
I'm sorry I was unclear, it isn't python that's the issue, it's pypy.  Pypy 2.5 has python 2.7, but this is the output from the crossbar install:

Collecting cryptography>=0.9.3 (from crossbar[all])
  Downloading cryptography-1.3.1.tar.gz (383kB)
    100% |████████████████████████████████| 389kB 1.6MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "app_main.py", line 75, in run_toplevel
      File "app_main.py", line 581, in run_it
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-tyQXpj/cryptography/setup.py", line 53, in <module>
        "cryptography 1.0 is not compatible with PyPy < 2.6. Please "
    RuntimeError: cryptography 1.0 is not compatible with PyPy < 2.6. Please upgrade PyPy to use this library.

**Comment by oberstet** [comment]
Ah, ok. Then: Crossbar.io isnt compatible with old pypy <  2.6. Sorry. My recommendation for CB on pypy: use our binary packages .. these come with lattest pypy bundled
