### ISSUE TITLE
Stricter type checking for node config

### ISSUE THREAD

**Issue by Paranaix** [crossbario/crossbar#693]
accepts strings as well (strings are sequences as well huehue, zen of python huehue), we need a changelog

**Comment by oberstet** [comment]
This isn't Python's fault: the fact that the check on `ca_certificates` does actually check for type `Sequence` not `six._text_type` ([here](https://github.com/crossbario/crossbar/blob/master/crossbar/common/checkconfig.py#L663)) is a deliberate result (though with unfortunate side-effects .. see your issue) of [this](https://github.com/crossbario/crossbar/commit/f8121120f2523e2495df220c82ce6e45544d2738) commit, which I did to support upgrading configs while preserving order of arrays and dicts. Well. Ah yeah, and the docs and changelog, sure, that should be addressed too of course.

**Comment by oberstet** [comment]
```python
(python279_1)oberstet@thinkpad-t430s:~/scm/crossbario/crossbarexamples$ python
Python 2.7.9 (default, Jan 18 2015, 21:40:29) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from collections import Mapping, Sequence
>>> isinstance('hello', Sequence)
True
>>> isinstance('hello', list)
False
>>> 
```
