### ISSUE TITLE
parseWsUrl has moved

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#695]
The function has been moved from `autobahn.websocket.protocol.parseWsUrl` to `autobahn.websocket.util.parse_url`:

```console
(python279_1)oberstet@thinkpad-t430s:~/node4$ crossbar convert
Traceback (most recent call last):
  File "/home/oberstet/python279_1/bin/crossbar", line 9, in <module>
    load_entry_point('crossbar', 'console_scripts', 'crossbar')()
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/controller/cli.py", line 994, in run
    options.func(options, reactor=reactor)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/controller/cli.py", line 682, in run_command_convert
    from crossbar.common.checkconfig import convert_config_file
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/common/checkconfig.py", line 45, in <module>
    from autobahn.websocket.protocol import parseWsUrl
ImportError: cannot import name parseWsUrl
```

**Comment by stevenevados** [comment]
What version of autobahn.websocket are you using and where did you get it?  My system says there is no module called "util".

**Comment by meejah** [comment]
@stevenevados 0.14.0 from PyPI has ``autobahn.websocket.util.parse_url``

**Comment by stevenevados** [comment]
Thanks, that got me past that issue.

On Fri, May 6, 2016 at 2:01 PM, meejah <notifications@github.com> wrote:

> @stevenevados <https://github.com/stevenevados> 0.14.0 from PyPI has
> autobahn.websocket.util.parse_url
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/crossbario/crossbar/issues/695#issuecomment-217557510>
>



-- 
Steve Ihnen
Nevados Engineering
