### ISSUE TITLE
How to implments asyncrounous authentication with ticket method (using node.js) 

### ISSUE THREAD

**Issue by rafael-freitas** [crossbario/crossbar#700]
I need to check credentials on mongodb on authenticate method but it should return the rules else throw error if fail...
The question is: how I can to implement an asynchronous authenticator?

function authenticate (args) {
   var realm = args[0];
   var authid = args[1];
   var details = args[2];

   if (USERDB[authid] !== undefined) {
      if (null !== details.ticket && details.ticket == "pass_from_client") {
         // how to insert here an asynchronous solution? Can I return a promise? Or send back a response after?
         return {
            role: "frontend"
         }
      } else {
         throw "invalid ticket"
      }
   } else {
      throw "no such user";
   }
}

Something like this:
`
User.find( { login: authid, password: details.ticket }, function( err, result ) {
      // ok user must be authenticated...
     return {
            role: "frontend"
         }
} )
`

**Comment by oberstet** [comment]
Please use our mailing lists to ask questions:

* https://groups.google.com/forum/#!forum/autobahnws
* https://groups.google.com/forum/#!forum/crossbario
