### ISSUE TITLE
Crossbar won't start after update - Cannot import parseWsUrl

### ISSUE THREAD

**Issue by Tsunami2069** [crossbario/crossbar#709]
Hello guys.

Ran a update on crossbar and got a few updates (twister, setuptools, txaio and autobahn).

Unfortunately, our crossbar wouldn't start. Here's a screenshot of the error:

![autobahnerror](https://cloud.githubusercontent.com/assets/14236716/14424317/519788a6-ffd8-11e5-990c-37de3d046b82.JPG)

Rolled back on the updated tools and managed to pinpoint the culprit to Autobahn, meaning that, if i rollback autobahn to 0.13.0, crossbar starts fine.

Cheers...

**Comment by meejah** [comment]
I can confirm this; a fresh ``pip install crossbar`` needs an autobahn downgraded to 0.13.0 to work. (We re-named and moved that method in autobahn, so both ``master``s should work...)

**Comment by oberstet** [comment]
fixed with 0.13.2 release: https://pypi.python.org/pypi/crossbar/0.13.2

**Comment by Tsunami2069** [comment]
Confirmed.... All working with all modules up to date.

Thank you, keep up the great work.
