### ISSUE TITLE
Kernel detection for sharedport failed.

### ISSUE THREAD

**Issue by wboubi** [crossbario/crossbar#710]
If you have a kernel > 4.0 the test (line 50) in crossbar/twisted/sharedport.py failed.

It can be corrected by changing the test to :

`if (_LINUX_KERNEL_VERSION[0] == 3 and _LINUX_KERNEL_VERSION[1] >= 9) or _LINUX_KERNEL_VERSION[0] >= 4: `

**Comment by oberstet** [comment]
Oh, right. Thanks for this! Bug
