### ISSUE TITLE
API call to get all published topic names

### ISSUE THREAD

**Issue by joernroeder** [crossbario/crossbar#730]
I'm just wondering if there is an api call i can make from the client to receive a list off all (currently) available topic names?
thx in advance!

**Comment by goeddea** [comment]
You can get a list of all subscriptions (which gives you the subscription IDs) and then get the topics from that - see http://crossbar.io/docs/Subscription-Meta-Events-and-Procedures/.

BTW - there is a mailing list (https://groups.google.com/forum/#!forum/crossbario) which is intended for questions - this is an issue tracker!
