### ISSUE TITLE
Logging glitch

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#740]
I have a container worker with a Python component that does some (structured) logging. When Python is not running in unbuffered mode, I get

``` console
2016-04-26T15:22:26+0200 [Container   25289] INVALID JSON: {"level": "info", "text": "new worker database connection created (thread ID 139890767423232, backend PID 25416)", "namespace": "autobahn.wamp.protocol.ApplicationSession", "backend_pid": 25416, "thread_id": 139890767423232, "log_time": 1461676946.387648}{"level": "info", "text": "new worker database connection created (thread ID 139890775815936, backend PID 25417)", "namespace": "autobahn.wamp.protocol.ApplicationSession", "backend_pid": 25417, "thread_id": 139890775815936, "log_time": 1461676946.388107}
2016-04-26T15:22:26+0200 [Container   25289] INVALID JSON:
2016-04-26T15:22:26+0200 [Container   25289] INVALID JSON: {"level": "info", "text": "attaching new worker (thread ID 139890775815936, backend PID 25417) ...", "namespace": "autobahn.wamp.protocol.ApplicationSession", "backend_pid": 25417, "thread_id": 139890775815936, "log_time": 1461676946.388416}{"level": "info", "text": "attaching new worker (thread ID 139890767423232, backend PID 25416) ...", "namespace": "autobahn.wamp.protocol.ApplicationSession", "backend_pid": 25416, "thread_id": 139890767423232, "log_time": 1461676946.388542}
2016-04-26T15:22:26+0200 [Container   25289] INVALID JSON:
```

The reason is: structured logging when received over the pipes talking to a native worker fails to line separate the individual JSON log messages - stuff get collapsed into one line, and then it isn't JSON anymore and it bails out [here](https://github.com/crossbario/crossbar/blob/master/crossbar/controller/processtypes.py#L170)

**Comment by oberstet** [comment]
Also: the "INVALID JSON" message is a bit misleading - it's an internal error. We are doing it wrong. It is not the user's fault.

It's that same thing: Python running unbuffered. Right now, I forgot what and where we did something about it. But it is pretty annoying. This is like the third or forth time me myself falling into this trap;)

**Comment by oberstet** [comment]
For others passing by: this is in essence totally harmless, but since it is so annoying, I make it a "bug".

**Comment by oberstet** [comment]
Mmh. We already make the Python executable spawned for containers/workers unbuffered: https://github.com/crossbario/crossbar/blob/master/crossbar/controller/process.py#L408

We probably need to flush too? After each and every write to the pipe for structured logging ..

**Comment by meejah** [comment]
Also relevant, "hynek" pointed out this to me in #autobahn: http://stackoverflow.com/a/23034580/476759

So, we can just set PYTHONUNBUFFERED on our "current" process in Python3, but have to re-open stdout/stderr to get the same behavior on Python2 -- that is, unbuffered support in the main crossbar process (without forcing everyone to remember to set PYTHONUNBUFFERED in their shells...)

**Comment by FirefighterBlu3** [comment]
i'm guessing this bug is still relevant for systems? i just spent a bit of time thinking something was wrong in my server setup after making crossbar a systemd unit file managed instance and there was no output being collected. i needed to add PYTHONUNBUFFERED=1 to the unit file Environment= line.

the odd thing -- i didn't need to do this on my raspberrypi.

```
# server that requires PYTHONUNBUFFERED in environment before starting
┌[✓ Fri/Oct21 06:47:29z root@nds [/etc/systemd/system]
└─> crossbar version
     __  __  __  __  __  __      __     __
    /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
    \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
                                        
 Crossbar.io        : 0.15.0
   Autobahn         : 0.16.0 (with JSON, MessagePack, CBOR, UBJSON)
   Twisted          : 16.4.1-EPollReactor
   LMDB             : 0.89/lmdb-0.9.18
   Python           : 3.5.2/CPython
 OS                 : Linux-4.8.2-1-ARCH-x86_64-with-arch
 Machine            : x86_64
```

```
# raspberrypi where it worked without needing to add to environment
┌[✓ Fri/Oct21 06:50:36z root@reeferboy [/etc/systemd/system]
└─> crossbar version
     __  __  __  __  __  __      __     __
    /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
    \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
                                        
 Crossbar.io        : 0.15.0
   Autobahn         : 0.16.0 (with JSON, MessagePack, CBOR, UBJSON)
   Twisted          : 16.4.1-EPollReactor
   LMDB             : 0.89/lmdb-0.9.18
   Python           : 3.5.2/CPython
 OS                 : Linux-4.4.15-1-ARCH-armv6l-with-arch
 Machine            : armv6l
```

both systems are using almost identical setups for the crossbar worker and app, the config.json as well. notably, PYTHONUNBUFFERED is in config.json on both of them already.

**Comment by meejah** [comment]
I don't follow why the lack of a flush (and/or buffering) might lead to the INVALID JSON -- the code appears to be looking for a "record separator" special symbol. So it's like that's not getting written correctly/always or the parsing code isn't splitting properly on it -- and anyway, if we really are depending on a flush() or a certain amount of data to be written "at once", that's a bug in itself.

**Comment by oberstet** [comment]
haven't seen this "INVALID JSON" in a long time.

also, re:

> if we really are depending on a flush() or a certain amount of data to be written "at once", that's a bug in itself.

yes! that would be a bug ..
