### ISSUE TITLE
Something seems wrong

### ISSUE THREAD

**Issue by firasalkafri** [crossbario/crossbar#743]
I am getting this error constantly and I ended up setting a crobjob to restart the router every few hours:

`2016-04-28T16:26:59+0000 [Router1931] Could not accept new connection (EMFILE)
`

I have already tried increasing emfile limits on our servers but that didn't help, is there some specific configuration that would optimize the router's performance in the case of too many subscriptions/unsubscriptions in an IM app?

**Comment by oberstet** [comment]
Please ask questions on the mailing list https://groups.google.com/forum/#!forum/crossbario
