### ISSUE TITLE
crossbar/worker/test/examples/syntaxerror.py causing build issue

### ISSUE THREAD

**Issue by tpetazzoni** [crossbario/crossbar#750]
The file `crossbar/worker/test/examples/syntaxerror.py` apparently contains an intentional syntax error. Unfortunately, when byte-compiling, this causes an error, which is annoying for distributions or build systems that aim at checking byte-compiling issues.

Here is the issue:

```
PYTHONPATH="/home/thomas/projets/buildroot/output/target/usr/lib/python3.5/sysconfigdata/:/home/thomas/projets/buildroot/output/target/usr/lib/python3.5/site-packages/" /home/thomas/projets/buildroot/output/host/usr/bin/python3.5 support/scripts/pycompile.py /home/thomas/projets/buildroot/output/target/usr/lib/python3.5
Traceback (most recent call last):
  File "/home/thomas/projets/buildroot/output/host/usr/lib/python3.5/py_compile.py", line 125, in compile
    _optimize=optimize)
  File "<frozen importlib._bootstrap_external>", line 697, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/thomas/projets/buildroot/output/target/usr/lib/python3.5/site-packages/crossbar/worker/test/examples/syntaxerror.py", line 33
    class # noqa
               ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomas/projets/buildroot/output/host/usr/lib/python3.5/compileall.py", line 145, in compile_file
    optimize=optimize)
  File "/home/thomas/projets/buildroot/output/host/usr/lib/python3.5/py_compile.py", line 129, in compile
    raise py_exc
py_compile.PyCompileError:   File "/home/thomas/projets/buildroot/output/target/usr/lib/python3.5/site-packages/crossbar/worker/test/examples/syntaxerror.py", line 33
    class # noqa
               ^
SyntaxError: invalid syntax
```

Would it be possible to find a solution that does not break byte compilation? For the moment, we have to patch this file to avoid the syntax error.

**Comment by oberstet** [comment]
FWIW, this test is to test when there is a syntax error in user code that is to be started as a worker under Crossbar.io - it makes sure we properly catch that and process it (in the node controller). It is a quite important test.

Obviously, we could exclude the tests from distribution - but people will then complain about the tests missing (some distros have rules about that).

To be honest, I don't know what else we could do. It has to be a hard syntax error for the test to be "valid".

Maybe you could exclude certain directories from the byte compilation?

**Comment by oberstet** [comment]
We could exclude that single file https://github.com/crossbario/crossbar/blob/master/crossbar/worker/test/examples/syntaxerror.py from the distribution .. I have no clue if that "breaks" OS distro rules though. Well. But we would a good argument to exclude (as in above) at least.

**Comment by tpetazzoni** [comment]
You could either exclude it from the distribution, or maybe some environment variable that exists when the tests are run could be used so that the invalid syntax is only visible when the tests are executed, or something like that?

For the moment, we will simply patch the file to remove the syntax error, but it's not great to carry patches that cannot be merged upstream :/

**Comment by oberstet** [comment]
@meejah @hawkowl any ideas / preferences?

**Comment by hawkowl** [comment]
@oberstet write it out at runtime to a temp dir and then import it, maybe?

**Comment by meejah** [comment]
What about raising a ``SyntaxError`` "by hand" in the test, so e.g. instead of the ``class `` line, it's just ``raise SyntaxError('testing')``

**Comment by oberstet** [comment]
I think both of the suggestions are better than simply excluding the whole module `crossbar.worker.test`, and both would work.

With manually raising `SyntaxError`, the test implicitly relies on Python actually raising exactly this upon a real syntax error - which I'd say should be safe to rely on;)

Sidenote: interestingly, CPython and PyPy bail out at different places here (seems their source parsers work differently):

```console
(cpy351_2) oberstet@thinkpad-t430s:~/scm/crossbario/ueberschall$ python ~/.profile
  File "/home/oberstet/.profile", line 12
    if [ -n "$BASH_VERSION" ]; then
                          ^
SyntaxError: invalid syntax
(cpy351_2) oberstet@thinkpad-t430s:~/scm/crossbario/ueberschall$ /opt/crossbar/bin/pypy ~/.profile
  File "/home/oberstet/.profile", line 24
    export JS_COMPILER=$HOME/compiler.jar
                       ^
SyntaxError: Unknown character
(cpy351_2) oberstet@thinkpad-t430s:~/scm/crossbario/ueberschall$ echo "raise SyntaxError()" >> foo.py
(cpy351_2) oberstet@thinkpad-t430s:~/scm/crossbario/ueberschall$ python foo.py 
Traceback (most recent call last):
  File "foo.py", line 1, in <module>
    raise SyntaxError()
SyntaxError: None
(cpy351_2) oberstet@thinkpad-t430s:~/scm/crossbario/ueberschall$ /opt/crossbar/bin/pypy foo.py 
Traceback (most recent call last):
  File "foo.py", line 1, in <module>
    raise SyntaxError()
SyntaxError: None
```

More fun:

```console
(cpy351_2) oberstet@thinkpad-t430s:~/scm/crossbario/ueberschall$ /opt/crossbar/bin/pypy ~/Musik/Camo\ Krooked\ -\ Zeitgeist/01\ -\ camo-and-krooked-turn-back-the-time-original.flac 
  File "/home/oberstet/Musik/Camo Krooked - Zeitgeist/01 - camo-and-krooked-turn-back-the-time-original.flac", line 1
    fLaC"�E`
        ^
SyntaxError: Unknown character
(cpy351_2) oberstet@thinkpad-t430s:~/scm/crossbario/ueberschall$ python ~/Musik/Camo\ Krooked\ -\ Zeitgeist/01\ -\ camo-and-krooked-turn-back-the-time-original.flac   File "/home/oberstet/Musik/Camo Krooked - Zeitgeist/01 - camo-and-krooked-turn-back-the-time-original.flac", line 1
SyntaxError: Non-UTF-8 code starting with '\xc4' in file /home/oberstet/Musik/Camo Krooked - Zeitgeist/01 - camo-and-krooked-turn-back-the-time-original.flac on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

----

Manually raising is less intrusive, because we don't rely on being able to actually have a writable directory somewhere etc., and the change is trivial. Which is good;) So I'm for manually raising `SyntaxError`.

**Comment by om26er** [comment]
I am faced with the exact same issue while bytecompiling crossbar, I delete the `syntaxerror.py` file to "fix" that. It feels pretty natural to me to **not** ship tests with the wheel, if anyone needs to run the tests they should probably do that from source ?

**Comment by oberstet** [comment]
FWIW, revisiting this issue, I think _if_ we can preserve the actual test semantics (which checks that crossbar well behave even when a python module to be loaded as a router-embedded or container component as a plain syntax error ..) with what @meejah  hints at (`raise SyntaxError`), then that is the best solution.

**Comment by meejah** [comment]
I'm a little agnostic on "include tests in the dist" (I've done both) but lots of people like/recommend including the tests. (And I know at least Debian does run them if they're included). So, I don't think re-architecting all the tests to "not be in the distribution" is worthwhile.

The easiest thing seems to be "explicitly raise `SyntaxError` ourselves -- and I think still preserves the idea here (test that crossbar doesn't freak out on a syntax error).

**Comment by meejah** [comment]
I'm only 99% sure that `raise SyntaxError("whatever")` is the same semantics as "a 'real' syntax-error in a .py file"....

**Comment by oberstet** [comment]
yeah, also not sure. I seem to remember it is not the same.

plus, yes, distros don't even agree whether to include tests or not and why should we care or waste time on that (like potentially breaking a working test)? deleting the file is simple enough while building (should the whatever build system insist on that).

**Comment by meejah** [comment]
yeah, I even meant from a "python programmer's" perspective there's disagreement on that ;) And yeah, distros will do what they do...

**Comment by oberstet** [comment]
distros do distro things;) we are not a distro, but promote vendor packaging
