### ISSUE TITLE
User input crashes Crossbar.io

### ISSUE THREAD

**Issue by CasperAlant** [crossbario/crossbar#781]
I run a chat room and occasionally a user would input odd characters which would cause Crossbar.io to crash until I manually removed the message from the database. I exported the message that caused the crash, and I am able to recreate the crash by importing the message into my local database.

I have not been able to recreate the problem by copying and pasting the offending text. I think the encoding gets fixed when you do that.

The error:
`2016-05-07T19:58:19+0200 [Router      14800] Unable to format event {'log_logger': <Logger 'crossbar.router.protocol.WampWebSocketServerProtocol'>, 'log_time': 1462643899.836672, 'log_source': None, 'log_format': 'Traceback (most recent call last):\n  File "/home/casper/.local/lib/python2.7/site-packages/autobahn/wamp/websocket.py", line 88, in onMessage\n    for msg in self._serializer.unserialize(payload, isBinary):\n  File "/home/casper/.local/lib/python2.7/site-packages/autobahn/wamp/serializer.py", line 106, in unserialize\n    raise ProtocolError("invalid serialization of WAMP message ({0})".format(e))\nProtocolError: invalid serialization of WAMP message (Expected object or value)\n'}: tuple index out of range`

I cannot attach the SQL file used to recreate the problem. My fear is that by pasting the SQL here, the encoding may get fixed along the way. Here it is in any case:
`INSERT INTO `message` (`id`, `chat_room_id`, `user_id`, `date_time`, `message`, `deleted`) VALUES
(309973, 1, 4753, '2016-05-07 17:57:02', ': â€¦â€¦â€¦â€¦â€¦â€¦â€¦â€¦..._,,,...,,,_  â€¦â€¦â€¦â€¦â€¦â€¦â€¦..,-â€˜Â´ . . . _,,,,,'';:-,  â€¦â€¦â€¦â€¦â€¦â€¦..,-(c\\ \\`;-=Â´,_,-~-, \\`.  â€¦â€¦â€¦â€¦â€¦â€¦,/ . . .Â¯''\\, Âº ,/.â€˜-~Â°,â€˜ .Â¯`â€™-.  â€¦â€¦....â€¦....../ . . . . . .Â¯,_ ~--~â€™,, . . .''\\  â', 0);
`

Please let me know if there is anything more I can do to help. Basically this bug allows any user to bring a Crossbar.io application to its knees by posting some bad characters.

**Comment by oberstet** [comment]
What WAMP client library is accessing the database?

**Comment by CasperAlant** [comment]
PHP voryx/Thruway

**Comment by oberstet** [comment]
Please report there. This is likely a Thruway bug (wrong WAMP serialization). You can enable `--loglevel=trace` in Crossbar.io to get an (insane) amount of log output - including the bytes received.
