### ISSUE TITLE
Subscriber Black-/Whitelisting broken? Not broken? Undocumented?

### ISSUE THREAD

**Issue by deceze** [crossbario/crossbar#792]
I'm really interested in Subscriber Whitelisting based on `authrole`. According to [the documentation](http://crossbar.io/docs/Subscriber-Black-and-Whitelisting/) it was slated for 0.12.0 and it appears to be somewhat implemented, but the documentation has not been updated and I can't tell whether I'm misinterpreting how it *should* work, or whether it doesn't work as it should.

When publishing this:

```python
self.publish('foo', options=PublishOptions(eligible_authrole=['anonymous']))
```

The event is received by *anyone*, regardless of their `authrole`. Does that mean `authrole = 'anonymous'` is equivalent to "ignore authrole"? I'd have expected, and would require, that it means "send the event to all subscribers with `authrole` "anonymous". Or is the entire feature broken and not yet ready for primetime?

**Comment by DZabavchik** [comment]
A different approach that doesn't require delegating authorization responsibilities to publishers can be taken: use URI as discriminator instead.

- Configure authorizations via config file or dynamic authorizer.  Allow certain roles to subscribe to topics based on some convention/rules/etc.
- Publish messages with URIs specific to role(s) 
```Python
self.publish('foo.for.anonymous')
```

Will probably be more efficient than filtering through subscribers on every `publish`.

**Comment by deceze** [comment]
@DZabavchik I'm aware of that solution and it's what I'm currently doing, but I would in fact like to *simplify* that and use one defined topic instead of several. I need to notify specific front-end clients, for which I need to publish to a set of specific `eligible` session ids, and in addition I want to notify all of my `anonymous` backend about the event. `PublishOptions(eligible=[..], eligible_authrole=['anonymous'])` would do that perfectly, if it would actually work that way. Since this is published by a central coordinating authority, there's little concern about it taking on that responsibility.

**Comment by DZabavchik** [comment]
I see.  Faced similar problem.  Boils down to is `unicast` vs `multicast` vs `broadcast`.

Looked at the source and your snippet.  Try adding `u` for auth role.  Stepped on that rake with dynamic authenticator.

```Python
self.publish('foo', options=PublishOptions(eligible_authrole=[u'anonymous']))
```

**Comment by deceze** [comment]
@DZabavchik I'm running this on Python 3, `u''` should have zero effect.

**Comment by DZabavchik** [comment]
Although `eligible_authrole`, `exclude`, `exclude_authid`, `exclude_authrole`, `eligible`,             `eligible_authid` can be set on `PublishOptions` (autobahn/wamp/types), broker only seems to look for `eligible` and `excluded` session ids

```Python
# filter by "eligible" receivers
#
if publish.eligible:

    # map eligible session IDs to eligible sessions
   eligible = []
    for session_id in publish.eligible:
        if session_id in self._router._session_id_to_session:
            eligible.append(self._router._session_id_to_session[session_id])

    # filter receivers for eligible sessions
    receivers = set(eligible) & receivers

# remove "excluded" receivers
#
if publish.exclude:

    # map excluded session IDs to excluded sessions
    exclude = []
    for s in publish.exclude:

```

**Comment by oberstet** [comment]
The feature isn't implemented yet https://github.com/crossbario/crossbar/issues/656
