### ISSUE TITLE
Installing with pip 8.1.2 fails

### ISSUE THREAD

**Issue by moracarlos** [crossbario/crossbar#793]
I recently asked on crossbardocs but the issue was closed before I could reply. I'm having problems trying to install crossbar.io on Raspbian Jessie (RPi 3 model B). The error I'm getting is:

```
pi@raspberrypi:~ $ sudo pip install crossbar
Collecting crossbar
  Using cached crossbar-0.13.2-py2.py3-none-any.whl
Invalid requirement: 'pyinotify>=0.9.6; linux in "sys_platform"'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 78, in __init__
    req = Requirement(req)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
InvalidRequirement: Invalid requirement, parse error at "'; linux '"
```

@oberstet told me to try with `sudo pip install -U pip` before, but it didn't work. This is what I get:

```
pi@raspberrypi:~ $ sudo pip install -U pip
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages
pi@raspberrypi:~ $ sudo pip install crossbar
Collecting crossbar
  Using cached crossbar-0.13.2-py2.py3-none-any.whl
Invalid requirement: 'pyinotify>=0.9.6; linux in "sys_platform"'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 78, in __init__
    req = Requirement(req)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
InvalidRequirement: Invalid requirement, parse error at "'; linux '"
```

**Comment by meejah** [comment]
Can you try ``sudo pip install pip==8.1.1``? (I think 8.1.2 may have changed/broken how those types of dependencies are parsed).

(Also, FWIW it's usually recommended to not use pip globally/as root like that an instead operate in virtualenvs).

**Comment by meejah** [comment]
See also: https://github.com/pypa/packaging/issues/75

**Comment by meejah** [comment]
@oberstet I think all we need to fix this is a new crossbar release; current master doesn't include the pyinotify dependency anyway.

**Comment by moracarlos** [comment]
It worked! Thanks so much @meejah

**Comment by oberstet** [comment]
@meejah yeah, a new release! I replaced pyinotify with watchdog .. and one reason was to get rid of the conditional dependencies, as the latter supports multiple platforms.

**Comment by aaronk1** [comment]
Same issue here.  Works with 8.1.1 but not with 8.1.2.

**Comment by meejah** [comment]
Since the PyPA bug is fixed, I think it's just a matter of waiting for a 8.1.3 or 8.2.0 release of pip.
