### ISSUE TITLE
REST Bridge is broken when require_ip option is used

### ISSUE THREAD

**Issue by chaosk** [crossbario/crossbar#798]
Setting `require_ip` causes all HTTP requests result in a 500 response.

Crossbar log:

> Unhandled exception in Crossbar: ValueError('This is already a native string.',)

Error happens here: https://github.com/crossbario/crossbar/blob/4fe0cc89dce00c01bc53a14958a85ca4bb37fa76/crossbar/adapter/rest/common.py#L393

Transport path configuration:

```
...
"publish": {
    "type": "publisher",
    "realm": "default",
    "role": "application",
    "options": {
        "require_ip": ["127.0.0.1"]
    }
}
...
```

**Comment by oberstet** [comment]
@chaosk Could you dump the output of `crossbar version` here please? Python 2 vs 3 etc ..

**Comment by hawkowl** [comment]
Thanks for the report @chaosk, I'll look into it.

**Comment by chaosk** [comment]
`crossbar version` output:
```                                        
 Crossbar.io        : 0.13.2
   Autobahn         : 0.14.0 (with JSON, MessagePack, CBOR)
   Twisted          : 16.1.1-EPollReactor
   LMDB             : 0.89/lmdb-0.9.18
   Python           : 3.4.3/CPython
 OS                 : Linux-4.2.0-25-generic-x86_64-with-Ubuntu-15.10-wily
 Machine            : x86_64
```

**Comment by slav0nic** [comment]
``` Crossbar.io        : 0.15.0
   Autobahn         : 0.16.0 (with JSON, MessagePack, CBOR, UBJSON)
   Twisted          : 16.4.1-EPollReactor
   LMDB             : 0.89/lmdb-0.9.18
   Python           : 3.5.2/CPython
 OS                 : Linux-4.6.0-1-amd64-x86_64-with-debian-stretch-sid
 Machine            : x86_64
```
have same problem

**Comment by meejah** [comment]
@hawkowl can we just `return string` here https://github.com/crossbario/crossbar/blob/4fe0cc89dce00c01bc53a14958a85ca4bb37fa76/crossbar/_compat.py#L44 or is there Good Reasons that's an error?

**Comment by slav0nic** [comment]
in py3 tests `request.getClientIP()` return `bytes`, in real app `str`

**Comment by meejah** [comment]
Thanks for the patch @slav0nic!

(...and sorry the broken master build meant this took a while to merge even though it's a simple fix...)
