### ISSUE TITLE
Links to meta API are missing/broken

### ISSUE THREAD

**Issue by ecorm** [crossbario/crossbar#816]
I can longer find working document links to the meta API. In the Program Guide page, there's only a dead "Session Metaevent" link.

**Comment by goeddea** [comment]
Thanks for pointing out the broken link (fixed and deployed).

The links from the TOC (http://crossbar.io/docs/Table-of-Contents/) all work (http://crossbar.io/docs/Registration-Meta-Events-and-Procedures/, http://crossbar.io/docs/Subscription-Meta-Events-and-Procedures/, http://crossbar.io/docs/Session-Metaevents-and-Procedures/).
