### ISSUE TITLE
Authorizer actions are not documented

### ISSUE THREAD

**Issue by ecorm** [crossbario/crossbar#817]
The list of possible values for the `action` argument of the dynamic authorizer are not documented. In the meantime, if someone familiar with the Crossbar codebase can post a link to the relevant source file, that would be great.

The possible non-boolean return values should also be documented.

**Comment by oberstet** [comment]
register/subscribe actions:

```json
{
    "allow": true
}
```

call/publish actions:

```json
{
    "allow": true,
    "disclose": true
}
```

> Note: we'll also have an attribute `"cache": true` in the future for all actions.

**Comment by oberstet** [comment]
See: https://github.com/crossbario/crossbar/blob/master/crossbar/router/role.py#L286

**Comment by oberstet** [comment]
For backwards compat, you can also return a bool: https://github.com/crossbario/crossbar/blob/master/crossbar/router/router.py#L274
