### ISSUE TITLE
Can I do RESTFul API on Crossbar

### ISSUE THREAD

**Issue by morfair** [crossbario/crossbar#819]
Hello!
I like async of Crossbar Python AppComponent, I like this inline callbacks, its architecture etc. But I don't want use Autobahn.JS for clients, I don't want use WebSoccket on js-clients, I want use integrated in clients js framework restful methods like get/post/pathc/delete.
Do I have a tools to do this, or should I go back to Django REST framework?

**Comment by meejah** [comment]
You should ask questions like this on the mailing list or IRC. The answer in this case is "yes, there's ReST support".
