### ISSUE TITLE
Proposal : add interactive config reference to admin doc section

### ISSUE THREAD

**Issue by kernicPanel** [crossbario/crossbar#821]
Hi there

Thanks for your great work!

I'm currently working on a new doc page which is very similar to http://browsenpm.org/package.json but that can be used as a kind of TOC (#762)

So I have some questions:
1. What do you think of the idea?
2. I'm a little confused about what is up to date, as http://crossbar.io/docs/ seems out of sync with https://github.com/crossbario/crossbar/tree/master/docs (ie http://crossbar.io/docs/Manhole/ doesn't exists anymore on repo). I think I should use the repo as a reference, but I'd like to have a confirmation.
3. Currently I'm using `python -m flask run` to work on doc.
   Is it the recomended way?
4. I'm using already generated id attributes on h*, but on live site rendering is different.
   I there some way to buid a preview more close to the live one?

**Comment by meejah** [comment]
Hi @kernicPanel, I think it's a neat idea, after looking at the linked example.

Currently the docs are being moved back into this repository; I'm not sure of the exact status of that, but I'd say if in doubt the repo is right. I run the docs-site locally with `python docs/test_server.py` -- does this look better?

I don't understand the last question. @oberstet should know the answers to these.

**Comment by oberstet** [comment]
@kernicPanel sorry for the sluggish response - any helps / ideas with the docs is definitely highly appreciated!

The docs moving has been finished, and most glitches (broken links) _should_ be fixed. But well, maybe not all.

This repo here is the authorative source of docs for Crossbar.io - if our website is out of sync, then we failed to deploy the latest docs from here.

To work on the docs locally:

```console
pip install -r requirements-dev.txt
python docs/test_server.py
```

There should be a correspondence in URLs then:

* Local: http://127.0.0.1:8080/docs/Administration/#node-configuration
* Deployed: http://crossbar.io/docs/Administration/#node-configuration

**Comment by kernicPanel** [comment]
Hi @meejah, @oberstet 

Thanks for your answers.
Sorry too for my late response, I'm currently quite busy, but I'll work on this probably during august.
But this week, I'll try to expose more details of what I have done, so we could discuss it soon.
