### ISSUE TITLE
docs/Ticket-Authentication/: Can't understand the English.

### ISSUE THREAD

**Issue by tohagan** [crossbario/crossbar#827]
I'm sorry I have no idea what the highlighted English is supposed to mean ... Can you please revise it?  I'm a native English speaker.

"You need to explicitly allow Anonymous Authentication for a particular transport - as a default this is not allowed. Clients may explicitly request Anonymous Authentication, **but this is attempted absent any explicit defined authentication scheme as well**.

**Comment by tohagan** [comment]
I'm a native English speaker so I'm happy to review your suggested change if that helps.

**Comment by FirefighterBlu3** [comment]
it means that anonymous auth will be attempted if no other auth method is explicitly defined

**Comment by tohagan** [comment]
OK ... That make more sense!  Thanks.

**Comment by tohagan** [comment]
Hmmm actually that seems to contradict this statement "You need to explicitly allow Anonymous Authentication for a particular transport - as a default this is not allowed."

**Comment by FirefighterBlu3** [comment]
glad to help! it does appear to, and i'd like to test it to see the actual reaction but i believe the intent is to say that as long as some other auth method is defined, anonymous auth is not permitted by default. only in the case where no auth method is defined, it will then permit anonymous auth

**Comment by tohagan** [comment]
ok thanks. High quality docs are a major part of convincing developers to join your developer community.  I'm currently reading the all auth pages and thought I should provide some feedback where I found the explanation needed clarification.

**Comment by meejah** [comment]
@tohagan thanks for the feedback. I think it actually means two things:

1. the server has to explicitly enable anonymous authentication
2. clients will always try anonymous authentication, but can also explicitly request it if they want.

**Comment by tohagan** [comment]
The other Auth pages read very well :)

**Comment by meejah** [comment]
@tohagan does the wording in #828 sound better?
@oberstet is that actually correct still?

**Comment by tohagan** [comment]
Wording sounds much clearer.   Thanks.

**Comment by meejah** [comment]
merged.
