### ISSUE TITLE
crossbar 0.14.0 + twisted 16.3.0: messages don't get through websocket to crossbar

### ISSUE THREAD

**Issue by aleksmm** [crossbario/crossbar#829]
With the recent twisted 16.3.0 release I can't get latest crossbar working anymore. To reproduce the issue just create virtualenv with crossbar 0.14.0 installed and run example application and in tcpdump/browser console I see communication stuck after first wamp message via websocket.

Last log entry in crossbar output is 

[log1.txt](https://github.com/crossbario/crossbar/files/351982/log1.txt)

then it should follow with auth process, but it doesn't, because looks like doesn't get the message

[log2.txt](https://github.com/crossbario/crossbar/files/351984/log2.txt)

I tested this on Centos 6 and Ubuntu 16

**Comment by Tsunami2069** [comment]
Having the same issue.
After the update to twisted 16.3.0, launching my application gets stuck on the very first websocket operation that it tries to run.

Reverted back to Twisted 16.2.0 and its back to running ok.

Good luck, keep up the great work.

**Comment by kojicz983** [comment]
Reverting back to Twisted 16.2.0 doesn't help in my case

**Comment by meejah** [comment]
@kojicz983 can you try 16.1.1?

**Comment by kojicz983** [comment]
@meejah I have tried Twisted 16.1.1 Same story.

**Comment by AndreMiras** [comment]
I also had the issue with Crossbar 0.14.0 on Ubuntu Xenial and 2.7.11+.
I had to revert to Twisted==16.2.0 both Crossbar side and client side.

**Comment by meejah** [comment]
@kojicz983 Maybe you're running into a different issue? The symptom for 16.3.0 is that the connection "succeeds" but then nothing else works (it is because the underlying transport has become paused).

**Comment by oberstet** [comment]
I believe Autobahn 0.15.0 and Crossbar.io 0.15.0 just released properly work around recent Twisted changes that broke our stuff. Sorry for the glitch - complex interaction between projects moving fast (Crossbar.io / Twisted) ..

Anways. We now run Ubuntu 16.04 / Crossbar.io 0.15.0 on our public demo instances - see the version at the bottom of:

* https://cbdemo-eu-central-1.crossbar.io/ws
* https://cbdemo-us-west-1.crossbar.io/ws

and

```console
oberstet@thinkpad-t430s:~/scm/crossbario/crossbar$ ssh ubuntu@cbdemo-eu-central-1.crossbar.io
Welcome to Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-31-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.


Last login: Thu Jul 21 22:18:35 2016 from 195.77.54.65
ubuntu@cbdemo-eu-central-1:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
ubuntu@cbdemo-eu-central-1:~$ 
``` 

@AndreMiras @aleksmm @Tsunami2069 @kojicz983 

Could you please check on your side if it works for you?

**Comment by aleksmm** [comment]
just confirmed with my code:

crossbar 0.15.0 + autobahn 0.15.0 + Twisted 16.3.0 = working
crossbar 0.14.0 + autobahn 0.15.0 + Twisted 16.3.0 = working
crossbar 0.15.0 + autobahn 0.14.0 + Twisted 16.3.0 = not working

so looks like it is fixed. Thank you so much.

**Comment by AndreMiras** [comment]
Yes I first gave a try installing crossbar 0.14.0 and Twisted 16.3.0 to see if I could reproduce. But I couldn't because crossbar 0.14.0 was still pulling autobahn 0.15.0. After investigating different setups I came to the exact same conclusion as @aleksmm.

**Comment by kojicz983** [comment]
Confirmed. Thank you.
