### ISSUE TITLE
Reflection service apparently does not work

### ISSUE THREAD

**Issue by jsy1001** [crossbario/crossbar#835]
Hello,

I am trying to access the Crossbar.io reflection service using the example JavaScript code at http://crossbar.io/docs/Using-Schemas/

With either the demo router at wss://demo.crossbar.io/ws or Crossbar.io 0.13.2 running locally, the code fails with:

    failed to retrieve schemas Object { error: "wamp.error.no_such_procedure", args: Array[1], kwargs: Object }

Can someone please suggest what I am doing wrong. Does the reflection service need to be configured somehow?

Many thanks.

**Comment by oberstet** [comment]
The reflection feature is not yet finished. We should mark the feature as "under developement" in the documentation.

**Comment by jsy1001** [comment]
OK, thanks.
