### ISSUE TITLE
TLS non-existant path 'server_cert.pem'

### ISSUE THREAD

**Issue by moracarlos** [crossbario/crossbar#837]
I'm trying to use crossbar with TLS support and it throws me the following error:

`2016-07-17T17:28:10-0400 [Controller   5081] Invalid node configuration
2016-07-17T17:28:10-0400 [Controller   5081] 'ca_certificates' contains non-existant path 'server_cert.pem'`

My .crossbar/ directory contains these files:
`-rw-r--r--  1 moracarlos  staff  3122 Jul 17 17:25 config.json

-rw-r--r--  1 moracarlos  staff   244 Jul 17 17:05 dhparam.pem

-rw-------  1 moracarlos  staff   323 May  5 22:01 key.priv

-rw-------  1 moracarlos  staff   218 May  5 22:01 key.pub

-rw-r--r--  1 moracarlos  staff   487 Jul 17 17:28 node.pid

-r--------  1 moracarlos  staff  1175 Jul 17 17:05 server_cert.pem

-rw-r--r--  1 moracarlos  staff  1678 Jul 17 17:05 server_key.pem
`

PS: When I use absolute paths, it works perfect.

**Comment by oberstet** [comment]
The path needs to be either absolute or relative to the Crossbar.io node directory - which is the directory where your `config.json` resides.

**Comment by moracarlos** [comment]
I know it shoud be relative or absolute, but even using the wss example, I get this error:

`2016-10-08T21:18:55-0400 [Controller   7620] Invalid node configuration
2016-10-08T21:18:55-0400 [Controller   7620] 'ca_certificates' contains non-existant path './server_cert.pem'`

I'm using OSX

**Comment by meejah** [comment]
With both master and 0.15.0 the `crossbarexamples/authentication/tls/static` example works for me (both as-is or when I change the paths to `./*.pem`). This is on Debian. Does this example work for you, @moracarlos ? Or, what example is "the wss example" you refer to?

**Comment by moracarlos** [comment]
When running the python wss example (https://github.com/crossbario/crossbarexamples/tree/master/wss/python)
