### ISSUE TITLE
Controller attribute 'title' cannot be an environment variable

### ISSUE THREAD

**Issue by aquemy** [crossbario/crossbar#843]
Hi,

FYI: Crossbar.io Version: 0.15.0, Python 2.7

In the [documentation](http://crossbar.io/docs/Controller-Configuration/), I've seen that the default value of the controller title is the hostname of the machine.

I tried to explicitly set the title as ```$HOSTNAME``` because I think this is an awesome feature but unfortunately, ```checkconfig.py``` is checking the validity of that field using ```
_CONFIG_ITEM_ID_PAT_STR``` and not ```_ENV_VAR_PAT_STR```:

```
invalid configuration item ID '$HOSTNAME' - must match regular expression ^[a-z][a-z0-9_]{2,11}$
```

By the way, I had to guess the possibility to use environment variable into the configuration. IMHO, it would be great to add it to the documentation.

Regards,

**Comment by oberstet** [comment]
Reading configuration item values from env vars is not a general feature - only a handful of places allow that. In general, a CB config should be as much self-contained and non-system dependent as possible. 

Won't fix
