### ISSUE TITLE
Cannot set 'shutdown' controller attribute

### ISSUE THREAD

**Issue by aquemy** [crossbario/crossbar#844]
Hi,

FYI: Crossbar.io Version: 0.15.0, Python 2.7

I wanted to modify the ```shutdown``` controller attribute and I understood it should be a list (by the way, it is not documented [here](http://crossbar.io/docs/Controller-Configuration/)).

However, with or without ~~you~~ a list, I got the following:

```console
raise InvalidConfigException("invalid type {} for 'shutdown' in node controller options (must be a list)".format(type(options['shutdown_mode'])
```

I am using Python 2.7 and the test [here](https://github.com/crossbario/crossbar/blob/f4fa8a00b15d683280f36cfae6af2e9cad5e887a/crossbar/common/checkconfig.py#L2641) returns false when I do a simple manual test:

```python
>>> type(options['shutdown'])
<type 'list'>
>>> type(options['shutdown']) == Sequence
False
```

I suppose this is a problem of conversion earlier in the configuration check process but I am not really familiar with it.

On top of that ```['shutdown_mode']``` should be ```shutdown``` [here](https://github.com/crossbario/crossbar/blob/f4fa8a00b15d683280f36cfae6af2e9cad5e887a/crossbar/common/checkconfig.py#L2642).

Regards,

**Comment by meejah** [comment]
Yes, the check should be using `isinstance` not `==`

**Comment by oberstet** [comment]
Fixed via https://github.com/crossbario/crossbar/pull/845
