### ISSUE TITLE
WebSocket connection denied: origin 'null' not allowed

### ISSUE THREAD

**Issue by amigo00678** [crossbario/crossbar#850]
Hey! I've got crossbar running.
And copied files from sample:

http://pastebin.com/3pm5yGCK

so a call to `connection.open();` gives error:
`[Router      10008] failing WebSocket opening handshake ('WebSocket connection denied: origin 'null' not allowed')`

**Comment by amigo00678** [comment]
Hi oberstet! How can I fix this? I guess there was not a bug but some misconfiguration.

**Comment by amigo00678** [comment]
Thanks a lot!

**Comment by oberstet** [comment]
was fixed in https://github.com/crossbario/crossbar/pull/832
