### ISSUE TITLE
Dynamic authentication: authextra argument will not be forwarded.

### ISSUE THREAD

**Issue by KemperVreden** [crossbario/crossbar#853]
When using dynamic authentication the `authextra` argument of `def join(self, realm, authmethods=None, authid=None, authrole=None, authextra=None):` will not be forwarded from the client to the authenticator when using an other authentication method than `WAMP-cryptosign`.

I have discussed this issue with @oberstet on the Autobahn Google Group in this [Post](https://groups.google.com/forum/#!topic/autobahnws/6f9nehxn_6c).

Fixing the bug is very straightforward and requires adding the following code line to every `PendingAuth`-Subclass in the "dynamic authentication" part of the overridden `def hello(self, realm, details)` (except cryptosign.py, which is already forwarding the `authextra` argument):

    self._session_details[u'authextra'] = details.authextra

The Bug is located in the Authentication Subclasses (PendingAuth Subclasses) [here](https://github.com/crossbario/crossbar/tree/master/crossbar/router/auth). This line can be found in cryptosign.py at line 170 and is missing in every other subclass.

I have cloned the crossbar sources and fixed it myself to see if this is fixing the bug and yes, it is! When this line is added, the references are build up and the `authextra` argument is being forwarded into the dynamic authenticator, allowing clients to transmit additional information when requesting authentication.

**Comment by meejah** [comment]
Hi @KemperVreden 

If you can test this branch against your use-case, that'd be great!

You can install the branch in a new virtualenv by running `pip install https://github.com/meejah/crossbar/archive/issue853-authextra-dynamic-authenticators.zip#egg=crossbar`.

**Comment by KemperVreden** [comment]
Hi @meejah 

I have tested it against my use-case and now it works like expected. The auth-extra will be forwarded just like with my personally fixed version.
