### ISSUE TITLE
WAMP CRA more safe with bcrypt?

### ISSUE THREAD

**Issue by KemperVreden** [crossbario/crossbar#855]
I have been reading a great article about [Storing User Passwords Securely: hashing, salting, and Bcrypt](http://dustwell.com/how-to-handle-passwords-bcrypt.html) in which the author says that using bcrypt as the main password hashing method is safer than for example using sha-based password hashing methods since it is slower, making it harder (or more time consuming) to perform hardware-based database attacking.

The author points out that this is due to the repeating-nature of the bcrypt function. I have taken a look at the WAMP-CRA authentication methods and it seems like this is using a self-implemented variant of PBKDF hashing.

My question is, how safe is this compared to the bcrypt-version? Would switching to bcrypt improve security against attacks?

**Comment by meejah** [comment]
I believe the included PBKDF2 implementation was taken from https://github.com/mitsuhiko/python-pbkdf2 and AFAIK the algorithm isn't changed from the standard one.

Personally, I would choose `scrypt`, but they're all considered "pretty good" as I understand. There's also wamp-cryptosign coming; see https://github.com/wamp-proto/wamp-proto/issues/230
