### ISSUE TITLE
Connections Hang But Never Connect or Log Anything

### ISSUE THREAD

**Issue by rawberg** [crossbario/crossbar#857]
This is a PSA for other folks who run into this issue. Just spent a number of days troubleshooting a Crossbar app that was handed off by another dev team.

Crossbar would startup fine but when clients would try to connect to it they would just hang and never fully initiate the connection. Both the clients (nodejs and browser) and the server would not log any meaningful information despite flipping all the debug flags to True and setting AUTOBAHN_DEBUG to true.

Turns out the version of Crossbar being used 0.11.1 was not locked to a specific version of Twisted and it kept pulling down the latest version (16.3.0). Locking Twisted to anything below that version resolved the issue immediately.

Here is a section of the requirements file:
```
autobahn==0.10.9
crossbar==0.11.1
Twisted==16.2.0
```
Hope that saves others some valuable time.

**Comment by hawkowl** [comment]
Hi @rawberg, this is fixed in the latest version of Autobahn; Twisted changed the way HTTP pipelining worked in 16.3, which caused some issues for Autobahn that have now been fixed.
