### ISSUE TITLE
file:// origin not allowed

### ISSUE THREAD

**Issue by Harper04** [crossbario/crossbar#868]
i get
`2016-09-05T16:40:22+0200 [Router      23933] failing WebSocket opening handshake ('WebSocket connection denied: origin 'file://' not allowed')`

despite having
```
"ws": {
    "type": "websocket",
    "debug": true,
    "options": {
        "auto_ping_interval": 2000,
        "auto_ping_timeout": 5000,
        "auto_ping_size": 4,
        "allowed_origins":["ws://*","http://*","file://*","file://","https://*"]
    }
}
```

I try to use crossbar with ionic on android

**Comment by DZabavchik** [comment]
If you turn on `--loglevel=debug` you will notice that origin header is missing completely when you load from `file://`
See #832

**Comment by Harper04** [comment]
Thanks the newest version from master is working seamlessly.

**Comment by meejah** [comment]
Great thanks for reporting back :)
