### ISSUE TITLE
Worker container access to database postgresql through django block crossbar process and cpu grow up

### ISSUE THREAD

**Issue by codegastudio** [crossbario/crossbar#869]
Hello,

I write a python (3.4) project using django. 
This project is launched from supervisor.
Crossbar is used as "customer" and components are connected to a crossbar instance (as router) on another server. 
Crossbar is also launched by supervisor.
All run in a virtualenv.

Config file has only one worker as "container" and multiple component which are defined in the django project as ApplicationSession.

config.json example :
```
{
  "version": 2,
  "workers": [
    {
      "type": "container",
      "options": {
        "pythonpath": [
          ".."
        ]
      },
      "components": [
        {
          "type": "class",
          "realm": "realm1",
          "classname": "myproject.crossbar.MyAppSession",
          "transport": {
            "type": "websocket",
            "endpoint": {
              "type": "tcp",
              "host": "server.com",
              "port": 8080
            },
            "url": "ws://server.com:8080/ws"
          }
        },
        ...
      ]
    }
  ]
}
```

All ApplicationSessions defined as component push data every seconds. Very simple.
Every ApplicationSession looks like this :

```
class MyAppSession(ApplicationSession):

    @inlineCallbacks
    def onJoin(self, details):
        while True:
            try:
                data = {} # send fake data
                self.publish("myappsession",  data)
                print(data)
                yield sleep(1)
            except:
                continue
```

While ApplicationSessions do not access to the database, all work fine.
I had a third Crossbar instance as client to check incoming data. All is good.

Now i want send data saved in postgresql database.
I just add few line like this :

```
import django
django.setup() # absolutely necessary, else crossbar error : django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet. 
...
from myproject.models import MyObject

class MyAppSession(ApplicationSession):

    @inlineCallbacks
    def onJoin(self, details):
        while True:
            try:
                data = {} # send fake data
                for d in MyObject.objects.all():
                     data.append({"id": d.id,
                                  "name": d.name})
                self.publish("myappsession",  data)
                print(data)
                yield sleep(1)
            except:
                continue
```

Restart Crossbar and  ... BOOOOM

Crossbar cpu grow up until 100%
Any data is send.
Third instance of crossbar receive nothing (logic). 
htop command show me two postgresql process locked (idle and SELECT)

Crossbar "infinite" log :
`WAMP message serialization error: cannot serialize unknown object: <generator object myobjects at 0x7487ae90>`

Any help will be appreciate
Regards

**Comment by meejah** [comment]
I'm not familiar enough with Django to immediately see the problem, but you're better off asking questions like this on the mailing-list or in #autobahn on IRC. My understanding is that django is threaded, though, which could be part of your problem.

**Comment by codegastudio** [comment]
Ok it was just a serialization problem on boolean value :/

**Comment by meejah** [comment]
thanks for reporting back
