### ISSUE TITLE
Pub/Sub problem in python3.5

### ISSUE THREAD

**Issue by antuan1996** [crossbario/crossbar#872]
I try to use pub/sub features and get error in crossbar:
File ".../lib/python3.5/site-packages/crossbar/router/unisocket.py", line 96, in dataReceived
    request_uri_first_component = filter(lambda x: x.strip() != "", request_uri.split('/'))
builtins.TypeError: a bytes-like object is required, not 'str'

I do not have same problem if i run crossbar with python 2.7

**Comment by oberstet** [comment]
What Crossbar.io version? Please post the output of `crossbar version`. Also, could you retry with the master branch?

**Comment by antuan1996** [comment]
__  __  __  __  __  __      __     __
    /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
    \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
                                        
 Crossbar.io        : 0.15.0
   Autobahn         : 0.16.0 (with JSON, MessagePack, CBOR, UBJSON)
   Twisted          : 16.4.0-EPollReactor
   LMDB             : 0.89/lmdb-0.9.18
   Python           : 3.5.2/CPython
 OS                 : Linux-4.4.0-36-generic-x86_64-with-Ubuntu-16.04-xenial
 Machine            : x86_64

**Comment by meejah** [comment]
I can confirm that this is a bug in 0.15.0, but also that it is fixed on master. @antuan1996 you can install crossbar master to confirm for your use-case by doing `pip install https://github.com/crossbario/crossbar/archive/master.zip`
