### ISSUE TITLE
MQTT ping/pong

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#882]
MQTT includes a ping/pong mechanism. I *think* that both clients can ping servers and servers can ping clients.

Servers definitely need to answer `PINGREQ` messages received from client with `PINGRESP` messages. This is straighforward to implement at the MQTT transport level.

*If* MQTT also allows servers to ping clients (needs checking), then this should be done similar to how we do it for WebSocket. In particular:

* it should be configurable in the node configuration in the MQTT transport item
* it should use the intelligent batching/chunking mechanism that was introduced in AutobahnPython (and which is used in CB for mass WS ping/pong)

If MQTT *would not* allow servers to ping clients, then we need something else (like the client being expected to ping us regularily, and if not, assume the client to be dead).

In essence, this is all about keeping a connection alive and fast detection of client connection loss.

**Comment by oberstet** [comment]
> If the Keep Alive value is non-zero and the Server does not receive a Control Packet from the Client within one and a half times the Keep Alive time period, it MUST disconnect the Network Connection to the Client as if the network had failed [MQTT-3.1.2-24].

Does this suggest that there is only client-to-server pings, and that the server must detect a lost client by timing out the reception of a ping (or any other MQTT control message) within the keep alive period?

**Comment by hawkowl** [comment]
Only client-to-server pings, and the client must send a full packet (PINGREQ is just a semantically 'nothing' packet as all the others have side effects) within 1.5x of the keepalive, or the server disconnects.

The current MQTT PR has this implemented, w/ tests (`c.a.mqtt.test.test_tx`), so I think we could safely call this one done.

**Comment by oberstet** [comment]
Is the server side of the CB MQTT bridge already checking what I was wondering here https://github.com/crossbario/crossbar/issues/882#issuecomment-249423183 ?

**Comment by hawkowl** [comment]
@oberstet yep! https://github.com/crossbario/crossbar/pull/879/files#diff-b60d217beaef0d8e736f6238d3e0fb3fR144

**Comment by hawkowl** [comment]
Closing this one, as the timeout is implemented as per the MQTT spec in the current implementation. For detecting fast loss, we just have to ask clients to set a low timeout (like, say, 30 seconds), which will mean we have ~30s max for a dead connection. MQTT has no capacity for servers to detect if clients have timed out, so there's nothing we can really do here.
