### ISSUE TITLE
MQTT: message retention

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#887]
This needs to be added for regular WAMP first. This is similar to [event history](https://github.com/crossbario/crossbarexamples/tree/master/event-history) with limit 1. The difference is: event history is strictly a router config thing, and must be actively retrieved via meta API.

Retain should be requested by publisher via a new option to `PUBLISH` message. This needs to be done in AutobahnPython

When subscriber subscribes, we should have a new subscribe option for "get-retained" (better wording needed). If requested, router should publish the last event on the subscription (we have an object inside the broker already for that) to _that particular client_ (via eligible). The event should have a "retain" flag set (in EVENT.Details)

When publishing, we need a new option for "retain" flag.

**Comment by hawkowl** [comment]
Looking at the spec, we will need:

- `Publish.Options.retain|bool` (to set it as the topic's retained message, default is False)
- `Subscribe.Options.get_retained|bool` (to request the retained message along with the subscription)
- `Event.Details.retained|bool` (to say that it is a retained message, and not a new message)

Would a router advertise this via `Welcome.Roles.broker.message_retention := true`?

**Comment by hawkowl** [comment]
WAMP-proto ticket here: https://github.com/wamp-proto/wamp-proto/issues/261

**Comment by hawkowl** [comment]
@oberstet hmm, the current way it is laid out, if a publisher is publishing but nobody is subscribed, there is no subscription object to add it to. So it'll have to be done similar to event history -- in a store. Of course we don't want to use event history but the router's store seems like the best place to put it, considering. Otherwise, topics that drop subscribers to 0 will also drop any retained messages, which is not what we want...

**Comment by hawkowl** [comment]
Implemented in WAMP-proto and Autobahn|Python now...

**Comment by oberstet** [comment]
Currently, event history is implemented as follows: activating event history on a topic is done via node configuration, and that will lead to adding a "pseudo subscriber" internally inside the broker which is responsible for receiving and storing events in event store.

With message retention, there is nothing to configure in the node configuration. And yes, without a subscriber, there won't be a broker subscription object (and if the last subscriber leaves, that subscription object will be destroyed).

Now, with message retention, we could:

* create a subscription object on the first publish with `retained == True` - *even when there is no subscriber (yet)*
* never destroy the subscription object when a retained message has been set

That would be non-intrusive, and I think it would lead to the desired behavior ..
