### ISSUE TITLE
MQTT: interop testing

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#891]
We should test the MQTT bridge in Crossbar.io against these MQTT client libraries from the [Eclipse Paho project](http://www.eclipse.org/paho/):
1. [Paho MQTT C](http://www.eclipse.org/paho/clients/c/)
2. [Paho MQTT Go](http://www.eclipse.org/paho/clients/golang/)
3. [Paho MQTT Python](http://www.eclipse.org/paho/clients/python/)

> Note: there is also a nice, professional C library for embeeded use : [wolfMQTT](https://github.com/wolfSSL/wolfMQTT/)

**Comment by hawkowl** [comment]
Nyamuk and twisted-mqtt are two easy ones as well that I've been using in development.

**Comment by oberstet** [comment]
For now, we're testing using these clients:

* Paho Python
* MQTT.js

**Comment by meejah** [comment]
FWIW, I have been using the mosquitto command-line client to test as well, which also works.
