### ISSUE TITLE
running systemctl enable crossbar.service breaks service

### ISSUE THREAD

**Issue by sunf1re** [crossbario/crossbar#897]
we have had crossbar running for some time now and I was doing some tinkering to have it restart on a crash if it sees less than 2 child processes running, I ran a systemctl enable on it and did the other commands associated with changing a service. when i restart or start the service it then will accept about 5 connection then it goes to unable to accept any more connections. I am a linux engineer and have no experience with crossbar any help would be much appreciated. NOTE when i just run crossbar as the script it runs fine.

**Comment by sunf1re** [comment]
2016-10-05T13:59:14+0000 [Router       4802] Could not accept new connection (EMFILE)

this is the error that is spit out when it starts to fail.

**Comment by oberstet** [comment]
Please see the docs here http://crossbar.io/docs/Automatic-Startup-and-Restart/#systemd
