### ISSUE TITLE
Wrong statement about PyPy in FAQ

### ISSUE THREAD

**Issue by TiberiumPY** [crossbario/crossbar#907]
As FAQ state here: [http://crossbar.io/docs/FAQ/#what-is-pypy](http://crossbar.io/docs/FAQ/#what-is-pypy?)
"Different from CPython, PyPy is not an interpreter, but compiling Python bytecode to native machine code - transparently and on the fly. It is a JIT compiler.".
But PyPy always starts by interpreting, at some point when threshold is hit it starts meta-interpreting = tracing once tracing is done it executes machine code, but it's almost always doing interpreting anyway.

**Comment by oberstet** [comment]
Yeah, this isn't an introduction to PyPy.
