### ISSUE TITLE
404 on all blog posts

### ISSUE THREAD

**Issue by shirk3y** [crossbario/crossbar#913]
It seems that links on http://crossbario.com/blog are broken along images in documentation #905 and #876

For example: 
http://crossbario.com/blog/security-in-the-iot/

**Comment by meejah** [comment]
cc @goeddea

**Comment by braingineer** [comment]
found that it should be 

http://crossbario.com/blog/post/security-in-the-iot/

**Comment by oberstet** [comment]
fixed
