### ISSUE TITLE
Cannot install IOCP Twisted Reactor

### ISSUE THREAD

**Issue by Tsunami2069** [crossbario/crossbar#929]
Hello...

Small issue (nothing much, crossbar still runs) that has been happening since a recent update to my crossbar on Windows.

Whenever I start my crossbar I get the following error:

![crossb](https://cloud.githubusercontent.com/assets/14236716/20531817/d25802d8-b0cf-11e6-8aea-e2c79a712071.JPG)
~

Thank you for the help

**Comment by hawkowl** [comment]
Hi @Tsunami2069, a fix is in master, and will be in the next release. Sorry about that!

**Comment by Tsunami2069** [comment]
@hawkowl Awesome... Thank you.

**Comment by meejah** [comment]
Is this the same bug as #939?

**Comment by oberstet** [comment]
@meejah yep, likely the same (kqueue is for osx and the bsds)
