### ISSUE TITLE
MQTT: dynamic auth

### ISSUE THREAD

**Issue by meejah** [crossbario/crossbar#935]
In discussion on #autobahn it would be useful to be able to do dynamic-authentication on incoming MQTT requests (e.g. instead of using the realm + role that is statically-assigned in the config).

**Comment by oberstet** [comment]
The signature of the WAMP procedure a user can configure as a dynamic authenticator for one of the bridges as well as the WAMP router inside could depend on the bridge type of course. Eg for MQTT, as far as I understand, there is TLS client certs and cleartext user/password as auth methods? Not sure though.

**Comment by hawkowl** [comment]
Duplicate of https://github.com/crossbario/crossbar/issues/883
