### ISSUE TITLE
Twisted reactor errors on OSX in v16.10.x

### ISSUE THREAD

**Issue by rbcollins123** [crossbario/crossbar#939]
So running Crosssbar v0.15.0, all is well.  A clean virtualenv of 2.7.12 and then `pip install -I crossbar==0.15.0` yields the following output from `crossbar version` :  
```
crossbar version
     __  __  __  __  __  __      __     __
    /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
    \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/

 Crossbar.io        : 0.15.0
   Autobahn         : 0.17.0 (with JSON, MessagePack, CBOR, UBJSON)
   Twisted          : 16.6.0-KQueueReactor
   LMDB             : 0.92/lmdb-0.9.18
   Python           : 2.7.12/CPython
 OS                 : Darwin-16.1.0-x86_64-i386-64bit
 Machine            : x86_64
```

Then a quick `pip install -U crossbar` to jump up to v16.10.1 yields the following error:

```
crossbar version
Running on *BSD or MacOSX, but cannot install kqueue Twisted reactor
Running on *BSD or MacOSX, but cannot install kqueue Twisted reactor
Traceback (most recent call last):
  File "/Users/rcollins/.pyenv/versions/2.7.12/envs/crossbar-venv/lib/python2.7/site-packages/autobahn/twisted/choosereactor.py", line 68, in install_optimal_reactor
    kqreactor.install()
  File "/Users/rcollins/.pyenv/versions/2.7.12/envs/crossbar-venv/lib/python2.7/site-packages/twisted/internet/kqreactor.py", line 317, in install
    installReactor(p)
  File "/Users/rcollins/.pyenv/versions/2.7.12/envs/crossbar-venv/lib/python2.7/site-packages/twisted/internet/main.py", line 32, in installReactor
    raise error.ReactorAlreadyInstalledError("reactor already installed")
ReactorAlreadyInstalledError: reactor already installed

     __  __  __  __  __  __      __     __
    /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
    \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/

 Crossbar.io        : 16.10.1
   Autobahn         : 0.17.0 (with JSON, MessagePack, CBOR, UBJSON)
   Twisted          : 16.6.0-SelectReactor
   LMDB             : 0.92/lmdb-0.9.18
   Python           : 2.7.12/CPython
 OS                 : Darwin-16.1.0-x86_64-i386-64bit
 Machine            : x86_64
 Release key        : RWQ2MDk26PKBMNUZG2Jok1tMBB1SKyci+N7dtcep8jrikTl4NvI1Rnux
```

The same results occur with v16.10.0 of crossbar.  Any insight re: what has changed and why it's now using select vs kqueue on OSX?

**Comment by meejah** [comment]
I think #920 (addressed in https://github.com/crossbario/crossbar/pull/922) is the same as this bug; can you re-test with master? (You can do that by "pip install https://github.com/crossbario/crossbar/archive/master.zip")

**Comment by rbcollins123** [comment]
yep, running it from master works like a champ!

**Comment by meejah** [comment]
Great, thanks!
I'm closing this, then, and this fix will be in the next release.

**Comment by petri** [comment]
Nice that this has been fixed; I just ran into it, too. Hoping for a release soon...

**Comment by dfee** [comment]
This is a couple months old now… when is the release expected?

**Comment by Veronicacz** [comment]
Hi, @meejah I tried to use "pip install https://github.com/crossbario/crossbar/archive/master.zip".
And the output is still as follows:

`Running on *BSD or MacOSX, but cannot install kqueue Twisted reactor
Running on *BSD or MacOSX, but cannot install kqueue Twisted reactor
Traceback (most recent call last):
  File "/Users/Veronica/python-venv/lib/python2.7/site-packages/autobahn/twisted/choosereactor.py", line 68, in install_optimal_reactor
    kqreactor.install()
  File "/Users/Veronica/python-venv/lib/python2.7/site-packages/twisted/internet/kqreactor.py", line 317, in install
    installReactor(p)
  File "/Users/Veronica/python-venv/lib/python2.7/site-packages/twisted/internet/main.py", line 32, in installReactor
    raise error.ReactorAlreadyInstalledError("reactor already installed")
ReactorAlreadyInstalledError: reactor already installed

     __  __  __  __  __  __      __     __
    /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
    \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
                                        
 Crossbar.io        : 17.12.1 (Crossbar.io COMMUNITY)
   Autobahn         : 17.10.1 (with JSON, MessagePack, CBOR, UBJSON)
   Twisted          : 17.9.0-SelectReactor
   LMDB             : 0.93/lmdb-0.9.18
   Python           : 2.7.13/CPython
 OS                 : Darwin-16.7.0-x86_64-i386-64bit
 Machine            : x86_64
 Release key        : RWQ0XcNYBo35t9PnNO/8H9oV+bD6Ss3ti49fr6PoqhVfZSHPUvuvIyWT
`
May I know is there any other solution to solve it? Thanks!
