### ISSUE TITLE
Are some callbacks taking too long?

### ISSUE THREAD

**Issue by meejah** [crossbario/crossbar#942]
In https://github.com/crossbario/txaio/issues/81 it was reported that we sometimes try to do batched call_laters with a negative time. This indicates that something *may* be falling behind (or not yielding to the reactor within about 200ms).

@agronholm reports that the above-mentioned bug was happening on a crossbar with no components running "in process" (alongside crossbar) and with not very many connections.

We should try e.g. `twisted-theseus` or similar tool and see if we can find any callbacks taking "too long". Perhaps also the 200ms bucket-window for websocket timeouts is too short?

**Comment by meejah** [comment]
So the txaio thing turned out to be just a straight-up bug which was only revealed when using really-short ping/pong timeout (30ms) due to confusion over the configuration argument being in milliseconds not seconds. 

Most people will thus avoid this if we add a simple sanity-check on the timeout args (i.e. if they're < 1.0seconds they probably meant seconds when they typed in the value). That said, the other stuff above sounds good too :)

**Comment by blinkingmatt** [comment]
We also have problems with "lost transport" by ping/pong failure when processor is running under full load (image processing tasks running in C-extension modules).
I circumvented the problem by facilitating concurrent.futures.ThreadPoolExecutor() for the long-running synchronous functions. But this is not possible for coroutines. So any relief regarding ping/pong evaluation would by highly appreciated.
Our system (Python only):
- Windows 10
- Python 3.6.0
- Crossbar 17.9.2
- autobahn|Python 17.9.3

**Comment by oberstet** [comment]
unclear how to reproduce / if it is still an issue at this point (I seem to remember we did improve some bits that might be related) ...
