### ISSUE TITLE
Receiving reactor errors when running init of hello app on crossbario 16.10.1

### ISSUE THREAD

**Issue by patjnolan** [crossbario/crossbar#946]
Installed crossbar per instructions on http://crossbar.io/docs/Installation-on-Mac-OS-X/#installing-crossbar.io. I'm running macOS 10.12.2 (16C67) Sierra. Thank you!

`(pypy-venv) BUENOSAIRES:crossbar pat$ crossbar init --template hello:nodejs
Running on *BSD or MacOSX, but cannot install kqueue Twisted reactor
Running on *BSD or MacOSX, but cannot install kqueue Twisted reactor
Traceback (most recent call last):
  File "/Users/pat/pypy-venv/site-packages/autobahn/twisted/choosereactor.py", line 68, in install_optimal_reactor
    kqreactor.install()
  File "/Users/pat/pypy-venv/site-packages/twisted/internet/kqreactor.py", line 317, in install
    installReactor(p)
  File "/Users/pat/pypy-venv/site-packages/twisted/internet/main.py", line 32, in installReactor
    raise error.ReactorAlreadyInstalledError("reactor already installed")
ReactorAlreadyInstalledError: reactor already installed

Initializing application template 'hello:nodejs' in directory '/Users/pat/projects/crossbar'
Using template from '/Users/pat/pypy-venv/site-packages/crossbar/templates/hello/nodejs'
Creating directory /Users/pat/projects/crossbar/.crossbar
Creating directory /Users/pat/projects/crossbar/node
Creating directory /Users/pat/projects/crossbar/web
Creating file /Users/pat/projects/crossbar/package.json
Creating file /Users/pat/projects/crossbar/README.md
Creating file /Users/pat/projects/crossbar/.crossbar/config.json
Creating file /Users/pat/projects/crossbar/node/hello.js
Creating file /Users/pat/projects/crossbar/web/index.html
Application template initialized

Now install dependencies by doing 'npm install', start Crossbar using 'crossbar start' and open http://localhost:8080 in your browser.

(pypy-venv) BUENOSAIRES:crossbar pat$ 
`

**Comment by oberstet** [comment]
Should be fixed in https://github.com/crossbario/crossbar/pull/922
