### ISSUE TITLE
MQTT: Bad name in Connect

### ISSUE THREAD

**Issue by asimashfaq** [crossbario/crossbar#948]
Hi guys!

I am facing this problem 
**"Bad name in Connect"**
When ever i try to connect the mqtt port 
http://prnt.sc/dsix7p

I follow the exact same guide lines but dont know why this issue coming.

**Comment by markos** [comment]
I faced exactly the same issue today, both with mosquitto as client and paho-mqtt.
It appears that MQIsdp is a synonym for MQTT and stands for "MQ Integrator SCADA Device Protocol" (http://mqtt.org/faq). Risky assumption: somehow a compability-mode is triggered by crossbar and those tools reply in a legacy mode MQIsdp instead of proper MQTT?

**Comment by markos** [comment]
So, mosquitto defaults to mqttv31, however, if I force MQTT protocol version 3.1.1 then I don't get the same error anymore:

```
$ mosquitto_pub -d -h localhost -p 1883 -t mqtt.test_topic -m test -V mqttv311
Client mosqpub/20700-gaiusbalt sending CONNECT
Client mosqpub/20700-gaiusbalt received CONNACK
Connection Refused: unacceptable protocol version.
Error: The connection was refused
```

Maybe there is an extra protocol version check needed in Crossbar?

**Comment by oberstet** [comment]
Clients that are sending something different than `"MQTT"` in the `CONNECT` message a breaking the spec:

> If the protocol name is incorrect the Server MAY disconnect the Client, or it MAY continue processing the CONNECT packet in accordance with some other specification. In the latter case, the Server MUST NOT continue to process the CONNECT packet in line with this specification

http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc385349225

We correctly check for that [here](https://github.com/crossbario/crossbar/blob/master/crossbar/adapter/mqtt/_events.py#L689).

Regarding protocol version, the spec [says](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc385349227):

> The 8 bit unsigned value that represents the revision level of the protocol used by the Client. The value of the Protocol Level field for the version 3.1.1 of the protocol is 4 (0x04). The Server MUST respond to the CONNECT Packet with a CONNACK return code 0x01 (unacceptable protocol level) and then disconnect the Client if the Protocol Level is not supported by the Server 

It appears we are also processing this according to the letter of the spec, see [here](https://github.com/crossbario/crossbar/blob/master/crossbar/adapter/mqtt/_events.py#L694).

---

@markos Rgd the question what triggers the "unacceptable protocol version"

According to the spec, this is return value `0x01 Connection Refused, unacceptable protocol version` in the `CONNACK`.

It would be interesting to verify this by adding a log line printing the values returned from here https://github.com/crossbario/crossbar/blob/master/crossbar/adapter/mqtt/tx.py#L246

**Comment by markos** [comment]
I think the response is correct, MQTT identifier is sent for v3.1.1 which you explicitly support, MQIsdp is for pre-3.1.1 so I don't think it's worth the effort -but that's not my call obviously. I would just state it explicitly somewhere, to avoid confusion. Regarding the protocol version, I just added some extra info and it seems that the client does indeed send protocol_version = 4, so this is ok from the sender side. So the reply must be wrong someway.

**Comment by markos** [comment]
Ok, so after some investigation, I found that the event object
```
2017-03-03T14:23:46+0100 [Router      26372] Connect(client_id='mosqpub/26376-gaiusbalt', flags=ConnectFlags(username=False, password=False, will=False, will_retain=False, will_qos=0, clean_session=True, reserved=False), keep_alive=60, will_topic=None, will_message=None, username=None, password=None)
```

So a 0x01 was sent because a message.Abort is instantiated in crossbar/adapter/mqtt/wamp.py:189
which in turn came from a types.Deny in ./crossbar/router/session.py:428
Adding some extra debug print led to the following information:
```
2017-03-03T14:56:59+0100 [Router      26695] Denied: wamp.error.no_such_realm: no realm requested
```

So, in effect it was a realm issue?

**Comment by markos** [comment]
With @meejah's pull request https://github.com/crossbario/crossbar/pull/981, I can confirm that I had a successfull MQTT communication over crossbar :+1:
