### ISSUE TITLE
C# for Unity

### ISSUE THREAD

**Issue by ziiCz** [crossbario/crossbar#959]
Hi guys,

I have create a basic c# project and I can comunicate with a crossbar.io PHP server. Everything works good.

But I'm now trying to implement Crossbar.io with WampSharp to Unity but I cannot import / use WampSharp.

Can you help me ?

Thanks,
Best Regards

**Comment by darkl** [comment]
There are currently no plans (and probably won't be any plans) to port WampSharp to .NET 2.0/3.5 for Unity support. Unity is expected to support .NET 4.0+ (.NET 4.6/.NET Standard 1.3) in the near future, and then it will have WampSharp support automatically.

Best regards,
Elad
