### ISSUE TITLE
crossbar.io docs webpages are missing for HTTP-Bridge-Services and Logging-in-Crossbar.io

### ISSUE THREAD

**Issue by FirefighterBlu3** [crossbario/crossbar#962]
for the url: https://crossbar.io/docs/HTTP-Bridge-Services/
```
404 Not Found

Code: NoSuchKey
Message: The specified key does not exist.
Key: docs/HTTP-Bridge-Services/index.html
RequestId: E1CB6EA08C660084
HostId: UZnkOWiUl+Rp5WoaXrsHFr346tyiHKH/JHrqVqApcw9XAY8IjG5ReK6B4RLu/rC8kCgGyOCCc4U=
```

and for the url: https://crossbar.io/docs/Logging-in-Crossbar.io/
```
404 Not Found

Code: NoSuchKey
Message: The specified key does not exist.
Key: docs/Logging-in-Crossbar.io/index.html
RequestId: 447F26BA2DC08C2D
HostId: wL5FZDTKGmzDqgT+Ydcceh2xU5N0xJwfOubZEjbBWTAxnOYMl2FY6fVyfp72a5IB55fr8gNW65I=
```

**Comment by oberstet** [comment]
The correct URLs are

* http://crossbar.io/docs/HTTP-Bridge/
* http://crossbar.io/docs/Logging/

Where did you find the broken links?

**Comment by FirefighterBlu3** [comment]
I'm going to have to find it again, I found them when I was trying to set up a REST bridge using the crossbar.io website which appears to be offline right now. The existing documentation on your website references these other pages. If you have local access to the filesystem, `grep -r foo` will probably be faster

**Comment by goeddea** [comment]
Can't find either link in any of our page sources, or indeed repositories.

Web site was deployed today from current source, so closing this for now. (But highly interested if you manage to find these links again - maybe something on S3 doesn't get deleted properly, and there are still pages which you can access via their original link which have this content?)

**Comment by FirefighterBlu3** [comment]
thank you. i've gone through my browser history and all the pages i believed to have used the older URLs now point to valid pages
