### ISSUE TITLE
feature: add new meta subscription "wamp.session.before_subscription"

### ISSUE THREAD

**Issue by alexey2baranov** [crossbario/crossbar#963]
Hello! 
We would like to match user subscriptions with user permissions. So it would be great if Server can subscribe on `wamp.session.before_subscription` check `session.authid` inside callback and reject user subscription if user has no access rights

**Comment by oberstet** [comment]
Please see https://github.com/crossbario/crossbar-examples/tree/master/authorization/dynamic for examples how to do that.
