### ISSUE TITLE
Warn if auto_ping_interval (way) less than 1s

### ISSUE THREAD

**Issue by meejah** [crossbario/crossbar#968]
If you don't notice that `auto_ping_interval` (and friends) are in milliseconds (and not seconds) it would be nice to at least warn if you enter values like "30" or "60" (or anything much less than 1s) since you're probably expecting seconds.

**Comment by oberstet** [comment]
We could also allow for strings "30s" vs "1400ms". But I guest we have to leave the value interpetation at ms. Or propagate a new `auto_ping_interval_secs` and leave the existing `auto_ping_interval` with a warning in the log, and the existing ms interpretation.

**Comment by meejah** [comment]
fixed by #1059
