### ISSUE TITLE
Drop support for Python <3.6

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#970]
If and when PyPy supports 3.5, the question will arise whether we should support Python <3.5 longer (for Crossbar.io), because dropping that would allow us to use the nice, clean await/async style writing Crossbar.io code most of the time.

**Comment by vetsin** [comment]
This would disappoint me greatly.

**Comment by FirefighterBlu3** [comment]
@vetsin mind elaborating a tad? what's in 3.0-3.4 that you need?

**Comment by vetsin** [comment]
I've made the assumption here that <3.5 means no 2.7 support. I would like to continue using 2.7 for many reasons.

**Comment by oberstet** [comment]
Could you elaborate why the specific Py version Crossbar.io runs under matters to you at all? Why does it matter it is written in Py?Both should be details of no concern/effects for app devs and users.Trying to understand motivations and context here ...Am 10.03.2017 2:22 vorm. schrieb Matthew <notifications@github.com>:I've made the assumption here that <3.5 means no 2.7 support. I would like to continue using 2.7 for many reasons.

**Comment by meejah** [comment]
@vetsin to be clear, @oberstet  *just* means crossbar the router itself, not e.g. autobahn-python nor WAMP which would presumably continue to support Python2.7 for some time.

**Comment by oberstet** [comment]
Absolutely. Autobahn will continue to support 2.7. This is an important feature.

Crossbar on the other hand is not a library, but an app. And the impl. lang. or impl. lang. version should not matter ..

However, I am aware, this is a strict view that might find limits in real world practical needs I am unaware ..

**Comment by oberstet** [comment]
For me, Python 3 with 3.6 has reached a mature level for the following, which I can see a lot of advantages in:

* standards based syntax for type annotations which allows static type checking
* standards based syntax (and implementation) for the whole spectrum of async (up to async iterators and context managers).

Both of these are attractive.

As mentioned, Autobahn will continue to support 2.7+ and 3.3+. So this is only about Crossbar.io itself.

**Comment by agronholm** [comment]
If you drop support for Python 3.5 too, you won't be able to use PyPy3 for a while.

**Comment by glenfant** [comment]
Are there some consequences for user code (components, Crossbar / WSGI apps) developed for Python 2.7 or 3.4 ?

**Comment by oberstet** [comment]
@glenfant yes, there would be consequences for anything not run as a guest worker - which means, a WSGI app would need to be Py 3 too (as everything but guest workers is run under the same Python as Crossbar.io itself).

This is one reason it's unlikely we will do such a move - of course it would be nice if we could use the new syntax when writing Crossbar.io code itself, but "nice" isn't enough, as it would affect users.

For context: I filed the issue here (and keep it open) mainly to draw criticisms I expect to come up ("why don't you write CB in Py 3 syntax?") to one place ..

**Comment by agronholm** [comment]
Correct me if I'm wrong, but I heard that the notion of running applications in the same process as Crossbar itself is slowly being phased out. I for one would be uncomfortable developing anything in the same environment with Crossbar's pinned dependencies. If this happens then the option to go py3 only should open up again.

**Comment by oberstet** [comment]
@agronholm You are exactly right in all what you say! I was concentrating on one aspect here / simplifying a little.

But as you are quite deep into all this, here are more details / aspects:

With AB Py WAMP components, there is technically no need to run it embedded in router worker, or even using a container worker - this is true already today: one can use a guest worker, and that can run whatever Python version / deps is needed. And I'd consider that "recommended" / best practice (for production).

Also, running a AB Py WAMP component in a guest worker does have the same latencies compared to running embedded in container worker. Running embedded in a router worker will have lower latency (no process switching / IPC), but in the grand picture, this almost never matters.

> That being said: we need to implement caching for dynamic authenticators (because there, small latencies matter).

---

However, when using CB to host WSGI apps, there is another challenge: these WSGI apps currently run as part of a Web transport in router workers. The reason is partially historic: coming up with a "Web transport" in CB nicely fitted into the bigger picture. And originally I never wanted to add the ability to run **user code** as part of the **transport** (the Web transport == Twisted Web essentially).

Now users apparently like the ease and flexibility of configuring Web resource trees in CB. Which is good. As long as there where no Web resources that allowed custom code (resources of type "static" or "redirect" etc). But then people started to ask about WSGI, and full blown custom Twisted Web resources to put into CB's Web resource trees.

Here is what happened then: I tried to fight that back with various arguments. The above argument ("user code coupled into CB") is hard to graps / only understandable for people that really dived deep into all the WAMP philosophy. And people were like: "why are you fighting this? it is trivial for you to add to CB!!".

At some point I gave up and just added the couple of lines to allow it;)

So this is all a fine line: keeping the design / "philosophy" coherent, at the same time making people happy / give them what they want. And doing all that on a technically non-trivial fundament.

I hope this sheds more light into this rather than triggering doubt, me disclosing these weird thoughts, fine lines etc

But I am convinced transparency is almost always a good thing.

**Comment by OOPMan** [comment]
I think it would be pretty awesome to see the Router code transition to Python 3.6 as it would allow the usage of uvloop, among other things.

The async/await syntax is also much cleaner than the Twisted approach.

**Comment by meejah** [comment]
@OOPMan I think the idea would be to continue using Twisted, but use ``async def`` and ``await`` (which can be used with Twisted in Python3)

**Comment by OOPMan** [comment]
@meejah Ahhhh. Still, I wonder if there is someway to leverage uvloop with Twisted?

**Comment by oberstet** [comment]
for now, we'll

- continue to support Python 3.5+ (as this is what the current PyPy implements)
- gradually (when appropriate) move to `async/await`
- there are no plans whatsoever to move away from Twisted
- there is also no plan (and reason) to move to uvloop or what

**Comment by meejah** [comment]
AFAIK, yes you can use uvloop with Twisted (possible only via `asyncioreactor`). But, I'd want proof this is faster (for crossbar in particular) than PyPy + epoll or so...(maybe it is, but: benchmarks or it didn't happen ;) )

**Comment by oberstet** [comment]
yeah, if the selling point of uvloop vs twisted/bare-epoll would be performance, I don't believe that without proof. the actual bottleneck is syscalls/context switches .. uvloop calls epoll under the hood. this is not a zero-copy kernel bypass thingy
