### ISSUE TITLE
Crossbar fails to start on MacOS running Python 2.7

### ISSUE THREAD

**Issue by kstewart83** [crossbario/crossbar#972]
There is currently a bug where Crossbar dies due to a python TypeError:

`TypeError: list indices must be integers, not str`

This happens because when reading plist data, it is indexed using a string, when the method actually returns an array (which contains the dictionary as its first value).

In `crossbar/controller/node.py` currently at line 177...the current code:

```python
        if six.PY2:
            # Only API on 2.7
            return plistlib.readPlistFromString(plist_data)["IOPlatformSerialNumber"]
```

needs to be replaced with:

```python
        if six.PY2:
            # Only API on 2.7
            return plistlib.readPlistFromString(plist_data)[0]["IOPlatformSerialNumber"]
```

Should be a quick kill. I went to fix it and submit a PR, but going through the contrib agreement seemed like too much overhead for this.

**Comment by oberstet** [comment]
fixed in https://github.com/crossbario/crossbar/pull/991
