### ISSUE TITLE
RFI - Make a config-dir and move config.json to it. Allow to load extra configfiles

### ISSUE THREAD

**Issue by Trouffman** [crossbario/crossbar#973]
Suggestion for improvement : 

When spanning multiple router,realm and all on the same config it would be nice to be able to have them managed independently.

One way of doing it is to get config.json for the main configuration settings, and have a directory that will auto-load all of the .conf in there.

NB : That would also easy running crossbar into container without having to mount the complete node directory.

NB2 : i might be wrong all along ;)

**Comment by oberstet** [comment]
No, Crossbar.io has a builtin management API that allows to adress this, but also many more use cases.
