### ISSUE TITLE
Does eligible_authid work?

### ISSUE THREAD

**Issue by koxu1996** [crossbario/crossbar#998]
I tried following codes:
- AutobahnJS:
`session.publish("com.example.test", null, null, {eligible_authid: "john"});`
`session.publish("com.example.test", null, null, {eligible_authid: ["john","peter"]});`
- Thruway:
`$session->publish('com.example.test', null, null, ["eligible_authid" => "john"]);`
`$session->publish('com.example.test', null, null, ["eligible_authid" => ["john","peter"]);`

But I am getting errors like this:
```
2017-03-22T22:22:27+0100 [Router       1599] Traceback (most recent call last):
  File "/opt/crossbar/site-packages/autobahn/wamp/websocket.py", line 88, in onMessage
    for msg in self._serializer.unserialize(payload, isBinary):
  File "/opt/crossbar/site-packages/autobahn/wamp/serializer.py", line 131, in unserialize
    msg = Klass.parse(raw_msg)
  File "/opt/crossbar/site-packages/autobahn/wamp/message.py", line 1319, in parse
    raise ProtocolError("invalid type {0} for value in 'exclude' option in PUBLISH".format(type(_sessionid)))
ProtocolError: invalid type <type 'unicode'> for value in 'exclude' option in PUBLISH
```

**Comment by oberstet** [comment]
The feature is on master branches and not yet released

**Comment by koxu1996** [comment]
@oberstet For now I am using dynamic authorizer, but after release should I switch to black/whitelisting? It seems better because it work along with role permissions, but I wonder there are any drawbacks?

**Comment by oberstet** [comment]
If the behavior you desire is covered by BW listing on authid/authrole, I'd recommend moving to that. Simply, because it's now built in and hence will be further supported out of the box, runs inside the routing core, and you don't have to fiddle/maintain own code.
