### ISSUE TITLE
Crossbar TLS works into Chrome but not into Firefox and Chrome on Android

### ISSUE THREAD

**Issue by alexey2baranov** [crossbario/crossbar#999]
Hello! 

A few day ago we setted up ssl sertificates with letsencrypt service (cert.pem, chain.pem, fullchain.pem, privkey.pem). After that we configured crossbar.json. As a result Google Chrome say that connection is secure but Firefox and Chrome on Android say connection is not secure. Can you say what else should we do?

you can see what i am talking about if you visit our site https://kopnik.org . 

With regards!

> ubuntu@kopnik:~/htdocs/kp-client$ sudo /opt/crossbar/bin/crossbar start
> 2017-03-23T05:23:48+0000 [Controller  52726]      __  __  __  __  __  __      __     __
> 2017-03-23T05:23:48+0000 [Controller  52726]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
> 2017-03-23T05:23:48+0000 [Controller  52726]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
> 2017-03-23T05:23:48+0000 [Controller  52726]                                         
> 2017-03-23T05:23:48+0000 [Controller  52726]     Crossbar.io Version: 0.13.2
> 2017-03-23T05:23:48+0000 [Controller  52726]     Node Public Key: 6bdac064e46a1b3f4058f0aa2c8bfdaba8e26bc9eda406868555285f9240d9e5
> 2017-03-23T05:23:48+0000 [Controller  52726] 
> 2017-03-23T05:23:48+0000 [Controller  52726] Running from node directory '/home/ubuntu/htdocs/kp-client/.crossbar'
> 2017-03-23T05:23:48+0000 [Controller  52726] Controller process starting (PyPy-EPollReactor) ..
> 2017-03-23T05:23:48+0000 [Controller  52726] Node configuration loaded from 'config.json'
> 2017-03-23T05:23:48+0000 [Controller  52726] Node ID 'kopnik' set from hostname
> 2017-03-23T05:23:48+0000 [Controller  52726] Using default node shutdown triggers [u'shutdown_on_worker_exit']
> 2017-03-23T05:23:48+0000 [Controller  52726] Joined realm 'crossbar' on node management router
> 2017-03-23T05:23:48+0000 [Controller  52726] Starting Router with ID 'worker-001'...
> 2017-03-23T05:23:49+0000 [Router      52731] Worker process starting (PyPy-EPollReactor) ..
> 2017-03-23T05:23:51+0000 [Controller  52726] Router with ID 'worker-001' and PID 52731 started
> 2017-03-23T05:23:51+0000 [Router      52731] Realm 'kopa' started
> 2017-03-23T05:23:51+0000 [Controller  52726] Router 'worker-001': realm 'realm-001' (named 'kopa') started
> 2017-03-23T05:23:51+0000 [Controller  52726] Router 'worker-001': role 'role-001' (named 'server') started on realm 'realm-001'
> 2017-03-23T05:23:51+0000 [Controller  52726] Router 'worker-001': role 'role-002' (named 'kopnik') started on realm 'realm-001'
> 2017-03-23T05:23:51+0000 [Controller  52726] Router 'worker-001': role 'role-003' (named 'anonymous') started on realm 'realm-001'
> 2017-03-23T05:23:51+0000 [Controller  52726] Router 'worker-001': role 'role-004' (named 'authenticator') started on realm 'realm-001'
> 2017-03-23T05:23:51+0000 [Router      52731] started component: authenticator.AuthenticatorSession id=270946683292747
> 2017-03-23T05:23:51+0000 [Router      52731] WAMP-Ticket dynamic authenticator registered!
> 2017-03-23T05:23:51+0000 [Controller  52726] Router 'worker-001': component 'component-001' started
> 2017-03-23T05:23:51+0000 [Router      52731] Loaded 4 cookie records from file. Cookie store has 3 entries.
> 2017-03-23T05:23:51+0000 [Router      52731] File-backed cookie store active /home/ubuntu/htdocs/kp-client/.crossbar/cookies.dat
> 2017-03-23T05:23:51+0000 [Router      52731] Loading server TLS key from /etc/letsencrypt/live/kopnik.org/privkey.pem
> 2017-03-23T05:23:51+0000 [Router      52731] Loading server TLS certificate from /etc/letsencrypt/live/kopnik.org/fullchain.pem
> 2017-03-23T05:23:51+0000 [Router      52731] Using secure default TLS ciphers
> 2017-03-23T05:23:51+0000 [Router      52731] No OpenSSL DH parameter file set - DH cipher modes will be deactive!
> 2017-03-23T05:23:51+0000 [Router      52731] OpenSSL is using elliptic curve prime256v1 (NIST P-256)
> 2017-03-23T05:23:51+0000 [Router      52731] Site (TLS) starting on 443
> 2017-03-23T05:23:51+0000 [Controller  52726] Router 'worker-001': transport 'transport-001' started
> 2017-03-23T05:23:51+0000 [Router      52731] Loaded 4 cookie records from file. Cookie store has 3 entries.
> 2017-03-23T05:23:51+0000 [Router      52731] File-backed cookie store active /home/ubuntu/htdocs/kp-client/.crossbar/cookies.dat
> 2017-03-23T05:23:51+0000 [Router      52731] Site starting on 80
> 2017-03-23T05:23:51+0000 [Controller  52726] Router 'worker-001': transport 'transport-002' started
> 

**config.json**
```json
{
  "version": 2,
  "workers": [
    {
      "type": "router",
      "options": {
        "pythonpath": [
          ".",
          "/usr/lib/python3/dist-packages"
        ]
      },
      "realms": [
        {
          "name": "kopa",
          "roles": [
            {
              "name": "server",
              "permissions": [
                {
                  "uri": "ru",
                  "match": "prefix",
                  "allow": {
                    "call": true,
                    "register": true,
                    "publish": true,
                    "subscribe": true
                  },
                  "disclose": {
                    "caller": true,
                    "publisher": true
                  },
                  "cache": true
                },
                {
                  "uri": "wamp",
                  "match": "prefix",
                  "allow": {
                    "call": true,
                    "register": false,
                    "publish": false,
                    "subscribe": true
                  },
                  "disclose": {
                    "caller": true,
                    "publisher": true
                  },
                  "cache": true
                }
              ]
            },
            {
              "name": "kopnik",
              "permissions": [
                {
                  "uri": "ru",
                  "match": "prefix",
                  "allow": {
                    "call": true,
                    "register": true,
                    "publish": true,
                    "subscribe": true
                  },
                  "disclose": {
                    "caller": true,
                    "publisher": true
                  },
                  "cache": false
                }
              ]
            },
            {
              "name": "anonymous",
              "permissions": [
                {
                  "uri": "ru.kopa.registration",
                  "match": "prefix",
                  "allow": {
                    "call": true,
                    "register": false,
                    "publish": false,
                    "subscribe": false
                  }
                },
                {
                  "uri": "ru.kopa.model.create",
                  "match": "prefix",
                  "allow": {
                    "call": true,
                    "register": false,
                    "publish": false,
                    "subscribe": false
                  }
                }
              ]
            },
            {
              "name": "authenticator",
              "permissions": [
                {
                  "uri": "org.kopnik.authenticate",
                  "match": "prefix",
                  "allow": {
                    "call": false,
                    "register": true,
                    "publish": false,
                    "subscribe": false
                  },
                  "disclose": {
                    "caller": false,
                    "publisher": false
                  },
                  "cache": false
                }
              ]
            }
          ]
        }
      ],
      "transports": [
        {
          "type": "web",
          "endpoint": {
            "type": "tcp",
            "port": 443,
            "tls": {
              "certificate": "/etc/letsencrypt/live/kopnik.org/fullchain.pem",
              "key": "/etc/letsencrypt/live/kopnik.org/privkey.pem"
            }
          },
          "paths": {
            "/": {
              "type": "static",
              "directory": "../dist"
            },
            "ws": {
              "type": "websocket",
              "options":{
                "enable_webstatus": true,
                "max_frame_size": 1048576,
                "max_message_size": 1048576,
                "auto_fragment_size": 65536,
                "fail_by_drop": true,
                "open_handshake_timeout": 2500,
                "close_handshake_timeout": 1000,
                "auto_ping_interval": 10000,
                "auto_ping_timeout": 5000,
                "auto_ping_size": 4
              },
              "serializers": [
                "json"
              ],
              "cookie": {
                "store": {
                  "type": "file",
                  "filename": "cookies.dat"
                }
              },
              "auth": {
                "ticket": {
                  "type": "dynamic",
                  "authenticator": "org.kopnik.authenticate"
                },
                "anonymous": {
                  "type": "static",
                  "role": "anonymous"
                },
                "cookie": {
                }
              }
            }
          }
        },
        {
          "type": "web",
          "endpoint": {
            "type": "tcp",
            "port": 80
          },
          "paths": {
            "/": {
              "type": "static",
              "directory": "../dist"
            },
            "ws": {
              "type": "websocket",
              "options":{
                "enable_webstatus": true,
                "max_frame_size": 1048576,
                "max_message_size": 1048576,
                "auto_fragment_size": 65536,
                "fail_by_drop": true,
                "open_handshake_timeout": 2500,
                "close_handshake_timeout": 1000,
                "auto_ping_interval": 10000,
                "auto_ping_timeout": 5000,
                "auto_ping_size": 4
              },
              "serializers": [
                "json"
              ],
              "cookie": {
                "store": {
                  "type": "file",
                  "filename": "cookies.dat"
                }
              },
              "auth": {
                "ticket": {
                  "type": "dynamic",
                  "authenticator": "org.kopnik.authenticate"
                },
                "anonymous": {
                  "type": "static",
                  "role": "anonymous"
                },
                "cookie": {
                }
              }
            }
          }
        }
      ],
      "components": [
        {
          "type": "class",
          "classname": "authenticator.AuthenticatorSession",
          "realm": "kopa",
          "role": "authenticator"
        }
      ]
    }
  ]
}

```

**Comment by oberstet** [comment]
https://github.com/crossbario/crossbar/blob/master/CONTRIBUTING.md#asking-questions
